### ISSUE TITLE
[FEAT] Support for SQL Alerts and Destination

### ISSUE THREAD

**Issue by vadivelselvaraj** [databricks/terraform-provider-databricks#1136]
Need support for creating the below resources via Terraform.

- Create SQL Alerts.
- Configure Data Alerts destination.

**Comment by bryan-vgw** [comment]
Hey, could I check the status of this?

**Comment by nfx** [comment]
Not enough customer interest for this yet

**Comment by nicolai86** [comment]
@nfx how do you gauge that? :+1: on the tickets?

**Comment by zeemaleki** [comment]
@nfx where do you ask customers what they are interested?

**Comment by thetkoseek** [comment]
+1 need this also - when apis available

**Comment by alexott** [comment]
Closing this in favor of #1983 as Alerts are already implemented
