### ISSUE TITLE
[FEAT] Register ML Model version via Terraform

### ISSUE THREAD

**Issue by nicolai86** [databricks/terraform-provider-databricks#1153]
Hi there,

I have a MLFlow model archive locally that I'd like to register with databricks via terraform. I don't see a way for this to work today.
Ideally this should work the same way ie lambda functions can be provisioned with terraform today.

### Configuration
```hcl
resource "databricks_mlflow_model" "test" {
  name = "My MLflow Model"
}

resource "databricks_mlflow_model_version" "test" {
  model = databricks_mlflow_model.test.name

  source = "./my-model.zip"
  stage = "staging"
}
```

or

```hcl
resource "databricks_mlflow_model" "test" {
  name = "My MLflow Model"

  model_definition {
    source = "./my-model.zip"
    stage = "staging"
  }
}
```

### Expected Behavior
A new ML Version for "My MLFlow Model" should have been created, with the content of `./my-model.zip` as version content.

### Actual Behavior
Nothing, "databricks_mlflow_model_version" doesn't exist

Please let me know if this makes sense to you folks. I'll be more than happy to provide a pull-request implementing this if you are open to it.

**Comment by nfx** [comment]
@nicolai86 which tools and APIs do you use now to achieve the same?

**Comment by nfx** [comment]
@nicolai86 got it. then APIs exist. can you point us to the exact command you're using?

i actually really wonder if TF is good for managing CI, like model versions or job versions. **_can you share your ideas how you plan on structuring the entire pipeline?_**

**Comment by nicolai86** [comment]
toda we're using the following commands:

```
// snip
mv = mlflow.register_model(saved_model_locally, name="some model name")
// snip
    client.set_model_version_tag(
        name=service_name,
        version=mv.version,
        key="service_version",
        value=service_version
    )
// snip
    client.transition_model_version_stage(
        name=service_name,
        version=mv.version,
        stage="Staging",
    )
```

**Comment by nicolai86** [comment]
So today we want to feed the same models into multiple databricks workspaces. The entire pipeline as I see it looks like this:

Model Repo -> (Some CI, ie github actions) -> Model archive in S3
Model archive -> terraform -> databricks workspace

the thing that connects these two pipelines is CodePipeline in our case but that's really an implementation detail.
We target multiple databricks workspaces with the same model and we want to validate a model in a separate workspace before "promoting" it into a production setting, hence the desire to not push to databricks from the repository CI, but rather from our terraform automation.

**Comment by nfx** [comment]
Following up - is this issue still relevant?
