### ISSUE TITLE
[ISSUE] Incorrect diff for num_clusters in SQL Endpoint when endpoint is not running

### ISSUE THREAD

**Issue by ebarault** [databricks/terraform-provider-databricks#1204]
Hi,

### Configuration
```hcl
 resource "databricks_sql_endpoint" "this" {
   name             = "Terraform-testing Endpoint"
   cluster_size     = "Large"
   min_num_clusters = 1
   max_num_clusters = 2
   auto_stop_mins   = 10
 }
```

### Expected Behavior
No change on subsequent applies when endpoint is not running

### Actual Behavior
<img width="508" alt="image" src="https://user-images.githubusercontent.com/12000935/158980703-285e0934-f485-4aea-89fa-72b6b516089d.png">

### Steps to reproduce
create the endpoint
**turn it off**
`terraform apply` again

### Terraform and provider versions
provider 0.5.4

### Notes
Already reported in https://github.com/databrickslabs/terraform-provider-databricks/issues/1116 with attached fix: https://github.com/databrickslabs/terraform-provider-databricks/pull/1117

however the fix does not seem to work

**Comment by ebarault** [comment]
an additional question @nfx is there a reason why the endpoint is started on creation ? I guess it is required to get some of the outputs. Same thing for clusters

**Comment by nfx** [comment]
@ebarault exactly. also to verify that it's configuring properly.

**Comment by nfx** [comment]
@shreyas-goenka the fix should include adding `tf:"suppress_diff"` type tag to the field in question. see instructions at https://github.com/databricks/terraform-provider-databricks/blob/master/CONTRIBUTING.md#adding-a-new-resource

**Comment by alexott** [comment]
we really have `suppress_diff` for `num_clusters`: https://github.com/databricks/terraform-provider-databricks/blob/master/sql/resource_sql_endpoint.go#L30

**Comment by nfx** [comment]
@alexott then it doesn't seem to work

**Comment by mejnv** [comment]
We face the same issue.

We tried to hardcode the number of clusters
` num_clusters     = 1`

Is it normal to check this variable when you specify a min and a max for the num of clusters?

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by shreyas-goenka** [comment]
I think so yes, there are two things we need to solve here:
1. Figure out why suppress diff is not working for num_clusters.
2. Do we want a consistent endpoint experience on create and update, ie on update, start the endpoint. This makes sense from infrastructure as a code POV since the num_clusters for the endpoint are specified and terraform should create those by starting the endpoint.

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by gpdenny** [comment]
Running v1.5.0 I'm not able to re-create this anymore :+1:

**Comment by ul400** [comment]
We are using version 1.7.0 and getting this error.

**Comment by manojhegde97** [comment]
This issue can be reproducible in 1.6.5 and 1.7.0 as well

**Comment by ePak** [comment]
We are also getting this error in 1.7.0
