### ISSUE TITLE
[ISSUE] `databricks_spark_version` LTS filter does not work

### ISSUE THREAD

**Issue by bsamseth** [databricks/terraform-provider-databricks#1205]
The `long_term_support` filter for `databricks_spark_version` seems to just not work.

### Configuration
```hcl
terraform {
  required_version = "1.1.7"
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.5.4"
    }
  }
}

data "databricks_spark_version" "lts" {
  long_term_support = true
}

output "version" {
  value = data.databricks_spark_version.lts.id
}
```

### Expected Behavior
The output should point to an LTS version.

### Actual Behavior
I get `version = "10.4.x-scala2.12"`, despite the latest LTS at the time of writing being 9.1, ref https://docs.databricks.com/release-notes/runtime/releases.html 

### Steps to Reproduce

Put the above configuration in an empty directory in a file called `main.tf`. Then run
```bash
terraform init && terraform apply -auto-approve
```

### Terraform and provider versions

The configuration above specifies exact versions of both for reproducibility.

### Debug Output
The output of `TF_LOG=DEBUG terraform apply -auto-approve 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'` is provided here: https://gist.github.com/bsamseth/09d5cfe2b97d2b23715baa803785d853

**Comment by bsamseth** [comment]
Actually, I looked at the actual API output, which does have 10.4 as LTS:

```
$ databricks clusters spark-versions
....
    {
      "key": "10.4.x-gpu-ml-scala2.12",
      "name": "10.4 LTS ML (includes Apache Spark 3.2.1, GPU, Scala 2.12)"
    }
  ]
}
```

However the documentation does not list 10.4 at all. I'm guessing I just happened to stouble across this between the new LTS release and it being updated in the documentation? If so, please consider this issue invalid and close.

**Comment by nfx** [comment]
It relies on whatever is returned by API.

**Comment by rscottwatson** [comment]
Does anyone @bsamseth @nfx know how to print out the result of the query?  For example I have the following

```
data "databricks_spark_version" "cpu" {
  latest = false
}
```
But then I want to print out the result of this
```
output cpu {
    value = data.databricks_spark_version.cpu.id 
}
```
However, I get the following error 

Error: spark versions query returned multiple results. Please change your search criteria and try again
│ 
│   with data.databricks_spark_version.cpu,
│   on main.tf line 39, in data "databricks_spark_version" "cpu":
│   39: data "databricks_spark_version" "cpu" {

I want to see how to print out the result and then add one of the values in my TF code.
I have tried all the following output options with no success.

    value = data.databricks_spark_version.cpu.id[*]
    value = data.databricks_spark_version.cpu[*].id
    value = data.databricks_spark_version.cpu.*.id 
    value = [data.databricks_spark_version.cpu.id]

Thanks.

**Comment by alexott** [comment]
This data source is designed for use in resource where only one value is expected. It wont return multiple results
