### ISSUE TITLE
[FEATURE] data source  `databricks_cluster`

### ISSUE THREAD

**Issue by justinTM** [databricks/terraform-provider-databricks#1270]
Feature request :)

Currently, the data source `databricks_clusters` merely exports `id`s. There's a wealth of data in the DataBricks API to show more than just Cluster ID; we should give users the ability to retrieve the entire information for cluster(s) by a variety of different query parameters (id, name, spark version, etc.).

I'd be happy to work on this.

**Comment by nfx** [comment]
Why a data source for a single cluster is needed?

**Comment by nfx** [comment]
got it. please make a PR then. make sure to use `common.DataResource`

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
