### ISSUE TITLE
[FEATURE] data source `databricks_job`

### ISSUE THREAD

**Issue by justinTM** [databricks/terraform-provider-databricks#1272]
Hi there!

Similarly to https://github.com/databrickslabs/terraform-provider-databricks/issues/1270 , it is currently impossible to retrieve data about DataBricks Jobs other than merely the id

I propose a new data source which will provide the entire list of attributes for a databricks job.

Happy to work on this as well.

**Comment by nfx** [comment]
Please go ahead and create data resource on top of `common.DataResource`

**Comment by nfx** [comment]
Thank you for the feature request, @justinTM ! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
gen boilerplate via https://github.com/databricks/terraform-provider-databricks/pull/1496
