### ISSUE TITLE
[Feat] Add data sources for retrieving local hive_metastores tables and views

### ISSUE THREAD

**Issue by vadivelselvaraj** [databricks/terraform-provider-databricks#1275]
To prevent hard-coding tables for databases when granting privileges to principals(as detailed in my [previous request](https://github.com/databrickslabs/terraform-provider-databricks/issues/1105)), a data resource that pulls up the tables and views(via separate TF resources ideally) from the Databricks workspace's local **hive_metastore** would be great to keep all of the permissions management within the terraform codebase.

This could be part of the existing `databricks_tables` terraform resource as well with the only difference being the _catalog_name_ set to **hive_metastore** rather than one of the Unity Catalog catalogs.

```hcl
data "databricks_tables" "things" {
  catalog_name = "hive_metastore"
  schema_name = "things"
}

output "all_things_tables" {
  value = data.databricks_tables.things
}
```

**Comment by nfx** [comment]
Thank you for the feature request, @vadivelselvaraj ! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by vadivelselvaraj** [comment]
> Following up - is this issue still relevant?

Yes, @nfx. I don’t have bandwidth to work on this now though. Will make a comment when we start this.

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by vadivelselvaraj** [comment]
Yes, @nfx. Though we migrate to UC, we still have certain workspace HMS dbs/tables to work through.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
