### ISSUE TITLE
[ISSUE] Unable to import databricks_metastore_assignment

### ISSUE THREAD

**Issue by pietern** [databricks/terraform-provider-databricks#1307]
### Configuration
```hcl
resource "databricks_metastore_assignment" "this" {
  metastore_id = databricks_metastore.this.id
  workspace_id = var.workspace_id
}
```

### Expected Behavior

Import should work.

```
terraform import databricks_metastore_assignment.this <metastore id>/12345678
```

### Actual Behavior

The apply after the import produces a "force new" change.

```
-/+ resource "databricks_metastore_assignment" "this" {
      + default_catalog_name = "hive_metastore"
      ~ id                   = "<metastore id>/12345678" -> (known after apply)
      + workspace_id         = 12345678 # forces replacement
        # (1 unchanged attribute hidden)
    }
```

### Terraform and provider versions

```
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.5.7
```

### Important Factoids

The read path doesn't read the workspace ID, so it either needs to be assumed to be correct (and taken from the compound ID), or read through some auxiliary API call (e.g. current workspace ID).

https://github.com/databrickslabs/terraform-provider-databricks/blob/24ed7fd7673f0db26b1fab6e655eed1a49a9d4b8/catalog/resource_metastore_assignment.go#L36-L40

**Comment by nfx** [comment]
@pietern - there's another option - nil out the importer property for this resource, https://github.com/databrickslabs/terraform-provider-databricks/blob/master/storage/resource_mount.go#L66-L67, as we didn't document it yet - https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/metastore_assignment :-)

there's no API that gives a workspace id back. There's X-Databricks-Org-Id response header, though we need to think how to pull it from deeply hidden layer... alternatively, we can ask @adamcain-db to add workspace id to metastore summary reponse 🤷

**Comment by nfx** [comment]
Following up - is this issue still relevant?

**Comment by nkvuong** [comment]
so the workaround at the moment is to manually edit the `.tfstate` file. After the import, you can see
```
          "attributes": {
            "default_catalog_name": null,
            "id": "blahblah/workspaceid",
            "metastore_id": "blahblah",
            "workspace_id": "null"
          }
```

set `workspace_id` & `default_catalog_name` will fix this

**Comment by mikemowgli** [comment]
> so the workaround at the moment is to manually edit the `.tfstate` file. After the import, you can see
> 
> ```
>           "attributes": {
>             "default_catalog_name": null,
>             "id": "blahblah/workspaceid",
>             "metastore_id": "blahblah",
>             "workspace_id": "null"
>           }
> ```
> 
> set `workspace_id` & `default_catalog_name` will fix this

that really helped :) thanks

**Comment by nfx** [comment]
All resources (except a couple) do support imports generically by just specifying an ID. But we just don’t document the cases of “paired IDs”, as it turns out that users can damage their state by using those commands improperly 🤷🏻‍♂️

**Comment by nkvuong** [comment]
with #2182, importing `databricks_metastore_assignment` works now, if the provider is defined at account level.
