### ISSUE TITLE
add support for byo vpc based workspace creation on gcp

### ISSUE THREAD

**Issue by bhavink** [databricks/terraform-provider-databricks#1393]
please add GCP support to https://github.com/databricks/terraform-provider-databricks/blob/master/docs/resources/mws_networks.md , byo vpc on GCP feature - https://docs.gcp.databricks.com/administration-guide/cloud-configurations/gcp/customer-managed-vpc.html

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
