### ISSUE TITLE
[ISSUE] Terraform should use the 2.1 API version for UC service calls

### ISSUE THREAD

**Issue by cpettitt-databricks** [databricks/terraform-provider-databricks#1394]
Terraform is using the `/api/2.0` endpoint for UC service calls currently.

We need to switch this to `/api/2.1` as soon as possible, as we will be turning off `/api/2.0` for privileges at UC GA. `/api/2.1` behaves the same as `/api/2.0` before UC GA. After GA it will be able to serve the new privilege model in UC.

**Comment by alexeyegorov** [comment]
Does it include the mismatch of Databricks Terraform API and Jobs API? e.g. [Databricks Terraform Jobs API](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#argument-reference) claims that the parameter ``new_cluster`` has the same parameters as ``Databricks Cluster``, but when you apply the changes it gets rejected when you set the ``cluster_name``. [Databrics Jobs API](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate)

**Comment by nfx** [comment]
@alexeyegorov job resource has nothing to do with Unity Catalog resources. why do you need to set a `cluster_name` in the `new_cluster` block in `databricks_job`?
