### ISSUE TITLE
[ISSUE] databricks_pipeline does not support updating the resource

### ISSUE THREAD

**Issue by TomNash** [databricks/terraform-provider-databricks#1401]
### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline

### Expected Details
The field `cluster.custom_tags.cluster_type` is not listed as a required field (implied to be therefore optional), yet creating a DLT pipeline without at least one `cluster` block containing the following configuration will allow the pipeline to be created but NOT subsequently updated.
```
cluster {
    custom_tags {
        cluster_type = 'default'
    }
}
```

Attempting to update a pipeline created without the above block will return the error:
`Error: cannot update pipeline: clusters must have exactly 1 default cluster`

It seems that updates to the pipeline are trying to reference this tag which could be non-existent, not the `label` field.

**EDIT:** It seems that this is not a documentation issue, requiring the custom tag still will not allow the resource to be updated in subsequent `terraform apply`

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by vadivelselvaraj** [comment]
We've been facing this issue for a while now. Would appreciate bumping up the priority on this.

@stikkireddy: This is the issue we've been referring to in our last conversation.

**Comment by TomNash** [comment]
@vadivelselvaraj Yeah I agree this is not the fix either, having the label + custom tags. It seems to still be an issue. We're having to resort to full `-replace` the resource every time. How are you addressing it?

**Comment by TomNash** [comment]
We have to force `-replace` the pipeline got get a successful build, but now our automated jobs are failing because we get a new runtime error after running the replacement pipeline.

> A table should only be managed by one pipeline. Concurrent pipeline
operations such as maintenance and full refresh will conflict with each other.

**Comment by oaltalabani** [comment]
Seeing exact same behavior.

> In our case, we have the `default` set in both the `cluster.label` and `cluster.custom_tags` but the updates always fail with `Error: cannot update pipeline: clusters must have exactly 1 default cluster` error. We've only one `cluster` block btw.
> 
> `databricks TF provider version: 1.0.0`
> 
> ```terraform
> cluster {
>     label        = "default"
>     ...
>     custom_tags = merge({
>       cluster_type  = "default",
>       ResourceClass = "Serverless",
>       JobName       = "Data Ingestion pipeline"
>     }, var.shared_tags)
>     ...
> }
> ```
> 
> We've been facing this issue for a while now. Would appreciate bumping up the priority on this.
> 
> @stikkireddy: This is the issue we've been referring to in our last conversation.

**Comment by oaltalabani** [comment]
seeing similar issue, reverting provider version until this is sorted.

> We have to force `-replace` the pipeline to get a successful build, but now our automated jobs are failing because we get a new runtime error after running the replacement pipeline.
> 
> > A table should only be managed by one pipeline. Concurrent pipeline
> > operations such as maintenance and full refresh will conflict with each other.

**Comment by alexott** [comment]
Then it could be some changes in the APIs, we need to recheck with dev team. The part that handles clusters didn't change significantly since the initial release.  The latest change just added a couple of attributes

**Comment by oaltalabani** [comment]
In case it helps, reverting back to 0.6.0 resolved the issue.
This is the last version we were using before seeing this issue, we bumped up to 1.0.0 from 0.6.0.
Not sure if that points to a bug introduced after v0.6.0 or the api. 
Please note I did not test 0.6.1.

@TomNash heads up in case it helps unblock you for now.

> Then it could be some changes in the APIs, we need to recheck with dev team. The part that handles clusters didn't change significantly since the initial release. The latest change just added a couple of attributes

**Comment by alexott** [comment]
I'll look into it in the next days

**Comment by alexott** [comment]
@oaltalabani is it possible to send output of `TF_LOG=DEBUG DATABRICKS_DEBUG_TRUNCATE_BYTES=250000 terraform apply 2>&1 > tf-debug.log` ? if you can't share it publicly, please send that debug log to alexey.ott at databricks.com

**Comment by oaltalabani** [comment]
Sent you the log, was able to work just fine for a few hours using v0.6.0 after reverting back but now I am replicating the same behavior as seen in higher provider versions. This is becoming a production blocker.

> @oaltalabani is it possible to send output of `TF_LOG=DEBUG DATABRICKS_DEBUG_TRUNCATE_BYTES=250000 terraform apply 2>&1 > tf-debug.log` ? if you can't share it publicly, please send that debug log to alexey.ott at databricks.com

**Comment by mmacneillecatalyst** [comment]
I am working with @oaltalabani . We found that this occurred when we made a terraform configuration change that was rejected by the databricks api. In our case we were setting memory thresholds above what was allowed for our instance type. 

This caused the pipeline's cluster to be in a broken state, and at the same time the terraform provider was showing the error above.

When I removed our rejected configuration manually, and then we did an empty apply the provider began to function correctly again.

After this we were able to apply correct memory configuration through terraform.

**Comment by TomNash** [comment]
> I am working with @oaltalabani . We found that this occurred when we made a terraform configuration change that was rejected by the databricks api. In our case we were setting memory thresholds above what was allowed for our instance type.
> 
> This caused the pipeline's cluster to be in a broken state, and at the same time the terraform provider was showing the error above.
> 
> When I removed our rejected configuration manually, and then we did an empty apply the provider began to function correctly again.
> 
> After this we were able to apply correct memory configuration through terraform.

I'll have to look into that and see if there's some setting we may have that is being rejected by Databricks API, we have a pretty simple configuration.

**Comment by vadivelselvaraj** [comment]
> @vadivelselvaraj Yeah I realized my suggestion is not the fix either, having the label + custom tags does not seem to work either. It seems to still be an issue. We're having to resort to full `-replace` the resource every time. How are you addressing it?

@TomNash  We don't. We've been ignoring the errors from `TF apply` which is why I'd like to see this fixed sooner.

**Comment by alexott** [comment]
Managed to reproduce it. But it looks like more a problem not of provider, but of the backend:

```
2022-07-01T09:41:11.002+0200 [DEBUG] provider.terraform-provider-databricks: PUT /api/2.0/pipelines/4ab2795b-85b3-466e-83bc-c91e39c84cca {
  "channel": "preview",
  "clusters": [
    {
      "custom_tags": {
        "cluster_type": "default"
      },
      "label": "default",
      "num_workers": 3
    },
    {}
  ],
  "edition": "advanced",
  "id": "4ab2795b-85b3-466e-83bc-c91e39c84cca",
  "libraries": [
    {
      "notebook": {
        "path": "/Users/alexey.ott@databricks.com/Terraform/dlt_test_alexey_ott/dlt_test_alexey_ott"
      }
    }
  ],
  "name": "dlt_test_alexey_ott",
  "storage": "/Users/alexey.ott@databricks.com/Terraform/dlt_test_alexey_ott"
}: timestamp=2022-07-01T09:41:11.002+0200
2022-07-01T09:41:11.607+0200 [DEBUG] provider.terraform-provider-databricks: 400 Bad Request {
  "error_code": "INVALID_PARAMETER_VALUE",
  "message": "clusters must have exactly 1 default cluster"
}: timestamp=2022-07-01T09:41:11.607+0200
```

**Comment by alexott** [comment]
@vadivelselvaraj @TomNash @oaltalabani can you try to build from the linked PR & try?

**Comment by TomNash** [comment]
I see in my plan now what you may be trying to address. There is this additionally "empty cluster" created at the bottom with no attributes but the AWS instance profile ARN. Looking at your PR, it would not exclude this cluster from the list given that is not `nil`
```
      - cluster {
          - custom_tags      = {} -> null
          - instance_pool_id = "<pool_id>" -> null
          - label            = "default" -> null
          - num_workers      = 0 -> null
          - spark_conf       = {} -> null
          - spark_env_vars   = {} -> null
          - ssh_public_keys  = [] -> null

          - autoscale {
              - max_workers = 5 -> null
              - min_workers = 1 -> null
            }

          - aws_attributes {
              - first_on_demand      = 0 -> null
              - instance_profile_arn = "<arn>" -> null
            }
        }
      + cluster {
          + driver_node_type_id = (known after apply)
          + instance_pool_id    = "<pool_id>"
          + label               = "default"
          + node_type_id        = (known after apply)
          + ssh_public_keys     = []

          + autoscale {
              + max_workers = 5
              + min_workers = 1
            }

          + aws_attributes {
              + instance_profile_arn = "<arn>"
            }
        }
      - cluster {
          - custom_tags      = {} -> null
          - instance_pool_id = "<pool_id>" -> null
          - label            = "maintenance" -> null
          - num_workers      = 1 -> null
          - spark_conf       = {} -> null
          - spark_env_vars   = {} -> null
          - ssh_public_keys  = [] -> null

          - aws_attributes {
              - first_on_demand      = 0 -> null
              - instance_profile_arn = "<arn>" -> null
            }
        }
      + cluster {
          + driver_node_type_id = (known after apply)
          + instance_pool_id    = "<pool_id>"
          + label               = "maintenance"
          + node_type_id        = (known after apply)
          + num_workers         = 1
          + ssh_public_keys     = []

          + aws_attributes {
              + instance_profile_arn = "<arn>"
            }
        }
      + cluster {
          + custom_tags     = {}
          + spark_conf      = {}
          + spark_env_vars  = {}
          + ssh_public_keys = []

          + aws_attributes {
              + instance_profile_arn = "<arn>"
            }
        }


        # (5 unchanged blocks hidden)
    }  ```

**Comment by alexott** [comment]
It’s really interesting. Not sure from where this 3rd cluster comes. Will continue to debug it on Monday

**Comment by alexott** [comment]
@TomNash can you say what have you changed in your terraform code for this specific plan?

**Comment by TomNash** [comment]
I believe it was a change in the upstream remote state changing the instance pool ID, I can try and check again on Tuesday.

**Comment by alexott** [comment]
Hmmm, it looks like a bug in the Terraform itself... Because it generate additional blocks
