### ISSUE TITLE
[Feature] Add workspace storage option to workspace_conf 

### ISSUE THREAD

**Issue by atombravo** [databricks/terraform-provider-databricks#1404]
By default, databricks stores interactive notebook results that are below a threshold size in the control plane.  This is configurable to store the results always in the customer storage account via the REST API and the workspace GUI.  This request is to add this option to the workspace_conf resource to allow it to be controlled via Terraform.

https://docs.microsoft.com/en-us/azure/databricks/administration-guide/workspace/storage#--configure-the-storage-location-for-interactive-notebook-results

### Configuration
```hcl
# Sample of feature
resource "databricks_workspace_conf" "this" {
  custom_config = {
    "storeInteractiveNotebookResultsInCustomerAccount" : true
  }
}

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
