### ISSUE TITLE
[Feature] Add verbose audit logging option for workspace_conf

### ISSUE THREAD

**Issue by atombravo** [databricks/terraform-provider-databricks#1405]
Please add the enableVerboseAuditLogs option to the workspace_conf resource, so that verbose audit logging can be enabled by Terraform.

https://docs.microsoft.com/en-us/azure/databricks/administration-guide/account-settings/azure-diagnostic-logs

### Configuration
```hcl
resource "databricks_workspace_conf" "this" {
  custom_config = {
    "enableVerboseAuditLogs " : true
  }
}
```

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by dvasdekis** [comment]
It's disappointing that this was closed without resolution, as it's a security requirement for us from our central IT department. We are now considering replacement of Databricks with other tools given that there is no way to obtain proper logs from notebook runs in an automated way across our 50+ instances.
