### ISSUE TITLE
[ISSUE] Errors while trying to give users access to root of workspace

### ISSUE THREAD

**Issue by jschra** [databricks/terraform-provider-databricks#1410]
Hello,

In configuring our Databricks workspace, I am trying to give users access to the root directory in the workspace so they can freely create directories and notebooks. When I try to do so, however, I run into issues, as shown below.

#### Option 1: try to add user access to root
```hcl
resource "databricks_permissions" "folder_usage" {
  directory_path = "/"

  access_control {
    group_name       = databricks_group.developers.display_name
    permission_level = "CAN_MANAGE"
  }
}
```
#### Option 2: try to add user access to root while including admins
```hcl
resource "databricks_permissions" "folder_usage" {
  directory_path = "/"

  access_control {
    group_name       = "admins"
    permission_level = "CAN_MANAGE"
  }

  access_control {
    group_name       = databricks_group.developers.display_name
    permission_level = "CAN_MANAGE"
  }
}
```

### Expected Behavior
I would expect to be able to give user groups full access to the workspace (from the root, it is doable from the UI) without adjusting the access of admins to the root. 

### Actual Behavior
When I run the first configuration in a newly launched Databricks workspace with a 'developers' group, I get the following error:
![image](https://user-images.githubusercontent.com/25622698/176139680-370ee6cc-1742-4c4b-8ec6-6b34592d03df.png)

If I try to run the second configuration in the same, fresh workspace, I get the following error:
![image](https://user-images.githubusercontent.com/25622698/176139287-b6bc5524-dba4-43a7-bc3e-76299ce941c2.png)

### Steps to Reproduce
Generate a new Databricks workspace using Terraform (e.g. by following the example code online) with a 'developers' group within it. Then add one of the two configurations as shown above and run `terraform apply`

### Terraform and provider versions

Please paste the output of `terraform version`. If version of `databricks` provider is not the latest Terraform v1.1.2
```
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.0.0
+ provider registry.terraform.io/hashicorp/aws v4.20.1
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Debug Output
https://gist.github.com/jschra/16a31a88e54e41aa7ec8f1b06edfa3a3

### Important Factoids
None

**Comment by nfx** [comment]
It is not possible to restrict any permissions from admins. Please create a top-level folder for developers to have full access in.
