### ISSUE TITLE
[ISSUE] Token authorization grants to service principal doesn't work

### ISSUE THREAD

**Issue by vadivelselvaraj** [databricks/terraform-provider-databricks#1415]
Granting token authorization to a service principal using the below config results in an `Error: cannot create permissions: Principal: ServicePrincipalName(deployment-user) does not exist` error though the service principal does exist(checked it via the API/UI).

*Databricks Provider version: 1.0.0*
```hcl
resource "databricks_service_principal" "deployment_user" {
  display_name         = "deployment-user"
  allow_cluster_create = true
}

resource "databricks_permissions" "token_usage" {
  authorization = "tokens"

  access_control {
    service_principal_name = databricks_service_principal.deployment_user.display_name
    permission_level       = "CAN_USE"
  }
}
```

**Comment by nfx** [comment]
@vadivelselvaraj you should use `application_id` instead of `display_name`.

**Comment by nfx** [comment]
need to improve documentation on it, as it may not be that logical...
