### ISSUE TITLE
[ISSUE] Feature request - Add libraries to shared workspace

### ISSUE THREAD

**Issue by Rumbles** [databricks/terraform-provider-databricks#1430]
We currently use terraform to create a workspace, using the `databricks_mws_workspaces` resource we create a workspace and then users log in to create their clusters as required. I have been able to add a library to the workspace manually through the UI, but I want to be able to do this using terraform.

I have tried using `databricks_library` to install the library on a running cluster, which works for the one cluster that is running, but then if someone creates a new cluster, there is no easy way to instal the library from the shared workspace.

For example I have used this to install a library:

```
data "databricks_clusters" "all" {
}

resource "databricks_library" "spark_cassandra" {
  for_each   = data.databricks_clusters.all.ids
  cluster_id = each.key
  maven {
    coordinates = "com.datastax.spark:spark-cassandra-connector_2.12:3.2.0"
  }
}
```

This works on a running cluster and if I look at the libraries section on my running cluster and click on my new library I see a message that just serves to rub salt in the wound:

> Install automatically on all clusters - This option does not work on clusters with Runtime version >= 7.0

If that feature still worked I guess we wouldn't need this, I have no idea if there is any plan to revive that feature.

What I really want is something like this:

```
resource "databricks_mws_library" "spark_cassandra" {
  maven {
    coordinates = "com.datastax.spark:spark-cassandra-connector_2.12:3.2.0"
  }
}
```

Which would just add the library to the Workspace > Shared section so adding libraries to new clusters would be trivial.

#954 suggests:

> One of the ways of doing it is through databricks_global_init_scirpt, though this is more of a workaround

But I don't see any documentation about how that would work, but I assume that would be along the lines of add steps to your init script to grab your libraries using maven or whatever (the old fashioned way). In that case we wouldn't have any evidence of installed libraries in the console, and updating the packages might be tricky.

**Comment by alexott** [comment]
@Rumbles The main problem is that we don't have public REST API for that, so we can't implement that in Terraform.

**Comment by Rumbles** [comment]
Thanks for your reply @alexott , is there somewhere I should raise a feature request so we can get one? Or is there another way to do this that I'm missing?

**Comment by alexott** [comment]
You can raise a feature request for new API via solution architect or customer success engineer attached to your account...
But I would really recommend to think about workspace-level libraries:

* Using maven coordinates won't bring performance benefits as these coordinates need to be resolved on each installation
* Having single version of library for all clusters that need it could be problematic from point of DBR upgrades. For example, Cassandra connector is bound to specific version of Spark, and may not work if you go from DBR 9.1 to 10.4, etc.

**Comment by Rumbles** [comment]
Thanks for the reply, if you don't recommend using workspace level libraries, what is the right way to install libraries so that users can access services like cassandra/scylla using spark?

> Using maven coordinates won't bring performance benefits

I'm less concerned about performance benefits, it's more about ease of use for end users, if they have to find the right libraries to use from maven every time they need a library installing on a new cluster it would be time consuming and prone to error, which is why I would prefer to have a list of available libraries for my users to chose from instead of expecting them to find the libraries themselves.

> Having single version of library for all clusters that need it could be problematic from point of DBR upgrades

I have already found that the latest version of the connector in maven is 3.2.0 (I assume that's the spark version) and your LTS is using 3.2.1, we have to check whether these are compatible and run without error. If they don't I guess we need to figure out another way of doing this (maybe build the library ourselves? I'm not sure I want to go down that rabbit hole)

It is definitely something we would need to keep on top of, but since we are trying to stick to using your LTS, hopefully we won't have to keep track of changes too often.

Again, if I have missed something glaringly obvious please point me in the right direction. I am relatively new to databricks, I am managing the cloud infra for my organisation and I am trying to make databricks as usable it can be for my team.

**Comment by Rumbles** [comment]
@alexott could I get a reply to my previous questions please?

**Comment by nfx** [comment]
closing this as it's a Platform feature request and is not relevant to provider
