### ISSUE TITLE
[Unexpected Behavior] SQL Endpoint creation - No param target workspace

### ISSUE THREAD

**Issue by RachidAZ** [databricks/terraform-provider-databricks#1441]
Hello Team,

In the example below, where the SQL endpoint will be created? because there is no param to specify the target databricks workspace, I am confused. 
Thank you in advance.

### Configuration
```hcl
# resource "databricks_sql_endpoint" "this" {
  name             = "Endpoint one"
  cluster_size     = "Small"
  max_num_clusters = 1

  tags {
    custom_tags {
      key   = "City"
      value = "Amsterdam"
    }
  }
}
```

### Expected Behavior
Having a param to specify the target workspace

### Actual Behavior
I have no clue

**Comment by nfx** [comment]
@RachidAZ you must specify it via `host` provider attribute - please consult the docs https://registry.terraform.io/providers/databricks/databricks/latest/docs#host
