### ISSUE TITLE
[DOC] Example databricks_job 'multi-workflow' with DLT Pipeline as Sub Step?

### ISSUE THREAD

**Issue by kurtmaile** [databricks/terraform-provider-databricks#1442]
Hi there,

### Affected Resource(s)
Example for Multi-step workflows (databricks_job) that use DLT as a sub job

### Expected Details
Worked example in docs using DLT
Sorry if I missed an example elsewhere, but looking for a decent example of using DLT as part of an e2E workflow with other job steps?  Similar to the presentation at data and Ai summit, any examples extremely appreciated

**Comment by kurtmaile** [comment]
Im sorry I missed the 'pipeline_task" block which I assume is this?

**Comment by alexott** [comment]
Yes, DLT pipeline is the `task` with `pipeline_task` inside it
