### ISSUE TITLE
Rename SQL Endpoints to SQL Warehouse

### ISSUE THREAD

**Issue by amansehgal82** [databricks/terraform-provider-databricks#1444]
Recently, Databricks SQL Endpoints was renamed to SQL Warehouse and hence, all the references to Databricks SQL Endpoints needs to be updated. 

### Affected Resource(s)
Affected doc pages:
https://registry.terraform.io/providers/databricks/databricks/latest/docs
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_endpoint
https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/experimental-exporter

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Replace URL title for Datarbirkcs SQL Endpoint webpage to SQL Warehouse on above mentioned URLs.
- [ ] Replace `endpoint` to `warehouse` in sample code snippets.
- [ ] Replace resource name in support matrix from `endpoint` to `warehouse`. Eg: `databricks_sql_endpoint` to `databricks_sql_warehouse`

### Important Factoids
Change in name documentation: [Databricks SQL Endpoints](https://docs.databricks.com/sql/admin/sql-endpoints.html)

**Comment by alexott** [comment]
it's not only doc issue - changing the resource name could be a bit amount of work to maintain compatibility

**Comment by alexott** [comment]
let track this as #1800
