### ISSUE TITLE
[DOC] Instance Pool - Zone ID - Required or Optional

### ISSUE THREAD

**Issue by msherman** [databricks/terraform-provider-databricks#1448]
### Affected Resource(s)
[Instance Pool - Zone ID](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/instance_pool#zone_id)

### Expected Details
The Zone ID is listed as a (Required) field, but in the description it states "This is an optional field" on the third to last sentence. Can you please clarify if this is a required field, and in either case update the documentation to reflect?

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Update Zone ID to clarify if it is or is not required.

### References
I did not find any.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
