### ISSUE TITLE
[DOC] Instance Pool - Max Capacity - Default value not listed

### ISSUE THREAD

**Issue by msherman** [databricks/terraform-provider-databricks#1449]
### Affected Resource(s)
[Instance Pool - Max Capacity](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/instance_pool#max_capacity)

### Expected Details
Max capacity was changed from being required to optional in PR 256 linked below. If it is not passed in, what is the default? Can the default be added to the documentation for clarity? Without it set, is it infinite? The databricks documentation listed below does not state either.

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Update documentation listing default value for MAX_CAPACITY

### Important Factoids
[Databricks documentation](https://docs.databricks.com/clusters/instance-pools/configure.html#maximum-capacity)

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- [PR 256](https://github.com/databricks/terraform-provider-databricks/pull/256)

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
