### ISSUE TITLE
Data source for a SQL warehouse

### ISSUE THREAD

**Issue by pietern** [databricks/terraform-provider-databricks#1456]
To associate DBSQL queries with a warehouse, we need its `data_source_id`.

This ID is not the same as the warehouse ID. Therefore we need functionality to look up a warehouse either by its name or by its warehouse ID to access its data source ID. I imagine writing something like:

```
data "databricks_sql_warehouse" "this" {
  name = "Small warehouse"
  // Optionally specify:
  // id = "[UUID OF EXISTING WAREHOUSE"]
}
resource "databricks_sql_query" "this" {
  data_source_id = data.databricks_sql_warehouse.this.data_source_id
}
```

Thoughts?

**Comment by nfx** [comment]
This is a great feature request. For those who'll want implementing it, please know that it's never been so easy to add a new data resource - https://github.com/databricks/terraform-provider-databricks/blob/master/catalog/data_tables.go#L10-L30
