### ISSUE TITLE
[FEAT] Enhancements for `databricks_clusters` and `databricks_warehouses` data sources

### ISSUE THREAD

**Issue by nkvuong** [databricks/terraform-provider-databricks#1480]
Follow-up work for #1460
- expose name-to-id mapping for warehouses & clusters

Example syntax could be as below
```tf
data "databricks_sql_warehouses" "all_shared" {
  warehouse_name_contains = "shared"
}

output "warehouses_mapping" {
  value = data.databricks_sql_warehouses.all_shared.mappings <- this returns { "shared" = "11", "shared_1" = [12, 13]}
}
```

- add lookup of cluster/warehouse by name
This should fail if more or less than a single match is returned by the search
```tf
data "databricks_sql_warehouse" "all" {
  name       = "this_is_a_unique_name"
}
```

**Comment by nfx** [comment]
follow-up once https://github.com/databricks/databricks-sdk-go is migrated

**Comment by alexott** [comment]
lookup cluster by name is done as part of #1901
