### ISSUE TITLE
[FEATURE] Allow to use `extra_configs` with `s3` block in `databricks_mount`

### ISSUE THREAD

**Issue by thaiphv** [databricks/terraform-provider-databricks#1492]
### Use-cases
I'm having an issue with mounting newly created S3 buckets. I think it might be related to the use of the S3 gateway endpoint in our VPC or maybe not. However, I think it'd be useful if we are allowed to pass extra configuration items to the `databricks_mount` resource. Specifically I'd like to pass the following extra configurations to the `dbutils.fs.mount` command:
```
<property>
  <name>fs.s3a.endpoint</name>
  <description>AWS S3 endpoint to connect to. An up-to-date list is
    provided in the AWS Documentation: regions and endpoints. Without this
    property, the standard region (s3.amazonaws.com) is assumed.
  </description>
</property>

<property>
  <name>fs.s3a.endpoint.region</name>
  <description>AWS S3 region for a bucket, which bypasses the parsing of
    fs.s3a.endpoint to know the region. Would be helpful in avoiding errors
    while using privateLink URL and explicitly set the bucket region.
    If set to a blank string (or 1+ space), falls back to the
    (potentially brittle) SDK region resolution process.
  </description>
</property>
```
As they may fix my issue when mounting a newly created bucket.

### Attempted Solutions
N/A

### Proposal
N/A

### References
N/A

**Comment by nfx** [comment]
There should be extra configs field in the mount resource, please check the docs

**Comment by thaiphv** [comment]
Hi @nfx 

It looks to me that I can only specify `instance_profile` within the `s3` block. That's why I can't specify both `extra_configs` and `s3` blocks within the same `databricks_mount` resource.

**Comment by thaiphv** [comment]
My use case looks like below
```
resource "databricks_mount" "s3" {
  s3 {
    instance_profile = var.s3_mount_instance_profile
    bucket_name = var.s3_bucket_name
  }

  extra_configs = {
    "fs.s3a.endpoint.region" = var.aws_region
  }
}
```
It doesn't work because I can't specify both `s3` and `extra_configs` within the `databricks_mount` resource.

**Comment by nfx** [comment]
@thaiphv we don’t plan on adding more parameters to s3 block. Please check if you can achieve the goal with uri and extra_configs.

**Comment by nfx** [comment]
@thaiphv please use a combination of `uri` and `extra_configs` - https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mount#example-mounting-adls-gen2-using-uri-and-extra_configs
