### ISSUE TITLE
[ISSUE] Provider Auth issue when applying changes on workspace that force resource re-creation (Azure)

### ISSUE THREAD

**Issue by gbusch** [databricks/terraform-provider-databricks#1495]
We are requested by our customer policy to enable infrastructure encryption for Databricks workspaces for an existing workspace. I provide a minimal example of our setup below: we configure the workspace using the azurerm-provider and configure clusters etc. using the Databricks-provider.

When we make changes to the workspace configurations that enforce a resource-recreation, "terraform plan" fails with 
"Error: cannot read cluster: authentication is not configured for provider. Please check https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication for details"

* Creation from scratch works for all used settings
* Changing other parameters *that do not require resource re-creation* (for example sku "standard" -> "premium" and back) *does work*
* Changing other parameters *that do require resource re-creation* (for example re-naming storage-account name) *does not work*

### Configuration
```hcl
# main.tf
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.15.0"
    }

    databricks = {
      source  = "databricks/databricks"
      version = "1.1.0"
    }
  }

  required_version = ">= 1.1.0"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "analytics" {
  name     = "test-analytics-rg"
  location = "West Europe"
}
```

```hcl
# databricks.tf
resource "azurerm_databricks_workspace" "analytics" {
  name                              = "test-analytics-databricks-ws"
  location                          = "West Europe"
  resource_group_name               = azurerm_resource_group.analytics.name
  sku                               = "premium"
  managed_resource_group_name       = "test-analytics-databricks-rg"
  *infrastructure_encryption_enabled = true*  # this here is changed from false to true

  custom_parameters {
    storage_account_name = substr(replace("test-analytics-dbfs", "/[^a-z\\d]/", ""), 0, 24)
  }
}

provider "databricks" {
  host                        = azurerm_databricks_workspace.analytics.workspace_url
  azure_workspace_resource_id = azurerm_databricks_workspace.analytics.id
}

resource "databricks_cluster" "analytics-superset" {
  cluster_name            = "superset"
  idempotency_token       = "superset"
  spark_version           = "9.1.x-scala2.12"
  node_type_id            = "Standard_DS3_v2"
  autotermination_minutes = 0
  spark_env_vars = {
      PYSPARK_PYTHON = "/databricks/python3/bin/python3"
    }
  spark_conf = {
    "spark.databricks.repl.allowedLanguages": "python,sql",
    "spark.databricks.passthrough.enabled": "true",
    "spark.sql.legacy.timeParserPolicy": "LEGACY",
    "spark.databricks.cluster.profile": "singleNode",
    "spark.master" : "local[*]",
    "spark.databricks.io.cache.compression.enabled": "true",
  }
  custom_tags = {
    "ResourceClass" = "SingleNode"
  }

  depends_on = [
    azurerm_databricks_workspace.analytics
  ]
}
```

### Expected Behavior
"terraform plan" tells me that the workspace has to be re-created... "terraform apply" re-creates the workspace and afterwards, infrastructure-encryption is enabled.

### Actual Behavior
"terraform apply" fails with
"Error: cannot read cluster: authentication is not configured for provider. Please check https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication for details"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Run "terraform apply" on the above example with "infrastructure_encryption_enabled = false"
2. Change the setting to "infrastructure_encryption_enabled = true" and run "terraform plan"

### Terraform and provider versions
Terraform v1.2.5
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.1.0
+ provider registry.terraform.io/hashicorp/azurerm v3.15.0

**Comment by nfx** [comment]
@gbusch this is how terraform works and is not particularly related to this provider. Please try the following and update back the issue:

a. add `depends_on = [azurerm_databricks_workspace.analytics]` to every databricks resource, this is hacky, you may forget it here and there, but it should work. 
a. move `databricks_cluster` to a separate module and perform the similar changes.

**Comment by gbusch** [comment]
Thanks for the prompt reply, Serge.
I did already have "depends_on" in the example above and also moving the cluster definition to a module does not help unfortunately.
Any other ideas/suggestions?
If Github Issues is not the right place to discuss it, let me know where to move the discussion to.

**Comment by nfx** [comment]
@gbusch  please raise this on terraform issue tracker.

**Comment by gbusch** [comment]
So to summarize, the only option I have at the moment (checked out old issues with label "lazy auth" and it sounds like this is a terraform issue that I cannot hope for a fix soon):
* Destroy all resources that are dependent on the workspace (and provider)
* change the workspace 
* set up the provider and dependent resources new.

Since re-creation of the workspace will also delete the associated storage-account with the DBFS, can you - by any chance - refer me to a resource that explains how to backup this data? Apparently the storage account is managed by Databricks and therefore, I cannot give me blob-contributor role which would be necessary to simply azcopy the data.
