### ISSUE TITLE
[ISSUE] Granting permissions to an MLflow model removes manage permissions from MLflow model creator by default

### ISSUE THREAD

**Issue by smurching** [databricks/terraform-provider-databricks#1504]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
I'm currently applying the following Terraform config, authenticating to Databricks using an Azure service principal.

```hcl
resource "databricks_mlflow_model" "registered_model" {
  name = "staging-mlops-azure-demo-model"
  description = "My MLflow model description"
}

resource "databricks_permissions" "mlflow_model_permissions" {
  registered_model_id = databricks_mlflow_model.registered_model.registered_model_id

  access_control {
    group_name       = "${local.read_user_group}"
    permission_level = "CAN_READ"
  }
}
```

### Expected Behavior
What should have happened?

I would expect that a) the registered model is created and b) that the "users" group is granted read access to the model in addition to c) preserving `CAN_MANAGE` permissions on the model for the service principal that created the model.

### Actual Behavior
a) and b) do happen, but c) does not. The configuration removes `CAN_MANAGE` permissions from the Databricks service principal applying Terraform changes, resulting in the following error:

```
╷
│ Error: cannot create permissions: *** does not have Owner permissions on 4e4cd6a8cafe4a14b942d236dc804f7c. Please contact the owner or an administrator for access. Using pat auth: host=https://adb-1173035118216611.11.azuredatabricks.net/, token=***REDACTED***
│ 
│   with databricks_permissions.mlflow_model_permissions,
│   on permissions.tf line 28, in resource "databricks_permissions" "mlflow_model_permissions":
│   28: resource "databricks_permissions" "mlflow_model_permissions" {
│ 
╵
```

Users are successfully granted read permissions, but the model is shown to be managed only by admins in the UI:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/2358483/181435373-6ea59726-3091-4ca4-9e32-b149d47a5e4f.png">

For MLflow models (seemingly also Databricks clusters), you can remove `CAN_MANAGE` permissions on the model owner (creator), without specifying another owner. This means that if you declare permissions on a model using infra as code, it’s pretty easy to create a model and accidentally remove the owner’s permissions, as shown in the above example. There is a user-code fix which is to explicitly grant the current service principal manage permissions on the model, but this is counterintuitive & a little brittle (requires knowing whether the user applying the Terraform config is a normal user vs service principal):

```
data "databricks_current_user" "current_sp" {}

resource "databricks_permissions" "mlflow_model_permissions" {
  registered_model_id = databricks_mlflow_model.registered_model.registered_model_id

  access_control {
    group_name       = "${local.read_user_group}"
    permission_level = "CAN_READ"
  }
  // New: preserve CAN_MANAGE permissions on the model for the current user
  access_control {
    service_principal_name       = data.databricks_current_user.current_sp.user_name
    permission_level = "CAN_MANAGE"
  }
}
```

I'm curious if this issue also affects clusters which have a similar permission model to MLflow models. If no, I wonder if we can reuse the fix for clusters for MLflow models. Either way, it seems we should also consider updating the underlying permissions REST APIs to ensure that there is always an owner of the MLflow model with `CAN_MANAGE` permissions, similar to [Databricks job permissions](https://docs.databricks.com/security/access-control/jobs-acl.html), but that may be further away

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions
Terraform version:

```
Terraform v1.2.2
on darwin_amd64
```

Provider version: 1.1.0

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by smurching** [comment]
I looked into this a little - it seems for jobs specifically, we have logic in the provider to inject the current user as an owner (with `IS_OWNER` permissions) if no owners are specified in the Terraform config, [see here](https://github.com/databricks/terraform-provider-databricks/blob/c72250b58ca18883fd62745902cbdd33eb881527/permissions/resource_permissions.go#L166-L170)

I wonder if we should do the same for models and clusters (grant current user `CAN_MANAGE` permissions if no `CAN_MANAGE` permissions are specified in the Terraform config) - @nfx @nkvuong what do you think?

**Comment by nfx** [comment]
`CAN_MANAGE` on clusters even has own old issue - #1139

@smurching yes, please make a PR. please make sure to test it with non-admin user/spn. Soon i'll have "non-admin" in our terraform testing infra.

**Comment by nkvuong** [comment]
@smurching I think [this](https://github.com/databricks/terraform-provider-databricks/blob/c72250b58ca18883fd62745902cbdd33eb881527/permissions/resource_permissions.go#L129) is the more appropriate workaround - adding `CAN_MANAGE` permission for the calling user for SQLA entities

Can we check if this issue also applies to other MLflow objects?

**Comment by smurching** [comment]
> I think [this](https://github.com/databricks/terraform-provider-databricks/blob/c72250b58ca18883fd62745902cbdd33eb881527/permissions/resource_permissions.go#L129) is the more appropriate workaround - adding CAN_MANAGE permission for the calling user for SQLA entities

Makes sense, we came to the same realization - we want the calling user to unconditionally have `CAN_MANAGE` permissions even if the config grants `CAN_MANAGE` to other users/principals - anyways the calling user needs `CAN_MANAGE` permissions to manage permissions on the resource in the first place.

**Comment by smurching** [comment]
> Can we check if this issue also applies to other MLflow objects?
For sure - I think it does apply to MLflow experiments other MLflow objects (namely MLflow experiments), but in a niche way.  Experiment permissions are governed by the workspace. In order to configure permissions on an experiment, the calling user needs either a) `CAN_MANAGE` permissions on one of the experiment's parent directories (the typical case) or b) `CAN_MANAGE` permissions on the experiment itself. In scenario a), the `CAN_MANAGE` permission is inherited from the parent directory and so can't be removed by configuring experiment permissions.

In scenario b), e.g. an admin creates an experiment and grants the calling user `CAN_MANAGE` permissions on just the experiment, I think it is actually possible for the calling user to inadvertently remove their own `CAN_MANAGE` permissions. This should also hold for other workspace objects (notebooks, folders, etc). But it seems like a lower priority to fix since usually permissions are inherited from the parent directory

**Comment by smurching** [comment]
@arpitjasa-db also called out another issue with the proposed workaround, namely that for resources created by a different user from the calling user (e.g. say I create a model as sid@company.com and then import it into Terraform + manage it and deploy it via a service principal), we may still inadvertently remove `CAN_MANAGE` permissions for the original resource creator, e.g. sid@company.com in this case, effectively transferring ownership to the calling service principal. 

I think in that case though we should be able to detect the change and show the diff during `terraform plan`, which should help mitigate a bit

**Comment by arpitjasa-db** [comment]
@smurching actually if we're only creating the permissions object, we don't have to import the model into the state, so you can overwrite permissions without seeing a diff during `terraform plan`

**Comment by arpitjasa-db** [comment]
@smurching and I synced offline and agree that the solution that makes most sense is similar to what jobs does, in that we just add the current user to have `CAN_MANAGE` permissions on the model/experiment.
