### ISSUE TITLE
[DOC] cluster_log_conf does not accept s3a://

### ISSUE THREAD

**Issue by Israphel** [databricks/terraform-provider-databricks#1517]
### Affected Resource(s)

[cluster](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster)

### Expected Details

cluster_log_conf says you can use s3a:// but you get an error if you use it, telling you to use s3://

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
[line with the issue](https://github.com/databricks/terraform-provider-databricks/blob/master/docs/resources/cluster.md?plain=1#L227)

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
