### ISSUE TITLE
[ISSUE] Cluster is created in wrong workspace

### ISSUE THREAD

**Issue by pgruetter** [databricks/terraform-provider-databricks#1520]
### Configuration
```hcl
resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Autoscaling"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 3
  }
  is_pinned = true
  depends_on = [azurerm_databricks_workspace.adb]
}

```

### Expected Behavior
The cluster is created in the workspace mentioned in `depends_on`. 

### Actual Behavior
The cluster is actually created in a completely different workspace in the same Azure subscription. 
The "other" cluster was created first, but not with Terraform. 

### Steps to Reproduce (high level)
1. Create Databricks Workspace manually (or using az cli) in an Azure subscription
2. Use Terraform to create a second Databricks Workspace in the same subscription. It gets created correctly.
3. Extend Terraform scripts with the section above (Configuration) to create a cluster in the new workspace
4. The cluster is created in the workspace from step 1 that wasn't even created with Terraform.

### Terraform and provider versions
```
Terraform v1.2.5
on linux_386
+ provider registry.terraform.io/databricks/databricks v1.2.0
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
```

**Comment by nkvuong** [comment]
@pgruetter what is your provider block? this issue suggests an incorrect provider definition

```hcl
provider "databricks" {
}
```

**Comment by pgruetter** [comment]
@nkvuong Thanks for the quick reply. Here's the provider block:
```hcl
provider "databricks" {
  alias                       = "db"
  azure_workspace_resource_id = azurerm_databricks_workspace.adb.id
}
```
I now saw there is an example that uses
```hcl
host = azurerm_databricks_workspace.adb.workspace_url
```
but if I insert that, `terraform plan` just hangs.

**Comment by nkvuong** [comment]
so your provider block is now
```hcl
provider "databricks" {
  alias                       = "db"
  host = azurerm_databricks_workspace.adb.workspace_url
}
```

then you need to specify 
```hcl
provider = databricks.db
```
in your resource definition

**Comment by pgruetter** [comment]
Yes, that worked!
Thanks a lot for your support. Pretty new to Terraform, appreciate the help. 👍
