### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource

### ISSUE THREAD

**Issue by scm-vivek-singh** [databricks/terraform-provider-databricks#1527]
### Configuration
```hcl
# Copy-paste your Terraform configuration here
```

resource "databricks_job" "this" {
  provider = databricks.mws
  name     = var.job_name
  format   = var.format
  dynamic "task" {
    for_each = var.tasks
    content {
      task_key = task.value.task_key
      max_retries = task.value.max_retries
      min_retry_interval_millis = task.value.min_retry_interval_millis
      retry_on_timeout = task.value.retry_on_timeout
      timeout_seconds = task.value.timeout_seconds
      description = task.value.description
      existing_cluster_id = try(lookup(task.value, "cluster_id", null))
      job_cluster_key = task.value.job_cluster_key
      **depends_on {
        task_key = task.value.depends_on_task_key
      }**

### Expected Behavior

It should be looking for depends_on with query "settings.task.depends_on.task_key" as the block is called as task in job resource.
### Actual Behavior

It searches depends_on with query "settings.tasks.depends_on.task_key" and throws error "Missing required field: settings.tasks.depends_on.task_key"

note- point of concern is the 's' in tasks here.
### Terraform and provider versions

terraform version - 1.1.8
databricks provider - 1.2.0

**Comment by alexott** [comment]
Please provide an example of your tasks variable...

**Comment by scm-vivek-singh** [comment]
tasks = {
    task-1 = {
      task_key = "wna"
      job_cluster_key = null
      depends_on_task_key = ""
      notebook_path = "/Repos/user/a-nz-pipeline"
      base_parameters = {}
      cluster_name = ""
      spark_version = "9.1.x-scala2.12"
      spark_conf = {
        "spark.master": "local[*, 4]"
        "spark.databricks.cluster.profile": "singleNode"
      }
      aws_attributes = {
        first_on_demand = 1
        availability = "SPOT_WITH_FALLBACK"
        zone_id = "eu-west-1b"
        spot_bid_price_percent = 100
      }
      node_type_id = "i3.xlarge"
      driver_node_type_id = "i3.xlarge"
      custom_tags = {
        ResourceClass = "SingleNode"
      }
      spark_env_vars = {
      "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
    }
      enable_elastic_disk = true
      num_workers = 0
      max_retries = 1
      min_retry_interval_millis = 300000
      retry_on_timeout = true
      timeout_seconds = 0
      email_notifications = {}
      description = ""

    },
    task-2 = {
      task_key = "wg"
      depends_on_task_key = "wna"
      job_cluster_key = null
      notebook_path = "/Repos/user/b-pipeline"
      base_parameters = {}
      cluster_name = ""
      spark_version = "9.1.x-scala2.12"
      spark_conf = {
        "spark.master": "local[*, 4]",
        "spark.databricks.cluster.profile": "singleNode"
      }
      aws_attributes = {
        first_on_demand = 1
        availability = "SPOT_WITH_FALLBACK"
        zone_id = "eu-west-1b"
        spot_bid_price_percent = 100
      }
      node_type_id = "i3.xlarge"
      driver_node_type_id = "i3.xlarge"
      custom_tags = {
        ResourceClass = "SingleNode"
      }
      spark_env_vars = {
        "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
      }
      enable_elastic_disk = true
      num_workers = 0
      max_retries = 2
      min_retry_interval_millis = 300000
      retry_on_timeout = true
      timeout_seconds = 0
      email_notifications = {}
      description = ""
    },
    task-3 = {
      task_key = "w"
      depends_on_task_key = "wg"
      job_cluster_key = null
      notebook_path = "/Repos/user/s-pipeline"
      base_parameters = {}
      cluster_name = ""
      spark_version = "9.1.x-scala2.12"
      spark_conf = {
        "spark.master": "local[*, 4]",
        "spark.databricks.cluster.profile": "singleNode"
      }
      aws_attributes = {
        first_on_demand = 1
        availability = "SPOT_WITH_FALLBACK"
        zone_id = "eu-west-1b"
        spot_bid_price_percent = 100
      }
      node_type_id = "i3.xlarge"
      driver_node_type_id = "i3.xlarge"
      custom_tags = {
        ResourceClass = "SingleNode"
      }
      spark_env_vars = {
        "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
      }
      enable_elastic_disk = true
      num_workers = 0
      max_retries = 2
      min_retry_interval_millis = 300000
      retry_on_timeout = true
      timeout_seconds = 0
      email_notifications = {}
      description = ""
    },
    task-3 = {
      task_key = "v"
      depends_on_task_key = "w"
      job_cluster_key = "j_cluster"
      notebook_path = "/Repos/user/r-pipeline"
      base_parameters = {}
      cluster_name = ""
      spark_version = "9.1.x-scala2.12"
      spark_conf = {
        "spark.master": "local[*, 4]",
        "spark.databricks.cluster.profile": "singleNode"
      }
      aws_attributes = {
        first_on_demand = 1
        availability = "SPOT_WITH_FALLBACK"
        zone_id = "eu-west-1b"
        spot_bid_price_percent = 100
      }
      node_type_id = "i3.xlarge"
      driver_node_type_id = "i3.xlarge"
      custom_tags = {
        ResourceClass = "SingleNode"
      }
      spark_env_vars = {
        "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
      }
      enable_elastic_disk = true
      num_workers = 0
      max_retries = 2
      min_retry_interval_millis = 300000
      retry_on_timeout = true
      timeout_seconds = 0
      email_notifications = {}
      description = ""
    }
  }

**Comment by scm-vivek-singh** [comment]
Got resolved.
I was passing wrong depends_on. Thanks for the time.
