### ISSUE TITLE
[FEATURE] Create another terraform job resource

### ISSUE THREAD

**Issue by scm-vivek-singh** [databricks/terraform-provider-databricks#1528]
### Use-cases

Databricks job is very complicated and its difficult to create a complicated job directly from a terraform. 
### Attempted Solutions

I attempted this, by creating a job.json file by exporting from databricks cli (#databricks jobs get  --job-id 1234 --profile dev > sample-pipeline.json).
Then I created a data template to for sample-pipeline.json and variablzed few imp variables.
Then I created a null resource to run command "databricks jobs create --json-file ./sample-pipeline.json --profile ${var.environment}" where I also passed all the variables in trigger to detect changes in variables

data "template_file" "sample" {
  template = file("${path.module}/jobs/sample-pipeline.json")
  vars = {
    env    = "dev"
    cron   = "17 0 0/2 * * ?"
    notebook_path_1 = "/Repos/user1@domain/sample/sample-pipeline1"
    notebook_path_2 = "/Repos/user1@domain/sample/sample-pipeline2"
  }
}

resource "null_resource" "sample_pipeline-cli" {
  pipeline = data.template_file.sample
  provider = null
  depends_on = [null_resource.databricks-cli, module.databricks_workspace]
  triggers = data.template_file.sample.vars
  provisioner "local-exec" {
    when    = "create"
    command =<<EOT
cat > pipeline.json <<EOF
${data.template_file.sample.rendered}
EOF
    databricks jobs create --json-file ./pipeline.json --profile ${var.environment};
    rm pipeline.json
  EOT
}
}

**Comment by alexott** [comment]
No, you misuse Terraform... Pipeline definition and other things are easy to create from Terraform - just follow [documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline).

**Comment by alexott** [comment]
If you have specific questions about Terraform provider usage, ask them at https://community.databricks.com/
