### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster_policy` resource

### ISSUE THREAD

**Issue by PreetiCK** [databricks/terraform-provider-databricks#1529]
### Configuration
```hcl
 resource "databricks_cluster_policy" "test_processing_policy" {
  count      = (var.execute_microservice && var.create_default_cluster_policy) ? 1 : 0
  provider   = databricks.workspace
  name       = "TEST Processing Policy"
  definition = data.template_file.test_processing_policy[0].rendered
}
```

### Expected Behavior
Should create policy

### Actual Behavior
Getting below deadlock error

### Terraform and provider versions
Terraform v0.13.7
Databricks v0.3.4
(https://github.com/databricks/terraform-provider-databricks/releases), please make sure to use the latest one. -->

### Debug Output
Error: Unexpected error. Message: java.sql.SQLTransactionRollbackException: (conn=23309085) Deadlock found when trying to get lock; try restarting transaction

  on ../../cluster_policy_creation.tf line 123, in resource "databricks_cluster_policy" "test_processing_policy":
 123: resource "databricks_cluster_policy" "test_processing_policy" {

**Comment by alexott** [comment]
It's a platform problem, should be remediated by the platform team

P.S. It's better to upgrade terraform provider - this version is at least 1 year old

**Comment by PreetiCK** [comment]
This error is not consistent on particular resource. 
First terraform apply run gives error on different cluster policy resources everytime
Rerunning apply command completes the provision.

Is this because terraform is trying to create multiple resources at same time?

**Comment by alexott** [comment]
by default, Terraform tries to perform all independent operations in parallel...
