### ISSUE TITLE
Azure KeyVault-based secret scope

### ISSUE THREAD

**Issue by AarthiGowdhaman** [databricks/terraform-provider-databricks#1531]
### Configuration
```hcl
# Trying to create Azure KeyVault-based secret scope for databricks in Terraform. Received error as Error: you can't set up Azure KeyVault-based secret scope via Service Principal. Please let me know how to fix this
```

**Comment by alexott** [comment]
It's well [documented](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/secret_scope#keyvault_metadata). Right now you can't do this because it's not implemented on Azure. As soon as it will be supported by platform, this limitation will go away
