### ISSUE TITLE
[ISSUE] Issue with data `databricks_node_type` (Azure) while setting local_disk = true 

### ISSUE THREAD

**Issue by pratik-databricks** [databricks/terraform-provider-databricks#1533]
When we set local_disk=true in data “databricks_node_type” to fetch the node, it picks up unsupported node(Standard_L8as_v3) in the region (Central India) as well. 

While the [list-node-types](https://docs.databricks.com/dev-tools/api/latest/clusters.html#list-node-types) API is called in the process and receives the below status for that unsupported node in the response **(for Azure)**- 

"node_info": {
        "status": [
          "NotEnabledOnSubscription",
          "NotAvailableInRegion"
        ]
}

The data “databricks_node_type” doesn’t honor the "NotAvailableInRegion" status for that node_type_id and give that as a response. 

_Went through the [provider code](https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/data_node_type.go) and doesn’t look like the exception is handled._

### Configuration
```hcl
data "databricks_node_type" "smallest" {
  local_disk = true
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Shared Autoscaling"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 50
  }
}
```

### Expected Behavior
The node_type_id returned via data "databricks_node_type" should be a supported one in that region. (Azure)

### Actual Behavior
It is returning unsupported nodes too, for e.g Standard_L8as_v3 in Central India (Azure)

Error thrown is - 
Could not launch cluster due to cloud provider failures. azure_error_code: InvalidParameter, azure_error_message: The requested VM size Standard_L8as_v3 is not available in the current region. The ..., Termination info: code: CLOUD_PROVIDER_LAUNCH_FAILURE, type: CLOUD_FAILURE, parameters: map[azure_error_code:InvalidParameter azure_error_message:The requested VM size Standard_L8as_v3 is not available in the current region. 

### Steps to Reproduce
You can run the above code in a workspace region where the Standard_L8as_v3 node is not supported.

### Debug Output
https://gist.github.com/pratik-databricks/d92103543eeb7f21b6ef6358233687cb

**Comment by alexott** [comment]
Can you collect debug logs with DATABRICKS_DEBUG_TRUNCATE_BYTES=250000 as described in https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting

**Comment by pratik-databricks** [comment]
As discussed, here is the API response of /api/2.0/clusters/list-node-types 
https://gist.github.com/pratik-databricks/b913ac3811f0aa447f0dd55e825f1317
