### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource

### ISSUE THREAD

**Issue by bjgbeelen** [databricks/terraform-provider-databricks#1542]
### Configuration
```hcl
resource "databricks_job" "job" {

  task {
    task_key        = "task_A"
    ...
  }

  task {
    task_key        = "task_B"
    ...
  }
}
```

### Expected Behavior
If I don't make any code change to the above (simplified) resource, I don't want terraform to take any action on this resource

### Actual Behavior
A `terraform plan` results in:

```
Plan: 0 to add, 1 to change, 0 to destroy.

 ~ task {
          ~ task_key                  = "task_A" -> "task_B"
    }

 ~ task {
          ~ task_key                  = "task_B" -> "task_A"
    }
```

So, it tries to completely swap the two tasks everytime. I would expect it would somehow recognise each task by it's task_key and check for changes there?

### Steps to Reproduce

```
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.2.0
+ provider registry.terraform.io/hashicorp/google v4.31.0

Your version of Terraform is out of date! The latest version
is 1.2.7. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by nkvuong** [comment]
This is a limitation in how Terraform handles diff. From the [doc](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#jobs-with-multiple-tasks)

> In terraform configuration, it is recommended to define tasks in alphabetical order of their task_key arguments, so that you get consistent and readable diff. Whenever tasks are added or removed, or task_key is renamed, you'll observe a change in the majority of tasks. It's related to the fact that the current version of the provider treats task blocks as an ordered list. Alternatively, task block could have been an unordered set, though end-users would see the entire block replaced upon a change in single property of the task

**Comment by bjgbeelen** [comment]
Ah ok, thanks for pointing this out!
Just tested the suggested approach and indeed results in expected behaviour when I organize them alphabetically.
Closing the issue then!
