### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_permissions` resource

### ISSUE THREAD

**Issue by mrh-jishan** [databricks/terraform-provider-databricks#1546]
### Configuration
```hcl
# Copy-paste your Terraform configuration here
 + resource "databricks_sql_permissions" "acl" {
      + catalog    = true
      + cluster_id = "xxx"
      + database   = "db"
      + id         = (known after apply)
      + table      = "table"
      + privilege_assignments {
          + principal  = "xxx@example.com"
          + privileges = [
              + "CREATE",
              + "SELECT",
            ]
        }
    }
```

### Expected Behavior

should create sql as below 

GRANT CREATE, SELECT ON TABLE `db`.`table` TO `xxx@example.com`

### Actual Behavior

GRANT CREATE, SELECT ON TABLE `hive_metastore `.`db`.`table` TO `xxx@example.com`

### Steps to Reproduce

use terraform for databricks_sql_permissions where unity catalog is not configured and use external hive meta-store.

### Terraform and provider versions

terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.2.0"
    }
  }
  required_version = ">= 1.2.0"
}

### Debug Output

Error: cannot create sql permissions: cannot execute GRANT CREATE, SELECT ON TABLE `overwatch_etl`.`job_gold` TO `xxx@example`: Action CREATE cannot be granted on table `hive_metastore`.`db`.`table`
│ 
│   with module.overwatch_access.databricks_sql_permissions.acl["overwatch_etl-job_gold"],
│   on ../acl-access/main.tf line 17, in resource "databricks_sql_permissions" "acl":
│   17: resource "databricks_sql_permissions" "acl" {
### Important Factoids

use databricks acl cluster and use external meta-store

**Comment by alexott** [comment]
Do you have unity catalog enabled?  Your cluster has all necessary configuration for hive metastore?

**Comment by mrh-jishan** [comment]
no, the unity catalog is not enabled and we have external hive meta-store configured.

**Comment by theesen** [comment]
As additional info ... the external hive metastore is configured using a global init script for all clusters.
```sh
#!/bin/sh
cat << EOF > /databricks/driver/conf/00-custom-spark.conf
[driver] {
    "spark.hadoop.hive.metastore.uris" = "thrift://metastore.some.domain:9083"
    "spark.sql.hive.metastore.version" = "$HIVE_VERSION"
    "spark.sql.hive.metastore.jars" = "/databricks/hive_metastore_jar/*"
    "hive.metastore.warehouse.dir" = "s3a://our-data-warehouse-s3-bucket/warehouse/"
}
EOF

```
