### ISSUE TITLE
[FEATURE] Support policies in DLT pipelines

### ISSUE THREAD

**Issue by kirksw** [databricks/terraform-provider-databricks#1551]
We use policies to manage the configurations/cost of clusters in our environments (including dlt pipelines), so that users can create their own pipelines within the guards we have set.

I can see currently that the provider doesn't support using policies with dlt pipelines, when will it be added?

**Comment by alexott** [comment]
Have you checked if it’s available in the rest api? I don’t see policy related things here: https://docs.databricks.com/workflows/delta-live-tables/delta-live-tables-api-guide.html#pipeline-spec

**Comment by kirksw** [comment]
We use it currently via the rest api (cluster.policy_id property) using a custom deployment library I whipped together, was hoping to move it to terraform now that the provider was GA.

**Comment by alexott** [comment]
Ah, sorry. It’s on cluster level - it’s easy to add…
