### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource

### ISSUE THREAD

**Issue by tomarv2** [databricks/terraform-provider-databricks#1559]
Databricks permissions for job lists `id`. However when looking at `databricks_job` resource. I only see job `url` and not job `id` in output. 
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permissions

### Configuration
```hcl
resource "databricks_job" "this" {
  name                = "Featurization"
  max_concurrent_runs = 1

  new_cluster {
    num_workers   = 300
    spark_version = data.databricks_spark_version.latest.id
    node_type_id  = data.databricks_node_type.smallest.id
  }

  notebook_task {
    notebook_path = "/Production/MakeFeatures"
  }
}

resource "databricks_permissions" "job_usage" {
  job_id = databricks_job.this.id

  access_control {
    group_name       = "users"
    permission_level = "CAN_VIEW"
  }
```

[Exported attributes](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#exported-attributes)
In addition to all arguments above, the following attributes are exported:

[url](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#url) - URL of the job on the given workspace

**Comment by alexott** [comment]
All terraform resources have `id` attribute - it's really required by terraform, and you can't omit it
