### ISSUE TITLE
[ISSUE] Issue with `databricks_notebook` resource

### ISSUE THREAD

**Issue by Koalion** [databricks/terraform-provider-databricks#1563]
Hi, below is the description of my current issue with databricks provider deployment, is there something you could help me here with?

### Configuration
terraform {
  backend "azurerm" {}

  required_providers {
    random     = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    time       = {
      source  = "hashicorp/time"
      version = "~> 0.7.0"
    }
    azurerm    = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.2"
    }
  }
  required_version = "~> 1.2.8"
}

I have TF state configured on a remote storage account on Azure

The whole deployment consists of around 5 databricks_notebooks and then some other data objects for configuration.

### Expected Behavior
terraform plan working properly for several databricks_notebook resources

### Actual Behavior
error during terraform plan. Refreshing state of all azurerm objects goes ok, but there is a problem with refreshing objects (data and resource) from 

│ Error: Plugin did not respond
│
│   with data.databricks_notebook_paths.uc_common,
│   on data.tf line 3, in data "databricks_notebook_paths" "uc_common":
│    3: data "databricks_notebook_paths" "xxx" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-databricks_v1.2.0.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "1348226433712416": value out of range

goroutine 100 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x1287ed70, {0x12d58a78, 0x1, 0x1}, 0x8)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x1287ed70)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:351 +0x3a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x12d5f260, {{{0xe0da4c, 0x12d586d8}}, {0xbe9440, 0x12b8b640}})
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x12f10000, {0xe0d4ec, 0x12f26438}, 0x12b8aec0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x12ea6000, {0xe0d4ec, 0x12f26168}, 0x12d04240)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:747 +0x44d
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xca1960, 0x12ea6000}, {0xe0d4ec, 0x12f26168}, 0x12f1a140, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x12cf6240, {0xe0f0d8, 0x12902120}, 0x12ee6140, 0x12eac000, 0x13545e8, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1295 +0xaab
google.golang.org/grpc.(*Server).handleStream(0x12cf6240, {0xe0f0d8, 0x12902120}, 0x12ee6140, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1636 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:932 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:930 +0x25f

Error: The terraform-provider-databricks_v1.2.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
### Debug Output
There is a full stack trace above, so i hope that is enough, but please let me know if you need more information

### Important Factoids
The number on which ParseInt crashes (1348226433712416) is actually object id of one of the notebooks from the state file.
It seems the issue may be caused by difference between operating systems - the state file was created on linux Azure devops agent (wth the same terraform code as above - and this works properly. The problem arises when i try to recreate the same deployment on my local windows machine. When i delete the databricks_notebook from the state and then import them again, the deployment seems to work again for both local and devops deployments.

**Comment by alexott** [comment]
Do you have 64-bit windows?

**Comment by Koalion** [comment]
Hi, I had a weird flush of inspiration and looked into terraform version i should actually use. I changed the terraform version from _386 to _amd64 and everything works fine now, sorry for the bother!
