### ISSUE TITLE
[FEATURE] Provide purge flag for databricks_schema

### ISSUE THREAD

**Issue by neil90** [databricks/terraform-provider-databricks#1576]
Currently when doing a terraform destroy if there are existing tables the schema can't be destroyed, it would be ideal if there was a purge flag so if when set to true it will go through and drop all tables in schema when its being destroyed. See databricks-cli for purge functionality https://docs.databricks.com/dev-tools/cli/unity-catalog-cli.html#delete-a-schema

**Comment by neil90** [comment]
What would be best practice here then? use Provisioner on the databricks_schema resource that on when_destroy run a script that drops the tables?

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
