### ISSUE TITLE
Cluster Libraries are not ordered

### ISSUE THREAD

**Issue by davidglevy** [databricks/terraform-provider-databricks#1585]
As per the title, there is no ordering applied to libraries and it is a "surprise" with the underlying object being a Set rather than a List. This causes unpredictable results. For some configurations this may be harmless but can also result in clusters failing to provision.

Expectation is that library ordering in Terraform cluster definition is mapped to the order within the cluster provisioned.

**Comment by nfx** [comment]
@davidglevy  there are no guarantees of libraries being installed in a certain order on the api level. please use [databricks_library](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/library) with `depends_on` attributes to achieve what you're describing.

**Comment by edwardfeng-db** [comment]
Fixed in https://github.com/databricks/terraform-provider-databricks/pull/3398
