### ISSUE TITLE
Terraform on aws databricks workspace deployment throwing below error 

### ISSUE THREAD

**Issue by karthik-apisero** [databricks/terraform-provider-databricks#1586]
HI Team,

when we are executing terraform modules to deploy workspace, we are seeing below issue 

Error: cannot create mws storage configurations: INVALID_STATE: Storage configuration limit exceeded, only 50 storage configurations are allowed

do we have any limit for storage configurations for aws databricks

**Comment by stikkireddy** [comment]
all AWS Databricks platform limits are documented here: https://docs.databricks.com/resources/limits.html#limits
