### ISSUE TITLE
Unable to set properties for UC Catalogs

### ISSUE THREAD

**Issue by niraj8241** [databricks/terraform-provider-databricks#1593]
It seems like the UC [catalog resource](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/catalog#example-usage) does not set the *"properties"* value. By looking at the databricks documentation [here](https://docs.databricks.com/data-governance/unity-catalog/create-catalogs.html). It doesn't seem like the property value exist for the catalogs. I do see that the same exists for the [schema](https://docs.databricks.com/data-governance/unity-catalog/create-schemas.html#language-SQL) resource.

**Comment by nkvuong** [comment]
@niraj8241 the properties value of a catalog is available in the backend, as documented in the API spec [here](https://api-docs.databricks.com/rest/latest/unity-catalog-api-specification-2-1.html)

Currently this is not exposed via the UI or the SQL syntax like for the schema resource

**Comment by niraj8241** [comment]
@nkvuong Thanks for the info. Appreciate the response.
