### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster_policy` resource - Unsupported path enable_elastic_disk was provided

### ISSUE THREAD

**Issue by DougEspindola** [databricks/terraform-provider-databricks#1596]
### Configuration
```hcl
  "enable_elastic_disk": {
    "type": "fixed",
    "value": "true",
    "hidden": true
  },
```

### Expected Behavior
the value of enable_elastic_disk was expected to be fixed and hidden

### Actual Behavior
After apply the configuration I tried to use my cluster police and faced this **error:** Cluster policy is invalid as unsupported path enable_elastic_disk was provided

<img width="251" alt="Screenshot 2022-09-02 at 12 17 09" src="https://user-images.githubusercontent.com/97887493/189742779-50306fe5-2d12-4e6a-baeb-1becac9b72db.png">

### Steps to Reproduce

1. terraform apply in cluster policy configuration with enable_elastic_disk using the configurations above.
2. open azure Databricks UI and try to create a cluster using the policy created previously
3. you will face the error **Cluster policy is invalid as unsupported path enable_elastic_disk was provided**  when trying to select the police that was created.

### Terraform and provider versions
 Terraform v1.1.3
 databricks = {
    source  = "databricks/databricks"
    version = "=1.0.2"
  }

### Important Factoids
I'm using the Databricks on azure.

I don't face any problem applying the configuration itself, but I have the error when I use the configuration that was applied through terraform. image below:
<img width="251" alt="Screenshot 2022-09-02 at 12 17 09" src="https://user-images.githubusercontent.com/97887493/189742779-50306fe5-2d12-4e6a-baeb-1becac9b72db.png">

**Comment by alexott** [comment]
Does this cluster policy work if you create it via UI?

**Comment by DougEspindola** [comment]
Hi @alexott,

After try to create through the UI I faced this: **Policy field enable_elastic_disk is unavailable on your cloud platform.** In that case I think the limitation is in the Azure side and not in the Databricks provider side, right?

**Comment by alexott** [comment]
Yes, it's a limitation on Azure side. Usually if you see such problems, it's a platform issue, because Terraform mostly wraps REST APIs...
