### ISSUE TITLE
Question: Has auto availability zone selection been implemented?

### ISSUE THREAD

**Issue by didopop3** [databricks/terraform-provider-databricks#1601]
Just wondering if setting the zone_id value to "auto" to enable the automatic availability zone selection feature has been implemented? Databricks API docs here [here ](https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterawsattributes)

OR if set zone_id to a region, say "eu-west-1", will enable automatic availability zone selection in that region?

**Comment by nfx** [comment]
yes, it was implemented [9 months ago](https://github.com/databricks/terraform-provider-databricks/blame/master/clusters/resource_cluster.go#L50-L56)
