### ISSUE TITLE
databricks_storage_credential | Unsupported argument for azure_managed_identity

### ISSUE THREAD

**Issue by anumanlap** [databricks/terraform-provider-databricks#1608]
We are getting the following error wile we try to create databricks storage credentials

```
Error: Unsupported argument

  on main.tf line 3, in resource "databricks_storage_credential" "storage_credential":
   3:   azure_managed_identity = {

An argument named "azure_managed_identity" is not expected here.
```

here is the code I am using:

```
resource "databricks_storage_credential" "storage_credential" {
  name = "torage_credential_mi"
  azure_managed_identity {
    access_connector_id = var.access_connector_id
  }
  comment = "Managed identity credential"
}
```

**Comment by anumanlap** [comment]
Appreciate if the issue can be resolved at the earliest.

**Comment by anumanlap** [comment]
We are using the following providers as listed below. I have tested with terraform v0.13.0 and v1.2.9 with  no luck
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.92.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~>2.15.0"
    }
    databricks = {
      source  = "databrickslabs/databricks"
      version = "~>0.4.0"
    }
  }
}

provider "azuread" {
  tenant_id = "XXXXXX"
}

provider "azurerm" {
  subscription_id = "XXXXXX"
  features {}
}

provider "databricks" {
  host = "XXXX"
}

**Comment by alexott** [comment]
what actual version is used? Run `terraform -version` and you should get something like this:

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.1.0
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
```

**Comment by anumanlap** [comment]
@alexott Thank you for the response.  I have tested with 2 different versions as mentioned below:
----
$ terraform --version
Terraform v1.2.9
on windows_amd64
---
$ terraform --version
Your version of Terraform is out of date! The latest version
is 1.2.9. You can update by downloading from https://www.terraform.io/downloads.html
Terraform v0.13.0
------------

**Comment by nkvuong** [comment]
your provider version is really out of date

```hcl
databricks = {
source = "databrickslabs/databricks"
version = "~>0.4.0"
}
```
