### ISSUE TITLE
maxTokenLifetimeDays Issue with `databricks_workspace_conf` resource

### ISSUE THREAD

**Issue by rohitnijhawan** [databricks/terraform-provider-databricks#1614]
### Expected Behavior
The terraform experimental exporter should fill in a value for the `maxTokenLifetimeDays` attribute

### Actual Behavior
The exporter puts in an empty string "" when the workspace administrator hasn't set a different default. The default value is 3650 (ie. 10 years).

The terraform apply fails because it needs a value or the attribute key should **not** be generated for `databricks_workspace_conf`

### Steps to Reproduce
Run the exporter with all services.

### Terraform and provider versions
Tested with 1.3.0

**Comment by nfx** [comment]
due to certain constraints, exporter cannot export workspace conf
