### ISSUE TITLE
[ISSUE] Issue with `databricks_permissions` exporter for sql endpoints

### ISSUE THREAD

**Issue by rohitnijhawan** [databricks/terraform-provider-databricks#1628]
### Configuration
```hcl
resource "databricks_permissions" "sql_endpoint_starter_endpoint" {
    sql_endpoint_id = "fb8......xyz"
    access_control {
        permission_level = "CAN_USE"
        group_name = data.databricks_group.users.display_name
    }
    access_control {
        user_name = databricks_user.k0p00te.user_name
        permission_level  = "CAN_MANAGE"
    }
}
```

### Expected Behavior
IDs for resources should be provided with dotted notation as in: a reference to a value (**to be known in the future**)

### Actual Behavior

The Terraform Exporter is writing **some** hcl configuration files with IDs that are hardcoded for resources.
Resources with these IDs do no exist when other resources look for them.
The culprit here is 
`sql_endpoint_id = "fb8......xyz"` which leads to the error message

**Error: cannot create permissions: endpoints fb8.......xyz does not exist**

### Steps to Reproduce
- Create a new SQL Endpoint
- Add user permissions to manage the endpoint
- Run the terraform exporter with `-services=sql,access`

### Terraform and provider versions
Databricks terraform Provider 1.3.0
Terraform - versions above 0.15

### Important Factoids
Technically the output shown above is not wrong. It reflects the state of the workspace but the user can't use it to run apply because IDs are autogenerated.
As a result, all resources should have reference notation.

**Comment by nfx** [comment]
@alexott this is a simple fix

**Comment by alexott** [comment]
I know. will fix it together with other stuff

**Comment by alexott** [comment]
Really, I already had that fix as a part of the dbsql branch. Will extract into a separate PR
