### ISSUE TITLE
[ISSUE] Issue with `resource_metastore` resource

### ISSUE THREAD

**Issue by TakeshiKovacs** [databricks/terraform-provider-databricks#1636]
### Configuration
```hcl
resource "databricks_metastore" "this" {
  name = "samplename"
  storage_root = format("abfss://%s@%s.dfs.core.windows.net/",
    azurerm_storage_container.unity_catalog.name,
  azurerm_storage_account.unity_catalog.name)
  
  force_destroy = true
  //Can't actually specify this
  region = azurerm_storage_account.unity_catalog.location
}

```

### Expected Behavior
We should have the metastore deploy to a specified region.

### Actual Behavior
The metastore deploys to West Europe in my case.

### Steps to Reproduce
Deploy a metastore into Azure

### Terraform and provider versions
Terraform v1.3.0
on windows_amd64
+ provider registry.terraform.io/azure/azapi v0.6.0
+ provider registry.terraform.io/databricks/databricks v1.3.1
+ provider registry.terraform.io/hashicorp/azurerm v3.24.0

### Important Factoids
Nothing exotic, we simply want to deploy to a specified region.
I believe we should be able to add the Region as an optional parameter to CreateMetastore in
https://github.com/databricks/terraform-provider-databricks/blob/master/catalog/resource_metastore.go

The latest API documentation doesn't specify that as a parameter but the GUI asks for a region so assume it should be possible.

**Comment by TakeshiKovacs** [comment]
Additionally, per the browser
![image](https://user-images.githubusercontent.com/13132191/192718440-e0e00453-05ee-4f1f-ae62-73072a6090d2.png)
The region gets passed to the metastores API

**Comment by nkvuong** [comment]
the UI uses a different route than the public API, hence the difference in the spec and what you observed in the browser network traffic

I'll double check if the public API supports specifying the region, and if it is the case, we will add it to the provider

**Comment by nkvuong** [comment]
@TakeshiKovacs I checked and the location of the workspace takes precedent, so if you want to create a metastore in a specific region, you'll need to call the API/Terraform via a workspace in that region (even if it's a blank one to bootstrap)

This is currently a limitation due to the different API spec

**Comment by TakeshiKovacs** [comment]
@nkvuong The workspace I reference is already in the northeurope region, it still creates the metastore in westeurope.

**Comment by nkvuong** [comment]
there was a recent rollout that should create the metastore in northeurope - I tested it just now and it works

**Comment by TakeshiKovacs** [comment]
@nkvuong It started working now, I will close this for now, although it would be nice to specify region if that becomes available in a future API version.
