### ISSUE TITLE
[FEATURE] `databricks_sql_global_config` isn't exported

### ISSUE THREAD

**Issue by rohitnijhawan** [databricks/terraform-provider-databricks#1640]
Exporter process not creating / filling in sql_endpoint configuration information as seen below
Information is redacted to protect customer information.

Source workspace has an sql endpoint.
![dbsql1](https://user-images.githubusercontent.com/47123996/192888079-e3179fd6-7e4f-41c9-9bb7-6860a64a0f66.png)

### When Imported this information is not available in the target workspace.

![dbsql2](https://user-images.githubusercontent.com/47123996/192888165-a313c116-0cdb-40ba-9557-ab7fec53d2de.png)

### Important Notes
- SQL Endpoint name and other information is imported using terraform apply

**Comment by alexott** [comment]
It's not SQL endpoint it `databricks_sql_global_config`
