### ISSUE TITLE
[FEATURE] Assign workspace permission to user/group using account-level provider

### ISSUE THREAD

**Issue by miro1127** [databricks/terraform-provider-databricks#1643]
### Use-cases
We have an identity-federated Azure Databricks workspace linked to Unity Catalog and Azure Active Directory. We would like to have an option to manage **workspace permission** (User/Admin) using Databricks **account-level** Terraform provider. 

Screenshot of relevant feature in Account-level portal UI (https://accounts.azuredatabricks.net/):
![image](https://user-images.githubusercontent.com/114656640/193002329-d2fbf4f4-e09b-4a78-9ca7-c8ebe20b7c48.png)

### Attempted Solutions
I was looking for a relevant attributes in `databricks_user`, `databricks_group` and `databricks_permissions `, but I couldn't find anything related to the requested feature.

### Proposal
It's possible to configure the above permissions using the [Permission Assignment Account API](https://api-docs.databricks.com/rest/latest/permission-assignment-account-api.html). Hopefully it can be incorporated into relevant Terraform resources.

### References
- [Permission Assignment Account API](https://api-docs.databricks.com/rest/latest/permission-assignment-account-api.html)
- [Docs: Add users to a identity-federated workspace](https://learn.microsoft.com/en-us/azure/databricks/administration-guide/users-groups/users#--add-users-to-a-workspace)

**Comment by nkvuong** [comment]
@miro1127 this is possible using [databricks_mws_permission_assignment](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_permission_assignment)

**Comment by miro1127** [comment]
@nkvuong That's exactly what I was looking for. Thanks!
Closing the request then.
