### ISSUE TITLE
[DOC] Update resource diagram with databricks_mws_permission_assignment

### ISSUE THREAD

**Issue by dmoore247** [databricks/terraform-provider-databricks#1646]
### Affected Resource(s)
This diagram 
https://raw.githubusercontent.com/databricks/terraform-provider-databricks/master/docs/resources.png
doesn't show the `databricks_mws_permission_assignment` resource and it's relationship.

### Expected Details
Diagram should have `databricks_mws_permission_assignment` entity displayed

### List of things to potentially add/remove:
Also add item to `Security` section
Should list resource and link to page https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_permission_assignment

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by dmoore247** [comment]
@nkvuong 
I can't find databricks_mws_permission_assignment in the new diagram. There are no new yellow-orange entities on the diagram.

**Comment by dmoore247** [comment]
LGTM!
