### ISSUE TITLE
[FEATURE] New feature request `databricks_notebook` resource should allow jupyter notebooks

### ISSUE THREAD

**Issue by avinashpancham** [databricks/terraform-provider-databricks#1647]
### Use-cases
Via the databricks UI it is possible to upload a Jupyter notebook  (`.ipynb`) to Databricks, but via the `databricks_notebook` resource this is not yet possible. According to the [docs](https://docs.databricks.com/notebooks/notebooks-manage.html#convert-a-file-to-a-notebook) it is possible to store all code in a `.py` file and read that in as a Jupyter notebook by distinguishing between cells via `# COMMAND ----------`, but this is not ideal since it creates a long and difficult to read Python file. I would therefore rather upload a `.ipynb` file via the `databricks_notebook` resource

I am not yet familiar with the codebase of the terraform databricks provider, but I can have a look!

### Attempted Solutions

```hcl
resource "databricks_notebook" "test" {
  source = "${path.module}/foo.ipnyb"
  path   = "foo" 
}
```

╷
│ Error: cannot create notebook: The zip file may not be valid or may be an unsupported version.
│ 
│   with databricks_notebook.test,
│   on main.tf line 1, in resource "databricks_notebook" "test":
│   1: resource "databricks_notebook" "test" {

### Proposal

```hcl
resource "databricks_notebook" "test" {
  source = "${path.module}/foo.ipnyb"
  path   = "foo" 
}
```

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

Basically, you need to add `JUPYTER` format in [workspace/resource_notebook.go](https://github.com/databricks/terraform-provider-databricks/blob/master/workspace/resource_notebook.go). You can find more info in contributing guidelines.

**Comment by avinashpancham** [comment]
Thanks @nfx! I would like to give it a try myself, so thanks for the support.

**Comment by nfx** [comment]
Of course, will review the PR =)

Please make sure to bump code coverage if codecov.io complains ;)

**Comment by AlexC** [comment]
@nfx I have just made PR #1801 which should address this, and would be useful for a project I am involved in
