### ISSUE TITLE
[ISSUE] Issue with `databricks_grants` resource

### ISSUE THREAD

**Issue by panselaukik** [databricks/terraform-provider-databricks#1658]
### Configuration
```hcl
terraform {
  required_version = ">=v0.14.7"
}
```

### Expected Behavior
```hcl
Previously we used the below:
resource "databricks_grants" "catalog-grants" {
  catalog    = <SOME-NAME>
  grant {
    principal  = <SOME-GROUP>
    privileges = ["USAGE", "CREATE"]
  }

But we started observing issues, when the GRANTS were set back to NULL as Databricks showed `USE CATALOG` and Terraform resource had `USAGE`

So we saw an open [PR](https://github.com/databricks/terraform-provider-databricks/pull/1657/files) which shows the new privileges and replaced `USAGE` with `USE CATALOG` but facing a different error now:

resource "databricks_grants" "catalog-grants" {
  catalog    = <SOME-NAME>
  grant {
    principal  = <SOME-GROUP>
    privileges = ["USE CATALOG", "CREATE"]
  }

Should apply necessary grants
```

### Actual Behavior
```hcl
When used `USAGE`:

      + grant {
          + principal  = <SOME-GROUP>
          + privileges = [
              + "CREATE",
              + "USE_CATALOG",
            ]
        }
      - grant {
          - principal  = <SOME-GROUP> -> null
          - privileges = [
              - "CREATE_SCHEMA",
              - "USE_CATALOG",
            ] -> null
        }

When used `USE CATALOG`:

Error: USE CATALOG is not allowed on catalog
```

### Steps to Reproduce
```hcl
1. Set `USAGE` for `databricks_grants`
2. terraform apply
3. Again terraform apply -> you will see the first error as above

1. Set `USE CATALOG` for `databricks_grants`
2. terraform apply
3. You will see the second error as above
```

### Terraform and provider versions
```hcl
provider "databricks" {
  host       = var.host
  token      = var.token
  account_id = var.account_id
  alias      = <SOME-NAME>
}


terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = ">=1.4.0"
    }
  }
}
```

**Comment by panselaukik** [comment]
I think we are missing this which is mentioned in a note, will post an update once we do so

- This article refers to the privileges and inheritance model in Privilege Model version 1.0. If you created your metastore during the public preview (before August 25, 2022), you can upgrade to Privilege Model version 1.0 following [Upgrade to privilege inheritance]

**Comment by panselaukik** [comment]
We have the metastore upgraded to `Privilege Model version 1.0` still face the issue

**Comment by nkvuong** [comment]
@panselaukik the permissions should have underscore, so could you try with `USE_CATALOG`

**Comment by Nestor10** [comment]
This could be a new issue but i also am experiencing issues with databricks_grant resource.

`╷
│ Error: SELECT is not allowed on schema
│ 
│   with databricks_grants.transactional_message_interface,
│   on main.tf line 166, in resource "databricks_grants" "transactional_message_interface":
│  166: resource "databricks_grants" "transactional_message_interface" {
│ 
╵
`

To reproduce on my side, I need only to provide 'select'. The interesting thing is that on a blank workspace this works fine. I can plan and apply. However, the next time i plan i get this error. I get this error when no changes to the terraform project have been made!

Im on terraform 1.3.2 databricks provider 1.4.0. This is a newer unity deployment so I had inheritance model in Privilege Model from the start. The code as you may guess is very simple. However, i would suspect there is no unit test for a plan after apply.

**Comment by Nestor10** [comment]
ok, i think this was fixed here. https://github.com/databricks/terraform-provider-databricks/commit/d0fecab8fd76d551843c24401f1fe2e863d02203
i suspect 1.4.1 will capture the behavior i listed above.

**Comment by nkvuong** [comment]
@panselaukik  @Nestor10 1.5.0 was just released, could you check if it is now fixed?

**Comment by panselaukik** [comment]
@nkvuong Yes, the new version has fixed the issue, Thankyou
