### ISSUE TITLE
[FEATURE] Enabling admin protection for "no-isolation shared" clusters

### ISSUE THREAD

**Issue by dvasdekis** [databricks/terraform-provider-databricks#1680]
### Use-cases
We wish to enable admin protection for "no-isolation shared" clusters ([see here for MS docs](https://learn.microsoft.com/en-gb/azure/databricks/administration-guide/account-settings/no-isolation-shared)).

Microsoft just added this parameter to their list of security advisory flags, so now our databricks instances are considered insecure by our internal IT department unless this flag is switched on.

### Attempted Solutions
I haven't been able to determine a means to turn on this flag in the current Databricks config.

We can't do it manually as we currently have 48 databricks instances, and growing.

### Proposal
Add a parameter to the `databricks_workspace_conf` resource to control this, plus an entry in the docs.

**Comment by nfx** [comment]
@hemal-khat-db is driving the effort of account-level settings

**Comment by nfx** [comment]
closing this issue, as it needs proper api
