### ISSUE TITLE
Trying to create a `databricks_group` in account, but always created in workspace

### ISSUE THREAD

**Issue by erniebilling** [databricks/terraform-provider-databricks#1687]
I'm trying to create a new `databricks_group` at the account level using the following general code (per [docs](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/group)):

```
terraform {
  required_version = "~> 1.3.1"
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.6.1"
    }
  }
}

provider "databricks" {
  alias      = "mws"
  host       = "https://accounts.cloud.databricks.com"
}

resource "databricks_group" "this" {
  provider     = databricks.mws
  display_name = "Some Group"
}

output "group_id" {
  value = databricks_group.this.id
}

output "group_url" {
  value = databricks_group.this.url
}
```

When `terraform init` and `terraform apply` are run, the new group gets created in the workspace instead of the account.

Output looks like:

```
group_id = "532261919295289"
group_url = "https://anaplan-primary-us-east-1-dev.cloud.databricks.com/#setting/accounts/groups/532261919295289"
```

When I turned on `TF_LOG=DEBUG` I see this in the output:

```
2022-10-21T22:24:48.987Z [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/databricks/databricks\"].mws" changed the config value, but that value is unused
2022-10-21T22:24:48.989Z [INFO]  provider.terraform-provider-databricks_v1.6.1: Explicit and implicit attributes: host: timestamp=2022-10-21T22:24:48.989Z
```

**Comment by nfx** [comment]
Apparently it’s a configuration drift recently introduced in the platform. It was a quick fix for our nightly integration tests.

It did work okay before, right?

Would you like to open the PR to tune validations?

**Comment by erniebilling** [comment]
I've only tried provider versions 1.6.0 and 1.6.1 and both seem to create workspace local groups.

Not clear what you mean by:

> Would you like to open the PR to tune validations?

**Comment by erniebilling** [comment]
After further digging, it seems to work as expected when authenticated with username/password instead of token. I take it tokens are workspace scoped? Is there any way to get an account scoped token? We plan to use service principals to automate our workflows and requiring username/password to create account level resources isn't ideal.

**Comment by sienkiewiczPat** [comment]
Hi @erniebilling,

It's not currently possible to use Service Principal token using account level resources. I was looking into it as well.
I heard from Databricks that this is planned, but I don't have ETA.
I had the same plan to use SP to automate deployment, setup nice CI/CD pipelines, but currently I am executing deployment with my credential form my local machine. It's pain - I have mulit-region, mulit-account setup with 10 Unity Catalogs (2-3 workspaces per UC) planned to deploy this month. 
The biggest pain for me so far is deploying Unity Catalog resources and Workspaces resources, when you have to switch provider level between account and workspace. 

I encourage you to use the databricks community to share your ideas: https://community.databricks.com/s/question/0D58Y000098lPUkSAM/uc-service-principalterraform

**Comment by rohitnijhawan** [comment]
The exporter code reads the account level group and writes its definition in groups.tf indistinguishable from a workspace level group (to be imported) into another workspace, also.
