### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore_assignment` resource

### ISSUE THREAD

**Issue by antoncorredoira** [databricks/terraform-provider-databricks#1699]
### Configuration
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.20.0"
    }
    databricks = {
      source = "databricks/databricks"
      version = "1.6.1"
    }
    azapi = {
      source = "azure/azapi"
    }
  }
}

provider "databricks" {
  host = azurerm_databricks_workspace._01.workspace_url
}

provider "azuread" {
  # Configuration options
}

provider "azurerm" {
  # Configuration options
  features {}
}

data "azurerm_client_config" "current" {
}

provider "azapi" {
  subscription_id = data.azurerm_client_config.current.subscription_id
}

resource "azurerm_resource_group" "_01" {
  location = "West Europe"
  name     = "${local.resource_naming}--rg"
}

locals {
  resource_naming = "testuniycatalogdbw"
}

resource "azurerm_databricks_workspace" "_01" {
  location            = azurerm_resource_group._01.location
  name                = "${local.resource_naming}-dbw"
  resource_group_name = azurerm_resource_group._01.name
  sku                 = "premium"
  managed_resource_group_name = "test-dbw-rg"
}

resource "azapi_resource" "access_connector" {
  type      = "Microsoft.Databricks/accessConnectors@2022-04-01-preview"
  name      = "${local.resource_naming}--databricks-mi"
  location  = azurerm_resource_group._01.location
  parent_id = azurerm_resource_group._01.id
  identity {
    type = "SystemAssigned"
  }
  body = jsonencode({
    properties = {}
  })
}

resource "azurerm_storage_account" "unity_catalog" {
  name                     = "${local.resource_naming}dls"
  resource_group_name      = azurerm_resource_group._01.name
  location                 = azurerm_resource_group._01.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  is_hns_enabled           = true
}

resource "azurerm_storage_container" "unity_catalog" {
  name                  = "unity"
  storage_account_name  = azurerm_storage_account.unity_catalog.name
  container_access_type = "private"
}

resource "azurerm_role_assignment" "example" {
  scope                = azurerm_storage_account.unity_catalog.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azapi_resource.access_connector.identity[0].principal_id
}

resource "databricks_metastore" "_01" {
  name = "primary"
  storage_root = format("abfss://%s@%s.dfs.core.windows.net/",
    azurerm_storage_container.unity_catalog.name,
  azurerm_storage_account.unity_catalog.name)
  force_destroy = true
}

resource "databricks_metastore_data_access" "first" {
  metastore_id = databricks_metastore._01.id
  name         = "the-keys"
  azure_managed_identity {
    access_connector_id = azapi_resource.access_connector.id
  }
  is_default = true
}

resource "databricks_metastore_assignment" "this" {
  workspace_id         = azurerm_databricks_workspace._01.workspace_id
  metastore_id         = databricks_metastore._01.id
  default_catalog_name = "hive_metastore"
}


```

### Expected Behavior
Create the resource successfully

### Actual Behavior
│ Error: Attribute must be a whole number, got 2.194435133354776e+15
│
│   with databricks_metastore_assignment.this,
│   on main.tf line 106, in resource "databricks_metastore_assignment" "this":
│  106:   workspace_id         = azurerm_databricks_workspace._01.workspace_id

Looks like the resource_id in Azure is a number that is too large and gets converted somewhere along the way.

### Steps to Reproduce
1. terraform apply (will fail as you are not admin yet, excluded this to shorten the script)
2. Databricks sign in
3. terraform apply again

### Terraform and provider versions
Terraform v1.3.3
on windows_386
+ provider registry.terraform.io/azure/azapi v1.0.0
+ provider registry.terraform.io/databricks/databricks v1.6.1
+ provider registry.terraform.io/hashicorp/azuread v2.28.1
+ provider registry.terraform.io/hashicorp/azurerm v3.20.0

### Debug Output
2022-10-27T10:55:47.026+0200 [ERROR] provider.terraform-provider-databricks_v1.6.1.exe: Response contains error diagnostic: diagnostic_attribute=AttributeName("workspace_id") diagnostic_detail= @module=sdk.proto tf_provider_addr=regi
stry.terraform.io/databricks/databricks tf_req_id=f9b30f97-a921-27ce-a1c7-b58c1f0db453 tf_rpc=ValidateResourceTypeConfig @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicor
p/terraform-plugin-go/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_summary="Attribute must be a whole number, got 2.194435133354776e+15" tf_proto_version=5.3 diagnostic_severity=ERROR tf_resource_type=databricks_metastore_ass
ignment timestamp=2022-10-27T10:55:47.026+0200
2022-10-27T10:55:47.027+0200 [ERROR] vertex "databricks_metastore_assignment.this" error: Attribute must be a whole number, got 2.194435133354776e+15
2022-10-27T10:55:47.027+0200 [ERROR] vertex "databricks_metastore_assignment.this (expand)" error: Attribute must be a whole number, got 2.194435133354776e+15

### Important Factoids
No additional information

**Comment by nkvuong** [comment]
@antoncorredoira could you try with Terraform Amd64? This might be an issue with 386

**Comment by antoncorredoira** [comment]
> @antoncorredoira could you try with Terraform Amd64? This might be an issue with 386

Thank you @nkvuong for your suggestion, can confirm that it was indeed an issue with 386. Changing to Amd64 "fixed" it.

**Comment by c-thiel** [comment]
@antoncorredoira, we had the same problem and the Amd64 Version fixed it.
