### ISSUE TITLE
[ISSUE] Issue with malformed library blocks in `databricks_job` resource

### ISSUE THREAD

**Issue by alev000** [databricks/terraform-provider-databricks#1701]
### Configuration
Note that the following contains one library block with maven and pypi sub-blocks.

```hcl
resource "databricks_job" "this" {
  name = "Terraform Demo"

  job_cluster {
    job_cluster_key = "my_cluster"
    new_cluster {
      num_workers   = 1
      spark_version = "10.4.x-scala2.12"
      node_type_id  = "c5d.4xlarge"
    }
  }

  task {
    task_key        = "my_task"
    job_cluster_key = "my_cluster"
    notebook_task {
      notebook_path = "path/to/notebook"
    }
    library {
      maven {
        coordinates = "commons-io:commons-io:2.11.0"
      }
      pypi {
        package = "pydantic"
      }
    }
  }
}
```

### Expected Behavior
Either successfully install both libraries (from maven and from pypi) or report a validation error

Based on the documentation [here](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#library-configuration-block), it seems like a validation error would be the expected behavior:
> To install libraries, one must specify each library in a separate configuration block. Each different type of library has a slightly different syntax. It's possible to set only one type of library within one config block. Otherwise, the plan will fail with an error.

### Actual Behavior
The plan applied successfully, but the pypi package is not listed as a dependency on any tasks of the job (for example, when viewing in the UI or when querying via the Jobs REST API).

### Steps to Reproduce
* `terraform validate` reports no errors
* `terraform plan` produces a set of changes that makes it appear that both libraries will be attached to the given task
* `terraform apply` succeeds, but the databricks job only shows the maven dependency, not the pypi dependency (this is true both when viewing the job in the UI and when querying the job via the REST API)

### Terraform and provider versions
```text
$ terraform version
Terraform v1.3.3
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.6.1
```

**Comment by nfx** [comment]
please use only one library type per block

**Comment by alev000** [comment]
@nfx Thanks for confirming that library blocks are only intended to contain one library type per block. However, as I mentioned above:

> Based on the documentation [here](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#library-configuration-block), it seems like a validation error would be the expected behavior

Isn't there some way that this provider could validate the structure of the library blocks and report an error if invalid?
