### ISSUE TITLE
[ISSUE] Issue with `databricks_group` resource not using unity groups in workspace on Azure

### ISSUE THREAD

**Issue by cmollgaard** [databricks/terraform-provider-databricks#1703]
### Configuration
```hcl
# Copy-paste your Terraform configuration here

provider "databricks" {
  alias      = "azure_account"
  host       = "https://accounts.azuredatabricks.net"
  account_id = "0000-0000-00-0-0-000-0-0--00"
  auth_type  = "azure-cli"
}

provider "databricks" {
  host       = "https://adb-000000000000.0.azuredatabricks.net/"
}

resource "databricks_group" "test_unity" {
  display_name = "test"
  provider     = databricks.azure_account
}
resource "databricks_group" "test_workspace" {
  display_name = databricks_group.test_unity.display_name
}
```

### Expected Behavior
I expected the workspace group to be a reference to the account group.
This should keep the two groups in sync

### Actual Behavior
It creates a workspace local group that is not synchronized with the account group 

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
Terraform v1.3.3
on windows_amd64
+ provider registry.terraform.io/databricks/databricks v1.6.1

### Important Factoids

I am unable to create a workspace group when using the GUI in the workspace.
The GUI forces me to use account groups.

**Comment by alexott** [comment]
You need to use [databricks_mws_permission_assignment](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/mws_permission_assignment) instead to assign UC groups to the workspace

**Comment by cmollgaard** [comment]
I forget to mention it’s on Azure.Isn’t mws an AWS thing?On 28 Oct 2022, at 10.49, Alex Ott ***@***.***> wrote:﻿
You need to use databricks_mws_permission_assignment instead to assign UC groups to the workspace

**Comment by cmollgaard** [comment]
Okay having played around with it, it sure looks like databricks_mws_permission_assignment is what is needed.
I do not really find it reflected in the docs though.

**Comment by troyel** [comment]
Thanks for pointing me in this direction @alexott . My issue in #1709 seems to work, but I don't understand how I can set the workspace_access and databricks_sql_access fields that we normally would set when provisioning groups against the workspace when using "databricks_mws_permission_assignment" the documentation here is severely lacking.
