### ISSUE TITLE
[FEATURE] Add parent field to `databricks_sql_query`

### ISSUE THREAD

**Issue by thetkoseek** [databricks/terraform-provider-databricks#1715]
### Use-cases
It would be good to be able to specify which directory that sql_query is stored under

### Proposal
Add the field `parent` and map the the parent api field `parent`. https://docs.databricks.com/sql/api/queries-dashboards.html#tag/Queries-Results/paths/~1queries/post

**Comment by alexott** [comment]
We need to think a bit about the UI part of it, as `parent` uses Workspace object ID instead of the directory name...

**Comment by thetkoseek** [comment]
Interesting. You are absolutely correct, I missed that in the rest api docs. Looks like we need to create a datasource for `databricks_directory`
