### ISSUE TITLE
spark-python-task to be able to use Repos or Workspace paths

### ISSUE THREAD

**Issue by dougspadotto** [databricks/terraform-provider-databricks#1724]
We need to be able to create jobs with Python script tasks pointing to Python files stored on a Git repository and not only DBFS or other cloud storage.

The only possible approach I see today would be to get the Python script from the Repo, create a [DBFS file](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/dbfs_file#path) from it and then use that as reference when creating the [job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) using [spark_python_task](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#spark_python_task-configuration-block).

Now with the general availability of Files in Repos, I believe there is the possibility of making [python_file](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#python_file) to be a Workspace path and not DBFS/cloud storage one.

I hope this is implemented so a DR solution from a customer can rely on this Databricks functionality that already exists on the workspace and API but not on the Terraform provider yet.

**Comment by dougspadotto** [comment]
In fact, just setting a path relative to the Workspace on the python_file configuration works. So this is just a documentation issue. 
Need to remove the wording that python_file must be on DBFS or S3 and mention that it now can also be a workspace path.

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
