### ISSUE TITLE
[ISSUE] Issue with `databricks_directory` , 'databricks_permissions' and 'databricks_notebook' resources

### ISSUE THREAD

**Issue by eddylu1s** [databricks/terraform-provider-databricks#1738]
### Configuration
```hcl
resource "databricks_directory" "team_directories" {
  for_each = {for dir in local.team_directories: dir.name => dir}
  path = "/${each.key}"
}

resource "databricks_permissions" "folder_usage" {
  for_each = {for dir in local.team_directories: dir.name => dir}
  directory_path = databricks_directory.team_directories[each.key].path
  depends_on     = [databricks_directory.team_directories]

  access_control {
    group_name       = each.value.ad_group
    permission_level = "CAN_EDIT"
  }
}

# ================ CREATE NOTEBOOK TO DEPLOY THE CODE ================
resource "databricks_notebook" "notebook" {
  for_each = {for notebook in local.notebooks: notebook.name => notebook}
  source = each.value.source
  path = "/each.value.ad_group/${each.key}"
}

# ================ ATTACH USER GROUP TO NOTEBOOK ================

resource "databricks_permissions" "notebook_usage" {
  for_each = {for notebook in local.notebooks: notebook.name => notebook}
  notebook_path = databricks_notebook.notebook[each.key].path
  access_control {
    group_name       = each.value.ad_group
    permission_level = "CAN_EDIT"
  }
}


moved {
  from = databricks_directory.team_directory_xx
  to = databricks_directory.team_directories["XX_A"]
}

moved {
  from = databricks_directory.team_directory_yy
  to = databricks_directory.team_directories["YY_A"]
}

moved {
  from = databricks_permissions.folder_usage_xx
  to = databricks_permissions.folder_usage["XX_A"]
}

moved {
  from = databricks_permissions.folder_usage_yy
  to = databricks_permissions.folder_usage["YY_A"]
}

moved {
  from = databricks_notebook.notebook_snowflake_connection
  to = databricks_notebook.notebook["sf-python-connector"]
}

moved {
  from = databricks_notebook.notebook_snowflake_connection_spark
  to = databricks_notebook.notebook["sf-spark-connector"]
}

moved{
from = databricks_permissions.notebook_usage_sf
to = databricks_permissions.notebook_usage["sf-python-connector"]
}

moved{
from = databricks_permissions.notebook_usage_sf_spark
to = databricks_permissions.notebook_usage["sf-spark-connector"]
}
```

### Expected Behavior
Show plan output, with the moved resources. So only the resource id was changed, to a resource id with an index [ ]
Now I have to import them all as a workaround. 

### Actual Behavior
Plugin crashed, see logs. 

### Steps to Reproduce

1. `terraform plan`

### Terraform and provider versions
Terraform v1.3.4
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.6.3"
    }
  }
}

### Debug Output
 Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with databricks_directory.team_directories["XX_A"],
│   on databricks_directories.tf line 1, in resource "databricks_directory" "team_directories":
│    1: resource "databricks_directory" "team_directories" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ValidateResourceConfig call. The plugin logs may contain more details. 
╵
╷
│ Error: Plugin did not respond
│
│   with databricks_directory.team_directories["YY_A"],
│   on databricks_directories.tf line 1, in resource "databricks_directory" "team_directories":
│    1: resource "databricks_directory" "team_directories" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.     
╵
╷
│ Error: Plugin did not respond
│
│   with databricks_notebook.notebook["sf-spark-connector"],
│   on databricks_notebooks.tf line 2, in resource "databricks_notebook" "notebook":
│    2: resource "databricks_notebook" "notebook" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.     
╵
╷
│ Error: Plugin did not respond
│
│   with databricks_notebook.notebook["sf-python-connector"],
│   on databricks_notebooks.tf line 2, in resource "databricks_notebook" "notebook":
│    2: resource "databricks_notebook" "notebook" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).PlanResourceChange call. The plugin logs may contain more details.     
╵

Stack trace from the terraform-provider-databricks_v1.6.3.exe plugin:

panic: Error reading level state: strconv.ParseInt: parsing "3569843849581302": value out of range

goroutine 103 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x14634230, {0x14490a68, 0x1, 0x1}, 0x8)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x14634230)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:351 +0x3a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x149164d0, {{{0x11a9d3c, 0x14490260}}, {0xf7e320, 0x14a273c0}})
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1470bfb0, {0x11a97dc, 0x1468ab70}, 0x14a27160)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x149b24b0, {0x11a97dc, 0x1468a8e8}, 0x14b086f0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1038440, 0x149b24b0}, {0x11a97dc, 0x1468a8e8}, 0x1466e9c0, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x14876240, {0x11ab2e0, 0x14876000}, 0x1499aaa0, 0x14701020, 0x16fd608, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x14876240, {0x11ab2e0, 0x14876000}, 0x1499aaa0, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:963 +0x25f

Error: The terraform-provider-databricks_v1.6.3.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Important Factoids
Working on 0.5.9 before, upgraded from there, but even when turning back to it or another version (1.6.1 or 0.6.1) it keeps on crashing. It looks like there seems to be a parsing issue in the plugin:
panic: Error reading level state: strconv.ParseInt: parsing "3569843849581302": value out of range

**Comment by nfx** [comment]
interesting. @eddylu1s , could you elaborate on

```
moved {
  from = databricks_directory.team_directory_xx
  to = databricks_directory.team_directories["XX_A"]
}
```

what's the syntax of those?

**Comment by eddylu1s** [comment]
> interesting. @eddylu1s , could you elaborate on
> 
> ```
> moved {
>   from = databricks_directory.team_directory_xx
>   to = databricks_directory.team_directories["XX_A"]
> }
> ```
> 
> what's the syntax of those?

It is just a team_name, for example XX would then be: "FIN" (team: Finance)

**Comment by nickbrownapollo** [comment]
I'm seeing something similar. The pertinent code is:

```
resource "databricks_metastore_assignment" "this" {
  provider     = databricks.workspace
  metastore_id = module.environment_config.databricks_metastore_id
  workspace_id = local.databricks_workspace_id
}
```
### Summary output from running a plan:
Planning failed. Terraform encountered an error while generating this plan.

│ Error: Plugin did not respond
│
│   with databricks_metastore_assignment.this,
│   on main.tf line 16, in resource "databricks_metastore_assignment" "this":
│   16: resource "databricks_metastore_assignment" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

panic: Error reading level state: strconv.ParseInt: parsing "<redacted id>": value out of range
[stack trace snipped]
Error: The terraform-provider-databricks_v1.14.3.exe plugin crashed!
### Additional info
This only occurs with terraform version 1.4.5. If I revert to version 1.3.7 my code runs fine.

Let me know if you need more detail.

**Comment by alexott** [comment]
Most probably the issue is caused by the 32-bit version of the Databricks provider downloaded. Please make sure you use 64-bit version

**Comment by nickbrownapollo** [comment]
Looks like I had the 32 bit version of Terraform. Now working. Thanks for the prompt response!
