### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_endpoint` resource

### ISSUE THREAD

**Issue by eczerwin** [databricks/terraform-provider-databricks#1743]
### Configuration
resource "databricks_sql_endpoint" "this" {
  name             = "test"
  cluster_size     = "2X-Small"
  max_num_clusters = 1
  min_num_clusters = 1
  num_clusters     = 1
  auto_stop_mins   = 30

### Expected Behavior
Terraform should apply successfully and then on new plan not find any changes

### Actual Behavior
 # databricks_sql_endpoint.this will be updated in-place
  ~ resource "databricks_sql_endpoint" "this" {
        id                        = "21fa58321fa1c6a7"
        name                      = "azadbengcloud01"
      ~ num_clusters              = 0 -> 1
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

### Steps to Reproduce
run a terraform plan and apply and the behavior repeats

### Terraform and provider versions
Terraform v1.2.5
on windows_amd64
+ provider registry.terraform.io/databricks/databricks v1.6.3
+ provider registry.terraform.io/hashicorp/azuread v2.30.0
+ provider registry.terraform.io/hashicorp/azurerm v3.30.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

**Comment by fava9410** [comment]
Totally agree with this one, for me the `num_clusters` shouldnt be pass because this is like the active cluster in that moment, with the min and max should be enough

**Comment by eczerwin** [comment]
I see this was considered config drift...  However, I have noted it comes down simply to if the cluster is running or not.  At time of creation it is for sure running but since it is configurable timeout..  It cannot always be running during a plan and terraform does not start it on interaction

**Comment by Israphel** [comment]
I'd recommend ignoring that line in your module (at least for now)

```terraform
# Databricks SQL Endpoint
resource "databricks_sql_endpoint" "sql_endpoint" {
  name                      = var.name
  cluster_size              = var.cluster_size
  min_num_clusters          = var.min_num_clusters
  max_num_clusters          = var.max_num_clusters
  auto_stop_mins            = var.auto_stop_mins
  spot_instance_policy      = var.spot_instance_policy
  enable_serverless_compute = var.enable_serverless_compute

  dynamic "tags" {
    for_each = var.tags != null ? [var.tags] : []
    content {
      dynamic "custom_tags" {
        for_each = var.tags
        content {
          key   = custom_tags.key
          value = custom_tags.value
        }
      }
    }
  }

  lifecycle {
    ignore_changes = [
      num_clusters
    ]
  }
}
```

**Comment by eczerwin** [comment]
Thanks a lot.  The ignore does work in this case
