### ISSUE TITLE
[ISSUE] Issue with Databricks databricks_permissions resource

### ISSUE THREAD

**Issue by nsampietrowam** [databricks/terraform-provider-databricks#1746]
### Configuration
```hcl
#Terraform v1.3.4
on linux_amd64
```

### Expected Behavior
A job was deleted from Databricks GUI and terraform plan was to remove this permission:

 databricks_permissions.everyone_can_view_all_jobs["test_pool_notebook_job"] will be destroyed
  (because databricks_permissions.everyone_can_view_all_jobs is not in configuration)
  - resource "databricks_permissions" "everyone_can_view_all_jobs" {
      - id          = "/jobs/259718719510571" -> null
      - job_id      = "259718719510571" -> null
      - object_type = "job" -> null
      - access_control {
          - group_name       = "users" -> null
          - permission_level = "CAN_VIEW" -> null
        }
    }

### Actual Behavior
Error: cannot delete permissions: Principal name not defined

### Steps to Reproduce
1) Delete Databricks job from GUI
2) Terraform plan / apply 

### Terraform and provider versions
Terraform v1.3.4

**Comment by nkvuong** [comment]
@nsampietrowam this is how Terraform works - you are not meant to delete resources currently managed by Terraform as that would lead to unexpected behaviour like this

You will need to remove the orphaned permission from the state file using `terraform state rm`

**Comment by nsampietrowam** [comment]
Understood.  I guess the confusion was that the job itself was not managed by Terraforming... but databricks_permissions was. Thanks for all your work on this library, have a good day.
