### ISSUE TITLE
[ISSUE] Issue with `databricks_mount` resource

### ISSUE THREAD

**Issue by jackhuo-db** [databricks/terraform-provider-databricks#1756]
Hi there, I'm using aws_databricks terraform to manage the mount point for our workspace. It looks like it's trying to create a ephemeral cluster to perform the mount operation. However, it always creates `m5dn.large` instance in a specific AZ (`us-west-2d` in my account) in that region, which there is no sufficient capacity on AWS side. Our usage is like below.

```
databricks_mount: {
  ***: {
    name: ***,
    s3: {
      instance_profile: ***,
      bucket_name: ***,
    },
  }
},
```

I have checked all my cluster policy and all use `auto` as default value for `aws_attributes.zone_id`. So my questions are

* Is `m5dn.large` instance type set by provider somewhere for this type of resource provisioning task? If so, can we make more dynamic to always choose something available, or at least switch to a more available hardcoded type.
* Is `us-west-2d` (single AZ as oppose to `auto`) set by provider? If so, similar change would be appreciated.
* If neither of these are managed by the provider code, any clues on where I should explore as next step?

### Configuration
```hcl
# Copy-paste your Terraform configuration here
```

### Expected Behavior

Successfully mount the configurations

### Actual Behavior

Failed to mount due to insufficient EC2 capacity.

![image](https://user-images.githubusercontent.com/110431610/201450905-c3bc8342-aef4-4bde-92f4-2aa203e37161.png)

### Debug Output

`Error: mount via profile: 1112-013315-vgf96cxa is not able to transition from TERMINATED to RUNNING: The specified request is not supported.  aws_api_error_code: Unsupported, aws_error_message: Your requested instance type (m5dn.large) is not supported in your requested Availability Zone (us-west-..., Termination info: code: AWS_UNSUPPORTED_FAILURE, type: CLOUD_FAILURE, parameters: map[aws_api_error_code:Unsupported aws_error_message:Your requested instance type (m5dn.large) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c.]. Please see https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterclusterstate for more details`

**Comment by nkvuong** [comment]
@jackhuo-db the cluster auto-created by terraform for the mount picks the smallest node type defined by `databricks_node_type`, which will be `m5dn.large` for AWS. The code does not set the az, so will also use the default of the API. Changing this to auto-az will require significant refactoring as `databricks_mount` is designed to be cloud-agnostic.

To avoid this issue, could you explicitly set a [`cluster_id`](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mount#cluster_id) of a cluster that will be used for the mount operations?

**Comment by marekbrysa** [comment]
@nkvuong thanks for updating the docs!
That does not seems like a true solution to the problem.

Just my naive idea: what if in https://github.com/databricks/terraform-provider-databricks/blob/fd1f11aa22dc343a83fa1747ea4b6bc31a83a28e/storage/aws_s3_mount.go#L135 we added `ZoneId: "auto"`?

**Comment by alexott** [comment]
@marekbrysa use explicit `cluster_id` configured with `zone_id = "auto"`

**Comment by marekbrysa** [comment]
@alexott that has its own problems. If the cluster expires or is deleted, tf can't even get status of the mount. AFAIK there is no way to recover from that, other than manually editing the TF state file and changing the clusterId.

Using this mechanism with providing `instance_profile` instead of `cluster_id` is better, because then the provided can recover from deletion of the mounting cluster.
