### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource: `driver_node_type_id` does not update when removed

### ISSUE THREAD

**Issue by MigQ2** [databricks/terraform-provider-databricks#1757]
I had a `databricks_job` block that contained a `job_cluster`block where both `node_type_id` and `driver_node_type_id` were set and had different values. I had previously deployed it via `terraform apply`.
Then I removed the `driver_node_type_id` from the `job_cluster` configuration block and did `terraform apply` again. 

### Expected Behavior
I expected the driver node type would have been changed to the same as the worker node type as per the `driver_node_type_id` [documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#driver_node_type_id)

### Actual Behavior
The driver node type stayed the same as before and didn't change to the same node type as the workers. 

### Configuration
I am using Databricks Terraform provider 1.6.5 in an Azure Databricks Premium workspace

**Comment by alexott** [comment]
Should be fixed in #2502 & 2507. Please check.
