### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_permissions` resource

### ISSUE THREAD

**Issue by TheoPth** [databricks/terraform-provider-databricks#1764]
### Configuration
```hcl
# Copy-paste your Terraform configuration here

resource "databricks_sql_permissions" "databases_groups_sql_permissions" {
  cluster_id = "<my-cluster-id>"
  database   = "mydatabase"

  privilege_assignments {
    principal  = "Grouptest"
    privileges = ["USAGE", "SELECT", "READ_METADATA"]
  }
}
```

### Expected Behavior
the resource is applied and should no longer appear as a change in the next plan 

### Actual Behavior
the block "privilege_assignments" appears in every plan and is applied every time
![image](https://user-images.githubusercontent.com/32432470/201950441-fb698d4d-4870-4e11-bdf9-1747a28f4a5c.png)

### Steps to Reproduce

1. `terraform plan`-->
Create  a databricks_sql_permissions with privilege_assignments
Plan and apply two times.
you'll see that it's planned and applied every time.

### Terraform and provider versions
terraform version : 1.2.2
databricks provider version : 1.6.3 and after

### Important Factoids
The bug was introduced in the version 1.6.3. this feature was working in version 1.6.2 (I did not manage to find the root cause by myself)

**Comment by nfx** [comment]
I think this might be the regression caused by #1730 https://github.com/databricks/terraform-provider-databricks/compare/v1.6.2...v1.6.3 

could you share the logs?

**Comment by TheoPth** [comment]
Hi @nfx 
Thanks for your response, here LOG_TRACE of the plan
[run-5Mxk5yxFoDMbZLYs-plan-log.txt](https://github.com/databricks/terraform-provider-databricks/files/10019761/run-5Mxk5yxFoDMbZLYs-plan-log.txt)

**Comment by TheoPth** [comment]
I created a exemple with only one ressource, it's easier to understand the issue.

It's a plan / apply / plan , you'll see that the first and second plan are same. So the apply takes place every time (big issue when you have a lot of sql permissions)

Removed the commit 976b793fd947e3a5a7c52ddbfcaf992cccf0e488 fixed the issue.

This is my first contribution, if you have any comments I will be glad to hear them


[logs.txt](https://github.com/databricks/terraform-provider-databricks/files/10288455/logs.txt)

**Comment by nfx** [comment]
@adamcain-db - could you take a look at this table-acl permissions issue, when you have time?

**Comment by TheoPth** [comment]
```hcl
terraform {
  required_providers {
    databricks = {
      version = "1.7.0"
      source = "registry.terraform.io/databricks/databricks"
    }
  }
}

provider "databricks" {
  host  = "<host>"
  token = "<token>"
}

resource "databricks_sql_permissions" "this" {
  database = "preprod_finance"
  cluster_id = "<cluster-id>"
  privilege_assignments {
    principal  = "users"
    privileges = ["SELECT"]
  }
}
```
Here the code to reproduce the issue 
Issue can be reproduced with all provider versions v1.6.3 and after

**Comment by nkvuong** [comment]
@TheoPth the issue is with [this line](https://github.com/databricks/terraform-provider-databricks/blob/master/access/resource_sql_permissions.go#L151)

Basically it tries to match the name of the database, but the extra backtick to handle certain database names failed the match.

I've suggested how to fix it in your PR

**Comment by venkatasai-vanaparthi** [comment]
Thanks @nkvuong for the fix. Will the fix be added to the next release, could you please share an ETA for this?
cc: @TheoPth

**Comment by TheoPth** [comment]
Hi !
I hope to be able to propose the tests for this Friday, if not next week

**Comment by TheoPth** [comment]
Hi @venkatasai-vanaparthi 
All done, I provided the test who cover the fix. You'll find it in the MR ( I need a review )
