### ISSUE TITLE
[databricks_pipeline] should support Fixed size as Cluster mode

### ISSUE THREAD

**Issue by benbauer89** [databricks/terraform-provider-databricks#1776]
### Use-cases

Delta Live Tables pipeline should support fixed size cluster mode (as offered by the UI). Currently only `ENHANCED` and `LEGACY` are supported.

### Attempted Solutions

I've tried the following setup:

```  
  spark_conf = {
    "spark.databricks.cluster.profile" : "singleNode"
    "spark.master" : "local[*]"
  }

  num_workers = 0

  custom_tags = {
    "ResourceClass" : "SingleNode",
  }
```

 However, this does not create a `FIXED_SIZE` cluster mode but rather the default cluster mode is used. 

### Proposal
Extend available `cluster_mode` values.

**Comment by alexott** [comment]
Fixed size cluster in DLT is a cluster with fixed number of workers that is defined by `num_workers = N` (you can check this by looking into JSON in the UI).   I'm not sure that DLT supports single node clusters

**Comment by benbauer89** [comment]
Yes, that makes sense. However, I still feel there is sth. off. My terraform plan looks like this:

![image](https://user-images.githubusercontent.com/11137481/202505198-47f57fe8-f728-497b-8a97-ce196d8a2f2c.png)

However, once applied the `num_workers` is ignored and doesn't show up in the UI

**Comment by benbauer89** [comment]
I had several iterations and I am pretty sure it is a provider issue. It always uses the default setup and ignores the num_workers. 

```  + resource "databricks_pipeline" "main" {
      + channel       = "PREVIEW"
      + configuration = {
          + "Terraform"                            = "true"
          + "pipelines.applyChangesPreviewEnabled" = "true"
        }
      + continuous    = false
      + development   = false
      + edition       = "pro"
      + id            = (known after apply)
      + name          = "***"
      + photon        = false
      + storage       = "s3://***"
      + target        = "database"
      + url           = (known after apply)

      + cluster {
          + driver_node_type_id = (known after apply)
          + label               = "default"
          + node_type_id        = "c5.xlarge"
          + num_workers         = 0

          + aws_attributes {
              + instance_profile_arn = "arn:aws:iam::***"
            }
        }

      + library {

          + notebook {
              + path = "/Repos/***"
            }
        }
    }
```

**Comment by alexott** [comment]
it requires discussion with DLT dev team - if it's not supported in UI, then it most probably won't be supported in terraform.

**Comment by benbauer89** [comment]
Setting fixed size and num_workers == 0 is allowed via the UI. The documentation is also wrong, but this is an issue with the terraform provider package. I also linked the issue that is likely responsible for the incorrect behaviour

**Comment by benbauer89** [comment]
It has been fixed on Databricks and is now also working via terraform provider: https://docs.databricks.com/release-notes/delta-live-tables/2023/21/index.html
