### ISSUE TITLE
[FEATURE] New feature request: databricks_sql_alert resource

### ISSUE THREAD

**Issue by mikestiver** [databricks/terraform-provider-databricks#1780]
Hello!

I am working in a databricks workspace and want to use SQL Alerts to enhance monitoring for data issues.  I would like to create the Alerts via terraform, but there does not seem to be a resource yet to create Alerts.  It would be great if a databricks_sql_alert resource could be created to use in my terraform module.

**Comment by hawkaa** [comment]
I'd also be interested in this functionality!

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

The required API bindings could be found at https://pkg.go.dev/github.com/databricks/databricks-sdk-go@v0.3.3/service/sql#AlertsAPI.Create

**Comment by nfx** [comment]
@kartikgupta-db - do you want to pick this one up? it'll be a bit more fun
