### ISSUE TITLE
[ISSUE] Issue with `databricks_git_credential` resource

### ISSUE THREAD

**Issue by dflcosta-sonaemc** [databricks/terraform-provider-databricks#1781]
### Configuration
```hcl
# Copy-paste your Terraform configuration here

# GIT
 resource "databricks_git_credential" "ado" {
   depends_on = [azurerm_databricks_workspace.databricksBIT]
   provider = databricks.BIT
   git_username          = "XXXX"
   git_provider          = "gitHubEnterprise"
   personal_access_token = "${data.azurerm_key_vault_secret.KVSecret-XXXX.value}"
 }
 
 resource "databricks_repo" "bi_dlmaster_adbdmf" {
   depends_on = [azurerm_databricks_workspace.databricksBIT]
   provider = databricks.BIT
   git_provider = "gitHubEnterprise"
   path = "/Repos/XXX" 
   url = "https://github.com/XXX"
   branch = "${lookup(var.branchdatabricks, terraform.workspace)}"
```

### Expected Behavior

If another person runs this Terraform after another, even without having this resource in the local state, it should try a PATCH before a POST, to mitigate the error of a credential being already there.

### Actual Behavior

When we run our Terraform plan, it happens two things. If it is the first time running in a environment, it runs successfully and it creates the credential correctly. But when another person runs it afterwards, it shows this error: 

```
Error: cannot create git credential: Only one Git credential is supported at this time. If you would like to update your credential, please use the PATCH endpoint.
│
│   with databricks_git_credential.ado,
│   on DatabricksBIT.tf line 842, in resource "databricks_git_credential" "ado":
│  842:  resource "databricks_git_credential" "ado" {
│
```

### Steps to Reproduce

1. `terraform apply`
2. (another person/another run) `terraform apply`

### Terraform and provider versions

```hcl
terraform {   
  required_providers {
    databricks = {
      source = "databricks/databricks"
      version = "1.6.2"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.89.0"
    }
  }
}
```

**Comment by nkvuong** [comment]
are you running Terraform against the same remote state? the error suggests Terraform is trying to create the credential again in the 2nd run

**Comment by dflcosta-sonaemc** [comment]
Yeah, all teams' members use the same `backend` for our Terraform project.

```hcl
terraform {
  backend "azurerm" {
    storage_account_name = "infraiactfstatXXXX"
    container_name       = "azure"
    key                  = "XXX/XXXX/tfstate"
    use_azuread_auth     = true
    subscription_id      = "XXX"
    tenant_id            = "XXX"
  }
}
```

**Comment by alexott** [comment]
It looks like more a problem with the state management than with resource.

But we also have [force](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/git_credential#force) option...
