### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster_policy` resource. Data block needed

### ISSUE THREAD

**Issue by rohitnijhawan** [databricks/terraform-provider-databricks#1785]
When a user authors a terraform descriptor file (.tf file) to create a policy with one of these names:

1. Personal Compute
2. Power User Compute
3. Shared Compute
4. Job Compute

Errors are thrown

### Expected Behavior
For terraform resource like

```
resource "databricks_cluster_policy" {
  name = "Job Compute"
  definition =.....
}
```

The policy should either be created or ignored.

### Actual Behavior
The back end of the API throws an error informing the user that, "This policy already exists"

### Steps to Reproduce
Attempt to create a databricks cluster policy named Job Compute (or one of those listed above) using Terraform

### Exporter Notes
This isn't an exporter related ticket but the exporter will fetch all policies and an attempt to re-create them in a target workspace will fail.

These policies should be handled in a special way - ie. by using a a data block - and this ticket is about implementing that block.

**Comment by alexott** [comment]
We don’t have data source for cluster policies

**Comment by nkvuong** [comment]
This should either be handled by manually import the existing policy, or having a `force` option for Terraform to override the existing policy.

These policies are editable anyway

**Comment by rohitnijhawan** [comment]
Yes I agree @alexott 

That's why I wrote

>and this ticket is about implementing that block. 

meaning we need that data source

**Comment by timharsch** [comment]
Chance timing, but, I would really need to make use of this feature. Is the next release due out soon?
