### ISSUE TITLE
Creating cluster - apply policy default values does not work properly

### ISSUE THREAD

**Issue by hoaihuongbk** [databricks/terraform-provider-databricks#1787]
Dear team, I see somehow below flag does not work properly
```
apply_policy_default_values = true
```
**First:** I define a policy includes these 
```
 "spark_conf.spark.databricks.cluster.profile": {
    "type": "fixed",
    "value": "singleNode",
    "hidden": true
  },
  "custom_tags.ResourceClass": {
    "type": "fixed",
    "value": "SingleNode",
    "hidden": true
  }

...
  "num_workers": {
    "type": "fixed",
    "value": 0,
    "hidden": true
  },

...

"instance_pool_id": {
    "type": "fixed",
    "value": "${instance_pool_id}",
    "hidden": true
  },

```

**Second:** I suppose when creating a new cluster using this policy

```
resource "databricks_cluster" "single_node_cluster" {
  provider                = databricks.workspace
  cluster_name            = var.cluster_name
  spark_version           = var.databricks_spark_version
  policy_id               = var.cluster_policy_id
  autotermination_minutes = var.autotermination_minutes
  single_user_name        = var.single_user_name

 ...
  # Apply default value from the policy
  apply_policy_default_values = true

...
}
```
If I specify the **policy_id** & use **apply_policy_default_values** is **true** then the final request to Databricks APIs should include the default value if the key is not provided.

But, when I run the above code, it throws 
```
NumWorkers could be 0 only for SingleNode clusters. See https://docs.databricks.com/clusters/single-node.html for more details
```
I have tried to debug & see `profile` & `resourceClass` are not right.

**Question:** 

1. I see when TF runs Validate function, it does not know the policy default values, right?
2. Why don't we skip Validate in locally & let the server side (Databricks API) validate the request?

**Reference code:**
https://github.com/databricks/terraform-provider-databricks/blob/8c7b4fc062821a0f514cb4cfd3281b53c2e46232/clusters/clusters_api.go#L411

**Comment by alexott** [comment]
yes, terraform doesn't know about default values because they are defined in another resource

**Comment by alexott** [comment]
Even with the skipping validation on Terraform side, applying default values will not work correctly as it will lead to the configuration drift, and Terraform will try to change settings back to what you have in the cluster definition on each plan/apply. 

This is how Terraform works, and we can't do much there. The correct approach is to pull default values from the policy itself, something like this (here it's using `cluster_policy` data source):

```hcl
data "databricks_cluster_policy" "init_script" {
  name = "Policy with DBFS init script"
}

locals {
  policy = tomap(jsondecode(data.databricks_cluster_policy.init_script.definition))
  init_scripts = [
    for k, v in local.policy:
    join("|", [format("%03s", regexall("init_scripts\\.(\\d+)\\.dbfs\\.destination", k)[0][0]), v["value"]])
    if v["type"] == "fixed" && length(regexall("init_scripts\\.(\\d+)\\.dbfs\\.destination", k)) > 0
  ]
}
...
resource "databricks_job" "this" {
  name = "Terraform Demo (${data.databricks_current_user.me.alphanumeric})"
  new_cluster {
    num_workers   = 1
    spark_version = data.databricks_spark_version.latest.id
    node_type_id  = data.databricks_node_type.smallest.id
    dynamic "init_scripts" {
      for_each = toset(local.init_scripts)
      content {
        dbfs {
          destination = split("|",init_scripts.value)[1]
        }
      }
    }
  }
  notebook_task {
    notebook_path = databricks_notebook.this.path
  }
}
```

**Comment by ankitha-v1** [comment]
An alternative workaround would be to use lifecycle block to ignore the changes using ignore_changes, the below example is demonstrated for a job_cluster resource

Thank you for your assistance on this @alexott 

`locals {
  default_policy = {
    "custom_tags.Team" : {
      "type" : "fixed",
      "value" : "Test"
    },
    "node_type_id": {
      "type": "fixed",
      "value": "Standard_DS3_v2"
    },
  }
}

resource "databricks_cluster_policy" "fair_use" {
  name       = "Test cluster policy"
  definition = jsonencode(local.default_policy)
}

data "databricks_spark_version" "latest" {
  long_term_support = true
}

resource "databricks_job" "this" {
  name = "Job with multiple tasks - TF"

  job_cluster {
    job_cluster_key = "j"
    new_cluster {
      num_workers   = 2
      spark_version = data.databricks_spark_version.latest.id
      apply_policy_default_values = true
      policy_id = databricks_cluster_policy.fair_use.id
    }
  }

  task {
    task_key = "c"

    job_cluster_key = "j"

    notebook_task {
      notebook_path = "/Shared/Test"
    }
  }

    lifecycle {
      ignore_changes = [
        job_cluster,
      ]
  }

}`
