### ISSUE TITLE
[ISSUE] Issue with `databricks_table` resource. Views can not be created.

### ISSUE THREAD

**Issue by initions-soeren** [databricks/terraform-provider-databricks#1790]
### Configuration
```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.6.5"
    }
  }
  backend = "local"
}

provider "databricks" {
  alias = "workspace"
  host  = "https://<some_id>.azuredatabricks.net"
}

resource "databricks_table" "view_a" {
  provider           = databricks.workspace
  name               = "view_a"
  catalog_name       = "catalog_a"
  schema_name        = "schema_a"
  table_type         = "VIEW"
  data_source_format = "DELTA"
  view_definition    = <<EOT
    SELECT * FROM table_a
  EOT
  comment = "this table is managed by terraform"
  column {
    name      = "Id"
    position  = 0
    type_name = "INT"
    type_text = "int"
    type_json = "{\"name\":\"Id\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}}"
  }
}
```

### Expected Behavior
Creation of the view should complete with no errors.

### Actual Behavior
I get an error with the message:
- Error: cannot create table: CreateTable data_source_format can not be provided.

In the documentation it's not claryfied wether to set `data_source_format` or not. 
If I don't set the `data_source_format` I get the following error message:
- Error: Missing required argument. ... The argument "data_source_format" is required, but no definition was found.

### Steps to Reproduce
1. `terraform plan`
2. `terraform apply`

### Terraform and provider versions
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.6.5
+ provider registry.terraform.io/hashicorp/azurerm v3.31.0

### Important Factoids
It's kind of weired to provide a column block when trying to create a view, but this seems to be a different issue.

**Comment by initions-soeren** [comment]
As the API Specification states, the `data_source_format` is **only required** when table_type is VIEW:
- https://api-docs.databricks.com/rest/latest/unity-catalog-api-specification-2-1.html#:~:text=managed/external%20Table-,data_source_format,-string
- https://api-docs.databricks.com/rest/latest/unity-catalog-api-specification-2-1.html#:~:text=REQ*%20%3D%20Required%20for%20External%20and%20Managed%20Tables

**Comment by nkvuong** [comment]
`databricks_table` is deprecated, instead `databricks_sql_table` is recommended and now supports view
