### ISSUE TITLE
Issue with `databricks_job` resource during creation of a `sql_task`

### ISSUE THREAD

**Issue by MRubaldo** [databricks/terraform-provider-databricks#1794]
### Configuration
```hcl
resource "databricks_job" "heart_beat_job" {

  name = "Heartbeat_Sql"

  sql_task {
    query {
      query_id = databricks_sql_query.heart_beat.id
    }
    warehouse_id = module.adb_sql_endpoint.dbsqle_id
  }

  schedule {

    quartz_cron_expression=var.databricks_sql_job_heartbeat_schedule
    timezone_id="Europe/Rome"
    pause_status=var.databricks_sql_job_heartbeat_paused
  }
 
  depends_on = [
    databricks_sql_query.heart_beat_query
  ]
}

```

### Expected Behavior
create a sql databricks job with a schedule

### Actual Behavior
│ Error: Unsupported block type
on databricks.tf line 171, in resource "databricks_job" "heart_beat_job":
171: sql_task {
Blocks of type "sql_task" are not expected here.

### Terraform and provider versions
We are using the last version of the provider (1.6.5)

**Comment by MRubaldo** [comment]
Ok, it works.
Please update documentation, it is not clear that it is required to embed it on a task object (it says that task is required only when multiple tasks are needed).

Thanks a lot for your feedback.

**Comment by nkvuong** [comment]
agree, I will update the doc to reflect this (task block is the recommended way going forward, as that is supported with the latest API)
