### ISSUE TITLE
databrickes instance profile create error

### ISSUE THREAD

**Issue by suprobhat** [databricks/terraform-provider-databricks#1805]
<!-- Hi there,

cannot create instance profile: Verification of the instance profile failed. AWS error: Value (arn:aws:iam::<aws_
account_id>:instance-profile/databricks-profile-s3) for parameter iamInstanceProfile.arn is invalid. Invalid IAM Instance Profile ARN

### Affected Resource(s)
variable "prefix" {
  default = "databricks"
}

resource "aws_s3_bucket" "ds" {
  bucket = "${var.prefix}-ds"
  acl    = "private"
  versioning {
    enabled = false
  }
  force_destroy = true
  # tags = merge(var.tags, {
  #   Name = "${var.prefix}-ds"
  # })
}

data "aws_iam_policy_document" "assume_role_for_ec2" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      identifiers = ["ec2.amazonaws.com"]
      type        = "Service"
    }
  }
}

resource "aws_iam_role" "data_role" {
  name               = "${var.prefix}-first-ec2s3"
  description        = "(${var.prefix}) EC2 Assume Role role for S3 access"
  assume_role_policy = data.aws_iam_policy_document.assume_role_for_ec2.json
  #tags               = var.tags
}

data "databricks_aws_bucket_policy" "ds" {
  provider         = databricks.mws
  full_access_role = aws_iam_role.data_role.arn
  bucket           = aws_s3_bucket.ds.bucket
}

resource "aws_s3_bucket_policy" "ds" {
  bucket = aws_s3_bucket.ds.id
  policy = data.databricks_aws_bucket_policy.ds.json
}

data "databricks_aws_crossaccount_policy" "this" {
  pass_roles = [aws_iam_role.data_role.arn]
}

resource "aws_iam_policy" "cross_account_policy" {
  name   = "${var.prefix}-crossaccount-iam-policy"
  policy = data.databricks_aws_crossaccount_policy.this.json
}

data "databricks_aws_assume_role_policy" "this-2" {
    external_id = var.databricks_account_id
}

resource "aws_iam_role" "cross_account" {
  name               = "${var.prefix}-crossaccount-iam-role"
  assume_role_policy = data.databricks_aws_assume_role_policy.this.json
  description        = "Grants Databricks full access to VPC resources"
}

resource "aws_iam_role_policy_attachment" "cross_account" {
  policy_arn = aws_iam_policy.cross_account_policy.arn
  role       = aws_iam_role.cross_account.name
}

# resource "databricks_mws_credentials" "this-2" {
#   provider         = databricks.mws
#   account_id       = var.databricks_account_id
#   credentials_name = "${var.prefix}-creds"
#   role_arn         = aws_iam_role.cross_account.arn
# }

resource "aws_iam_instance_profile" "this" {
  name = "${var.prefix}-first-profile"
  role = aws_iam_role.data_role.name
}

resource "databricks_instance_profile" "ds" {
  provider = databricks.created_workspace
  instance_profile_arn = aws_iam_instance_profile.this.arn
}

resource "databricks_aws_s3_mount" "this" {
    instance_profile = databricks_instance_profile.ds.id
    s3_bucket_name = aws_s3_bucket.ds.bucket
    mount_name = "experiments"
}

resource "time_sleep" "wait-5" {
  depends_on = [
    aws_iam_role.cross_account]
  create_duration = "10s"
}

create error

**Comment by nkvuong** [comment]
@suprobhat do you have more details for this issue?
