### ISSUE TITLE
[DOC] The documentation of the databricks_entitlements resource is missing workspace_access as a possible entitlement

### ISSUE THREAD

**Issue by bricksterlad** [databricks/terraform-provider-databricks#1824]
### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/entitlements 

### Expected Details
[this](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/entitlements#argument-reference) section  should have **workspace_access** as a possible entitlement

```
resource "databricks_entitlements" "group_entitlement" {
  group_id                    = "group_id"
  databricks_sql_access = true
  workspace_access = true
}
```

**Comment by dvasdekis** [comment]
Probably same as #1853
