### ISSUE TITLE
[ISSUE] Issue with `databricks_user` resource. Not exported if user *only* has membership in the `users` group

### ISSUE THREAD

**Issue by rohitnijhawan** [databricks/terraform-provider-databricks#1827]
Users are not exported if they only belong to the `users` group

### Expected Behavior
a resource block like this should be created even if a user is not a member of any group other than `users`
```
resource "databricks_user" "data_lake_xp" {
  user_name "vbx@acme.com"
  external_id = "03800485473048"
}
```
### Actual Behavior
Perhaps to prevent the emission of a very large set of users (hundreds or thousands) the default behavior of the exporter is to only export users that belong to non-default groups

1. Default groups are - `admins` and `users`
2. Admins are exported

### Steps to Reproduce
1. Import a user into the workspace and do not add them to any group
2. Verify the user is in the users group
3. run the exporter with -services users,groups

### Terraform and provider versions
All Terraform versions
Provider versions 1.6.5 and lower

**Comment by rohitnijhawan** [comment]
This is also true for service principals - if a service principal is **only in the `users` group** it will not be exported.
If a service principal also has two separate external IDs but the same "display name", that too can cause problems on export (duplicate resource blocks)

**Comment by alexott** [comment]
issue with duplicate names is already fixed
