### ISSUE TITLE
[ISSUE] Issue with `databricks_secret_scope` resource - Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by evandrobeserra** [databricks/terraform-provider-databricks#1833]
### Configuration
provider.tf
```hcl
provider "databricks" {
  azure_workspace_resource_id = var.databricks_workspace_id
}

terraform {
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.3.0"
    }
  }
  required_version = ">= 0.14"
}
```
main.tf
```hcl
locals {
  suffix = var.environment
}

/*
# Retirado em conf com Jean e Gregory em 21/05/2021 - Não devemos provisionar Cluster através do module do Databricks no IaC. 
# Conforme o Projeto Analytics, o Cluster deve ser criado a partir dos pipelines do ADF, à partir dos pools criados no IaC.
resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = format("%s-%s-%s-%s", var.databricks_cluster_name, var.company_name, var.project_name, var.environment)
  spark_version           = var.databricks_spark_version
  node_type_id            = var.databricks_cluster_node_type_id
  autotermination_minutes = var.databricks_cluster_autotermination_minutes
  autoscale {
    min_workers = var.databricks_cluster_min_workers
    max_workers = var.databricks_cluster_max_workers
  }
  spark_conf = {
    "spark.databricks.cluster.profile" : "serverless",
    "spark.databricks.repl.allowedLanguages" : "python,sql",
    "spark.databricks.acl.dfAclsEnabled" : "true"
  }
}
*/

#databrick pools
resource "databricks_instance_pool" "databricks_pools" {
  for_each = { for idx, instance in var.databricks_pools_specs : idx => instance }

  instance_pool_name = each.value.instance_name
  min_idle_instances = each.value.min_idle_instances
  #max_capacity                          = each.value.max_capacity
  node_type_id                          = each.value.node_type_id
  idle_instance_autotermination_minutes = each.value.idle_instance_autotermination_minutes
  preloaded_spark_versions              = [var.spark_version]
}

resource "databricks_secret_scope" "storage" {
  name = "storage-scope"

  #keyvault_metadata {
  #  resource_id = var.key_vault_name
  #  dns_name    = var.key_vault_uri
  #}
}


```

### Actual Behavior
Error: Provider produced inconsistent result after apply

 When applying changes to databricks_secret_scope.storage, provider
"provider[\"registry.terraform.io/databrickslabs/databricks\"]" produced an
 unexpected new value: Root resource was present, but now absent.
 
 This is a bug in the provider, which should be reported in the provider's own
 issue tracker.

### Steps to Reproduce
terraform apply

### Terraform and provider versions
Terraform version: >= 0.14
Provider azurerm: 2.67.0
Provider Databricks: 0.3.0

**Comment by alexott** [comment]
please test with the latest version of provider - 0.3.0 is more than year old

**Comment by evandrobeserra** [comment]
I updated to the latest version of the provider (version 1.6.5). However, it is showing the error below at the time of "terraform init":

   Initializing provider plugins...
   - Finding Databricks/Databrick versions matching "1.6.5"...
   - Finding the latest version of databrickslabs/databricks...
   - Installing databricks/databricks v1.6.5...
   - Databricks/databricks v1.6.5 installed (self-signed, key ID 92A95A66446BCE3F)
   - Installing databrickslabs/databricks v1.5.0...
 
   Partner and community providers are signed by their developers.
Z If you want to know more about provider subscription, read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
 
   Notice: Additional information from registry provider
 
   The remote registry returned warnings for
Registry.terraform.io/databrickslabs/databricks:
   - For users on Terraform 0.13 or higher, this provider has changed to
   databricks/databricks. Update your source in required_providers.


   Error: Failed to install provider

   Error installing databrickslabs/databricks v1.5.0: checksum list is missing
   hash SHA-256 to
"https://github.com/databricks/terraform-provider-databricks/releases/download/v1.5.0/terraform-provider-databricks_1.5.0_linux_amd64.zip"

**Comment by alexott** [comment]
Please refactor to replace `databrickslabs` with `databricks` - the namespace has changed in version 1.0.0

**Comment by nfx** [comment]
closing issue due to the usage of old version
