### ISSUE TITLE
[DOC] Issue Update the client id section for azure data_access_config 

### ISSUE THREAD

**Issue by srvmsr** [databricks/terraform-provider-databricks#1843]
### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_global_config#azure-example
![image](https://user-images.githubusercontent.com/12263277/207324976-9c9efd37-728c-4171-888d-b72f5e0a66d2.png)

### Expected Details
Value of the client id should be client id of the service principle /user not tenant id 

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] "spark.hadoop.fs.azure.account.oauth2.client.id" : "${var.tenant_id}",

**Comment by nkvuong** [comment]
Closes by #1849
