### ISSUE TITLE
[FEATURE] Extend the `databricks_catalog` resource to allow for the creation of catalogs from Delta Shares

### ISSUE THREAD

**Issue by brianham-db** [databricks/terraform-provider-databricks#1858]
### Use-cases

When creating a Databricks-to-Databricks Delta Share via Terraform a user can create a Recipient, a Share, and add tables to a share.  However, there is no way to create a catalog on the recipient Metastore for the share via the databricks_catalog resource.  This step is necessary as the catalog is then used for a recipient to provide access to other users/groups in their workspace.

### Attempted Solutions

Only current workaround is to do this step manually via the UI.  Steps are detailed here via Data Explorer, SQL, or CLI.

https://docs.databricks.com/data-sharing/read-data-databricks.html

### Proposal

Extend the TF databricks_catalog resource to allow for the creation of catalogs from Delta Shares.

### References

https://api-docs.databricks.com/rest/latest/unity-catalog-api-specification-2-1.html?_ga=2.256550600.2105607269.1671031203-450893202.1659449140#:~:text=the%20External%20Location.-,Catalog%20CRUD%20API,-Object%20Models

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
