### ISSUE TITLE
[ISSUE] Cannot set `num_workers` to 0 `databricks_pipeline` in resource

### ISSUE THREAD

**Issue by ahirreddy** [databricks/terraform-provider-databricks#1875]
If you set `num_workers` to 0 in a `databricks_pipeline` resource - the field is considered "unset" and this is omitted. This is a mistake as 0 is a supported value for a DLT pipeline (0 implies a single-node cluster as per https://docs.databricks.com/workflows/delta-live-tables/delta-live-tables-configuration.html#cluster-config). When you set 0 - you end up with a legacy auto-scaling cluster of 1 -5 workers.

**Comment by ahirreddy** [comment]
I believe this issue is here https://github.com/databricks/terraform-provider-databricks/blob/master/pipelines/resource_pipeline.go#L37 - basically 0 is treated as "empty". Also note the incorrect comment here https://github.com/databricks/terraform-provider-databricks/blob/master/pipelines/resource_pipeline.go#L33 (maybe previously correct)

**Comment by nfx** [comment]
Tracked by https://github.com/databricks/databricks-sdk-go/issues/268

**Comment by alexott** [comment]
I've attempted to fix it, but it's not so easy:

We need to remove `omitempty` from that field and it will then default to `0`.  But this changes the behavior because if nothing is specified, then DLT creates a cluster with enhanced autoscaling from 1 to 5 nodes...  And we really can't distinguish if field is explicitly set to 0 vs not set at all

@nfx what do you think about this?

**Comment by roicostas** [comment]
In order to effectively have a single node cluster I think you should also set spark conf property "spark.databricks.cluster.profile" to "singleNode", at least to have a correct configuration. So that property may be checked too.

**Comment by hh-nharward** [comment]
> And we really can't distinguish if field is explicitly set to 0 vs not set at all

For a patch/minor fix would using a sentinel value like `-1` work, and separately remove `omitempty` (and the sentinel value) as a major/breaking change?

**Comment by hectorcast-db** [comment]
Hi,
we fixed this is the linked PR. When `num_workers` is zero, we cannot determine if the field is set in the Terraform Resource. We use the `spark_conf` to determine this instead. Be sure to set "spark.databricks.cluster.profile" to "singleNode".
