### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource

### ISSUE THREAD

**Issue by amitca71** [databricks/terraform-provider-databricks#1910]
### Configuration
I use foreach for dynamic tasks (databricks) as following:

```hcl
locals {
md_tables = [ “table1”,
“table2”,
“…”,
“table n”,
]
}
resource “databricks_job” “lakehouse-data” {
name = “master_data_${var.catalog}”
j…
######bronze tasks
dynamic “task” {
for_each = local.md_tables
content {
task_key = join(“-”, [“bronze”,replace(task.value, “.”, “-”)])
job_cluster_key = “j”
notebook_task {
notebook_path = var.stream_notebook_path
base_parameters={
“input_source”: var.lake_input_path
“output_path”: var.output_path,
“orig_table_name”: task.value,
“catalog”: var.catalog
}
}
}
}
…
```

the problem is that every time i execute the plan, the order of the tasks is changed, and it apears as if the resources are changed, while they are not. its very difficult to track the changes this way. is there away to make sure that the order would be guarenteed?
### Expected Behavior

if dynamic task was not changed, dont present as if its changed
### Actual Behavior

dynamic tasks always shows they are changed even if they are not
### Terraform and provider versions

all terraform versions
provider version = "1.7.0"

see also: https://discuss.hashicorp.com/t/for-each-keeps-changing-the-order-of-a-list-that-has-not-changed/39440/3
where it states that its provider to take care of it

**Comment by nfx** [comment]
unfortunately, this is a limitation of TF core at the moment. I've tried making this as set, but it didn't UX nicely

**Comment by dtcMLOps** [comment]
Having same issue

**Comment by dtcMLOps** [comment]
It seems this issue is already resolved since I have used numbers in the task and is keeping the order, e.g:

01_task...
02_task...
03_task...

and after running the same plan I got:

![Screenshot from 2023-08-11 17-54-11](https://github.com/databricks/terraform-provider-databricks/assets/115469901/ca9300de-665f-4764-a8d6-5859e1cb02cd)
