### ISSUE TITLE
[DOC] typo in argument reference of 'databricks_job' resource

### ISSUE THREAD

**Issue by teaVeloper** [databricks/terraform-provider-databricks#1916]
### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#job_clusters

### Expected Details
referenced argument should be 'job_cluster' in singular, as opposed to plural, as `terraform validate` outputs an error with plural and the example above uses singular.

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
change the markdown file https://github.com/databricks/terraform-provider-databricks/blob/master/docs/resources/job.md?plain=1#L80

### Important Factoids
i used `terraform validate` on both versions (plural and singular) with 
```
terraform {
  required_version = ">= 1.3.7"
  required_providers {
    databricks = {
      version = ">= 1.7.0"
      source  = "databricks/databricks"
    }
  }
}
```

### References
none

**Comment by nfx** [comment]
Thank you for the feature request! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.
