### ISSUE TITLE
[ISSUE] Issue with `databricks_dbfs_file` resource

### ISSUE THREAD

**Issue by rocksde** [databricks/terraform-provider-databricks#1920]
### Configuration

since version 1.8.0 there is a bug with below resource when running apply, works in plan though.
error says cannot find files. works without issues in 1.7.0
resource "databricks_dbfs_file" "jar_up" {
  for_each = toset(var.jar_upload)
  source   = "${path.root}/jar/${each.value}"
  path     = "/FileStore/${each.value}"
}

### Expected Behavior

upload files to dbfs as follows from plan:
 module.dbr_cluster.databricks_dbfs_file.jar_up["azure-eventhubs-spark_2.12-2.3.22.jar"] will be created
  + resource "databricks_dbfs_file" "jar_up" {
      + dbfs_path = (known after apply)
      + file_size = (known after apply)
      + id        = (known after apply)
      + md5       = "different"
      + path      = "/FileStore/azure-eventhubs-spark_2.12-2.3.22.jar"
      + source    = "./jar/azure-eventhubs-spark_2.12-2.3.22.jar"
    }

  module.dbr_cluster.databricks_dbfs_file.jar_up["overwatch_2.12-0.7.1.0.jar"] will be created
  + resource "databricks_dbfs_file" "jar_up" {
      + dbfs_path = (known after apply)
      + file_size = (known after apply)
      + id        = (known after apply)
      + md5       = "different"
      + path      = "/FileStore/overwatch_2.12-0.7.1.0.jar"
      + source    = "./jar/overwatch_2.12-0.7.1.0.jar"
    }

### Actual Behavior
says files don't exist during apply
╷
│ Error: File ./jar/overwatch_2.12-0.7.1.0.jar does not exist
│ 
│   with module.dbr_cluster.databricks_dbfs_file.jar_up["overwatch_2.12-0.7.1.0.jar"],
│   on modules/dbr_cluster/main.tf line 65, in resource "databricks_dbfs_file" "jar_up":
│   65:   source   = "${path.root}/jar/${each.value}"
│ 
╵
╷
│ Error: File ./jar/azure-eventhubs-spark_2.12-2.3.22.jar does not exist
│ 
│   with module.dbr_cluster.databricks_dbfs_file.jar_up["azure-eventhubs-spark_2.12-2.3.22.jar"],
│   on modules/dbr_cluster/main.tf line 65, in resource "databricks_dbfs_file" "jar_up":
│   65:   source   = "${path.root}/jar/${each.value}"
│ 
╵

### Steps to Reproduce
it goes through the plan phase ok but after apply with plan files it throughs the file does not exist error
works in 1.70 but not 1.8.0

### Terraform and provider versions
Terraform v1.3.6
provider[registry.terraform.io/databricks/databricks] ~> 1.8.0

**Comment by alexott** [comment]
Please attach debug output as described in the troubleshooting guide

**Comment by rocksde** [comment]
i am unable to reproduce the issue to run the debug. it is now running on both version. I will close this now.
