### ISSUE TITLE
[DOC] Missing project argument in google_project_iam_member and google_project_iam_custom_role in GCP deployment

### ISSUE THREAD

**Issue by AleksCallebat** [databricks/terraform-provider-databricks#1930]
### Affected Resource(s)

GCP deployment doc : https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/gcp-workspace#creating-a-vpc

### Expected Details

Running this code as is raises an error for the two roles, saying that the project argument is missing

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- Add `project=var.project` in `google_project_iam_member` and `google_project_iam_custom_role`

**Comment by nkvuong** [comment]
@AleksCallebat 
`google_project_iam_custom_role ` should default to the provider project configuration, but you are correct that `google_project_iam_member` requires a `project` argument.

**Comment by nkvuong** [comment]
Closes by #1999
