### ISSUE TITLE
[ISSUE] Issue with `databricks_dbfs_file` Data Source

### ISSUE THREAD

**Issue by mand35** [databricks/terraform-provider-databricks#1937]
### Configuration
```hcl
data "databricks_dbfs_file" "this" {
  path            = "dbfs:/path/to/file.jar"
  limit_file_size = false
}
```

### Expected Behavior
The documentation fit the actual requirement

### Actual Behavior
In the documentation is the example ` limit_file_size = 10240` and the description `[limit_file_size](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/dbfs_file#limit_file_size) - (Required) Do lot load content for files smaller than this in bytes`, but when I use this I get `Inappropriate value for attribute "limit_file_size": bool required.`

### Steps to Reproduce
```
data "databricks_dbfs_file" "report" {
  path            = "dbfs:/reports/some.jar"
  limit_file_size = 10240
}
```

### Terraform and provider versions
```
Version      : 3.209.19
Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/azurerm] ~> 3.20
└── provider[registry.terraform.io/databricks/databricks] ~> 1.3
```

**Comment by nkvuong** [comment]
@mand35 

the doc was incorrect, `limit_file_size` should be Boolean, and when set to true, it will not load content for files larger than 4MB
