### ISSUE TITLE
[ISSUE] Issue with `databricks_provider` resource

### ISSUE THREAD

**Issue by jantijink** [databricks/terraform-provider-databricks#1938]
### Configuration
I have a configuration with different modules. 
Note that some things might have been configured by users in the databricks workspace GUI. The workspace has already been deployed for some time.

databricks workspace code:
> resource "azurerm_databricks_workspace" "default" {
  name                          = format("dbw-%s-%s-%s", var.dbw-name, var.dbw-project, var.dbw-env)
  resource_group_name           = var.dbw-resource-group-name
  location                      = var.dbw-location
  sku                           = var.dbw-sku
  public_network_access_enabled = true

>  custom_parameters {
    no_public_ip                                         = true
    virtual_network_id                                   = var.dbw-vnet-id
    public_subnet_name                                   = var.dbw-public-subnet-name
    private_subnet_name                                  = var.dbw-private-subnet-name
    public_subnet_network_security_group_association_id  = var.dbw-public-subnet-nsg-association-id
    private_subnet_network_security_group_association_id = var.dbw-private-subnet-nsg-association-id
  }
}

additional databricks configuration (using databricks provider)
>resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Shared Autoscaling"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  library {
    maven {
      coordinates = "io.confluent:kafka-avro-serializer:6.2.1"
      repo        = "https://packages.confluent.io/maven/"
    }
  }
  library {
    maven {
      coordinates = "za.co.absa:abris_2.12:6.3.0"
      exclusions  = ["io.confluent:kafka-avro-serializer"]
    }
  }
  library {
    maven {
      coordinates = "org.apache.spark:spark-streaming-kafka-0-10_2.12:3.3.0"
    }
  }
  autoscale {
    min_workers = 1
    max_workers = 3
  }
}

>resource "databricks_mount" "lakehouse" {
  for_each = toset(var.dbw-st-containers)
  name       = each.value
  uri        = "abfss://${each.value}@${var.dbw-st-account}.dfs.core.windows.net"
  cluster_id = databricks_cluster.shared_autoscaling.cluster_id
  extra_configs = {
    "fs.azure.account.auth.type" : "OAuth",
    "fs.azure.account.oauth.provider.type" : "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider",
    "fs.azure.account.oauth2.client.id" : "{{secrets/${local.secret_scope}/${local.app_id_key}}}",
    "fs.azure.account.oauth2.client.secret" : "{{secrets/${local.secret_scope}/${local.secret_key}}}",
    "fs.azure.account.oauth2.client.endpoint" : "{{secrets/${local.secret_scope}/${local.endpoint_key}}}",
    "fs.azure.createRemoteFileSystemDuringInitialization" : "false",
  }
}

### Expected Behavior
Succesful completion of the 'terraform plan' command.

### Actual Behavior
The terraform plan step did not complete and produced an error as detailed under the debug output.

### Steps to Reproduce
1. `terraform plan'

### Terraform and provider versions
Terraform v1.3.7
on windows_386
+ provider registry.terraform.io/confluentinc/confluent v1.24.0
+ provider registry.terraform.io/databricks/databricks v1.9.0
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v3.39.1
+ provider registry.terraform.io/hashicorp/random v3.4.3

### Debug Output
>│ Error: Plugin did not respond
│
│   with module.dbw-content.databricks_secret.service_principal_secret,
│   on modules\dbw-content\secrets.tf line 23, in resource "databricks_secret" "service_principal_secret":
│   23: resource "databricks_secret" "service_principal_secret" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.dbw-content.databricks_secret.service_principal_endpoint,
│   on modules\dbw-content\secrets.tf line 29, in resource "databricks_secret" "service_principal_endpoint":
│   29: resource "databricks_secret" "service_principal_endpoint" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

>Stack trace from the terraform-provider-databricks_v1.9.0.exe plugin:

>panic: Error reading level state: strconv.ParseInt: parsing "1673948697061": value out of range

>goroutine 103 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x131117c0, {0x13184a60, 0x1, 0x1}, 0x8)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:553 +0x279
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0x131117c0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:351 +0x3a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0x13493dc0, {{{0x15676e8, 0x13184730}}, {0x1339160, 0x135482c0}})        
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:599 +0x1d9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x13005810, {0x1567188, 0x13708498}, 0x13548060)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:587 +0x23f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x134707d0, {0x1567188, 0x137081c8}, 0x1370a480)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x13f43e0, 0x134707d0}, {0x1567188, 0x137081c8}, 0x1346e080, 0x0)    
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x133fa360, {0x1568ce0, 0x133fa000}, 0x135440a0, 0x1342b9e0, 0x1ac2788, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x133fa360, {0x1568ce0, 0x133fa000}, 0x135440a0, 0x0)
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/google.golang.org/grpc/server.go:963 +0x25f

>Error: The terraform-provider-databricks_v1.9.0.exe plugin crashed!

>This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Important Factoids
Other versions of the databricks provider also seem to have this issue.

**Comment by nkvuong** [comment]
@William-LP @jantijink it is similar to this issue, could you check about the 32/64-bit issue?

https://github.com/hashicorp/terraform-plugin-sdk/issues/469

**Comment by jantijink** [comment]
My apologies, it seems that indeed I accidentally used the 32-bit version when updating my terraform version. Using the correct version resolves the problem.

**Comment by William-LP** [comment]
Same here, installing terraform in 64-bits version fixed the issue.
