### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource

### ISSUE THREAD

**Issue by manojhegde97** [databricks/terraform-provider-databricks#1940]
### Configuration
```hcl
resource "databricks_catalog" "sandbox" {
  metastore_id = "6a131802-e340-4322-b356-98cb0f0ba7f8"
  name         = "SANDBOX"
  comment      = "this catalog is managed by terraform"
  properties = {
    purpose = "testing"
  }
}
```

### Expected Behavior
After creating the catalog , and planning the terraform again it should not recreate the catalog

### Actual Behavior
Catalog name will be created in the lowercase letter, but if we do terraform plan again, terraform tries to recreate the resource

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `Create the Catalog with uppercase letter name`
2. `Run terraform plan again`

### Terraform and provider versions
terraform :  1.3.7 , Provider : 1.9.0

### Debug Output

Below is the log which we get when we do terraform plan after the catalog creation
databricks_catalog.sandbox: Refreshing state... [id=sandbox]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

 databricks_catalog.sandbox must be replaced
-/+ resource "databricks_catalog" "sandbox" {
      ~ id            = "sandbox" -> (known after apply)
      ~ name          = "sandbox" -> "SANDBOX" # forces replacement
      ~ owner         = "manoj.hegde+uc@databricks.com" -> (known after apply)
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

### Important Factoids
As a workaround pass the catalog name with the lowercase letter by using lower()
```hcl
resource "databricks_catalog" "sandbox" {
  metastore_id = "6a131802-e340-4322-b356-98cb0f0ba7f8"
  name         = lower("SANDBOX")
  comment      = "this catalog is managed by terraform"
  properties = {
    purpose = "testing"
  }
}
```

**Comment by nfx** [comment]
this is a feature of our platform and not a bug.
