### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource

### ISSUE THREAD

**Issue by nsenno-dbr** [databricks/terraform-provider-databricks#1942]
### Configuration
```hcl
resource "databricks_external_location" "external_location" {
  name = "${var.region}-external"
  url = format("abfss://%s@%s.dfs.core.windows.net/",
    var.storage_container_name,
  var.storage_account_name)
  credential_name = var.storage_credential_id
  comment         = "Managed by TF"
}

resource "databricks_grants" "external_location" {
  external_location = databricks_external_location.external_location.id
  grant {
    principal  = var.user_group
    privileges = ["READ_FILES", "WRITE_FILES", "CREATE_EXTERNAL_TABLE"]
  }
}

resource "databricks_catalog" "catalog" {
  metastore_id = var.metastore_id
  name         = var.catalog_name
  storage_root = "${databricks_external_location.external_location.url}${databricks_external_location.external_location.name}"
}

resource "databricks_grants" "catalog" {
  catalog = databricks_catalog.catalog.name
  grant {
    principal  = var.user_group
    privileges = ["USE_CATALOG", "USE_SCHEMA", "CREATE_SCHEMA", "CREATE_TABLE", "MODIFY"]
  }
}

```

### Expected Behavior
When running the above module a unity catalog catalog should be created at the location based on the co-created external location. 

### Actual Behavior
Error message was returned: 

```
Error: Provider produced inconsistent final plan

When expanding the plan for module.spoke-catalog.databricks_catalog.catalog
to include new values learned so far during apply, provider
"registry.terraform.io/databricks/databricks" produced an invalid new value
for .storage_root: was
cty.StringVal("abfss://data@dbradvsrdeveussa.dfs.core.windows.net/eu-external"),
but now
cty.StringVal("abfss://data@dbradvsrdeveussa.dfs.core.windows.neteu-external").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce
 

1. create a `databricks_catalog` resource with a `storage_root` location built from the concatination of an external location url and the external location name 

### Terraform and provider versions

running azure rm 3.38.0 and databricks 1.7.0

Unfortunately this is running on a customers jenkins instance so I'm unable to get additional version information 

### Debug Output

Unable to run using deubg

**Comment by nsenno-dbr** [comment]
Note that issue goes away if the `storage_root` is hardcoded. Therefore, it seems this is an issue with the `databricks_external_location.url` attribute

**Comment by nkvuong** [comment]
@nsenno-dbr could you check what `databricks_external_location.external_location.url` is by either inspecting TF state, or outputting it?

**Comment by nsenno-dbr** [comment]
Hey @nkvuong here is the output of `terraform show` 

![image](https://user-images.githubusercontent.com/59416974/213749982-88d1b4c7-aef7-4f91-bf65-c649f380ef51.png)

**Comment by nsenno-dbr** [comment]
Note that when the external location is defined it has a slash at the end 

![image](https://user-images.githubusercontent.com/59416974/213755409-589ea32a-f1f1-41e6-9990-ac19ddd98b05.png)

**Comment by nkvuong** [comment]
UC Ext Location API removes the trailing slash from the url automatically (which is annoying)

Could you remove the trailing slash in the local variable, and then supply it for `storage_root`?

The proper fix would be to put validation to disallow url that ends with slash

**Comment by nsenno-dbr** [comment]
Sure I've already done that. Just as a note, this code block for the external location came directly from our documentation 

https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/external_location#example-usage
