### ISSUE TITLE
[FEATURE] Add job run now functionality

### ISSUE THREAD

**Issue by EMiiiiiler** [databricks/terraform-provider-databricks#1946]
### Use-cases

We commonly use jobs to set up databases or schemas and to set configurations for our delta tables.

### Attempted Solutions

At the moment we can deploy these jobs via Terraform, but have to output the Job URL in the hope that the person running the terraform remembers to run the created job too.

### Proposal

Integrate the Run now part of the Databricks Jobs API to the Databricks Terraform provider.

### References
N/A

**Comment by alexott** [comment]
Running a job is an action, while Terraform is concentrating on the making sure that objects are in the "desired" state. 
You can achieve such thing right now already by using the `null` resource, something like this (example is for submit run):

```hcl
locals {
  job_params = {
    "run_name": "init metastore",
    "existing_cluster_id": databricks_cluster.ms_setup.id
    "notebook_task": {
      "notebook_path": databricks_notebook.metastore_setup.path
    }
  }
}

# TODO: think about more portable solution... Maybe https://github.com/Mastercard/terraform-provider-restapi ?
resource "null_resource" "do_metastore_init" {
  depends_on = [databricks_notebook.metastore_setup, databricks_cluster.ms_setup, 
      azurerm_private_endpoint.sql_server, azurerm_mssql_database.metastore_db]
  provisioner "local-exec" {
    command = "curl -n -X POST -H 'Authorization: Bearer ${databricks_token.pat.token_value}' 'https://${azurerm_databricks_workspace.this.workspace_url}/api/2.0/jobs/runs/submit' -d '${jsonencode(local.job_params)}'"
    interpreter = ["bash", "-c" ]
  }
}

```

**Comment by EMiiiiiler** [comment]
@alexott -
