### ISSUE TITLE
[Feature] Feature to modify/override the Default Personal Compute Policy

### ISSUE THREAD

**Issue by pramodpawade** [databricks/terraform-provider-databricks#1947]
### Use-cases

Feature to modify/Override the default personal compute policy

### Attempted Solutions

The data resource within `databricks_cluster_policy` doesn't have any option for an override.

### Proposal

To provide a feature for overriding the default personal compute policy the same way we can do this from the Databricks UI. Please see reference section for the Databricks UI screenshot 

### References
 https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/cluster_policy
![image](https://user-images.githubusercontent.com/26111406/214014064-e482c431-a8eb-40a8-966f-e2ffeca09e33.png)

**Comment by pramodpawade** [comment]
Hi @nfx @alexott Can you please have a look at this feature request?

**Comment by wabujabal** [comment]
Hello Team 

What is this feature state at your end? can you please share if there is any ETA you can share for this feature to be imbedded in future releases?

**Comment by kelseymok** [comment]
@pramodpawade @nfx Hi there, while #2351 is marked as completed, the databricks_cluster_policy does not create an override as described by the ticket because it is a data source (read-only). If I am mistaken about its usage, any chance someone from the team can post an example of how to do this by just using the data source? If not, I think this ticket should be re-opened.

Thanks so much for your help!

**Comment by pramodpawade** [comment]
Hi @kelseymok  I can confirm the same behaviour as I tried the below code

```
data "databricks_cluster_policy" "default_personal_policy" {
  name                                                = "Personal Compute"
  max_clusters_per_user                  = 10
  policy_family_id                               = "personal-vm"
  policy_family_definition_overrides = jsonencode(local.default_personal_compute_overrides)
}
```
The above data resource does seem to add the `max_clusters_per_user` but it's not overriding the policy.

@nfx @alexott Can you please share a working example of modifying the personal compute policy?

**Comment by alexandremoyrand** [comment]
I'm facing the same issue: can't modify the default Personal Compute policy.
Any news on this ?
