### ISSUE TITLE
[ISSUE] Issue with webhook_notifications for `databricks_job` resource

### ISSUE THREAD

**Issue by fuselessmatt** [databricks/terraform-provider-databricks#1950]
### Configuration
```hcl
resource "databricks_job" "incremental_job" {
  [...]
  webhook_notifications {
    on_failure = var.not_system_destinations
  }
}

variable "not_system_destinations" {
  type = list(string)
  default = ["databricks-alerts channel"]
}
```

### Expected Behavior

According the [official documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#webhook_notifications-configuration-block), that is how you the `webhook_notifications` if you have defined a [Slack alert notification](https://docs.databricks.com/sql/admin/alert-destinations.html#slack-destination).

### Actual Behavior

We get this error when we run plan

> │ Error: Unsupported argument
> │ 
> │   on dms/dms.tf line 124, in resource "databricks_job" "incremental_job":
> │  124:     on_failure = var.not_system_destinations
> │ 
> │ An argument named "on_failure" is not expected here. Did you mean to define
> │ a block of type "on_failure"?

Note that this syntax works with email_notifications

### Steps to Reproduce

Define a job and try to use webhook_notifications block and the on_failure parameter

### Terraform and provider versions

Terraform 1.3.5
Databricks 1.9.0

### Important Factoids

Maybe you should also give an example how this is expected to [look here](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#webhook_notifications-configuration-block).

**Comment by TakeshiMatsukura** [comment]
https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate
Please check this.
Though email_notification's on_failure is just the array of strings, webhook_notification's on_failure is the array of (json) objects.

Please set the list of the json like below and check if it works.
`"on_failure": [
{
"id": "0481e838-0a59-4eff-9541-a4ca6f149574"
}
]`

https://docs.databricks.com/administration-guide/workspace/notification-destinations.html

**Comment by fuselessmatt** [comment]
You mean as a variable somehow?

Otherwise, the syntax seems to be

```hcl
  webhook_notifications {
    on_failure {
      id = var.not_system_destinations[0]
    }
  }
```

**Comment by TakeshiMatsukura** [comment]
Sorry, I misunderstood the spec.
Yes, you're correct.

https://github.com/databricks/terraform-provider-databricks/pull/1842

You can get the id from the url of the UI on SQL Admin Console - Alert destinations - <your destination>.

https://<workspace url>/sql/destinations/<notification ID>

**Comment by fuselessmatt** [comment]
No worries! I am confused by this as well! My point is that the documentation is not clear enough to make it easy to add a Slack notification at the moment and that the Databricks Terraform team should improve the documentation about this.

Regarding the URL, at least in AWS the format seems to be 

`https://<workspace url>/sql/destinations/<notification ID>?o=<unknown_number>`, 

but it is the `<notification ID>` part and not the entire thing?

**Comment by TakeshiMatsukura** [comment]
Yes, you need only <notification ID>.
