### ISSUE TITLE
[DOC] Unclear how to configure webhooks

### ISSUE THREAD

**Issue by EvanMiiiiler** [databricks/terraform-provider-databricks#1972]
First off - incredible resource, this repo has made managing our Databricks environments significantly simpler. 

I've configured a few Slack webhooks and they work well when setting up via the UI, but I can't get them working using Terraform.

I'm happy to update the docs with direction from developers.

### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job

### Expected Details

"Each entry in webhook_notification block takes a list webhook blocks. The field is documented below."

I've tried to create a webhook block in many places in the resource "databricks_job" but every time it says "Blocks of type "webhook" are not expected here."

I've also looked at the Databricks Job Create 2.1 API in an attempt to use the webhook logic presented there to back solve for how it might work in Terraform. I've tried multiple approaches and haven't been able to get it working.

**If an example can be shared I'm happy to update the Example Usage add webhook configuration.**

#### Tried approaches

```
  webhook_notifications {

    on_start = [
      dynamic "webhook" {
        content {
        id = "notification-id"
        }
      }
      ]

      }


Error: Missing item separator
│ 
│ On main.tf line 176: Expected a comma to mark the beginning of the next
│ item.

```

```
  webhook_notifications {

    on_start = [webhook{id="notification-id"}]

      }

│ Error: Missing item separator
│ 
│ On main.tf line 175: Expected a comma to mark the beginning of the next
│ item.
```

```
  webhook_notifications {

    on_start = ["notification-id"]

    webhook{
      id="notification-id"
      }

    }

│   on main.tf line 174, in resource "databricks_job" "this":
│  174:     webhook {
│ 
│ Blocks of type "webhook" are not expected here.
```

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- Add working example for adding webhook notifications to existing jobs
- Ideally I would like to have the Databricks API Job Create 2.1 Example implemented as the example for the Databricks Terraform Job Resource as it is much more complex than the existing Databricks Terraform Jobs example

### Important Factoids
- Databricks API Job Create 2.1 has much more comprehensive examples than Terraform: https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate

**Comment by EvanMiiiiler** [comment]
I FOUND IT. It looks like the github documentation is more up to date than the Terraform provider page (which I was using). Do you need to push this documentation to Terraform is it managed by them?

https://github.com/databricks/terraform-provider-databricks/blob/master/docs/resources/job.md

After all this I'm still a little unsure about two things:

- Am I right in understanding tha ton_start/on_failure etc aren't lists, they are blocks that need to be set?
- What is the purpose of the webhook block?

**Comment by fuselessmatt** [comment]
Yes! It seems we are on the same track here https://github.com/databricks/terraform-provider-databricks/issues/1950

**Comment by EvanMiiiiler** [comment]
@fuselessmatt - yep seems to be covered elsewhere. I'll close this
