### ISSUE TITLE
[DOC] Correct identifier of data source "databricks job" is "job_id" and not "id"

### ISSUE THREAD

**Issue by guillesd** [databricks/terraform-provider-databricks#1986]
### Affected Resource(s)
In https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job it is specified in the Attribute reference that: "[id](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#id) - the id of [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) if the resource was matched by name."

### Expected Details
This is actually not true, since `id` just returns "-". The actual id of the job is `job_id`.

### List of things to potentially add/remove:
Just change `id` for `job_id` in the docs.

**Comment by iandexter** [comment]
I think what this means is the ID to reference when **importing** a `databricks_job` resource? Can you elaborate what you mean with an example, @guillesd ? Thanks!

**Comment by guillesd** [comment]
sure, what I mean is, when you have a databricks job resource, i.e.:
```hcl
data "databricks_job" "this" {
  job_name = "My job"
}
```
and then let's say you want to explore what is the actual content of this data source, so you create an output to explore easier:
```hcl
output "my_databricks_job" {
  value = data.databricks_job.this
}
```
This is what `data.databricks_job.this` provides as an output:
```
      + my_job  = {
          + id           = "_"
          + job_id       = "764062641151921"
          + job_name     = "My job"
          + job_settings = [
              + {
                  + created_time      = 1673259719254
                  + creator_user_name = "9f4d197a-a483-4659-adbf-51f52d693f5d"
                  + job_id            = 764062641151921
                  + settings          = [
                      + {
                          + dbt_task                  = []
                          + email_notifications       = [
                              + {
                                  + alert_on_last_attempt     = false
                                  + no_alert_for_skipped_runs = false
                                  + on_failure                = []
                                  + on_start                  = []
                                  + on_success                = []
                                },
                            ]
                          + existing_cluster_id       = ""
                          + format                    = "MULTI_TASK"
                          + git_source                = []
                          + job_cluster               = []
                          + library                   = []
                          + max_concurrent_runs       = 1
                          + max_retries               = 0
                          + min_retry_interval_millis = 0
                          + name                      = "my_job"
                          + new_cluster               = []
                          + notebook_task             = []
                          + pipeline_task             = []
                          + python_wheel_task         = []
                          + retry_on_timeout          = false
                          + schedule                  = []
                          + spark_jar_task            = []
                          + spark_python_task         = []
                          + spark_submit_task         = []
                          + tags                      = {}
                          + task                      = []
                          + timeout_seconds           = 0
                        },
```
As you can see, the actual job ID is under the attribute `job_id` and under `id` there's only a "-". In the documentation however, the following reads:

*This data source exports the following attributes:*

*[id](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#id) - the id of [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) if the resource was matched by [name](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#name).
name - the job name of [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) if the resource was matched by id.
[job_settings](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#job_settings) - the same fields as in [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job).*

**Comment by guillesd** [comment]
Concretelly, this sentence:
*[id](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#id) - the id of [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) if the resource was matched by [name](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#name).*

**Should be:**
*[job_id](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#id) - the id of [databricks_job](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) if the resource was matched by [name](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/job#name).*

**Comment by guillesd** [comment]
@iandexter I opned a PR to address this.

**Comment by guillesd** [comment]
@iandexter my bad, I was using the 1.5.0 version of the provider, which indeed had `job_id` as the attribute containing the job ID. In more recent versions this has been corrected.

**Comment by alexott** [comment]
@guillesd do we still need PR ?

**Comment by guillesd** [comment]
Noo, I closed it! It was a confusion on my side with the provider versions!
