### ISSUE TITLE
[ISSUE] Removing webhook_notifications block in databricks_job errors out

### ISSUE THREAD

**Issue by vadivelselvaraj** [databricks/terraform-provider-databricks#1989]
When we remove `webhook_notifications` block from an existing databricks job, we see `Error: cannot update job: Webhook with id '' was not found.`

### Expected Behavior
The webhook should get removed without throwing an error

### Versions
Terraform version: 1.3.5
Databricks TF provider version: 1.9.2

**Comment by alexott** [comment]
Can you add a debug log as described in the [troubleshooting guide](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting)

**Comment by fdvieira** [comment]
Hello,

I also have this error. Is there any news on this?

Francisco Vieira

**Comment by iandexter** [comment]
Hi, @fdvieira -- please add the debug logs for the error you encounter. Thanks!

**Comment by fdvieira** [comment]
Hello,

It's the exact issue described in this issue: https://github.com/databricks/terraform-provider-databricks/issues/2123.

Still need my debug logs?

Francisco

**Comment by mvilts** [comment]
I can reproduce this via the UI with the following steps:
1. create a notification destination (in my case a slack webhook)
2. create a new job 
3. add the notification to at the task level (notification on Failure)
4. delete the notification destination
5. attempt to add a notification at the job level and you will receive a message similar to the attached image.
![image](https://github.com/databricks/terraform-provider-databricks/assets/118782236/3c6ab49e-bf40-492a-ab19-a32f7ead9425)
I've come across two ways to solve this (there may be more);
1. delete the job and recreate it (not a big deal if you have it terraformed)
2. add an existing notification back to the task itself

**Comment by yb-yu** [comment]
Due to this issue I cannot remove webhook notifications settings from asset bundle..

**Comment by pietern** [comment]
Repro in #3309. Discussed the issue with @mgyucht.
