### ISSUE TITLE
 Error: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by mattjames1978** [databricks/terraform-provider-databricks#1993]
When I try to create a databricks cluster using the below code I get the following error.

```hcl
terraform {
    required_providers {
      databricks = {
       source = "databricks/databricks"
       #version = "=0.5.9"
       version = "=1.9.1"
    }
  }
}

data "databricks_node_type" "smallest" {
  local_disk = true

    depends_on = [
    azurerm_databricks_workspace.lgr-databricks-workspace
  ]
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true

  depends_on = [
    azurerm_databricks_workspace.lgr-databricks-workspace
  ]
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = var.databricks_cluster_name
  spark_version           = data.databricks_spark_version.latest_lts.id
  #spark_version           = data.databricks_spark_version.gpu_ml.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20

  autoscale {
    min_workers = 1
    max_workers = 50
  }
  spark_conf = {
    #"spark.databricks.cluster.profile" : "singleNode"
    "spark.databricks.io.cache.enabled" : true,
    "spark.hadoop.javax.jdo.option.ConnectionDriverName" : "com.microsoft.sqlserver.jdbc.SQLServerDriver",
    "spark.hadoop.javax.jdo.option.ConnectionURL" : "jdbc:sqlserver://sqlserver-raghav-demo.database.windows.net:1433;database=metastoredb"
    "spark.databricks.delta.preview.enabled" : true,
    "spark.hadoop.javax.jdo.option.ConnectionUserName" : var.sql_server_admin,
    "datanucleus.fixedDatastore" : false,
    "spark.hadoop.javax.jdo.option.ConnectionPassword" : var.sql_server_admin_pwd,
    "spark.driver.maxResultSize" : "32gb", 
    "datanucleus.autoCreateSchema" : true,
    "spark.sql.hive.metastore.jars" : "builtin",
    "hive.metastore.schema.verification" : false,
    "datanucleus.schema.autoCreateTables" : true,
    "spark.sql.hive.metastore.version" : "2.3.9"

  }
}
```

ERROR
```
│ Error: invalid character '<' looking for beginning of value
│ <!doctype html><html><head><meta... (487 more bytes)
│ 
│   with module.adb.data.databricks_spark_version.latest_lts,
│   on ../../LGR-DataPlatform-Databricks/02.LandingZone/02.AzureDatabricks/adb/main.tf line 26, in data "databricks_spark_version" "latest_lts":
│   26: data "databricks_spark_version" "latest_lts" {
```

**Comment by mattjames1978** [comment]
[main.txt](https://github.com/databricks/terraform-provider-databricks/files/10716603/main.txt)

**Comment by alexott** [comment]
How do you configure the provider itself? What authentication method are you using? Please collect logs as described in troubleshooting guide or issue template and attach

**Comment by mattjames1978** [comment]
Hi Alex, I am calling the provider itself at the top using this code. I am running the job via ADO and authenticating to Azure with service principal. The workspaces get created, along with SQL server and DB for external metastore but fails to create the cluster. I will try and upload the logs. thanks

terraform {
    required_providers {
      databricks = {
       source = "databricks/databricks"
       #version = "=0.5.9"
       version = "=1.9.1"
    }
  }
}

**Comment by mattjames1978** [comment]
Hi Alex, I think I already set that else where

![image](https://user-images.githubusercontent.com/97545090/218433412-a46ca36d-6c3e-43b7-9b18-8b28cc4e781a.png)

**Comment by mattjames1978** [comment]
Hi Alex, I have run terraform locally (not from ADO) and authenticating using azure cli to gather some debug logs. Please find log file for further help.
thanks
Matt
[terraform.zip](https://github.com/databricks/terraform-provider-databricks/files/10732113/terraform.zip)

**Comment by mattjames1978** [comment]
If I change public_network_access_enabled to true and set NSGs to all rules it deploys, similar to issue logged here:
https://learn.microsoft.com/en-us/answers/questions/1040725/databricks-cluster-creation-fails-when-public-netw

**Comment by alexott** [comment]
yes, it's always a tricky part about private link :-)
