### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource shows changes for cluster with attached cluster_policy with no changes.

### ISSUE THREAD

**Issue by chandler1331** [databricks/terraform-provider-databricks#1994]
### Configuration

```hcl
resource "databricks_job" "this" {
  name                = "this"
  job_cluster {
    job_cluster_key = "multi-node-cluster"
    new_cluster {
      policy_id           = databricks_cluster_policy.databricks_cluster_policy_4.id
      data_security_mode  = "SINGLE_USER"
      enable_elastic_disk = false    
    }
  }
}
```
JSON for Cluster policy listed above:

```json
  "cluster_log_conf.path": {
    "type": "fixed",
    "value": "${logging_s3_path}"
  },
  "cluster_log_conf.region": {
    "type": "fixed",
    "value": "${aws_region}"
  },
  "cluster_log_conf.type": {
    "type": "fixed",
    "value": "S3"
  },
  "spark_env_vars.DATABRICKS_GANGLIA_SNAPSHOT_PERIOD_MINUTES": {
    "type": "fixed",
    "value": "10"
  },
```

### Expected Behavior
When a PLAN is performed, I would expect the provider to coalesce the changes between the Cluster and the Cluster policy. 

### Actual Behavior
With no changes to the Cluster or the Job, a PLAN and APPLY shows changes to the items that are listed in the Cluster policy for cluster_log_conf and spark_env_vars.

Output of PLAN and APPLY
# module.databricks_infrastructure.databricks_job.this will be updated in-place
~ resource "databricks_job" "this" {
      name                      = "this"      
      # (8 unchanged attributes hidden)
    ~ job_cluster {
          # (1 unchanged attribute hidden)

        ~ new_cluster {
            ~ spark_env_vars               = {
                - "DATABRICKS_GANGLIA_SNAPSHOT_PERIOD_MINUTES" = "10" -> null
                  # (1 unchanged element hidden)
              }
              # (13 unchanged attributes hidden)
            - cluster_log_conf {

                - s3 {
                    - destination       = "*****" -> null
                    - enable_encryption = false -> null
                    - region            = "****" -> null
                  }              
				}
              # (1 unchanged block hidden)
          }
      }
      # (9 unchanged blocks hidden)
 }

### Steps to Reproduce
1. `terraform apply` or `terraform plan`

### Terraform and provider versions
Terraform v1.3.7
on windows_amd64
- Using previously-installed hashicorp/time v0.9.1
- Using previously-installed hashicorp/local v2.3.0
- Using previously-installed databricks/databricks v1.9.2
- Using previously-installed hashicorp/aws v3.76.1
- Using previously-installed hashicorp/vault v3.12.0
- Using previously-installed hashicorp/null v3.2.1
- Using previously-installed hashicorp/template v2.2.0

### Debug Output
https://gist.github.com/chandler1331/5aaf2a77e5ba45c14bd230700c22cef0

### Important Factoids
It appears that the policy is being added to the Cluster after the Cluster state is saved to the state file.

**Comment by alexott** [comment]
it's the same issue as #1787. Unfortunately it's how Terraform works - job is created independently of the cluster policy, and default values ingested by policy are considered as configuration drift and removed as job resource isn't aware about these defaults. Please look for code in the #1787, you can build something like that.
