### ISSUE TITLE
[FEATURE] Add support for Partitions, CDF & History for `databricks_share`

### ISSUE THREAD

**Issue by nkvuong** [databricks/terraform-provider-databricks#2004]
Delta Sharing has Advanced table options, which needs to be supported via Terraform - `cdf_enabled` and `start_version`

Usage would be

```hcl
resource "databricks_share" "some" {
  name = "my_share"
  dynamic "object" {
    for_each = data.databricks_tables.things.ids
    content {
      name             = object.value
      data_object_type = "TABLE"
      history_data_sharing_status = "ENABLED"
      cdf_enabled = true
    }
  }
}
```

**Comment by marekbrysa** [comment]
https://github.com/databricks/terraform-provider-databricks/pull/2007 was merged too soon, `history_data_sharing_status` support is still missing.

**Comment by nkvuong** [comment]
Also need to add support for partition spec via `partition` blocks
