### ISSUE TITLE
[ISSUE] Issue with `databricks` provider `m2m` authentication

### ISSUE THREAD

**Issue by BostjanBozic** [databricks/terraform-provider-databricks#2042]
### Configuration
```hcl
provider "databricks" {
  alias          = "mws"
  host           = "https://accounts.cloud.databricks.com"
  account_id     = var.databricks_account.account_id
  client_id      = var.databricks_account.client_id
  client_secret  = var.databricks_account.client_secret
  token_endpoint = "https://accounts.cloud.databricks.com/oidc/accounts/${var.databricks_account.account_id}/v1/token"
}
```

### Expected Behavior

That authentication works without any issues.

### Actual Behavior

Authentication fails with following error:
```
╷
│ Error: Unsupported argument
│ 
│   on databricks/provider.tf line 7, in provider "databricks":
│    7:   token_endpoint = "https://accounts.cloud.databricks.com/oidc/accounts/${var.databricks_account.account_id}/v1/token"
│ 
│ An argument named "token_endpoint" is not expected here.
```

### Steps to Reproduce

1. `terraform apply`

### Terraform and provider versions

```
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.10.0
```

### Important Factoids

Yes, the important thing is that we have "Service Principal OAuth token on Databricks account level" private preview enabled and this is the reason why we are using `token_endpoint` parameter in provider configuration. It worked with provider version `v1.9.2`, but it no longer works with `v1.10.0`.

I would expect the problem is migration to Go SDK for configuration and http client (https://github.com/databricks/terraform-provider-databricks/pull/1848). I understand this is in private preview, but I am posting this here so that once it comes out, this will most likely have to be implemented in Go SDK.

**Comment by alexott** [comment]
You don't need this parameter anymore, it's automatically handled by the Go SDK: https://github.com/databricks/databricks-sdk-go/blob/main/config/auth_m2m.go#L45

**Comment by BostjanBozic** [comment]
@alexott  Thank you for pointing this out, sometimes it makes sense just to try it out without :)

I tried it without and in this case though all resources that are using account-level provider are failing:
```
╷
│ Error: cannot read mws vpc endpoint: Cannot complete request; user is unauthenticated
│ 
│   with module.databricks.databricks_mws_vpc_endpoint.api,
│   on databricks/network.tf line 1, in resource "databricks_mws_vpc_endpoint" "api":
│    1: resource "databricks_mws_vpc_endpoint" "api" {
│ 
╵
╷
│ Error: cannot read mws vpc endpoint: Cannot complete request; user is unauthenticated
│ 
│   with module.databricks.databricks_mws_vpc_endpoint.relay,
│   on databricks/network.tf line 9, in resource "databricks_mws_vpc_endpoint" "relay":
│    9: resource "databricks_mws_vpc_endpoint" "relay" {
│ 
╵
```

As mentioned, if I am using provider `v1.9.2`, everything works without any issues. Is there also a difference in parameters when using service principal authentication?

**Comment by alexott** [comment]
I'm not aware about it. @nfx - do you remember what has changed there

**Comment by nfx** [comment]
@BostjanBozic `token_endpoint` can be removed - it's determined automatically since 1.10 and migration to Go SDK. let me know if it doesn't work - arrange a call with me through @alexott .

**Comment by BostjanBozic** [comment]
@nfx Thank you for feedback. I tried to remove it already and then the error that I get is one above (user is unauthenticated).

Perfect, I will send you an email regarding this and we can schedule a short call.

**Comment by BostjanBozic** [comment]
Thank @nfx for call today. This issue was resolved by renaming `DEFAULT` profile in `~/.databrickscfg` to something else. Problem was (to my understanding) that provider was taking credentials from config file event though credentials were configured within provider specification.

**Comment by vmazobhc** [comment]
Just switched Databricks provider 1.9.2 to 1.10 seeing lots of auth errors in Terraform azure databricks 


what is going on with the  " not authorized" what is triggering this in 1.9.2 there is no issue what do I need to adjust 

@nfx 


`
│ Error: cannot read global init script: User not authorized
│ 
│   with module.engineering_workspace.module.metastore_init.databricks_global_init_script.query,
│   on ../../../../../modules/azure/databricks/external-metastore/main.tf line 1, in resource "databricks_global_init_script" "query":
│    1: resource "databricks_global_init_script" "query" {
│ 
╵
╷
│ Error: cannot read global init script: User not authorized
│ 
│   with module.integration_workspace.module.metastore_init.databricks_global_init_script.query,
│   on ../../../../../modules/azure/databricks/external-metastore/main.tf line 1, in resource "databricks_global_init_script" "query":
│    1: resource "databricks_global_init_script" "query" {
│ 
╵
╷
│ Error: User not authorized
│ 
│   with module.engineering_workspace.data.databricks_spark_version.bhg,
│   on ../../../../../modules/azure/databricks/workspace/clusters.tf line 1, in data "databricks_spark_version" "bhg":
│    1: data "databricks_spark_version" "bhg" {
│ 
╵
╷
│ Error: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.data.databricks_spark_version.bhg,
│   on ../../../../../modules/azure/databricks/workspace/clusters.tf line 1, in data "databricks_spark_version" "bhg":
│    1: data "databricks_spark_version" "bhg" {
│ 
╵
╷
│ Error: cannot read instance pool: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_instance_pool.team_clusters["medium"],
│   on ../../../../../modules/azure/databricks/workspace/clusters.tf line 7, in resource "databricks_instance_pool" "team_clusters":
│    7: resource "databricks_instance_pool" "team_clusters" {
│ 
╵
╷
│ Error: cannot read instance pool: User not authorized
│ 
│   with module.integration_workspace.databricks_instance_pool.team_clusters["small"],
│   on ../../../../../modules/azure/databricks/workspace/clusters.tf line 7, in resource "databricks_instance_pool" "team_clusters":
│    7: resource "databricks_instance_pool" "team_clusters" {
│ 
╵
╷
│ Error: cannot read group: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.databricks_group.team_workspace_scim["Great Lakes Databricks-Dev01-Cus-Engineering Infrastructure Workspace Users"],
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 41, in resource "databricks_group" "team_workspace_scim":
│   41: resource "databricks_group" "team_workspace_scim" {
│ 
╵
╷
│ Error: cannot read group: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.databricks_group.team_workspace_scim["Great Lakes Databricks-Dev01-Cus-Engineering Infrastructure2 Workspace Users"],
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 41, in resource "databricks_group" "team_workspace_scim":
│   41: resource "databricks_group" "team_workspace_scim" {
│ 
╵
╷
│ Error: cannot read group: User not authorized
│ 
│   with module.integration_workspace.databricks_group.team_workspace_scim["Great Lakes Databricks-Dev01-Cus-Integration Infrastructure2 Workspace Users"],
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 41, in resource "databricks_group" "team_workspace_scim":
│   41: resource "databricks_group" "team_workspace_scim" {
│ 
╵
╷
│ Error: cannot read group: User not authorized
│ 
│   with module.integration_workspace.databricks_group.team_workspace_scim["Great Lakes Databricks-Dev01-Cus-Integration Infrastructure Workspace Users"],
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 41, in resource "databricks_group" "team_workspace_scim":
│   41: resource "databricks_group" "team_workspace_scim" {
│ 
╵
╷
│ Error: cannot read group: User not authorized
│ 
│   with module.integration_workspace.databricks_group.team_sql_scim["Great Lakes Databricks-Dev01-Cus-Integration Infrastructure SQL Users"],
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 51, in resource "databricks_group" "team_sql_scim":
│   51: resource "databricks_group" "team_sql_scim" {
│ 
╵
╷
│ Error: cannot read group: User not authorized
│ 
│   with module.integration_workspace.databricks_group.dbt_users_scim,
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 61, in resource "databricks_group" "dbt_users_scim":
│   61: resource "databricks_group" "dbt_users_scim" {
│ 
╵
╷
│ Error: cannot read group: User not authorized
│ 
│   with module.engineering_workspace.databricks_group.dbt_users_scim,
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 61, in resource "databricks_group" "dbt_users_scim":
│   61: resource "databricks_group" "dbt_users_scim" {
│ 
╵
╷
│ Error: cannot read group: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.databricks_group.service_accounts,
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 65, in resource "databricks_group" "service_accounts":
│   65: resource "databricks_group" "service_accounts" {
│ 
╵
╷
│ Error: cannot read group: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_group.service_accounts,
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 65, in resource "databricks_group" "service_accounts":
│   65: resource "databricks_group" "service_accounts" {
│ 
╵
╷
│ Error: cannot read group: User not authorized
│ 
│   with module.engineering_workspace.databricks_group.job_viewers,
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 72, in resource "databricks_group" "job_viewers":
│   72: resource "databricks_group" "job_viewers" {
│ 
╵
╷
│ Error: cannot read group: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_group.job_viewers,
│   on ../../../../../modules/azure/databricks/workspace/groups.tf line 72, in resource "databricks_group" "job_viewers":
│   72: resource "databricks_group" "job_viewers" {
│ 
╵
╷
│ Error: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.data.databricks_group.admins,
│   on ../../../../../modules/azure/databricks/workspace/main.tf line 34, in data "databricks_group" "admins":
│   34: data "databricks_group" "admins" {
│ 
╵
╷
│ Error: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.data.databricks_group.admins,
│   on ../../../../../modules/azure/databricks/workspace/main.tf line 34, in data "databricks_group" "admins":
│   34: data "databricks_group" "admins" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-monitoring-10.0.sh"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.1.2_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.2.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners_2.4.5_2.11-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.1.2_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_2.4.5_2.11-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.2.0_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.2.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.0.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.0.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.integration_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.2.0_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.1.2_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-monitoring-10.0.sh"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_2.4.5_2.11-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.1.2_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners_2.4.5_2.11-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.2.0_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.0.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.2.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.2.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners-loganalytics_3.2.0_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read dbfs file: User not authorized
│ 
│   with module.engineering_workspace.databricks_dbfs_file.monitoring["spark-listeners_3.0.1_2.12-1.0.0.jar"],
│   on ../../../../../modules/azure/databricks/workspace/monitoring.tf line 1, in resource "databricks_dbfs_file" "monitoring":
│    1: resource "databricks_dbfs_file" "monitoring" {
│ 
╵
╷
│ Error: cannot read notebook: User not authorized
│ 
│   with module.engineering_workspace.databricks_notebook.setup_hive_jars[0],
│   on ../../../../../modules/azure/databricks/workspace/notebooks.tf line 1, in resource "databricks_notebook" "setup_hive_jars":
│    1: resource "databricks_notebook" "setup_hive_jars" {
│ 
╵
╷
│ Error: cannot read notebook: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_notebook.setup_hive_jars[0],
│   on ../../../../../modules/azure/databricks/workspace/notebooks.tf line 1, in resource "databricks_notebook" "setup_hive_jars":
│    1: resource "databricks_notebook" "setup_hive_jars" {
│ 
╵
╷
│ Error: cannot read git credential: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_git_credential.this,
│   on ../../../../../modules/azure/databricks/workspace/repos.tf line 1, in resource "databricks_git_credential" "this":
│    1: resource "databricks_git_credential" "this" {
│ 
╵
╷
│ Error: cannot read git credential: User not authorized
│ 
│   with module.engineering_workspace.databricks_git_credential.this,
│   on ../../../../../modules/azure/databricks/workspace/repos.tf line 1, in resource "databricks_git_credential" "this":
│    1: resource "databricks_git_credential" "this" {
│ 
╵
╷
│ Error: cannot read token: User not authorized
│ 
│   with module.engineering_workspace.databricks_token.scim,
│   on ../../../../../modules/azure/databricks/workspace/scim.tf line 22, in resource "databricks_token" "scim":
│   22: resource "databricks_token" "scim" {
│ 
╵
╷
│ Error: cannot read token: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_token.scim,
│   on ../../../../../modules/azure/databricks/workspace/scim.tf line 22, in resource "databricks_token" "scim":
│   22: resource "databricks_token" "scim" {
│ 
╵
╷
│ Error: cannot read secret scope: User not authorized
│ 
│   with module.integration_workspace.databricks_secret_scope.this,
│   on ../../../../../modules/azure/databricks/workspace/secret_scope.tf line 1, in resource "databricks_secret_scope" "this":
│    1: resource "databricks_secret_scope" "this" {
│ 
╵
╷
│ Error: cannot read secret scope: User not authorized
│ 
│   with module.engineering_workspace.databricks_secret_scope.this,
│   on ../../../../../modules/azure/databricks/workspace/secret_scope.tf line 1, in resource "databricks_secret_scope" "this":
│    1: resource "databricks_secret_scope" "this" {
│ 
╵
╷
│ Error: cannot read secret scope: User not authorized
│ 
│   with module.integration_workspace.databricks_secret_scope.others["HiveSyncScope"],
│   on ../../../../../modules/azure/databricks/workspace/secret_scope.tf line 29, in resource "databricks_secret_scope" "others":
│   29: resource "databricks_secret_scope" "others" {
│ 
╵
╷
│ Error: cannot read secret scope: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_secret_scope.monitoring,
│   on ../../../../../modules/azure/databricks/workspace/secret_scope.tf line 43, in resource "databricks_secret_scope" "monitoring":
│   43: resource "databricks_secret_scope" "monitoring" {
│ 
╵
╷
│ Error: cannot read secret scope: User not authorized
│ 
│   with module.engineering_workspace.databricks_secret_scope.monitoring,
│   on ../../../../../modules/azure/databricks/workspace/secret_scope.tf line 43, in resource "databricks_secret_scope" "monitoring":
│   43: resource "databricks_secret_scope" "monitoring" {
│ 
╵
╷
│ Error: cannot read service principal: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.databricks_service_principal.this["devops"],
│   on ../../../../../modules/azure/databricks/workspace/service_principal.tf line 24, in resource "databricks_service_principal" "this":
│   24: resource "databricks_service_principal" "this" {
│ 
╵
╷
│ Error: cannot read service principal: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.engineering_workspace.databricks_service_principal.this["orchestration"],
│   on ../../../../../modules/azure/databricks/workspace/service_principal.tf line 24, in resource "databricks_service_principal" "this":
│   24: resource "databricks_service_principal" "this" {
│ 
╵
╷
│ Error: cannot read service principal: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_service_principal.this["devops"],
│   on ../../../../../modules/azure/databricks/workspace/service_principal.tf line 24, in resource "databricks_service_principal" "this":
│   24: resource "databricks_service_principal" "this" {
│ 
╵
╷
│ Error: cannot read service principal: inner token: token error: {"error":"invalid_request","error_description":"Temporarily throttled, too many requests"}
│ 
│   with module.integration_workspace.databricks_service_principal.this["dpbhcdbt"],
│   on ../../../../../modules/azure/databricks/workspace/service_principal.tf line 24, in resource "databricks_service_principal" "this":
│   24: resource "databricks_service_principal" "this" {
│ 
╵
╷
│ Error: cannot read service principal: User not authorized
│ 
│   with module.integration_workspace.databricks_service_principal.this["orchestration"],
│   on ../../../../../modules/azure/databricks/workspace/service_principal.tf line 24, in resource "databricks_service_principal" "this":
│   24: resource "databricks_service_principal" "this" {
│ 
╵
╷
│ Error: cannot read sql endpoint: User not authorized
│ 
│   with module.integration_workspace.databricks_sql_endpoint.teams["Data Platform Endpoint"],
│   on ../../../../../modules/azure/databricks/workspace/sql-endpoints.tf line 1, in resource "databricks_sql_endpoint" "teams":
│    1: resource "databricks_sql_endpoint" "teams" {
│ 
╵
╷
│ Error: cannot read sql endpoint: User not authorized
│ 
│   with module.engineering_workspace.databricks_sql_endpoint.teams["Data Platform Endpoint"],
│   on ../../../../../modules/azure/databricks/workspace/sql-endpoints.tf line 1, in resource "databricks_sql_endpoint" "teams":
│    1: resource "databricks_sql_endpoint" "teams" {
│ `

**Comment by nfx** [comment]
I see “temporarily throttled” error message in the stack trace. Please open new issue with the details on how authentication is configured
