### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore_assignment` resource

### ISSUE THREAD

**Issue by francisco-ltech** [databricks/terraform-provider-databricks#2061]
### Configuration
```hcl
resource "databricks_metastore_assignment" "assignment" {
  metastore_id         = var.metastore-id
  workspace_id         = azurerm_databricks_workspace.build.workspace_id
  default_catalog_name = "default"
}
```

### Expected Behavior
Databricks workspace to be assigned to the given (existing) metastore

### Actual Behavior
Error: cannot read metastore assignment: No metastore assigned for the current workspace.

### Steps to Reproduce
Metastore already exists, new Databricks workspace is created, then assigned.

1. terraform plan 
2. terraform apply

### Terraform and provider versions
azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.45.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "1.11.1"
    }

### Debug Output
[DEBUG] provider.terraform-provider-databricks_v1.11.1: PUT /api/2.1/unity-catalog/workspaces/{id}/metastore
> {
>   "default_catalog_name": "default",
>   "metastore_id": "uuid-value",
>   "workspace_id": int-value
> }
< HTTP/2.0 200 OK
< {}: timestamp=2023-03-02T14:21:19.338Z
[DEBUG] provider.terraform-provider-databricks_v1.11.1: GET /api/2.1/unity-catalog/metastore_summary
< HTTP/2.0 404 Not Found
< {
<   "details": [
<     {
<       "@type": "type.googleapis.com/google.rpc.RequestInfo",
<       "request_id": "17e-8bf-4da-b23-b12",
<       "serving_data": ""
<     }
<   ],
<   "error_code": "METASTORE_DOES_NOT_EXIST",
<   "message": "No metastore assigned for the current workspace."

### Important Factoids
- The actual PUT request to the assignment reads a OK which indicates success, which indeed succeeds because I can see the metastore assigned to the workspace in the accounts.databricks portal.
- However, there seems to be a subsequent GET request that fails and I believe this makes TF not to update the state?
- If I terraform plan again, the plan indicates the assignment is yet to be created (again).

**Comment by nkvuong** [comment]
fixed in #2182
