### ISSUE TITLE
[DOC] SQL endpoint doc could link relevant SQL global config doc

### ISSUE THREAD

**Issue by kadu-vido** [databricks/terraform-provider-databricks#2064]
### Affected Resource(s)
In the Terraform docs for the [SQL endpoint resource](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_endpoint), the [`enable_serverless_compute`](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_endpoint#enable_serverless_compute) parameter says:
> To use a Serverless SQL endpoint, you must enable Serverless SQL endpoints for the workspace.

This wording led me to search for this config in the workspace level, conclude it's still not available via terraform, and set it manually -- only to later find out that it's in the [SQL global config resource](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_global_config#enable_serverless_compute).

### Expected Details
More clarity on how to enable serverless compute.

### List of things to potentially add/remove:
Given that both attributes have the exact same name and are related, the docs could explicitly link each other and clarify that both must be set to `true` in order to be able to use serverless compute.

**Comment by nkvuong** [comment]
fixed in #2137
