### ISSUE TITLE
[ISSUE] Issue with `databricks_secret_scope` resource

### ISSUE THREAD

**Issue by camilo-s** [databricks/terraform-provider-databricks#2082]
### Configuration
```hcl
terraform {
  backend "azurerm" {
    use_azuread_auth = true
  }
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.11.0"
    }
  }
}

provider "databricks" {
  host                        = module.databricks_workspace.databricks_workspace_url
  azure_workspace_resource_id = module.databricks_workspace.azure_workspace_resource_id
  azure_use_msi               = true
}

resource "databricks_secret_scope" "this" {
  name = "VERYSECRETSCOPE"
}
```

### Expected Behavior
The secret scope gets created

### Actual Behavior
Terraform encounters the following error during apply:
```
cannot create secret scope: inner token: token error: {"error":"invalid_request","error_description":"Identity not found"}
```
### Debug Output

[gist with debug logs](https://gist.github.com/camilo-s/30dac001d5a7774924135d436153ca2e)

### Important Factoids
Dialing down the Databricks provider version to v1.9.0 allows secret scope creation.

**Comment by alexott** [comment]
Please attach a debug log as it's described in the troubleshooting guide.

**Comment by nfx** [comment]
is it the same as https://github.com/databricks/terraform-provider-databricks/issues/2057 ?

**Comment by camilo-s** [comment]
@alexott I've attached debug logs in a [gist](https://gist.github.com/camilo-s/30dac001d5a7774924135d436153ca2e). I've also corrected the Databricks provider version constraint. When using `version = "~> 1.9.0"` the secret scope creation works.

**Comment by camilo-s** [comment]
Are there any updates on this? I'm stuck at provider version 1.9 because of this.

**Comment by camilo-s** [comment]
I've managed to overcome this problem by dropping `azure_use_msi = true` and instead setting `auth_type  = "azure-client-secret"` at the provider configuration.

It turns out `"azure-client-secret"` was the actual auth type I needed to target, but somehow prior to v1.10 the provider was managing to leverage existing tokens and environment variables to use Azure MSI authentication (even though the VM doing the deployment didn't have a Managed Identity with proper role assignments)
