### ISSUE TITLE
databricks secrets backed by azure Key vault 

### ISSUE THREAD

**Issue by nourriba** [databricks/terraform-provider-databricks#2105]
### Configuration
```hcl

    resource "databricks_secret" "secret" {
      config_reference       = (known after apply)
      id                     = (known after apply)
      key                    = "xxxxxx"
      last_updated_timestamp = (known after apply)
      scope                  = "xxxxxx"
      string_value           = (sensitive value)
    }

    resource "databricks_secret_acl" "secret_acl" {
       id         = (known after apply)
      permission = "MANAGE"
      principal  = "xxxxxxx"
      scope      = "xxxxxx"
    }
  resource "databricks_secret_scope" "secret_scope" {
       backend_type             = "AZURE_KEYVAULT"
       id                       = (known after apply)
       initial_manage_principal = "users"
       name                     = "testakvwithpep"

       keyvault_metadata {
          + dns_name    = "https://xxxxxxxx.vault.azure.net/"
          + resource_id = "/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.KeyVault/vaults/xxxxxx"
        }
    }
```

### Terraform and provider versions
1.3.8

### Debug Output
     resource "databricks_secret_scope" "secret_scope" {
       backend_type             = "AZURE_KEYVAULT"
       id                       = (known after apply)
       initial_manage_principal = "users"
       name                     = "testakvwithpep"

       keyvault_metadata {
          + dns_name    = "https://xxxxxxxx.vault.azure.net/"
          + resource_id = "/subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.KeyVault/vaults/xxxxxx"
        }
    }

Plan: 5 to add, 0 to change, 0 to destroy.
 databricks_secret_scope.secret_scope : Creating...
╷
│ Error: cannot create secret scope: Unable to grant read/list permission to Databricks service principal to KeyVault 'https://xxxxxxxvault.azure.net/': key not found: https://graph.windows.net/
│
│   with  databricks_secret_scope.secret_scope ,
│   on ../../databricks_main.tf line 349, in resource "databricks_secret_scope" "secret_scope":
│  349: resource "databricks_secret_scope" "secret_scope" {
│

### Important Factoids
no

**Comment by alexott** [comment]
it's described in the documentation: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/secret_scope#keyvault_metadata

**Comment by alexjbush** [comment]
Are you sure? It looks like this PR enabled the functionality: https://github.com/databricks/terraform-provider-databricks/pull/1965

Specifically the comment:
>This PR removes the check that was forbidding to call this from a Service Principal since it was not working. Now that MSFT fixed it we can remove the check and allow customers use it.

However, I also get the above error.

**Comment by alexott** [comment]
I'm 100% sure :-) This PR just removed the check from TF to unblock usage when this functionality will be available in the future. If it would be fully available for everyone we would update the documentation as well.

Just wait a bit more...

**Comment by alexjbush** [comment]
Thank you for the information and getting back to me! That sounds promising.
