### ISSUE TITLE
[FEATURE] Reduce API calls associated with `databricks_permissions` to avoid rate limiting

### ISSUE THREAD

**Issue by pahwaranger** [databricks/terraform-provider-databricks#2120]
### Use-cases
Databricks APIs often have rate limits so we would like to reduce calls to the API whenever possible.

### Attempted Solutions

N/A

### Proposal

In speaking with @nfx , we found that there are repeated calls to get the current user's access permissions before applying access permission changes. Code can be found here: https://github.com/databricks/terraform-provider-databricks/blob/master/permissions/resource_permissions.go#L411-L414

@nfx suggested that we could move this logic into the DatabricksProvider logic and cache the results. This would remove at least 1 API call for each access permission definition.

### References

N/A

**Comment by alexott** [comment]
Please ping me - I have a proposal for caching because it's also a problem for exporter functionality

**Comment by thaiphv** [comment]
I'm all for this because https://github.com/databricks/terraform-provider-databricks/issues/2052 still happened to me using the latest release.

**Comment by nfx** [comment]
@thaiphv, the issue is a bit different in this case, it's not related to #2052

**Comment by thaiphv** [comment]
> @thaiphv, the issue is a bit different in this case, it's not related to #2052

Agreed. But the symptom that I reported in [#2052](https://github.com/databricks/terraform-provider-databricks/issues/2052) is the same. I had to reduce the number of API calls down to 5 RPS otherwise I kept getting the error. But this slowed down the overall execution.

**Comment by pahwaranger** [comment]
I think this is addressed via https://github.com/databricks/terraform-provider-databricks/pull/2170?
