### ISSUE TITLE
[ISSUE] Issue with `databricks_repo` resource

### ISSUE THREAD

**Issue by Vykistwo** [databricks/terraform-provider-databricks#2122]
### Configuration
```hcl
resource "azurerm_databricks_workspace" "this" {
  name                = "databricks-test"
  resource_group_name = azurerm_resource_group.example.name
  location            = var.LOCATION
  sku                 = "premium"
}

data "databricks_current_user" "me" {
    depends_on = [
    azurerm_databricks_workspace.this
  ]
}

resource "databricks_repo" "this" {
  url = "https://dev.azure.com/*/_git/TF-Main"
  branch = "main"
  path = "${data.databricks_current_user.me.repos}/some_name"
  depends_on = [
     databricks_git_credential.ado
  ]
}

resource "databricks_git_credential" "ado" {
  git_username          = "*"
  git_provider          = "azureDevOpsServices"
  personal_access_token = "*"
  force = true
}

```

### Expected Behavior
Successful completion

### Actual Behavior
Terraform fails with error message "Error: cannot create repo: Failed to clone repo. Repo may be incomplete. Failure reason: com.microsoft.azure.storage.StorageException: The specified resource does not exist.", however the repo itself is created and can be visible in Databricks portal. Rerunning the pipeline results in error message "Error: cannot create repo: Repo /Repos/***/some_name already exists. If you would like to create two repos from the same remote Git repo, rename the first repo before creating the second repo." Deleting the repo from the portal manually and kicking of the pipeline one more time appears to do the trick.

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
    databricks = {
      source = "databricks/databricks"
      version = "1.13.0"
    }
Terraform v1.4.1

**Comment by iandexter** [comment]
Hi, @Vykistwo 

> `com.microsoft.azure.storage.StorageException: The specified resource does not exist`

suggests that something in the Azure storage backend may have gone wrong. I would suggest contacting Azure support. 

If you examine the contents of `/Repos/***/some_name` after the first occurrence of the error, do some files exist?

**Comment by Vykistwo** [comment]
> Hi, @Vykistwo
> 
> > `com.microsoft.azure.storage.StorageException: The specified resource does not exist`
> 
> suggests that something in the Azure storage backend may have gone wrong. I would suggest contacting Azure support.
> 
> If you examine the contents of `/Repos/***/some_name` after the first occurrence of the error, do some files exist?

Yeah the repo with all its content is there in the Databricks portal and can be used.

**Comment by iandexter** [comment]
Thanks, @Vykistwo. Feel free to ping us here for any other provider-related issues.
