### ISSUE TITLE
[ISSUE] Cannot read entitlements: `SCIM API Internal Error` with `Databricks_entitlements`

### ISSUE THREAD

**Issue by panselaukik** [databricks/terraform-provider-databricks#2129]
Description:
When attempting to read entitlements with Databricks_entitlements, an error is thrown: "cannot read entitlements: SCIM API Internal Error." This error message prevents the entitlements from being read and used, which is causing issues for our team.

Steps to Reproduce:

Use Databricks_entitlements to attempt to read entitlements.
Observe the error message `"cannot read entitlements: SCIM API Internal Error."`

```hcl
    databricks = {
      source  = "databricks/databricks"
      version = ">=1.4.0"
    }
```

### Expected Behavior
The entitlements should be able to be read without any errors.

### Actual Behavior
The error message "cannot read entitlements: SCIM API Internal Error" is preventing the entitlements from being read.

### Steps to Reproduce
 Succeeds after multiple re-runs
2. `terraform apply`--> Succeeds after multiple re-runs

### Terraform and provider versions
terraform {
  required_version = ">=v0.14.7"
}

**Comment by TakeshiMatsukura** [comment]
Can you share the actual code and debug log?
`TF_LOG=DEBUG DATABRICKS_DEBUG_TRUNCATE_BYTES=250000 terraform apply -no-color 2>&1 |tee tf-debug.log`

**Comment by nkvuong** [comment]
this indicates the SCIM APIs were having issues, and should affect not just Terraform. We have an internal ticket tracking this
