### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource

### ISSUE THREAD

**Issue by DRV2SI** [databricks/terraform-provider-databricks#2130]
### Configuration
```hcl
resource "databricks_job" "some_name" {
  name       = "SomeName"
  always_running = var.continuously_up

  continuous{
    pause_status           = var.continuously_up ? "UNPAUSED" : "PAUSED"
  }

  task {
    task_key            = "service"
    existing_cluster_id = databricks_cluster.cluster.id

    notebook_task {
      notebook_path = "some_path"
      source        = "GIT"
    }
  }
}
```

### Expected Behavior
It is possible to manage Databricks Jobs completely via IaC. In particular, it is possible to _stop_ already running jobs. 

### Actual Behavior
It is possible to change recovery (`always_running`) as well as trigger (`continuous` block) behaviour. However, this seems to not affect any already running jobs. 

### Steps to Reproduce
1. apply terraform configuration with `continuously_up=true`. The Databricks job is going to be triggered and run as expected
1. apply terraform configuration with `continuously_up=false`. The Databricks job is disabled, the trigger indicating that it is paused. However, any existing job run continues to run. In particular, this is a Spark Streaming application which runs 24/7 if not disabled. The problem obviously does not occur for one-off jobs. 

### Terraform and provider versions
```
databricks = {
      source  = "databricks/databricks"
      version = "1.13.0"
    }
```

### Debug Output
(gladly upon request, but this potentially contains confidential information, so I'd need to share this privately)

Thank you in advance!

**Comment by TakeshiMatsukura** [comment]
Do you want to stop active runs when always_running is set to false?

https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#always_running
`(Optional) (Bool) Whenever the job is always running, like a Spark Streaming application, on every update restart the current active run or start it again, if nothing it is not running. False by default. Any job runs are started with parameters specified in spark_jar_task or spark_submit_task or spark_python_task or notebook_task blocks.`

Currently it has only functions to start/restart the job run when it set to true.
https://github.com/databricks/terraform-provider-databricks/blob/9e2c64187c60e89a187c1f425d0d4a9a7d4f9199/jobs/resource_job.go#L418

**Comment by DRV2SI** [comment]
@TakeshiMatsukura Yes, `always_running=false` for my case. Specifically, imagine the situation that you want to disable a streaming application that would otherwise run continuously. You would be switching from 
```
always_running = true
 continuous{
    pause_status           =  "UNPAUSED"
  }
```

to 

```
always_running = false
 continuous{
    pause_status           =  "PAUSED"
  }
```

Judging from your answer, this is currently not supported, as it would require the databricks provider to actually go ahead and _stop_ an already running job. Am I correct in this assumption?

**Comment by alexott** [comment]
Really, `always_running` was needed only before `continuous` became available. We'll need to remove `always_running` in the future
