### ISSUE TITLE
[ISSUE] Issue with `databricks_node_type` resource

### ISSUE THREAD

**Issue by akash329d** [databricks/terraform-provider-databricks#2150]
### Configuration
```hcl
data "databricks_node_type" "shared_node_type" {
  local_disk            = true
  min_cores             = 4
  min_memory_gb         = 25
  photon_driver_capable = true
  photon_worker_capable = true
}
```

### Expected Behavior
Would expect this to select `Standard_E4ds_v4` as that is the cheapest node type that fufills these requirements. 

### Actual Behavior
Provider selects `Standard_DS12_v2`. I think this is due to it having less memory than `Standard_E4ds_v4`, however it is still more expensive so would be preferred for the provider to return `Standard_E4ds_v4`

### Terraform and provider versions
1.13.0 provider version, latest TF

**Comment by alexott** [comment]
Ok. It's a bug. DS12 shouldn't be selected because it has:

```
      "photon_worker_capable": false,
      "photon_driver_capable": false,
```

But otherwise, the selection algorithm is correct - we don't have any costs information in the node-type REST API, so we can use only technical information for that.

**Comment by alexott** [comment]
@akash329d can you check the latest version of TF provider?

**Comment by alexott** [comment]
Closing as there is no answer from reporter
