### ISSUE TITLE
[FEATURE] Be able to easily render workflow through JSON

### ISSUE THREAD

**Issue by LvffY** [databricks/terraform-provider-databricks#2153]
### Use-cases

Our purpose is to avoid having to develop twice our workflows (once in the UI and once in terraform), it would be great to have a method to tranform the JSON extracted from the UI into HCL.

### Proposal

Maybe just a documented method to pass from the JSON extracted from the UI to the HCL statement could be enough.

**Comment by alexott** [comment]
You can use [exporter functionality](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/experimental-exporter) to generate HCL for existing objects. To extract a single job, use `-match` option

**Comment by LvffY** [comment]
Thanks @alexott it seems to be exactly the tool I wanted ! 

Sorry that I missed the docs ^^'
