### ISSUE TITLE
[FEATURE] workspace_conf allow to enable table access control `enableTableAclsConfig`

### ISSUE THREAD

**Issue by aar6ncai** [databricks/terraform-provider-databricks#2163]
Hi There,

Can you add the feature to enable table-level access control via the workspace terraform resource in the custom config?

e.g. 
```
resource "databricks_workspace_conf" "this" {
  custom_config = {
    "enableTableAclsConfig" : true
  }
}
```

### Use-cases
As part of workspace bootstrap, it would be great if the workspace admin settings config is available to config via terraform databricks provider.

### References
https://github.com/databricks/terraform-provider-databricks/blob/f29e655c5e71d00f09044dce323e16b6ab463b7b/docs/resources/workspace_conf.md

**Comment by alexott** [comment]
It's not possible right now as there is no public API for that. Please raise this issue with your Databricks representative.

P.S. It's well know issue - it will be fixed ASAP, when API will be implemented

**Comment by w0ut0** [comment]
Hi @alexott,
does [this](https://docs.databricks.com/api/workspace/workspaceconf/setstatus) API now support arbitrary config properties? 
Can they be implemented in the TF provider? This would replace the only manual step in the workspace provisioning.

**Comment by alexott** [comment]
TACL switch doesn't use that API
