### ISSUE TITLE
[FEATURE] SQL dashboard filters

### ISSUE THREAD

**Issue by TaylorZowtuk** [databricks/terraform-provider-databricks#2172]
Hopefully, I am not just overlooking how to do this - I didn't see anything in the provider docs. I also recognize that the contributors are probably aware of this feature not existing but I didn't see any issues formally requesting this and was also wondering how far off this addition might be.

### Use-cases
- When we edit a dashboard through the Databricks UI, it is possible to create a new dashboard widget that filters one or more queries
- We want to manage our dashboards through terraform in order to version them
- If we want to fully manage our dashboards through terraform, then this is a missing feature which means that a terraform managed dashboard has less functionality than a manually created one

### Attempted Solutions

Not necessarily a solution but here is what I have done up to the point where I am blocked:
- I previously created a dashboard by writing queries and creating the dashboard, widgets, and visualizations all through the Databricks UI
- On my dashboard, I added some filters
<img width="421" alt="image" src="https://user-images.githubusercontent.com/43101199/228927888-6132eb22-0d86-4138-b194-0f040caee06d.png">

Then we wanted to keep our dashboard under version control:
- I used the terraform exporter tool to produce the terraform of my dashboard for me
- Everything except the dashboard filters is exported correctly and is useable and the dashboard filters are `databricks_sql_widget` resources without any connections/functionality
```
  resource "databricks_sql_widget" "abc" {
    title = "site"
    position {
      size_y = 3
      size_x = 3
      pos_y  = 64
    }
    dashboard_id = databricks_sql_dashboard.xyz.id
  }
```
<img width="597" alt="image" src="https://user-images.githubusercontent.com/43101199/228930079-1e317ba4-51a8-491d-9c76-cd1ab8282265.png">

### Proposal
I'm really not familiar enough with Terraform to propose anything. Sorry about that.

### References
N/A

**Comment by TaylorZowtuk** [comment]
> I tested it yesterday with the latest version yesterday, and filters were exported correctly

Oh, so filters are already addable using Terraform? So is this maybe just an issue with the exporter then?

I tried using the latest provider binary (v1.14.1; in my initial post, I was using v1.13.0 for reference) but it didn't seem to make a difference. The output was the exact same as what I posted in my initial message. Here is the command I am using: `../terraform-provider-databricks_v1.14.1 exporter -match="Recommenders" -listing=sql-dashboards -services=sql-dashboards -skip-interactive`

Would you be able to share with me an example of what a correctly exported filter should look like?

**Comment by alexott** [comment]
For me the dashboard widget was exported with the `dropdown` type, and then was used like this:

```hcl
resource "databricks_sql_visualization" "country_code_a01ebdc1_25a5_40c5_847e_4c23dcb8b90504be60a7_4756_4c54_aca9_0e3e761c2e4b" {
  type       = "dropdown"
  query_plan = "{\"selects\": [{\"kind\": \"identifier\", \"identifier\": \"country_code\"}], \"groups\": [{\"kind\": \"identifier\", \"identifier\": \"country_code\"}]}"
  query_id   = databricks_sql_query.country_filter_a01ebdc1_25a5_40c5_847e_4c23dcb8b905.id
  options    = "{\"column\": \"country_code\", \"type\": \"single-select\", \"associativeFilter\": true, \"sortOrder\": \"asc\", \"timeInterval\": \"daily\", \"mode\": \"diagonal\", \"showTooltips\": true, \"percentValues\": true, \"timeColumnTitle\": \"Time\", \"peopleColumnTitle\": \"Users\", \"stageColumnTitle\": \"{{ @ }}\", \"numberFormat\": \"0,0[.]00\", \"percentFormat\": \"0.00%\", \"noValuePlaceholder\": \"-\", \"colors\": {\"min\": \"#C4CCD6\", \"max\": \"#077A9D\", \"steps\": 7}}"
  name       = "country_code"
}
```

giving the correct results

![Screenshot 2023-04-06 at 11 12 12](https://user-images.githubusercontent.com/30342/230393471-bcd05ec8-1548-44a0-aaf3-e0dd0e52eab4.png)

![Screenshot 2023-04-06 at 11 08 59](https://user-images.githubusercontent.com/30342/230393480-f70e77cb-d53a-424e-b83c-885157446a5b.png)

**Comment by alexott** [comment]
if you can provide log, or at least more information on what kind of filters, etc., then it would be easier to debug the problem

**Comment by TaylorZowtuk** [comment]
Thanks for the code example!

When I add `-debug` flag to the exporter it gives way too much output (including information I don't think I can share) with my current example. I will try to create a smaller reproducible example.

In the meantime, the filters not exporting correctly are created via Edit > Add > Filter > 'New dashboard filter':
<img width="375" alt="edit_filter" src="https://user-images.githubusercontent.com/43101199/230484053-4dd6ddfe-06c6-434f-b67d-80ee626af444.png">

For testing purposes (I don't currently have any filters added to the dashboard created this way),  I added a filter via Edit > Add > Filter > 'Existing query filter' and then ran the exporter and it does appear to output the same as your example:
```
		resource "databricks_sql_visualization" "rule_xyz" {
		  type       = "dropdown"
		  query_plan = "{\"selects\": [{\"kind\": \"identifier\", \"identifier\": \"rule\"}], \"groups\": [{\"kind\": \"identifier\", \"identifier\": \"rule\"}]}"
		  query_id   = "abc"
		  options    = "{\"column\": \"rule\", \"type\": \"single-select\", \"associativeFilter\": true, \"sortOrder\": \"asc\"}"
		  name       = "rule"
}
```

So maybe the problem is with exporting dashboard-level filters?

**Comment by TaylorZowtuk** [comment]
Here is a smaller example. 

These are the steps I took:
1. Created a dashboard
2. Created a query
   - ```
       SELECT id, site_id, state
       FROM campaigns_silver_table
      ```
4. Created a visualization (table)
5. Added visualization to the dashboard
6. Added a dashboard-level filter to the dashboard; (id)
   - <img width="1222" alt="add_filter" src="https://user-images.githubusercontent.com/43101199/230488430-5c35f073-2c30-4298-80e1-967ea0edaa57.png">
7. Created a query-level filter (state)
    - <img width="624" alt="image" src="https://user-images.githubusercontent.com/43101199/230488805-413b91bd-3285-4d15-9c90-011d0954a12d.png">
9. Added the query-level filter to the dashboard
   - <img width="1219" alt="image" src="https://user-images.githubusercontent.com/43101199/230488993-42c6d1ff-8725-4005-bf3a-9162c2677871.png">

When running the exporter, `../terraform-provider-databricks_v1.14.1 exporter -match="DE-799" -listing=sql-dashboards -services=sql-dashboards -skip-interactive -debug 2>&1 | tee log.txt` outputs:
```
resource "databricks_sql_dashboard" "de_799_dashboard_e5edec40_0ca9_4a7c_b4a3_fa66fce75606" {
  parent = "folders/3434156589666450"
  name   = "DE-799-dashboard"
}
resource "databricks_sql_visualization" "de_799_table_f799f944_6d39_4807_a61e_02ee7a63b272e41e81cb_2e4d_4ba8_99ba_748b9e0d9a52" {
  type     = "table"
  query_id = "f799f944-6d39-4807-a61e-02ee7a63b272"
  options  = "{\"itemsPerPage\": 25, \"condensed\": true, \"withRowNumber\": false, \"columns\": [{\"numberFormat\": \"0\", \"booleanValues\": [\"false\", \"true\"], \"imageUrlTemplate\": \"{{ @ }}\", \"imageTitleTemplate\": \"{{ @ }}\", \"imageWidth\": \"\", \"imageHeight\": \"\", \"linkUrlTemplate\": \"{{ @ }}\", \"linkTextTemplate\": \"{{ @ }}\", \"linkTitleTemplate\": \"{{ @ }}\", \"linkOpenInNewTab\": true, \"name\": \"id\", \"type\": \"integer\", \"displayAs\": \"number\", \"visible\": true, \"order\": 100000, \"title\": \"id\", \"allowSearch\": false, \"alignContent\": \"right\", \"allowHTML\": false, \"highlightLinks\": false, \"useMonospaceFont\": false, \"preserveWhitespace\": false}, {\"booleanValues\": [\"false\", \"true\"], \"imageUrlTemplate\": \"{{ @ }}\", \"imageTitleTemplate\": \"{{ @ }}\", \"imageWidth\": \"\", \"imageHeight\": \"\", \"linkUrlTemplate\": \"{{ @ }}\", \"linkTextTemplate\": \"{{ @ }}\", \"linkTitleTemplate\": \"{{ @ }}\", \"linkOpenInNewTab\": true, \"name\": \"site_id\", \"type\": \"string\", \"displayAs\": \"string\", \"visible\": true, \"order\": 100001, \"title\": \"site_id\", \"allowSearch\": false, \"alignContent\": \"left\", \"allowHTML\": false, \"highlightLinks\": false, \"useMonospaceFont\": false, \"preserveWhitespace\": false}, {\"booleanValues\": [\"false\", \"true\"], \"imageUrlTemplate\": \"{{ @ }}\", \"imageTitleTemplate\": \"{{ @ }}\", \"imageWidth\": \"\", \"imageHeight\": \"\", \"linkUrlTemplate\": \"{{ @ }}\", \"linkTextTemplate\": \"{{ @ }}\", \"linkTitleTemplate\": \"{{ @ }}\", \"linkOpenInNewTab\": true, \"name\": \"state\", \"type\": \"string\", \"displayAs\": \"string\", \"visible\": true, \"order\": 100002, \"title\": \"state\", \"allowSearch\": false, \"alignContent\": \"left\", \"allowHTML\": false, \"highlightLinks\": false, \"useMonospaceFont\": false, \"preserveWhitespace\": false}], \"version\": 2}"
  name     = "DE-799-table"
}
resource "databricks_sql_widget" "e5edec40_0ca9_4a7c_b4a3_fa66fce7560626c2e597_169a_4f07_af52_febf35e1ebe1" {
  visualization_id = databricks_sql_visualization.state_f799f944_6d39_4807_a61e_02ee7a63b27212234d56_ea6d_4b12_bb80_d645d93b2228.visualization_id
  position {
    size_y = 8
    size_x = 3
    pos_y  = 12
  }
  dashboard_id = databricks_sql_dashboard.de_799_dashboard_e5edec40_0ca9_4a7c_b4a3_fa66fce75606.id
}
resource "databricks_sql_widget" "e5edec40_0ca9_4a7c_b4a3_fa66fce7560634050229_4cf6_4bba_83fd_008b1db46178" {
  title = "id"
  position {
    size_y = 3
    size_x = 3
    pos_y  = 12
  }
  dashboard_id = databricks_sql_dashboard.de_799_dashboard_e5edec40_0ca9_4a7c_b4a3_fa66fce75606.id
}
resource "databricks_sql_widget" "e5edec40_0ca9_4a7c_b4a3_fa66fce75606745ce4a2_45b9_4280_b1c0_ac5b8ff81cae" {
  visualization_id = databricks_sql_visualization.de_799_table_f799f944_6d39_4807_a61e_02ee7a63b272e41e81cb_2e4d_4ba8_99ba_748b9e0d9a52.visualization_id
  title            = "DE-799-table"
  position {
    size_y = 12
    size_x = 6
  }
  description  = "test"
  dashboard_id = databricks_sql_dashboard.de_799_dashboard_e5edec40_0ca9_4a7c_b4a3_fa66fce75606.id
}
resource "databricks_sql_visualization" "state_f799f944_6d39_4807_a61e_02ee7a63b27212234d56_ea6d_4b12_bb80_d645d93b2228" {
  type       = "dropdown"
  query_plan = "{\"selects\": [{\"kind\": \"identifier\", \"identifier\": \"state\"}], \"groups\": [{\"kind\": \"identifier\", \"identifier\": \"state\"}]}"
  query_id   = "f799f944-6d39-4807-a61e-02ee7a63b272"
  options    = "{\"column\": \"state\", \"type\": \"single-select\", \"associativeFilter\": true, \"sortOrder\": \"asc\", \"timeInterval\": \"daily\", \"mode\": \"diagonal\", \"showTooltips\": true, \"percentValues\": true, \"timeColumnTitle\": \"Time\", \"peopleColumnTitle\": \"Users\", \"stageColumnTitle\": \"{{ @ }}\", \"numberFormat\": \"0,0[.]00\", \"percentFormat\": \"0.00%\", \"noValuePlaceholder\": \"-\", \"colors\": {\"min\": \"#C4CCD6\", \"max\": \"#077A9D\", \"steps\": 7}}"
  name       = "state"
}
```

**Comment by alexott** [comment]
ah, ok - the dashboard-level filter adds following block to the widget. it needs to be fixed with the new code:

```
       "dashboard_filter_config": [
         {
           "filter_field": "country_code",
           "parameters": null,
           "query_id": "a01ebdc1-25a5-40c5-847e-4c23dcb8b905"
         }
```

**Comment by TaylorZowtuk** [comment]
> ah, ok - the dashboard-level filter adds following block to the widget. it needs to be fixed with the new code:
> 
> ```
>        "dashboard_filter_config": [
>          {
>            "filter_field": "country_code",
>            "parameters": null,
>            "query_id": "a01ebdc1-25a5-40c5-847e-4c23dcb8b905"
>          }
> ```

Just to clarify, you mean that this is something that would need to be added to the provider right? This isn't a block that I could currently add to my `databricks_sql_widget` and expect it to work right?

**Comment by alexott** [comment]
it needs to be added to provider... No ETA yet, we need to figure out what should be parameters, etc.

**Comment by RaccoonForever** [comment]
Hey guys :)

We would be delighted to see this feature too :D
Any news about the ETA ?
