### ISSUE TITLE
[ISSUE] Issue with `databricks_grants` resource. CREATE_VIEW has ceased to exist without warning?

### ISSUE THREAD

**Issue by fuselessmatt** [databricks/terraform-provider-databricks#2176]
### Configuration
```hcl

resource "databricks_grants" "sandbox" {
  provider = databricks.prod_workspace
  catalog  = "sandbox"
  grant {
    principal  = data.databricks_service_principal.sp_user_insights_prod.application_id
    privileges = ["USE_CATALOG", "USE_SCHEMA", "CREATE_SCHEMA", "CREATE_TABLE", "CREATE_VIEW", "CREATE_FUNCTION", "SELECT", "MODIFY"]
  }
```

### Expected Behavior

The Terraform should continue to work as usual

### Actual Behavior

It raises this error as if CREATE_VIEW does not exist

> │ Error: cannot update grants: Privilege CREATE VIEW is not applicable to this entity [sandbox:CATALOG/CATALOG_STANDARD]. If this seems unexpected, please check the privilege version of the metastore in use [1.0].
> │ 
> │   with databricks_grants.sandbox,
> │   on unity-catalog-grants.tf line 211, in resource "databricks_grants" "sandbox":
> │  211: resource "databricks_grants" "sandbox" {

### Terraform and provider versions

Terraform: 1.3.6
Databricks: 1.13.0

### Important Factoids

It is no longer in the [official documentation](https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/privileges.html#securable-objects), but still exists in the [Terraform documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grants#catalog-grants). This code has worked for until I tried to change it today

**Comment by iandexter** [comment]
Hi, @fuselessmatt -- this privilege has been subsumed into `CREATE_TABLE` [[doc link](https://docs.databricks.com/data-governance/unity-catalog/manage-privileges/privileges.html#create-table)]. Thanks for reporting.

**Comment by fuselessmatt** [comment]
This has now been resolved
