### ISSUE TITLE
[ISSUE] Issue with `databricks_service_principals` resource

### ISSUE THREAD

**Issue by jelmerk** [databricks/terraform-provider-databricks#2184]
### Expected Behavior

Scenario 1

```
data "databricks_service_principals" "this" {
  application_ids = ["application-id-here"]
}
```

I expect this would return the service principal for this application id

Scenario 2

```
data "databricks_service_principals" "this" {

}
```

I expect that this would return all service principals

### Actual Behavior

In both cases you get the following error

```
│ Error: cannot read data service principals: Index 1 out of bounds for length 1
│ 
│   with module.sql_endpoints["DBT sql endpoint"].data.databricks_service_principals.this,
│   on .terraform/modules/sql_endpoints/main.tf line 29, in data "databricks_service_principals" "this":
│   29: data "databricks_service_principals" "this" {
```

This is because the [scim api ](https://docs.databricks.com/dev-tools/api/latest/scim/scim-sp.html)returns a 500 error for filtering on empty string and [the terraform provider always adds a displayName filter](https://github.com/databricks/terraform-provider-databricks/blob/a729b96d5db9ff5cedac8701399efed640841267/scim/data_service_principals.go#L22) even when none is defined

```
curl --location --request GET "https://my_workspace.cloud.databricks.com/api/2.0/preview/scim/v2/ServicePrincipals?filter=displayName%20co%20%27%27" \
--header 'Authorization: Bearer dapi_token_here'

{"schemas":["urn:ietf:params:scim:api:messages:2.0:Error"],"detail":"Index 1 out of bounds for length 1","status":"500"}
```

### Terraform and provider versions
All versions

**Comment by nkvuong** [comment]
@jelmerk 

for scenario 1, you should use `databricks_service_principal` data source
```tf
data "databricks_service_principal" "this" {
  application_id = "application-id-here"
}
```

for scenario 2, it is a duplicate issue of #2178

**Comment by nkvuong** [comment]
Duplicate of #2178
