### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource /initialization of the provider 

### ISSUE THREAD

**Issue by nourriba** [databricks/terraform-provider-databricks#2187]
first we created a workspace with cluster,s workkspace_conf , users . goups .. 
when we try to modify any config for example add a flag to workspace_conf 
we are get this errors on pretty much all databricks resources  
Error: cannot read service principal: cannot configure azure-client-secret auth: cannot get workspace: please set `azure_workspace_resource_id` provider argument. Environment variables used: ARM_CLIENT_SECRET, ARM_CLIENT_ID, ARM_TENANT_ID. Please check https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication for details
 
this is an example for databricks_service_principal ( but the error is on all other resources )
     with module.databricks.databricks_service_principal.sp["xxxxxxx"],
    on ../templates/modules/analytics/databricks/v2/databricks_users_groups.tf line 118, in resource "databricks_service_principal" "sp":
  118: resource "databricks_service_principal" "sp" {
  
 the Workspace exists and its beeing read correcty 
from debug logs 
reading workspace **request**
 ```
module.databricks.azurerm_databricks_workspace.databricks["my-adb-workapce"]: Refreshing state... [id=/subscriptions/cxxxxxxxxxxxxx/resourceGroups/cdn-cdo-nprod-databricks/providers/Microsoft.Databricks/workspaces/my-adb-workapce]
13:11:58  2023-04-03T13:11:57.854-0400 [DEBUG] provider.terraform-provider-azurerm_v3.48.0_x5: AzureRM Request: 
13:11:58  GET /subscriptions/xxxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Databricks/workspaces/my-adb-workapce?api-version=2023-02-01 HTTP/1.1
13:11:58  Host: management.azure.com
13:11:58  User-Agent: Go/go1.19.3 (amd64-linux) go-autorest/v14.2.1 hashicorp/go-azure-sdk/workspaces/2023-02-01 HashiCorp Terraform/1.2.3 
             (+https://www.terraform.io) 
               Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
13:11:58  Content-Type: application/json; charset=utf-8
13:11:58  X-Ms-Correlation-Request-Id: 9f503b6d-44ae-9808-2e9e-dc10ec144a4e
13:11:58  Accept-Encoding: gzip: timestamp=2023-04-03T13:11:57.854-0400_
```
**Response**

```
13:11:58  2023-04-03T13:11:57.970-0400 [DEBUG] provider.terraform-provider-azurerm_v3.48.0_x5: AzureRM Response for
 https://management.azure.com/subscriptions/xxxxxxxxxxxxx/resourceGroups/yyyyyyyyyyyy/providers/Microsoft.Databricks/workspaces/my-adb-workapce?api-version=2023-02-01: 
13:11:58  HTTP/2.0 200 OK
13:11:58  Cache-Control: no-cache
13:11:58  Content-Type: application/json; charset=utf-8
13:11:58  Date: Mon, 03 Apr 2023 17:11:57 GMT
13:11:58  Expires: -1
13:11:58  Pragma: no-cache
13:11:58  Server: Microsoft-HTTPAPI/2.0
13:11:58  Strict-Transport-Security: max-age=31536000; includeSubDomains
13:11:58  Vary: Accept-Encoding
13:11:58  X-Content-Type-Options: nosniff
13:11:58  X-Ms-Correlation-Request-Id: 9f503b6d-44ae-9808-2e9e-dc10ec144a4e
13:11:58  X-Ms-Ratelimit-Remaining-Subscription-Resource-Requests: 1799
13:11:58  X-Ms-Request-Id: canadacentral:d24ae7cb-c28d-4505-80b0-d6e54aff3c05
13:11:58  X-Ms-Routing-Request-Id: CANADACENTRAL:20230403T171157Z:908b2289-b1e9-4411-ba4b-91bff743baeb
13:11:58  
13:11:58  {"properties":
    { .....
      "workspaceId":"<here_i_had_the_right_id>","workspaceUrl":"adb-<here_i_had_the_right_id>.19.azuredatabricks.net","createdDateTime":"2023-03-24T18:34:32.0346525Z"
    },
"id":"/subscriptions/xxxxxxxxxxxxx/resourceGroups/cdn-cdo-nprod-databricks/providers/Microsoft.Databricks/workspaces/my-adb-workapce","name":"my-adb-workapce",
"type":"Microsoft.Databricks/workspaces","sku":{"name":"premium"},"location":"canadacentral" }
: timestamp=2023-04-03T13:11:57.970-0400
```

 

### Expected Behavior
all databricks need to be able to use the provider ( initialzed with azurerm_databricks_workspace_id ) to connect to databricks api 

### Actual Behavior
Error: cannot read service principal: cannot configure azure-client-secret auth: cannot get workspace: please set `azure_workspace_resource_id` provider argument. Environment variables used: ARM_CLIENT_SECRET, ARM_CLIENT_ID, ARM_TENANT_ID. Please check https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication for details
 
this is an example for databricks_service_principal ( but the error is on all other resources )
     with module.databricks.databricks_service_principal.sp["cdn-cdo-cac-np-dev-adf"],
    on ../templates/modules/analytics/databricks/v2/databricks_users_groups.tf line 118, in resource "databricks_service_principal" "sp":
  118: resource "databricks_service_principal" "sp" {

**Comment by nkvuong** [comment]
@nourriba how do you configure the provider? there is no Terraform code and very little debug logs so we cannot meaningfully help you

**Comment by nfx** [comment]
this seems to be a bug with `azurerm` provider, as debug logs say `azurerm_databricks_workspace`.
