### ISSUE TITLE
Exporter: Answered "no" to export notebooks and "yes" to export directories, however, notebooks are also exported

### ISSUE THREAD

**Issue by alex-lopes-databricks** [databricks/terraform-provider-databricks#2191]
## Steps to reproduce

exporter_1_13_test % ./terraform-provider-databricks_v1.13.0 exporter 
🔍 Match entity names (optional): 
✅ Generate `databricks_global_init_script` and related resources? [Y/n] n
✅ Generate `databricks_sql_query` and related resources? [Y/n] n
✅ Generate `databricks_sql_endpoint` and related resources? [Y/n] n
✅ Generate `databricks_sql_global_config` and related resources? [Y/n] n
✅ Generate `databricks_cluster` and related resources? [Y/n] n
✅ Generate `databricks_group` and related resources? [Y/n] n
✅ Generate `databricks_sql_dashboard` and related resources? [Y/n] n
✅ Generate `databricks_directory` and related resources? [Y/n] y
✅ Generate `databricks_repo` and related resources? [Y/n] n
✅ Generate `databricks_notebook` and related resources? [Y/n] n
✅ Generate `databricks_pipeline` and related resources? [Y/n] n
✅ Generate `databricks_ip_access_list` and related resources? [Y/n] n
✅ Generate `databricks_job` and related resources? [Y/n] n
✅ Generate `databricks_secret_scope` and related resources? [Y/n] n
✅ Generate `databricks_workspace_conf` and related resources? [Y/n] n
✅ Generate `databricks_mount` and related resources? [Y/n] n

# Example
## Output: notebooks.tf 

data "databricks_directory" "shared_1265884303617918" {
  path = "/Shared"
}
resource "databricks_directory" "shared_queries_4283166323588369" {
  path = "/Shared/Queries"
}
data "databricks_directory" "users_1265884303617917" {
  path = "/Users"
}
data "databricks_directory" "users_alex_lopes_databricks_com_1265884303617919" {
  path = databricks_user.alex_lopes.home
}
resource "databricks_notebook" "users_alex_lopes_databricks_com_adlstables_4438596076588644" {
  source = "${path.module}/notebooks/Users/alex.lopes@databricks.com/ADLSTables.py"
  path   = "${databricks_user.amy_user.home}/ADLSTables"
}

## Desired: notebooks.tf 
data "databricks_directory" "shared_1265884303617918" {
  path = "/Shared"
}
resource "databricks_directory" "shared_queries_4283166323588369" {
  path = "/Shared/Queries"
}
data "databricks_directory" "users_1265884303617917" {
  path = "/Users"
}
data "databricks_directory" "users_alex_lopes_databricks_com_1265884303617919" {
  path = databricks_user.alex_lopes.home
}

**Comment by alexott** [comment]
I don't have access to Windows to test it. Can you try it with the following command-line:

```
terraform-provider-databricks exporter -directory output -skip-interactive -listing directories -services directories
```
