### ISSUE TITLE
[ISSUE] Issue with `databricks_group` data requiring workspace admin privileges since 1.14.1

### ISSUE THREAD

**Issue by mtrampont** [databricks/terraform-provider-databricks#2193]
### Configuration
```hcl
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
      version = "1.14.1"
    }
  }
}

provider "databricks" {
  host  = var.db_url
  token = var.databricksPAT
}

data "databricks_group" "somegroup" {
  display_name = "somegroup-display-name"
}

```

### Expected Behavior

No issue.

### Actual Behavior

Terraform plan fails with following error:
```
��� Error: /2.0/preview/scim/v2/Groups/916570868973800 is only accessible by admins

��� 

���   with databricks_group.somegroup,

���   on tstDatabricksInstance.tf line [...], in data "databricks_group" "somegroup":

���    4: data "databricks_group" "somegroup" {
```

### Steps to Reproduce

Terraform version 1.3.9
Databricks provider version: 1.14.1

### Important Factoids

I think the issue come from PR#2181, more specifically [this line](https://github.com/databricks/terraform-provider-databricks/commit/cb2f98b42c4407e2e67a34b31553c9738840cdd4#diff-11e6b6f6d6e6f4e8664a09b309d609b81f368b5dc272a1e565aa1f96e2980082R67).
A call to the Get Group by Id API was added and this is only usable by admin of the workspace from the [doc](https://learn.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/scim/scim-groups#get-group-by-id).

**Comment by mtrampont** [comment]
@shreyas-goenka regarding your changes to [scim/groups.go](https://github.com/databricks/terraform-provider-databricks/commit/cb2f98b42c4407e2e67a34b31553c9738840cdd4#diff-11e6b6f6d6e6f4e8664a09b309d609b81f368b5dc272a1e565aa1f96e2980082), I'm not an expert but was it really necessary to call `Filter` with `includeRoles` parameter to `false` on [this line](https://github.com/databricks/terraform-provider-databricks/blame/cb2f98b42c4407e2e67a34b31553c9738840cdd4/scim/groups.go#L57),
given that `Filter` is called with a matching condition on exactly one group display_name ?

In this case, is fetching the roles an issue since only one group should match ?

**Comment by nfx** [comment]
@mtrampont can you confirm this error didn't happen before 1.14.1?

**Comment by mtrampont** [comment]
@nfx not sure which kind of evidence I can provide to you.
In our case, we were using the latest version of the provider in our terraform configuration and fixing it to 1.14.0 solved the issue.

**Comment by nfx** [comment]
Got it. It’s a regression then. We’ll work on it next week.

**Comment by calloc** [comment]
This morning after using v1.88.0. I got the same error.

```
│ Error: cannot read group: https://xxx-data-sandbox.cloud.databricks.com/api/2.0/preview/scim/v2/Groups/xxxx?attributes=members,roles,entitlements,externalId is only accessible by admins.
│ 
│   with data.databricks_group.operation_team,
│   on data.tf line 20, in data "databricks_group" "operation_team":
│   20: data "databricks_group" "operation_team" {
```

I have to revert back to v1.87.1 for it to work

```
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
      version = "1.87.1"
    }
    utils = {
        source = "cloudposse/utils"
    }
  }
}

provider "databricks" {
  # alias = "dbc"
  profile = var.databricks_profile # workspace-level with non-admin sp
}
```
