### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore_assignment` resource

### ISSUE THREAD

**Issue by mukundbajaj** [databricks/terraform-provider-databricks#2196]
### Configuration
```hcl
resource "databricks_metastore_assignment" "this" {
  workspace_id         = var.default_metastore_workspace_id
  metastore_id         = databricks_metastore.this.id
  default_catalog_name = "hive_metastore"
}
```

### Expected Behavior
Workspace ID should have been accepted

### Actual Behavior
│ Error: Attribute must be a whole number, got 4.427624696409674e+15
│
│   with databricks_metastore_assignment.default_metastore,
│   on metastore.tf line 33, in resource "databricks_metastore_assignment" "default_metastore":
│   33:   workspace_id         = var.default_metastore_workspace_id
│

### Steps to Reproduce

Type of the  var.default_metastore_workspace_id is number, tried with string too and it's the same error.
### Terraform and provider versions

Provider is latest

**Comment by nkvuong** [comment]
@mukundbajaj could you check that you are using 64bit version of Terraform?

**Comment by mukundbajaj** [comment]
@nkvuong that was it! I was using the 386 (32 bit) version of Terraform in Windows, switched to AMD64 and it worked!

Is it because of the x86 vs x64 architectural differences that the length of the number was not getting processed?

**Comment by nkvuong** [comment]
@mukundbajaj yes, that is correct - as many of ids in Databricks are 64 bit

**Comment by mukundbajaj** [comment]
Thank you for the quick turnaround, @nkvuong! Closing this issue and this remains as an archive for others to troubleshoot!
