### ISSUE TITLE
[FEATURE] Add support for workspace files

### ISSUE THREAD

**Issue by alexott** [databricks/terraform-provider-databricks#2206]
### Use-cases

Databricks recently added support for [files in workspace](https://docs.databricks.com/files/workspace.html), similar to files in repos, that allows to put file of any format into the workspace, not only the notebooks.  

It would be really useful to have a dedicated resource for these files.

### Attempted Solutions

The main difference is that import/export functions of workspace API include the new format: `AUTO`.

### Proposal

Although it's possible to modify `databricks_notebook` to handle `AUTO` file format, having a dedicated resources could be more understandable.

**Comment by MADHBHAR** [comment]
Hi @alexott, when can we expect this new feature to be released.
