### ISSUE TITLE
[FEATURE] Add AzureAvailabilitySpotWithFallback to resource instance pool

### ISSUE THREAD

**Issue by DejiCodes** [databricks/terraform-provider-databricks#2214]
### Use-cases

Creating instance pools with the azure availability spot with fallback 
### Proposal

Adding AzureAvailabilitySpotWithFallback into the validation of the azure attributes

**Comment by alexott** [comment]
There is no API for that - see https://learn.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/clusters#clusterazureavailability that says 

> Does not apply to pool availability.

Please rise this as z feature request with your Databricks representative
