### ISSUE TITLE
[ISSUE] Issue with databricks_dbfs_file resource

### ISSUE THREAD

**Issue by francisco-ltech** [databricks/terraform-provider-databricks#2215]
### Configuration

resource "databricks_dbfs_file" "sh_script" {
  depends_on = [
    azurerm_databricks_workspace.my_wks
  ]

  path   = "/tmp/init/sh_script.sh"
  source = "${path.module}/sh_script.sh"
}

### Expected Behavior

Resource created. Sh file to be uploaded to dbf:/tmp/init

### Actual Behavior

Error: cannot create dbfs file: cannot create handle: Operation failed: "Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.", 403, PUT, https://managedsa.dfs.core.windows.net/root/6133664986147318/tmp/init/sh_script.sh?resource=file&timeout=90, AuthenticationFailed

### Steps to Reproduce

terraform apply

### Debug Output

2023-04-13T14:12:24.954+0100 [DEBUG] provider.terraform-provider-databricks_v1.11.1: POST /api/2.0/dbfs/create
> {
>   "overwrite": true,
>   "path": "/tmp/init/sh_script.sh"
> }
< HTTP/2.0 400 Bad Request
< {
<   "error_code": "IO_ERROR",
<   "message": "Operation failed: \"Server failed to authenticate the request. Make sure the value of Authorizati... (431 more bytes)"

### Important Factoids

- A second tf plan & apply also fails with the same error
- All other resources in the TF configuration are created
- The service principal used has the right permissions on the managed storage account

**Comment by francisco-ltech** [comment]
This seems to be a problem with Databricks API, the cli also comes back with the error.

```code
Response from server:
 { 'error_code': 'IO_ERROR',
  'message': 'Operation failed: "Server failed to authenticate the request. '
             'Make sure the value of Authorization header is formed correctly '
             'including the signature.", 403, HEAD, '
```

**Comment by GrantAnt** [comment]
Did you find any solution for this problem? I also run into the 403 "operation failed error". Also having the same problems with Databricks API. So far I did not find another thread that deals with this problem.

**Comment by francisco-ltech** [comment]
Hi @GrantAnt, at least for me it seems it was a glitch with the API at that time. 

However, I did migrate to use resource "databricks_workspace_file" instead as recommended by Databricks as there seems to be a vulnerability issue with "databricks_dbfs_file". And this has been working fine no problem at all.

**Comment by GrantAnt** [comment]
In my case the Databricks-PAT was not working directly after creating it, waiting for up to 5 minutes solved the problem.
