### ISSUE TITLE
[DOC] databricks_mws_workspaces Azure support

### ISSUE THREAD

**Issue by nickbrownapollo** [databricks/terraform-provider-databricks#2223]
### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces

### Expected Details
The description of the resource states that it can be used with AWS and GCP. No mention of Azure. Am I supposed to infer that Azure is not supported? It would be less ambiguous to have an explicit statement regarding Azure support. 

### List of things to potentially add/remove:
Add an explicit statement regarding Azure support.

**Comment by nickbrownapollo** [comment]
Apologies I'm conflating a couple of issues I'm having with:
1. databricks_mws_workspaces (as a data source to retrieve my workpsaces/ids at the account level). I appear to have an authentication issue, so turned to the docs and couldn't ascertain if the resource source was actually supported on Azure or not. Hence raising an issue regarding the documentation. 
2. databricks_metastore_assignment (to assign the workspace). Also looks like I have an authentication issue. But this not the subject of the issue that I have raised.

**Comment by alexott** [comment]
then the GH issue is not correct - it's about data source, not about resource.
