### ISSUE TITLE
[ISSUE] Multiple `auth_type` conflict with the provider

### ISSUE THREAD

**Issue by ehab-eb** [databricks/terraform-provider-databricks#2226]
Creating a workspace is failing on authentication. It seems to me this is failing post-creation at the validation stage.

All our terraform config is deployed using CI/CD which touches on many different providers, not just databricks. Some of our deployments are on Azure for which we use the [Azure Login action](https://github.com/marketplace/actions/azure-login).

That action creates a number of environment variables that are used when authenticating to Azure. This causes a conflict with the databricks provider which is why we use the `auth_type` variable for providers to bypass that. It seems that somewhere within the databricks provider `auth_type` setting isn't getting passed through all the way which causes the deployment to fail on provider auth.

### Configuration
```hcl
provider "databricks" {
  alias = "account"

  host       = "https://accounts.cloud.databricks.com"
  account_id = var.databricks_account_id
  username   = var.databricks_account_username
  password   = var.databricks_account_password
  auth_type  = "basic"
}

...

resource "databricks_mws_workspaces" "this" {
  provider        = databricks.account
  account_id      = var.databricks_account_id
  aws_region      = var.databricks_region
  workspace_name  = local.workspace_name
  deployment_name = var.databricks_deployment_name

  credentials_id                           = databricks_mws_credentials.this.credentials_id
  storage_configuration_id                 = databricks_mws_storage_configurations.root_bucket_storage_config.storage_configuration_id
  network_id                               = databricks_mws_networks.mws_network.network_id
  storage_customer_managed_key_id          = databricks_mws_customer_managed_keys.storage.customer_managed_key_id
  managed_services_customer_managed_key_id = databricks_mws_customer_managed_keys.managed_services.customer_managed_key_id

  token {
    comment = "Terraform"
  }
}
```

### Expected Behavior
Workspace should be created successfully

### Actual Behavior
The workspace is created and an email is received saying the workspace is ready but then terraform fails creation fails on verification and removes the workspace. 

### Steps to Reproduce

1. Set the below environment variables
```
AZURE_HTTP_USER_AGENT: 
AZUREPS_HOST_ENVIRONMENT: 
ARM_CLIENT_ID: ***
ARM_TENANT_ID: ***
ARM_SUBSCRIPTION_ID: ***
```
2. terraform apply
### Terraform and provider versions

Terraform v1.4.5
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.14.3
+ provider registry.terraform.io/hashicorp/aws v4.63.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

### Debug Output

```
databricks_mws_workspaces.this: Creating...
databricks_mws_workspaces.this: Still creating... [10s elapsed]
databricks_mws_workspaces.this: Still creating... [20s elapsed]
databricks_mws_workspaces.this: Still creating... [30s elapsed]
databricks_mws_workspaces.this: Still creating... [40s elapsed]
databricks_mws_workspaces.this: Still creating... [50s elapsed]
databricks_mws_workspaces.this: Still creating... [1m0s elapsed]
databricks_mws_workspaces.this: Still creating... [1m10s elapsed]
databricks_mws_workspaces.this: Still creating... [1m20s elapsed]
databricks_mws_workspaces.this: Still creating... [1m30s elapsed]
Error: cannot create mws workspaces: cannot configure new client: validate: more than one authorization method configured: azure and basic. Config: host=https://{var.databricks_deployment_name}.cloud.databricks.com/, username=user@domain.com, *** azure_client_id=***, azure_tenant_id=***. Env: ARM_CLIENT_ID, ARM_TENANT_ID

  with databricks_mws_workspaces.this,
  on main.tf line 220, in resource "databricks_mws_workspaces" "this":
 220: resource "databricks_mws_workspaces" "this" {
```

### Important Factoids

- We deploy through GitHub actions
- AWS is the main cloud and the one that hosts Databricks
- Azure is a secondary cloud used for some non-databricks resources
- We use terragrunt

**Comment by nkvuong** [comment]
This bug is due to the Go SDK incorrectly auto-detect the `auth_type`.

**Comment by ehab-eb** [comment]
@nkvuong 

No, this is the only databricks provider block. I've changed this part `{var.databricks_deployment_name}` in the host to redact the company name as it's shown in the prefix, and I did the same thing for the username. Everything else is as is.

We had this exact error a couple of months ago when we started using the Azure login action. Adding the `auth_type` fixed it.

**Comment by ehab-eb** [comment]
We ran into this issue again under slightly different circumstances - Long story short, this problem only appears starting v1.10.0. If the provider is set to 1.9.2, for example, then then env variables don't clash and the authentication works fine.

Looking at the release notes, it seems version 1.10.0 is when #1848 was merged which could very well be the culprit.

**Comment by taufort** [comment]
I've come across the same issue today for one of my workspaces when using `auth_type = "basic"` and also having Azure environment variables set. I confirm that using version 1.9.2 of the provider fixes the issue. Thanks for the workaround @ehab-eb 👍

**Comment by ehab-eb** [comment]
@nkvuong I'm still running into this issue with the latest provider. Any chance this can be looked into?

**Comment by Erikx3** [comment]
Also running into this issue. we specifically defined `auth_type = "oauth-m2m"`, which is working well for all databricks resources except for `databricks_mws_workspaces`. Also setting some variables to empty string did not work.

```
provider "databricks" {
  profile   = var.databricks_profile # This is referring to the profile name set under ~/.databrickscfg cfg file
  alias     = "account"
  auth_type = "oauth-m2m" # Necessary to avoid 'More than one authorization method configured' error on atlantis
  azure_client_secret = ""
  azure_tenant_id = ""
  azure_client_id = ""
}
```

The only workaround I found (and I had to set it for us on `atlantis`) is to basically do for that workflow

```
export ARM_CLIENT_ID=""
export ARM_CLIENT_SECRET=""
export ARM_SUBSCRIPTION_ID=""
export ARM_TENANT_ID=""
```

**Comment by ehab-eb** [comment]
Closing as this is is no longer an issue with provider version `1.48.2`. I've not tested other versions so not sure when/starting what version it got fixed.
