### ISSUE TITLE
[FEATURE] Unified tag handling across resources

### ISSUE THREAD

**Issue by fuselessmatt** [databricks/terraform-provider-databricks#2236]
Currently [databricks_cluster](https://github.com/databricks/terraform-provider-databricks/blob/v1.14.3/docs/resources/cluster.md), [databricks_job](https://github.com/databricks/terraform-provider-databricks/blob/v1.14.3/docs/resources/job.md) and [sql_endpoint](https://github.com/databricks/terraform-provider-databricks/blob/v1.14.3/docs/resources/sql_endpoint.md) all use different syntax for specifying tags. It would be nice if they could be unified.

```hcl
   custom_tags = {
    "ResourceClass" = "SingleNode"
  }
```

```hcl
  tags = {
    environment = "dev"
    owner       = "dream-team"
  }
```

```hcl
   tags {
    custom_tags {
      key   = "City"
      value = "Amsterdam"
    }
  }
```

### Use-cases

You use multiple resources and have the same tagging policy, then you have to remember which syntax goes where despite using the same Databricks Provider

### Proposal
It would be nice if everything would use the more compact job syntax. Controversial, but in my opinion, it would also be nice if job used custom_tag even there might not be any tags in the sql endpoint or cluster context

**Comment by alexott** [comment]
we already have #1799 for SQL tags

**Comment by fuselessmatt** [comment]
Nice, I missed that part see it. The SQL tags are the most import aspect, but this expanded it slight further with unifying custom_tags keyword for jobs (controversial) or removing tags from cluster (controversial)

**Comment by alexott** [comment]
`tags` & `custom_tags` are directly reflecting the corresponding API structures, and not necessary could be used interchangeably

**Comment by fuselessmatt** [comment]
But should you really encourage people to override the default tags? And only really doing it for one type of resource. Overall you are correct though and that is just a detail in the current state. I'll close this
