### ISSUE TITLE
[ISSUE] Issue with `databricks_1.14.3` Databricks Unable to parse jobid of length 15 and need unique job nameresource

### ISSUE THREAD

**Issue by santoshreddyspy** [databricks/terraform-provider-databricks#2245]
Hi,
Good Day!

I’m trying to set the permission to all the jobs in databricks.
Code:
resource “databricks_permissions” “everyone_can_view_all_jobs” {
for_each = data.databricks_jobs.this.ids
job_id = each.value

access_control {
group_name = var.user_group
permission_level = “CAN_VIEW”
}
}

Here I’m facing two problems.

Terraform is not able to parse 15 digit jobid. Error as below.
“Error: cannot delete permissions: strconv.ParseInt: parsing “986934303241309”: value out of range”

Databricks allow jobs with same name. Terraform should consider jobid instead of jobname.
Error: “Found jobs with same name”
Regards,
Santosh

**Comment by alexott** [comment]
Check that you don't use 32-bit version of the terraform provider

**Comment by santoshreddyspy** [comment]
> Check that you don't use 32-bit version of the terraform provider
This is the version I'm using.
Terraform v1.3.6
on windows_386

**Comment by alexott** [comment]
yes, it's 32-bit version. please use 64-bit version instead

**Comment by alexott** [comment]
@nfx one more problem caused by 32-bit version

**Comment by santoshreddyspy** [comment]
> @nfx one more problem caused by 32-bit version



> yes, it's 32-bit version. please use 64-bit version instead

Lemme try and get back.

**Comment by pimonteiro** [comment]
I apologize reopening this thread, but how does one force the installation of 64bit provider?
