### ISSUE TITLE
[ISSUE] AWS cross-account policy misses the support for AWS fleet 

### ISSUE THREAD

**Issue by allebacco** [databricks/terraform-provider-databricks#2255]
### Configuration

The following configuration is used to create the IAM policy used by Databricks for creating workspaces:

```hcl
data "databricks_aws_crossaccount_policy" "this" {
}
resource "aws_iam_policy" "cross_account_policy" {
  name   = var.iam_role_policy_name
  policy = data.databricks_aws_crossaccount_policy.this.json
}
```

### Expected Behavior

I am expecting the policy provides permissions for AWS Fleet like the one in https://docs.databricks.com/administration-guide/cloud-configurations/aws/iam-role.html#default-deployment-policy

### Actual Behavior

`ec2:CreateFleet` and other AWS Fleet actions are not present.

### Steps to Reproduce

See the current code in `master` branch: https://github.com/databricks/terraform-provider-databricks/blob/e431a018d9ca7973c7cd9bc2236ec6112c85569c/aws/data_aws_crossaccount_policy.go#L12

### Terraform and provider versions

Source code at commit e431a018d9ca7973c7cd9bc2236ec6112c85569c.

Thanks.

**Comment by allebacco** [comment]
@lcavator FYI

**Comment by iandexter** [comment]
Hi, @allebacco -- thanks for reporting. As the [documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/aws_crossaccount_policy) noted, this resource is from an "evolving API", so it may not be up-to-date. 

As a workaround, you can [specify](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iam_role_policy) the policy document in the resource itself:

```
resource "aws_iam_role_policy" "this" {
  name   = "${local.prefix}-policy"
  role   = aws_iam_role.cross_account_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
... <statement from https://docs.databricks.com/administration-guide/cloud-configurations/aws/iam-role.html#default-deployment-policy
    ]
  })
}}
```

PRs are always welcome (if you want to take a stab at it).

**Comment by ruqoyyasadiq** [comment]
@alexott the new upgrade/[PR](https://github.com/databricks/terraform-provider-databricks/pull/2262) is still missing a permission - `ec2:DescribeLaunchTemplateVersions` listed in [Databricks default policy](https://docs.databricks.com/administration-guide/account-settings-e2/credentials.html#default-policy). Can this be added or should a new issue be created for this?

**Comment by alexott** [comment]
@ruqoyyasadiq let me clarify with the documentation team - I don't see this permission in the default policy, but it exists in another policy

**Comment by ruqoyyasadiq** [comment]
Thanks for the quick turnaround @alexott. Any idea when this would be release? The missing permission is preventing me from using the provider for cluster creation.
