### ISSUE TITLE
[ISSUE] Terraform Exporter notebook listing breaks when it encounters special characters and/or backslash in the workspace path

### ISSUE THREAD

**Issue by antoniopinheirofilho** [databricks/terraform-provider-databricks#2256]
Hi there,

I'm using the Terraform Exporter to migrate a client to a new E2 environment.

The creation of databricks_notebook fails when a notebook or folder has some special characters in their path and display the messages below:

```
[DEBUG] GET /api/2.0/workspace/list?path=/Users/xxx@xxx.com/xxx/aaa/bbb/ccc
< HTTP/2.0 404 Not Found
[ERROR] **databricks_notebook (notebooks service) listing failed**: Path (/Users/xxx@xxx.com/xxx/aaa/bbb/ccc) doesn't exist.
```

In that case, "aaa/bbb/ccc" is a folder name, but since it has backslash in its name, the API gets lost.
Emojis in the path such as ⭐️ and 🔧 also cause the same disruption

I'm wondering if we can do anything in the Terraform Exporter to avoid this error. 

### Steps to Reproduce
Execute `./terraform-provider-databricks_v1.14.3 exporter -skip-interactive -listing=notebooks,repos -debug 2>&1 |tee tr_exporter_logs` in an environment where there are folders or notebooks with special characters and/or backslash in their names.

**Comment by alexott** [comment]
@antoniopinheirofilho for `/` character, for me it's a platform bug - it shouldn't allow to use `/` character in the path - there is a check for notebooks, but not for the directories.
