### ISSUE TITLE
[FEATURE] Tag driver/executor nodes specifically

### ISSUE THREAD

**Issue by michaelromero** [databricks/terraform-provider-databricks#2264]
Hello, was wondering if it was currently possible to tag/differentiate the driver node/executor node in terms of cloud resources spun up?

### Use-cases
We use terraform to deploy jobs and job clusters. In AWS Cloudwatch, we'd like to differentiate the driver node CPU usage from the executor CPU usage.

### Proposal
Is it possible to add a differentiator to the `default_tags` databricks already adds to the instances? e.g. isDriver:true/false.

**Comment by alexott** [comment]
There is no such functionality in the REST API on which we're relying.
