### ISSUE TITLE
[ISSUE] Issue with `databricks_mws_private_access_settings` resource

### ISSUE THREAD

**Issue by ashkan-db** [databricks/terraform-provider-databricks#2273]
When creating [private access settings] resource with TF, the "public_access_enabled" is set to the default value even if the argument is set to something else in TF code. 

### Configuration
```hcl

resource "databricks_mws_private_access_settings" "pas" {
  provider = databricks.accounts
  account_id                   = var.databricks_account_id
  private_access_settings_name = "test-pas"
  region                       = var.google_region
  public_access_enabled        = false
}

```

### Expected Behavior
A new Private Access Settings resource should get created with Public access set to **DISABLED**.

### Actual Behavior
A new Private Access Settings resource is created with Public access set to the default value of **ENABLED**.

### Steps to Reproduce
run terraform apply and create the resource as shown above

### Terraform and provider versions
Terraform v1.4.2
databricks/databricks v1.13.0
hashicorp/random v3.5.1
hashicorp/google v4.64.0

### Debug Output
(https://gist.github.com/ashkan-db/fa03a39e9d624cf393b9d315cb32f2a1)

**Comment by caveman8fb** [comment]
Looks like the omitempty is causing the setting to be removed because it is false.
Using pointers would be one way to fix this per https://themirgleich.medium.com/how-golangs-omitempty-can-confuse-the-google-apis-c0e46d22d9ff

**Comment by hectorcast-db** [comment]
Hi @ashkan-db  
Thanks for raising this. We have addressed this issue and the fix will be added to the next release:
https://github.com/databricks/terraform-provider-databricks/pull/3132
