### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource, unable to set continuous

### ISSUE THREAD

**Issue by taketarouex** [databricks/terraform-provider-databricks#2282]
### Configuration
```hcl
resource "databricks_job" "job" {
  name     = "continuous"

  continuous = {
    pause_status = "UNPAUSED"
  }
}
```

### Expected Behavior
being enable to set continuous to databricks workflow

### Actual Behavior

being unable to set continuous due to the following error

╷
│ Error: Unsupported block type
│ 
│   on databricks_job.tf line 375, in resource "databricks_job" "continuous":
│  375:   continuous {
│ 
│ Blocks of type "continuous" are not expected here.

### Terraform and provider versions

```
terraform version
Terraform v1.4.0
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.6.5
+ provider registry.terraform.io/hashicorp/aws v4.46.0
+ provider registry.terraform.io/integrations/github v5.8.0

```

**Comment by iandexter** [comment]
Hi, @taketarouex -- thanks for reporting. It looks like you're using an older version of the provider:

```bash
provider registry.terraform.io/databricks/databricks v1.6.5
```

Please upgrade to the latest version, and check if you're still getting the same error.

**Comment by taketarouex** [comment]
@iandexter 
My apologies for not checking thoroughly earlier. Thank you for your assistance.
I can set it in the latest version.
