### ISSUE TITLE
'catalog' option on databricks_pipeline module

### ISSUE THREAD

**Issue by TheRealJimShady** [databricks/terraform-provider-databricks#2286]
Recently the Delta Live Tables workflow configuration was updated to include a UC Catalogue as a target destination (previously only hive schemas were supported). Admittedly this is still in public preview, but it would be cool if this were supported in the terraform module as a `target` option 😃  

![image](https://github.com/databricks/terraform-provider-databricks/assets/12716005/4317abe3-9acf-41bf-aaea-85a3528d33e7)

**Comment by TheRealJimShady** [comment]
thought that might be the case! Superstar, thanks so much, I'll keep an eye on the docs 🙂

**Comment by alexott** [comment]
I wrote it 2 weeks ago, and even pushed, but forgot to create a PR 🤦
