### ISSUE TITLE
[DOC] Incorrect example of azurerm_key_vault_access_policy in databricks_secret_scope

### ISSUE THREAD

**Issue by rwaal** [databricks/terraform-provider-databricks#2293]
### Affected Resource(s)
The documentation for the `databricks_secret_scope` contains the section [keyvault_metadata](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/secret_scope#keyvault_metadata). The code example contains an error regarding the creation of the `azurerm_key_vault_access_policy` resource. 

The individual secret permissions in `secret_permissions` in the example are described in lowercase, while they need to be capitalized. I have verified it myself using the `hashicorp/azurerm` provider, version 3.52. 

### Expected Details
The example below shows the correct notation of the secret permissions.

```hcl
resource "azurerm_key_vault_access_policy" "this" {
  key_vault_id       = azurerm_key_vault.this.id
  tenant_id          = data.azurerm_client_config.current.tenant_id
  object_id          = data.azurerm_client_config.current.object_id
  secret_permissions = ["Delete", "Get", "List", "Set"]
}
```

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Capitalize the secret_permission names in `secret_permissions`

### Important Factoids
See the official documentation for the [azurerm_key_vault_access_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy#secret_permissions) where the format of the secret names is described.

### References
none

**Comment by alexott** [comment]
It's more a change on the azurerm side - previously the names were case insensitive

**Comment by rwaal** [comment]
> It's more a change on the azurerm side - previously the names were case insensitive

Hi @alexott, you are probably correct that it's related to a change to the azurerm provider. Nevertheless, I used the example in the documentation (for the Databricks provider) to configure the Secret Scope, which failed. It might be useful to update the example so that other people don't run into the same issue.
