### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster` resource with `node_type_id` and `instance pool id`

### ISSUE THREAD

**Issue by nagyryan** [databricks/terraform-provider-databricks#2310]
### Configuration
```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
    }
  }
}

provider "databricks" {
  host  = "abc"
  token = "abc"
}

locals {
  default_policy = {
    "dbus_per_hour" : {
      "type" : "range",
      "maxValue" : 10
    },
    "autotermination_minutes" : {
        "type": "range",
        "minValue": 0,
        "maxValue": 60,
        "defaultValue": 60
    },
    "custom_tags.Team" : {
      "type" : "fixed",
      "value" : "DSA"
    },
     "spark_version": {
         "type": "blocklist", 
         "values": [ "13.0.x-scala2.12" ],
         "defaultValue": "13.0.x-scala2.12"
        },
    "instance_pool_id": {
        "type": "fixed",
        "value": "instance pool value",
        "hidden": true
    },
    "driver_instance_pool_id": {
        "type": "fixed",
        "value": "driver pool value",
        "hidden": true
    }
}
}


# Spark Version data
data "databricks_spark_version" "latest_lts" {
    latest = true
    long_term_support = true
}

# Node type 
data "databricks_node_type" "node_type" {
    local_disk = true
    min_cores = 2
}

resource "databricks_cluster_policy" "my_policy" {
  name       = "Ryan's Terraform Cluster Policy"
  definition = jsonencode(local.default_policy)
}

# Actual Databricks Cluster Resource
resource "databricks_cluster" "ryan_terraform_cluster" {
    cluster_name = "Ryan's Terraform Cluster"
    spark_version = "12.2.x-scala2.12"
    # autotermination_minutes = 10
    policy_id = databricks_cluster_policy.my_policy.id
    # node_type_id = data.databricks_node_type.node_type.id
    autoscale {
        min_workers = 1
        max_workers = 2
    }
    apply_policy_default_values = true

    custom_tags = {
        "customTag" = "costCenterB"
  }
}
```

### Expected Behavior
After cluster creation I should be able to modify/change cluster configurations using terraform.

### Actual Behavior
After cluster creation, any changes are denied due to the fact that a `node_type_id` is applied after creation to the resource, which then conflicts with the check for an instance pool id:
```
│ Error: cannot update cluster: The field 'node_type_id' cannot be supplied when an instance pool ID is provided.
│ 
│   with databricks_cluster.ryan_terraform_cluster,
│   on maintf.tf line 67, in resource "databricks_cluster" "ryan_terraform_cluster":
│   67: resource "databricks_cluster" "ryan_terraform_cluster" {
```

### Steps to Reproduce
1. `terraform apply`
2. Make a change to the cluster configuration
3. `terraform apply`

### Terraform and provider versions

Terraform v1.4.6
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.16.1

### Debug Output

https://gist.github.com/nagyryan/ab8286c707c9e322cd141ebc72cdd011

**Comment by alexott** [comment]
The problem here most probably is that cluster settings are coming from the cluster policy, not from the terraform itself. we're doing some checks if the instance pool is set or not, and modify config accordingly: https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/clusters_api.go#L447.  

But in the given case, instance pool isn't set explicitly but via cluster policy.  And because Terraform doesn't know the content of the given cluster policy, then it isn't able to judge whet is set and what isn't. 

I'm in general don't recommend to use cluster policies for Terraform-managed resources - this usually causes configuration drift on each apply, etc.
