### ISSUE TITLE
[DOC] Inconsistent `edition` and `channel` case sensitivity in `databricks_pipeline` between API and docs

### ISSUE THREAD

**Issue by MigQ2** [databricks/terraform-provider-databricks#2319]
In the [`databricks_pipeline` documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline) the [`edition`](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline#edition) and [`channel`](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline#channel) properties have their supported values as lowercase, however, once applied they are stored as uppercase. 

This causes `terraform plan` to display the resource as to be changed every time, when it reality it shouldn't.

![image](https://github.com/databricks/terraform-provider-databricks/assets/18492295/64502a6d-a32f-467c-b591-996b8eca48ab)

For `channel` it seems to always display the uppercase to lowerchange in the plan. For `edition` it seems to do it only sometimes, and I can't figure out what makes it display and what not.

I suggest the docs are changed to use the uppercase values and make the output of `terraform plan` more readable

I am using `v.1.16.1`

**Comment by iandexter** [comment]
PR merged: https://github.com/databricks/terraform-provider-databricks/pull/2322
