### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource, cannot provision with storage_root specified

### ISSUE THREAD

**Issue by SLe-Corre** [databricks/terraform-provider-databricks#2321]
### Configuration
```hcl
# Copy-paste your Terraform configuration here
resource "databricks_catalog" "this" {
  provider     = databricks.workspace
  metastore_id = databricks_metastore.this.id
  for_each = var.initial_catalog_configuration
  name         = "${local.resource_prefix}/${each.key}"
  comment      = each.value.comment
  properties = each.value.properties
  storage_root = "${databricks_external_location.some[each.value.bucket].url}${each.value.bucket_subdir}"
  depends_on = [databricks_metastore_assignment.default_metastore, databricks_external_location.some]
}
```

### Expected Behavior
Catalog created with external locations on AWS S3, typically to subdirectories of a bucket.
Path should have generated in correct format.
New catalog is created.

### Actual Behavior
No catalog created, terraform errors with:

```
Error: Provider produced inconsistent final plan
When expanding the plan for databricks_catalog.this["reporting"] to include new values learned so far during apply, provider "registry.terraform.io/databricks/databricks" produced an invalid new value for .storage_root: was cty.StringVal("s3://<BUCKET>/reporting"), but now cty.StringVal("s3://<BUCKET>reporting").
```

### Steps to Reproduce

1. terraform apply a script using `databricks_catalog` with `databricks_external_location`

Plan completes successfully.

### Terraform and provider versions
Terraform v1.4.2
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.16.1
+ provider registry.terraform.io/hashicorp/time v0.9.1

Issue seems straightforward, inconsistent `.url` output between plan and apply, presumably from the `databricks_external_location` resource.

**Comment by nkvuong** [comment]
this looks to be the same as #2335

**Comment by SLe-Corre** [comment]
Yep appears to be same fundamental issue.
Will close this one to keep it tidy.
