### ISSUE TITLE
[FEATURE] Add support for model serving endpoints in `databricks_permissions`

### ISSUE THREAD

**Issue by kunaldb** [databricks/terraform-provider-databricks#2333]
Hi there,

Feature Request Proposal: Functionality to Add User , Groups and service principals to Model Serving Points using Databricks Terraform

### Use-cases
The ability to add user groups to model serving point using Databricks Terraform would allow users to more easily manage access to their models. Currently, the only way to add user groups to model serving point is through the Databricks UI. This can be a time-consuming and error-prone process, especially for large organizations with many user groups.

### Proposal

We propose extending the Databricks Terraform provider with a new resource type that allows users to define and manage user groups for model serving points. This new resource will provide the following functionality:

a. Ability to define user groups: Users will be able to define user groups within the Terraform configuration, specifying the desired group name, members, and associated permissions.

b. Association of user groups with model serving points: Users can assign one or more user groups to a model serving point, granting the defined group members access to the serving point. This association will ensure that the specified user groups have the necessary permissions to interact with the models.

c. Support for dynamic updates: The Terraform configuration should support dynamic updates to user groups and their associations with model serving points. This allows for easy modifications and adjustments as user groups evolve over time.

**Comment by alexott** [comment]
it's just standard permissions... see #2331
