### ISSUE TITLE
v1.17.0 does not have │ a package available for  linux_386.

### ISSUE THREAD

**Issue by amitca71** [databricks/terraform-provider-databricks#2334]
### Affected Resource(s)
Executing from circleci i get the error that its not supported by their machines:
Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/databricks/databricks v1.17.0 does not have
│ a package available for your current platform, linux_386.
### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] First item to change
- [ ] Second item to change

**Comment by alexott** [comment]
32-bit builds were removed due many problems with handling of 64-bit identifiers - see #2304

**Comment by iandexter** [comment]
Hi, @amitca71 -- can you try installing the 64-bit version instead?
