### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` and `databricks_external_location` resource and `storage_root`

### ISSUE THREAD

**Issue by plamb** [databricks/terraform-provider-databricks#2335]
Using both the 1.16.x and 1.17.x provider we are seeing that on every terraform plan that both catalogs and external locations are being recreated (catalogs) or updated (external locations) even when there are no changes to those resources. It looks like somewhere a trailing "/" is added to the storage_root and then terraform is wanting to change that to remove the trailing "/"

```text
  # databricks_catalog.business_units["enverus-databricks-unity-ba-ue1-dev"] must be replaced
-/+ resource "databricks_catalog" "business_units" {
      ~ id            = "sample_catalog_dev" -> (known after apply)
        name          = "sample_catalog_dev"
      ~ storage_root  = "s3://sample-catalog-dev/" -> "s3://sample-catalog-dev" # forces replacement
        # (4 unchanged attributes hidden)
    }
```

**Comment by victorwegeborn** [comment]
When will a fix for this issue be rolled out?

**Comment by alexott** [comment]
No, but you can update your terraform code to use trailing slash...

**Comment by victorwegeborn** [comment]
Added the trailing slash. Worked for a couple of days. Now I am seeing the same issue again, but of course reversed. I remove the trailing slash and now my terraform code rolls out with no changes. 

Did the Unity Catalog Team revert the change?

**Comment by alexott** [comment]
The PR fixes drift in both directions...
