### ISSUE TITLE
[ISSUE] Issue with `databricks_external_location` resource

### ISSUE THREAD

**Issue by sirishachaparla** [databricks/terraform-provider-databricks#2343]
Terraform plan shows changes to unity catalog external location urls when trying to upgrade the Databricks provider version to 1.15.x/ 1.16.x/ 1.17.x. Plan change looks like removing the "/" from url.

### Configuration

Changes in terraform plan

# resource databricks_external_location.test["container"] will be updated in-place
  ~ resource "databricks_external_location" "test" {
          ~ url             = "sample.net/" -> "sample.net"
        # (5 unchanged attributes hidden)
    }

### Expected Behavior
When we upgrade the provider version it should not change the existing structure

### Actual Behavior
Plans are showing the changes related to databricks external locations and storage url

### Steps to Reproduce
1.We are updating the databricks provider version from 1.10.0 to 1.16.0
2.Run terraform init and then terraform plan
3. Plan shows above changes

### Terraform and provider versions
Terraform-1.3.6
Databricks provider- trying to update from 1.10.0 to 1.16.0

**Comment by alexott** [comment]
duplicate of #2335

**Comment by sirishachaparla** [comment]
Issue is fixed and terraform plans showing no changes to databricks provider version upgrade
