### ISSUE TITLE
[ISSUE] Issue with databricks_grants resource - causes error "Error: unknown is not fully supported yet"

### ISSUE THREAD

**Issue by mmayurie** [databricks/terraform-provider-databricks#2361]
Hi team,
 I'm using databricks_grants to apply permissions to some unity catalog elements, specifically databricks_storage_credential and databricks_external_location. I'm working within a workspace, granting access to groups and service principals that have been added to that workspace.

I'm finding that the initial grant succeeds, but a subsequent immediate "terraform plan" fails.
When I changed the external location that S3 bucket name , I faced this issue.

**Configuration**
```
    provider "databricks"  {
          source  = "databricks/databricks"
          version = "~> 1.15.0"
        }
```

**Expected Behavior**

    The databricks_grants resource should not throw an error if the config has changed or external location has changed, the changes should be applied without error.

**Actual Behavior**
    The following error was observed:
```
    Error: unknown is not fully supported yet
    
      with module.databricks_tenant["concertai"].databricks_grants.external_location_permission,
      on .terraform/modules/databricks_tenant/storage_cred.tf line 18, in resource "databricks_grants" "external_location_permission":
      18: resource "databricks_grants" "external_location_permission" {
```

**Steps to Reproduce**
      create databricks_storage_credential and databricks_external_location resources in a unity catalog metastore
      use a databricks_grants resource to apply permissions to them
      terraform apply succesfully applies the permissions.
      terraform plan immediately fails with the error located.

**Terraform and provider versions**
    Terraform v1.3.6
    
    provider registry.terraform.io/databricks/databricks v1.15.0

**Comment by iandexter** [comment]
Hi, @mmayurie -- thanks for reporting this. Can you try using the latest version, and see if you're still facing the same issue?

**Comment by patakmi** [comment]
Hi! I got the same Error with the latest (1.19.0) version.

**Comment by catrider** [comment]
I'm also getting this error with version 1.21.0

**Comment by mgyucht** [comment]
This duplicates #1966, IIUC. Please follow that ticket for any updates.
