### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_table` resource

### ISSUE THREAD

**Issue by jasonhue8183** [databricks/terraform-provider-databricks#2363]
### Configuration
![image](https://github.com/databricks/terraform-provider-databricks/assets/8756745/3e92bf62-afc8-45d7-88e9-77cb85f93c50)

### Actual Behavior

![image](https://github.com/databricks/terraform-provider-databricks/assets/8756745/cd83b825-8c40-430d-88f7-bd3820097091)

### Debug Output

![image](https://github.com/databricks/terraform-provider-databricks/assets/8756745/736fa065-8f48-4714-b644-65a9cc9f0fff)

**Comment by nkvuong** [comment]
@jasonhue8183 you are using the wrong provider, this resource requires a workspace url
