### ISSUE TITLE
[FEATURE] Enforce all jobs/workflows deploy via Jobs clusters

### ISSUE THREAD

**Issue by trevorpburke** [databricks/terraform-provider-databricks#2369]
### Use-cases
Job clusters are much less expensive than All-Purpose clusters. It would be ideal to be able to restrict scheduling of Workflows to just Jobs clusters for users of a workspace. 

### Attempted Solutions
Nothing

### Proposal
I'm not even sure this would be possible within the scope of this Terraform provider; it may require an update to the Databricks API.

I'm thinking the `databricks_permissions` resource might be a way to support this?

### References
None

**Comment by alexott** [comment]
There is no such permission. But you can configure your clusters to deny jobs execution: https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/clusters_api.go#L428 (it's not documented yet), but you can get understanding of the required structure from the API docs: https://docs.databricks.com/api/workspace/clusters/create

**Comment by trevorpburke** [comment]
> There is no such permission. But you can configure your clusters to deny jobs execution: https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/clusters_api.go#L428 (it's not documented yet), but you can get understanding of the required structure from the API docs: https://docs.databricks.com/api/workspace/clusters/create

Awesome, this will work and it appears that this is valid within a cluster policy, which works for my use-case. 

```
    "workload_type.clients.jobs" : {
      "type" : "fixed",
      "value" : false
    }
```

**Comment by alexott** [comment]
I've added documentation for this block.
