### ISSUE TITLE
KMS details not mentioned

### ISSUE THREAD

**Issue by Poojashreesuvarna** [databricks/terraform-provider-databricks#2387]
Hi Team,
We noticed the difference in IAM policy on the below documents
https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog#configure-aws-objects

I understand that <KMS_KEY>: Optional but it is not mentioned on the below document. (This will be a problem if cx has KMS enabled)
https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog#configure-aws-objects

**Comment by iandexter** [comment]
Doc reference: https://docs.databricks.com/data-governance/unity-catalog/get-started.html#configure-a-storage-bucket-and-iam-role-in-aws
