### ISSUE TITLE
data.databricks_aws_crossaccount_policy and data.databricks_aws_assume_role_policy (30.06.2023 changes)

### ISSUE THREAD

**Issue by yevheniilukashov** [databricks/terraform-provider-databricks#2393]
**### [Action Required] Please Update Your AWS IAM Role Trust Policy**

Dear Databricks Customer,

We are reaching out to inform you of an upcoming change from AWS that affects the behavior of the [IAM](https://aws.amazon.com/iam/) trust policy and requires you to update your Unity Catalog storage credentials. This change will go into effect on **June 30, 2023.** Please read below for additional details and the action required.

AWS IAM Trust Policy Behavior Change
AWS Identity and Access Management (IAM) is [changing an aspect](https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/) of how role trust policy evaluation behaves when a role assumes itself. Previously, roles implicitly trusted themselves from a role trust policy perspective if they had identity-based permissions to assume themselves. Effective June 30, 2023, AWS will be changing role assumption behavior to always require self-referential role trust policy grants.

Impact
As a result of this change from AWS:

Unity Catalog will no longer be able to assume an IAM role configured for your [metastore's storage bucket](https://docs.databricks.com/data-governance/unity-catalog/create-metastore.html) or in [storage credentials](https://docs.databricks.com/data-governance/unity-catalog/manage-external-locations-and-credentials.html) for external locations.
Unity Catalog may fail to acquire access to these storage credentials.
Certain workloads may experience failures.

Action Required
To avoid impact to your workloads in Databricks, please review the details below and make sure you have implended the necessary updates before June 30, 2023.

Identify the IAM roles configured for your [Metastores](https://docs.databricks.com/data-governance/unity-catalog/create-metastore.html) and [Storage Credentials](https://docs.databricks.com/data-governance/unity-catalog/manage-external-locations-and-credentials.html).
Perform the following operations for each of these IAM roles:
Make sure the following highlighted permission is included in your IAM trust policy to allow the IAM role to assume itself. (The policies above can also be found in our [public documentation](https://docs.databricks.com/data-governance/unity-catalog/get-started.html#configure-a-storage-bucket-and-iam-role-in-aws))

{
  "Version": "2022-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::414351767826:role/unity-catalog-prod-UCMasterRole-14S5ZJVKOTYTL",
          **_"arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<THIS_ROLE_NAME>"_**
        ]
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "<DATABRICKS_ACCOUNT_ID>"
        }
      }
    }
  ]
}

Ensure that the IAM policy includes permissions for the role to assume itself as well.

{
 "Version": "2022-10-17",
 "Statement": [
     {
         "Action": [
             "s3:GetObject",
             "s3:PutObject",
             "s3:DeleteObject",
             "s3:ListBucket",
             "s3:GetBucketLocation",
             "s3:GetLifecycleConfiguration",
             "s3:PutLifecycleConfiguration"
         ],
         "Resource": [
             "arn:aws:s3:::<BUCKET>/*",
             "arn:aws:s3:::<BUCKET>"
         ],
         "Effect": "Allow"
     },
     {
         "Action": [
             "kms:Decrypt",
             "kms:Encrypt",
             "kms:GenerateDataKey*"
         ],
         "Resource": [
             "arn:aws:kms:<KMS_KEY>"
         ],
         "Effect": "Allow"
     },
     **_{
         "Action": [
             "sts:AssumeRole"
         ],
         "Resource": [
             "arn:aws:iam::<YOUR_AWS_ACCOUNT_ID>:role/<THIS_ROLE_NAME>"
         ],
         "Effect": "Allow"
     }_**
   ]
}

If you have any additional questions regarding the update, please contact Databricks Support at [help@databricks.com](mailto:help@databricks.com).

Thanks,
Databricks Support

**Comment by nkvuong** [comment]
@yevheniilukashov which part of the doc do we need to updated for this?

**Comment by tlecomte** [comment]
We are affected by this as well.

https://github.com/databricks/terraform-provider-databricks/issues/3110 has addressed the last part, about the IAM policy part.

However, the documentation is still out of date regarding the 1st part, about the trust policy.

**Comment by nkvuong** [comment]
Closed by #3622
