### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_table` resource for column comments

### ISSUE THREAD

**Issue by sercandogan** [databricks/terraform-provider-databricks#2396]
### Configuration
```hcl
resource "databricks_sql_table" "abc" {
  name               = "abc"
  catalog_name       = local.catalog
  schema_name        = databricks_schema.dummy_schema.name
  table_type         = "MANAGED"
  data_source_format = "DELTA"

  column {
    name    = "a"
    type    = "STRING"
    comment = "A comment"
  }
  column {
    name    = "b"
    type    = "STRING"
    comment = "Another comment that doesn't work."
  }
  comment = "Here the comment works"
}
```

### Expected Behavior
It needs single quoting for column comments as below:
```sql
-- Error: cannot create sql table: cannot execute
CREATE TABLE dummy_catalog.dummy_schema.abc (
a STRING COMMENT 'A comment.',
b STRING COMMENT 'Another comment that doesn't work.'
) USING DELTA
COMMENT 'Here the comment works';
```
Here is the line which creates the bug: https://github.com/databricks/terraform-provider-databricks/blob/v1.18.0/catalog/resource_sql_table.go#L149 It should be like this:
```go
comment = fmt.Sprintf(" COMMENT '%s'", col.Comment)
```

How should we proceed? Shall I open an fix PR?

### Actual Behavior
Currently the resource returns the query below which doesn't have quoting in comment for columns.
```sql
-- Error: cannot create sql table: cannot execute
CREATE TABLE dummy_catalog.dummy_schema.abc (
a STRING COMMENT A comment.,
b STRING COMMENT Another comment that doesn't work.
) USING DELTA
COMMENT 'Here the comment works';
```

### Steps to Reproduce

1. `terraform apply`

### Terraform and provider versions
Terraform v0.15.1 on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.18.0

**Comment by iandexter** [comment]
HI, @sercandogan -- thanks for reporting. Yes, please go ahead, and file a PR. Our team will review. Thanks!
