### ISSUE TITLE
[FEATURE] Support Unity Catalog Volumes with Azure ADLS Storage Locations

### ISSUE THREAD

**Issue by owlleg6** [databricks/terraform-provider-databricks#2402]
### Use-cases
Support Azure ADLS Storage Locations when creating Volumes in Unity Catalog. Currently creation of this type of volumes are failing.

### Attempted Solutions
None

### Proposal
Provide support within volume resource.

### References
(https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/volume)

**Comment by nkvuong** [comment]
@owlleg6 could you share the error messages you are getting?

**Comment by JenspederM** [comment]
```
╷
│ Error: cannot create volume: 
│ 
│   with module.adb_unity.databricks_volume.this["dlsmyaccount-mycontainer"],
│   on modules/databricks/unity/external_location.tf line 33, in resource "databricks_volume" "this":
│   33: resource "databricks_volume" "this" {
│ 
╵
```

**Comment by nkvuong** [comment]
@JenspederM you are correct - although currently UC Volumes is in a private preview, so you need to reach out to your account team for it to be enabled. Terraform provider support should work for ADLS paths, if not, could you please provide full debug logs, e.g. `TF_LOG=DEBUG terraform apply -no-color`

**Comment by owlleg6** [comment]
Hello @nkvuong , i will try to reach out to my Account team too and if it won't work, i will provide some detailed logs. Thanks for information.

**Comment by nkvuong** [comment]
@owlleg6 @JenspederM just want to check in on this - UC Volume is now in public preview, do you still have an issue with creating them?

**Comment by JenspederM** [comment]
@nkvuong I'm back from vacation next week, will test it then. Thank you for the heads up!

**Comment by JenspederM** [comment]
@nkvuong Works like a charm. Great job!

**Comment by owlleg6** [comment]
> 

Hello, works for me too, thanks!

**Comment by owlleg6** [comment]
Thank you guys, everything is working
