### ISSUE TITLE
[ISSUE] `databricks_job` resource run_as service principal not working as expected

### ISSUE THREAD

**Issue by hk0178gt** [databricks/terraform-provider-databricks#2417]
### Configuration
```hcl
resource "databricks_job" "this" {
  name = var.job_name

  run_as {
    service_principal_name = "00000000-0000-0000-0000-000000000"  #job-sp
  }
```

### Expected Behavior
run_as user is "00000000-0000-0000-0000-000000000"

### Actual Behavior
run_as user is the same as the creator sp. ie. It is set to the terraform sp

### Steps to Reproduce

`terraform apply`

### Terraform and provider versions

Terraform v1.4.4
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.19.0

### Important Factoids

As per [documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#run_as-configuration-block), the terraform sp has ServicePrincipalUser role.

**Comment by dvkuznietsov** [comment]
@hk0178gt thank you for reporting the issue! Are you creating a new job, or updating an existing one? When creating a job from scratch with the latest provider version, I see that the correct run_as is set. However, when I change the run_as of the job via API, terraform does not detect the drift. Is this the issue you're facing?

**Comment by hk0178gt** [comment]
@dvkuznietsov This issue was resolved with an api update from databricks back in July. The fix was unrelated to the terraform provider. Closing out the issue.
