### ISSUE TITLE
Metastore assignment throws error but is created in unity catalog

### ISSUE THREAD

**Issue by simonwitt98** [databricks/terraform-provider-databricks#2450]
I'm using databricks povider version "1.20.0". When assigning a databricks workspace to a metastore, terraform returns:

Error: cannot read metastore assignment: Storage Credential 'xxx' does not exist.
│ 
│   with databricks_metastore_assignment.adb_metastore_assignment,
│   on main.tf line 69, in resource "databricks_metastore_assignment" "adb_metastore_assignment":
│   69: resource "databricks_metastore_assignment" "adb_metastore_assignment" {

However, the metastore assignment is being executed. I can see it in the databricks account console.

**Comment by mgyucht** [comment]
@simonwitt98 can you please follow the issue template? If you can include an example configuration, debug logs, etc., this would all help in our investigation of this issue.

**Comment by owlleg6** [comment]
Hello, check if you also have created data access identity assignment (https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/metastore_data_access). I guess it behaves like Storage Credentials, and please make sure that parameter "is_default" is set to true.

**Comment by simonwitt98** [comment]
Hello,

thanks for your help. It seems like the "is_default" setting fixed the problem. Moreover, I've separated azurem and databricks provider resources.

Thanks!
