### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource

### ISSUE THREAD

**Issue by thaiphv** [databricks/terraform-provider-databricks#2454]
### Configuration
```hcl
resource "databricks_job" "daily" {
  name = "daily_job"
  job_cluster {
    job_cluster_key = "job_cluster"
    new_cluster {
      driver_node_type_id = "c5d.4xlarge"
      node_type_id        = "c5ad.4xlarge"
      spark_version       = "11.3.x-scala2.12"
      num_workers = 8
      aws_attributes {
        availability         = "SPOT_WITH_FALLBACK"
        first_on_demand      = 1
        instance_profile_arn = data.aws_iam_instance_profile.job_cluster.arn
      }
    }
  }
  task {
    task_key = "bronze_load"
    job_cluster_key = "job_cluster"
    notebook_task {
      notebook_path = databricks_notebook.this["bronze/01_bronze_load"].path
    }
  }
}
```
### Expected Behavior
1. Deploy the resource.
2. Manually update the job cluster to change its "Access Mode" to "Single User".
3. Deploy the Terraform code again.

### Actual Behavior
Step 3 didn't restore the "Access Mode" to the default value which was "NONE".

### Terraform and provider versions
Terraform: `1.4.6`
Databricks provider: `1.20.0`

**Comment by alexott** [comment]
if you want to restore the value, you need to explicitly set [data_security_mode](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#data_security_mode) to a specific value - then it will be restored. By default, we don't set any default and allow backend to decide about defaults. And to prevent resets back to `null` value, we have suppress diff function attached to that field: https://github.com/databricks/terraform-provider-databricks/blob/master/clusters/clusters_api.go#L425

it could be more an issue with docs, that says that default value is `NONE`, but terraform provider doesn't set it explicitly.

**Comment by thaiphv** [comment]
Hi @alexott, thanks for explaining the issue.
