### ISSUE TITLE
Issue with azure_databricks_cmk

### ISSUE THREAD

**Issue by aparna-reji** [databricks/terraform-provider-databricks#2464]
Hi Team, 

While trying to modify my databricks workspace (re-deploying via Terraform) with additional CMK’s (for DBFS and disk), I am hitting the below error :

╷
│ Error: updating Workspace (Subscription: 'XXXXXXXXXXXXXXXX'
│ Resource Group Name: 'XXXX-rg'
│ Workspace Name: 'XXXXXXX-databricks') Tags: performing Update: unexpected status 400 with error: ApplicationUpdateFail: Failed to update application: 'XXXXXXXX-databricks', because patch resource group failure.

The resource group mentioned in the error is resource group where the workspace is deployed . 
I have found  similar issue here : https://github.com/Azure/azure-cli/issues/22614 , but cannot find what is the fix applied. 

When checked with Microsoft, they confirmed, as the issue occurs before the resources are being deployed indicates that the issue does not occur at the resource provision step and therefore is not related to either Azure or Databricks. 

Can someone please let me know if there are some known fixes I can try from my end.

**Comment by alexott** [comment]
Azure databricks workspaces are created with `azurerm` provider, not with databricks provider. Please open issue in the corresponding [github repository](https://github.com/hashicorp/terraform-provider-azurerm)
