### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource

### ISSUE THREAD

**Issue by chandanparihar1986** [databricks/terraform-provider-databricks#2469]
### Configuration
```hcl
# Copy-paste your Terraform configuration here
Reference link - https://docs.databricks.com/dev-tools/terraform/tutorial-aws.html
terraform apply -var-file="tutorial.tfvars"
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.20.0"
    }
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

I tried multiple AWS versions including 3.49.0

```

### Expected Behavior

The steps given on the below web page should help provision both AWS and Databricks resources without any further adjustment. I'm using a service principal for authentication (generated client secret and client id as instructed)
https://docs.databricks.com/dev-tools/terraform/tutorial-aws.html

### Actual Behavior

With this link, the 'terraform apply' manages to create AWS resources but it fails to create Databricks resources i.e. workspace, credentials, storage, etc. It takes a long time to create AWS resources e.g. VPC, NAT, Routing tables, etc and eventually fails with the below error messages.
╷
│ Error: cannot create mws credentials: default auth: oauth-m2m: oidc: parse .well-known: invalid character '<' looking for beginning of value. Config: host=https://accounts.cloud.databricks.com, client_id=<client_id>, client_secret=***
│ 
│   with databricks_mws_credentials.this,
│   on cross-account-role.tf line 36, in resource "databricks_mws_credentials" "this":
│   36: resource "databricks_mws_credentials" "this" {
│ 
╵
╷
│ Error: cannot create mws storage configurations: default auth: oauth-m2m: oidc: parse .well-known: invalid character '<' looking for beginning of value. Config: host=https://accounts.cloud.databricks.com, client_id=<client_id>, client_secret=***
│ 
│   with databricks_mws_storage_configurations.this,
│   on root-bucket.tf line 39, in resource "databricks_mws_storage_configurations" "this":
│   39: resource "databricks_mws_storage_configurations" "this" {
│ 
╵
╷
│ Error: cannot create mws networks: default auth: oauth-m2m: oidc: parse .well-known: invalid character '<' looking for beginning of value. Config: host=https://accounts.cloud.databricks.com, client_id=<client_id>, client_secret=***

### Steps to Reproduce

Not sure if this can be reproduced as I'm pretty much doing what is given on the Databricks web page and I believe this would be a standard solution to provision the Databricks workspace using Terraform. However, in our case, our Databricks account is SSO enabled with Okta and by looking at the error message, it looks like Terraform is having trouble authenticating Databricks (i.e. oauth-m2m).

Apart from the service principal as instructed in the document, I also tried supplying the client-id and client-secret from Okta app (i.e. Databricks Account Administration) but encountered the same issue.

terraform apply -var-file="tutorial.tfvars"

### Terraform and provider versions

terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.20.0"
    }
    aws = {
      source = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

I tried multiple AWS versions including 3.49.0

**Comment by patrickwilliamconway** [comment]
I think this issue might be the same? https://github.com/databricks/terraform-provider-databricks/issues/2377
