### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster_policy` resource

### ISSUE THREAD

**Issue by dichico** [databricks/terraform-provider-databricks#2522]
### Configuration
```hcl
resource "databricks_cluster_policy" "demand_forecast_policy" {
  name       = "Demand Forecast Job Cluster Policy"
  definition = jsonencode(local.demandforecast_policy)
}
```

### Expected Behavior
Creates the cluster policy using the JSON in the local variable.

### Actual Behavior
It shows an expired token for JWT.
```
Error: cannot create cluster policy: Error while parsing token: io.jsonwebtoken.ExpiredJwtException: JWT expired at 2023-03-02T21:43:10Z. Current time: 2023-07-27T15:45:29Z, a difference of 12679339053 milliseconds.  Allowed clock skew: 0 milliseconds
│ 
│   with databricks_cluster_policy.demand_forecast_policy,
│   on Databricks_ClusterPolicies.tf line 65, in resource "databricks_cluster_policy" "demand_forecast_policy":
│   65: resource "databricks_cluster_policy" "demand_forecast_policy" {
```

### Steps to Reproduce

1. `terraform apply`

### Terraform and provider versions

```
Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.21.0
+ provider registry.terraform.io/hashicorp/azurerm v3.66.0
```

**Comment by mgyucht** [comment]
This is not a problem with cluster policy but with unified auth. Can you take a look at our authentication guide? https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication

**Comment by dichico** [comment]
I'm going to review our authentication process, and check if the error was related to that.
Thank you for your help either way.

**Comment by dichico** [comment]
The solution worked.

Thank you for your help.
