### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource: cannot add `notification_settings` to a task

### ISSUE THREAD

**Issue by junwei-db** [databricks/terraform-provider-databricks#2524]
### Configuration
```hcl
 resource "databricks_job" "daily_worker" {
    task {
        email_notifications: {
          on_failure: "junwei.zhang@databricks.com",
        },
        notification_settings: {
          no_alert_for_skipped_runs: true,
          no_alert_for_canceled_runs: true,
        },
    }
}
    
```

### Expected Behavior
Deployment successful. It's documented here that `notification_settings` is supported within a `task` block:
<img width="673" alt="Screenshot 2023-07-27 at 5 24 31 PM" src="https://github.com/databricks/terraform-provider-databricks/assets/131705892/b20f5d12-55a1-4198-875e-e8bde544c957">

### Actual Behavior
Deployment failed because `notification_settings` is not supported. From https://src.dev.databricks.com/databricks/terraform-provider-databricks/-/blob/jobs/resource_job.go?L172, it doesn't seem `notification_settings` is part of job task settings. 

[Databricks API](https://docs.databricks.com/api/workspace/jobs/create) does support `notification_settings` for each task.

### Terraform and provider versions
1.21.0

**Comment by alexott** [comment]
it's a doc error, being fixed in #2496
