### ISSUE TITLE
[ISSUE] Issue with `databricks_service_principal` resource

### ISSUE THREAD

**Issue by TobyPopeBG** [databricks/terraform-provider-databricks#2525]
### Configuration
```hcl
resource "databricks_service_principal" "databricksServicePrincipal" {
  display_name               = var.displayName
  application_id             = var.applicationId
  allow_cluster_create       = true
  allow_instance_pool_create = true
  databricks_sql_access      = true
  workspace_access           = true
  active                     = true

  provider = databricks.account
}
```

### Expected Behavior
When creating this resource, the entitlements (e.g. `allow_cluster_create = true`) should be reflected in the workspace UI.

### Actual Behavior
Entitlements show as not being set.

<img width="247" alt="image" src="https://github.com/databricks/terraform-provider-databricks/assets/72386992/ee9c0382-5a71-49c8-8773-3643b4cdcd84">

### Steps to Reproduce
1. Run a plan/apply with the entitlements set to true

### Terraform and provider versions
```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.21.0
+ provider registry.terraform.io/hashicorp/azuread v2.39.0
+ provider registry.terraform.io/hashicorp/azurerm v3.65.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
```

### Debug Output
N/A

### Important Factoids
We are using Azure Databricks

**Comment by alexott** [comment]
it looks like you're trying to do that on the account level, while these are workspace-level entitlements. You need to use [databricks_entitlements](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/entitlements) resource after you assign service principal to a specific workspace.
