### ISSUE TITLE
[ISSUE] Issue with Folder deletion scenario 

### ISSUE THREAD

**Issue by WAG10** [databricks/terraform-provider-databricks#2554]
### Configuration
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
      version = "1.21.0"
    }
  }
}

### Expected Behavior
Folder should get deleted on terraform apply to secondary databricks

### Actual Behavior
Folder deletion in failing with error " Error : cannot delete directory: Folder (/Users/username/foldername) is not empty"

### Steps to Reproduce
- Create a folder inside workspace >> User 
- Create some notebook inside the folder
- Run terraform databricks exporter to export the configuration 
 ./terraform-provider-databricks_v1.21.0 exporter -skip-interactive     -services=notebooks  -listing=notebooks      -debug

- With this notebooks.tf file along with notebooks folder structure gets created.
- now switch the profile to secondary databricks and run terraform plan ad apply. This will create the folder and notebook under that user in secondary databricks
- Navigate to primary databricks again and delete the folder created in step2. Please note that with this the notebook too inside the folder gets deleted.
- clean the previous export files and again export the configuration. Now we can see the folder is not here in configuration since it was deleted.
- Now again switch to secondary databricks profile and run terraform plan. This will show that the folder and the notebook will be deleted as expected
- Run terraform apply. This will throw error that cannot deleted the folder since it is not empty.
**Error : cannot delete directory: Folder (/Users/username/foldername) is not empty**
- Expectation is that the folder should get deleted since this is a normal scenario where user deleted a non empty folder that that has to be replicated to secondary databricks. Kindly help.

### Terraform and provider versions
$ terraform version
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/databricks/databricks v1.21.0

**Comment by umakann-db** [comment]
Please try the latest version of the provider. I just tested with the latest master and I see its working.
