### ISSUE TITLE
[ISSUE] Issue with `databricks_grants` resource: Delta Sharing share grants destruction/creation triggers on every apply

### ISSUE THREAD

**Issue by owlleg6** [databricks/terraform-provider-databricks#2556]
Hello guys, i have an issue with using `databricks_grants` to assign "SELECT" on Delta Share to Delta Sharing Recipient. Grants resources triggers on every apply after it's creation. There is no configuration changes in grants assignment at all.

### Configuration
```hcl
# Copy-paste your Terraform configuration here
variable "recipients" {
  type = list(object({
    name                               = string
    authentication_type                = string
    comment                            = optional(string)
    data_recipient_global_metastore_id = optional(string)
    ip_access_list                     = optional(list(string))
  }))
  description = "List of objects"
  default     = [
  {
    name                               = "databricks-to-databricks"
    comment                            = "terraform managed"
    authentication_type                = "DATABRICKS"
    data_recipient_global_metastore_id = "gcp:europe-west3:UUID"
  },
  {
    name                               = "external-token"
    comment                            = "terraform managed"
    authentication_type                = "TOKEN"
    ip_access_list =  ["0.0.0.0/0"]
  }
]
}

locals {
  recipients_mapped = { for i in var.recipients : i.name => i }
}

resource "databricks_share" "this" {
  name = "demo-name"
}

resource "databricks_recipient" "this" {
  for_each = local.recipients_mapped

  name                               = each.value.name
  comment                            = coalesce(each.value.comment, "Terraform managed")
  authentication_type                = each.value.authentication_type
  data_recipient_global_metastore_id = lookup(each.value, "data_recipient_global_metastore_id")

  dynamic "ip_access_list" {
    for_each = each.value.authentication_type == "TOKEN" ? [1] : []
    content {
      allowed_ip_addresses = each.value.ip_access_list
    }
  }
}

resource "databricks_grants" "this" {
  for_each = local.recipients_mapped

  share = databricks_share.this.name
  grant {
    principal  = databricks_recipient.this[each.value.name].name
    privileges = ["SELECT"]
  }
}
```

### Expected Behavior

No changes in configuration
### Actual Behavior

1. Changes on first plan after creation:
<img width="1265" alt="image" src="https://github.com/databricks/terraform-provider-databricks/assets/3865349/e414e782-1c16-4312-bc85-574c2811d884">

2. After plan applied, got an error:
<img width="1364" alt="image" src="https://github.com/databricks/terraform-provider-databricks/assets/3865349/437fde29-3f75-426f-8c88-425c2a1aa599">

3. Plan after an error above:
<img width="1197" alt="image" src="https://github.com/databricks/terraform-provider-databricks/assets/3865349/cdcc62f3-e181-40fa-a390-13957bfc675c">

4. After plan with creation applied, grants are successfully created, however cycle with "deletion -> error -> creation" stars from beginning.

### Terraform and provider versions

Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.21.0
+ provider registry.terraform.io/hashicorp/azurerm v3.62.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

**Comment by owlleg6** [comment]
@nkvuong right, looks like I should iterate within dynamic block instead of grants resource. One share - one grants resource for it.

**Comment by owlleg6** [comment]
In addition, I would like to ask if it is possible to provide an ability to assign owners to deltas shares and delta recipients with terraform?

**Comment by nkvuong** [comment]
@owlleg6 - we need to add that as a parameter for `databricks_share` or `databricks_recipient` resource - could you file a separate feature request and we'll add it to our backlog?

**Comment by owlleg6** [comment]
Sure, i will. We can close this ticket. Thanks!
