### ISSUE TITLE
[FEATURE] Add Lakehouse Federation Resources

### ISSUE THREAD

**Issue by adam133** [databricks/terraform-provider-databricks#2575]
### Use-cases
Create the resources described [here](https://docs.databricks.com/en/query-federation/index.html#) using the terraform provider.

### Attempted Solutions

These resources do not seem to exist yet, or it is not documented.

### Proposal

Add the resources for Lakehouse Query Federation, or implement them into existing resources and document the solution.

### References
N/A

**Comment by nkvuong** [comment]
Open PR to add support - #2528

**Comment by adam133** [comment]
> Open PR to add support - #2528

Oh nice! Searched the issues but didn't look at open PRs.
