### ISSUE TITLE
[ISSUE] `azure-cli` authentication works incorrectly after upgrade to Go SDK

### ISSUE THREAD

**Issue by alexott** [databricks/terraform-provider-databricks#2590]
`azure-cli` authentication method in Go SDK works differently compared to the original implementation. It works only when a user is already a part of the workspace, but fails when a user is a Contributor to the workspace, but not inside yet. 

The reason for it is that Go SDK's `azure-cli` authentication method generates only `Authorization` header with AAD token for `2ff814a6-3304-4ab8-85cb-cd0e6f879c1d`, but not adding additional headers like it was done in the [version before Go SDK introduction](https://github.com/databricks/terraform-provider-databricks/blob/v1.9.2/common/azure_auth.go#L168).

### Configuration

```hcl
provider "databricks" {
  host = "https://adb-.....azuredatabricks.net"
  azure_workspace_resource_id = "/subscriptions/...."
}

data "databricks_current_user" "me" {}

output "me" {
  value = data.databricks_current_user.me
}
```

### Expected Behavior

User having a Contributor role should be able to perform operations.

### Actual Behavior

user gets:

```
│ Error: User not authorized
│
│   with data.databricks_current_user.me,
│   on main.tf line 15, in data "databricks_current_user" "me":
│   15: data "databricks_current_user" "me" {}
```

### Terraform and provider versions

* 1.23.0 doesn't work
* 1.9.2 works (latest before Go SDK upgrade)

**Comment by mgyucht** [comment]
This is merged in #2599 and will be released in the next release of the TF provider, scheduled for later this week.
