### ISSUE TITLE
[ISSUE] Issue with `data.databricks_cluster_policy` resource

### ISSUE THREAD

**Issue by tguegan** [databricks/terraform-provider-databricks#2598]
### Configuration
```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "=1.23.0"
    }
  }
}

provider "databricks" {
  host                        = var.db_host
  azure_workspace_resource_id = var.db_id
  azure_client_id             = var.client_id
  azure_client_secret         = var.client_secret
  azure_tenant_id             = var.tenant_id
}

data "databricks_cluster_policy" "personal" {
  name = "Personal Compute"
}

output "policy_id" {
  value = data.databricks_cluster_policy.personal.id
}
```

### Expected Behavior
Output cluster policy id

### Actual Behavior
Throwing error
```
│ Error: cannot read data cluster policy: Invalid resource ID
│
│   with data.databricks_cluster_policy.personal,
│   on test.tf line 18, in data "databricks_cluster_policy" "personal":
│   18: data "databricks_cluster_policy" "personal" {
```

### Steps to Reproduce
1. Create an Azure application
2. Add this service principal on the metastore then assign it on the workspace with admin privilege
3. terraform plan -var-file .\test_env.tfvars

### Terraform and provider versions
Terraform: 1.5.5
Provider: 1.23.0

### Debug Output
[https://gist.github.com/tguegan/f0d445ebb2b8a338178b50e32028e4d3](https://gist.github.com/tguegan/f0d445ebb2b8a338178b50e32028e4d3)

### Important Factoids
I thought that was related with a permission issue on the policy (even if the SPN has admin right, who knows) but after granting "use" permission to the SPN I've got the same error.

**!!! It works when using PAT auth !!!:**
```hcl
provider "databricks" {
  host   = var.db_host
  token = "XXXXXXXXXXXXXXXXX"
}
```

So, it must be related to some configuration with my service principal then. But the SPN has admin right on the workspace from the account level:
![Account level permission](https://github.com/databricks/terraform-provider-databricks/assets/22313632/04dd716d-c65d-4090-9c7e-11e6f186aba0)

And even "use" permission on the policy:
![image](https://github.com/databricks/terraform-provider-databricks/assets/22313632/e95b136d-c0f4-4722-a282-daa83abfe9dc)

**Comment by tguegan** [comment]
After further investiguation I thought about looking at cluster policies using Databricks CLI with service principal auth and I can access policys without trouble:

```sh
➜  DB_CLI ./databricks current-user me -p SPN
{
  "active":true,
  "displayName":"MySPN",
  "emails": [
    {
      "primary":true,
      "type":"work",
      "value":"xxxxxxxxxxxxxxxxx"
    }
  ],
  "entitlements": [
    {
      "value":"workspace-access"
    }
  ],
  "externalId":"xxxxxxxxxxxxxxxxx",
  "groups": [
    {
      "display":"admins",
      "$ref":"Groups/237529223374597",
      "type":"direct",
      "value":"237529223374597"
    }
  ],
  "id":"2111650687509627",
  "name": {
    "givenName":"MySPN"
  },
  "userName":"xxxxxxxxxxxxxxxxx"
}
```

And policies:

```sh
➜  DB_CLI ./databricks cluster-policies list -p ADO
XXXX XXXXX
E963C085DA000629  Personal Compute
...
```

If you need any futher informations do not hesitate! Thank you 👍

**Comment by tguegan** [comment]
# Workaround

Instead of using direct service principal authentification with client_id, client_secret, etc. the idea is to generate a bearer token on the behalf of the service principal and use it.

- For Azure: [https://learn.microsoft.com/en-us/azure/databricks/administration-guide/users-groups/service-principals#--manage-tokens-for-a-service-principal](https://learn.microsoft.com/en-us/azure/databricks/administration-guide/users-groups/service-principals#--manage-tokens-for-a-service-principal)
  - Then call this API endpoint: [https://docs.databricks.com/api/workspace/tokens/create](https://docs.databricks.com/api/workspace/tokens/create) using the AD token generated from previous step
- For AWS: [https://docs.databricks.com/en/administration-guide/users-groups/service-principals.html#manage-personal-access-tokens-for-a-service-principal](https://docs.databricks.com/en/administration-guide/users-groups/service-principals.html#manage-personal-access-tokens-for-a-service-principal)
  - Then use the new API endpoint: [https://docs.databricks.com/api/workspace/tokenmanagement/createobotoken](https://docs.databricks.com/api/workspace/tokenmanagement/createobotoken) (not available on Azure, the call raise an "On-behalf-of token creation for service principals is not enabled for this workspace" error)

Regards

**Comment by tguegan** [comment]
@nkvuong Indeed I specify the Databricks workspace ID after the "/?o=" from the Databricks workspace URL.

The Databricks workspace itself is not managed by Terraform.

**Comment by nkvuong** [comment]
@tguegan that's the issue - the resource ID includes subscription id, rg name & workspace name. If the workspace is not managed by Terraform, you can read them using the corresponding [data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/databricks_workspace) from azurerm provider

the resource ID is of the format
`/subscriptions/<subscription_id>/resourceGroups/<rg_name>/providers/Microsoft.Databricks/workspaces/<workspace_name>`

**Comment by tguegan** [comment]
Hello @nkvuong, indeed you are right. I am surprised that was the issue because everything else (beside the policy ID thing) was working with a wrong resource ID 🤨

Anyway, thank you and sorry for the inconvenience.
