### ISSUE TITLE
[ISSUE] `TF_LOG=DEBUG` does not show API calls

### ISSUE THREAD

**Issue by nkvuong** [databricks/terraform-provider-databricks#2602]
`TF_LOG=DEBUG terraform apply -no-color` used to show API calls with request & response, but this has stopped showing in debug logs. This regression likely happened after upgrade to SDK

Example - https://gist.github.com/tguegan/f0d445ebb2b8a338178b50e32028e4d3

**Comment by alexott** [comment]
Fixed in 1.29.0
