### ISSUE TITLE
[DOC] Missing parameters in `databricks_workspace_conf` Resource `custom_config` argument

### ISSUE THREAD

**Issue by ehab-eb** [databricks/terraform-provider-databricks#2609]
### Affected Resource(s)

https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/workspace_conf#custom_config

### Expected Details

There is no comprehensive list of all options that can be used/set. I'm struggling to find any Databricks docs on it either. 

I was under the impression that the [example usage list](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/workspace_conf#example-usage) was comprehensive until I came across the [databricks/terraform-databricks-sra](https://github.com/databricks/terraform-databricks-sra/blob/main/aws/tf/modules/sra/databricks/admin_configuration/admin_configuration.tf) repo

I'm happy to help out with a PR if I can be pointed to somewhere that shows all paramters.

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Add known `custom_config` parameters

**Comment by fjakobs** [comment]
Thanks for reporting this issue.

The values of the workspace conf API are not guaranteed to be stable yet. We are working on a new workspace conf API, which will expose all settings but until then I don't expect the docs to change.
