### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_visualization` resource

### ISSUE THREAD

**Issue by eczerwin** [databricks/terraform-provider-databricks#2619]
<!--
Hi all,

 When we add a description into a visualization in Terraform this does not carry over as a description on the actual visualization.  When it is set manually in the workspace it works.

### Configuration
`
resource "databricks_sql_visualization" "q1v2" {
  query_id    = databricks_sql_query.q1.id
  type        = "chart"
  name        = "YieldLossTF"
  description = "Shows the yield loss [%] per hour of operation."
  options     = file("${path.module}/visualizations/q1v2.json")
  query_plan = jsonencode(
    {`
# Copy-paste your Terraform configuration here
```

### Expected Behavior
descriptions should appear under NAME

### Actual Behavior
no descriptions are visible


### Terraform and provider versions

Terraform 1.5.6
Finding latest version of hashicorp/azurerm...
- Finding latest version of databricks/databricks...
- Installing databricks/databricks v1.23.0...
- Installed databricks/databricks v1.23.0 (self-signed, key ID 92A95A66446BCE3F)
- Installing hashicorp/azurerm v3.69.0...
- Installed hashicorp/azurerm v3.69.0 (signed by HashiCorp)

**Comment by mgyucht** [comment]
Please follow the issue template. Closing this out for now.
