### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource "cannot remove new catalog default schema"

### ISSUE THREAD

**Issue by adam133** [databricks/terraform-provider-databricks#2621]
### Configuration
```hcl
resource "databricks_connection" "mysql" {
  name            = "mysql"
  connection_type = "MYSQL"
  comment         = "This is a connection to mysql database"
  options = {
    host     = "prod-db.com"
    port     = "3306"
    user     = "username"
    password = "password"
  }
}

resource "databricks_catalog" "mysql" {
  metastore_id = "some id"
  name         = "mysql"
  comment      = "this catalog is managed by terraform"
  connection_name = databricks_connection.mysql.name
}
```

### Expected Behavior
Foreign mysql catalog is created without error.

### Actual Behavior
`Error: cannot create catalog: cannot remove new catalog default schema: Schema 'mysql.default' does not exist.`
Error occurs during creation, although the resource is correctly created in databricks.

### Steps to Reproduce
terraform apply the above catalog/connection.

### Terraform and provider versions
Terraform v1.5.1
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.24.0
+ provider registry.terraform.io/hashicorp/aws v5.14.0

### Debug Output
│ Error: cannot create catalog: cannot remove new catalog default schema: Schema 'mysql.default' does not exist.
│ 
│   with databricks_catalog.mysql[0],
│   on federation.tf line 19, in resource "databricks_catalog" "mysql":
│   19: resource "databricks_catalog" "mysql_prod" {

### Important Factoids
Looks like this is happening because it's checking for a ShareName, where if it doesn't exist, delete the default schema. 
https://github.com/databricks/terraform-provider-databricks/blob/b52c2645bd6b8ce83bb1584feb9220386d68db79/catalog/resource_catalog.go#L68 
This check for ShareName should probably also exclude Foreign Catalogs.

I'll go ahead and propose a PR to resolve this.

**Comment by adam133** [comment]
PR should be ready to merge once I get the right person's approval.

**Comment by tanmay-db** [comment]
Thanks for the PR, it has been merged, we will do a release in few days.
