### ISSUE TITLE
[ISSUE] Creating storage credentials failing on GCP

### ISSUE THREAD

**Issue by nkvuong** [databricks/terraform-provider-databricks#2628]
### Configuration
```hcl
resource "databricks_storage_credential" "sc" {
    provider = databricks.accounts
    metastore_id = var.metastore_id
    name = "databricks-unity-catalog-test"
    databricks_gcp_service_account {}
}
```

### Expected Behavior
Storage credential is created

### Actual Behavior
`Error: cannot create storage credential: Unrecognized credential_secret type`

This issue also impacts `databricks_metastore_data_access` as both are using the same underlying APIs

### Terraform and provider versions
Provider version 1.24.1

### Debug Output
The SDK does not send the empty `databricks_gcp_service_account {}` struct to the server per [the spec](https://docs.databricks.com/api/gcp/account/accountstoragecredentials/create). This throws an error

**Comment by mgyucht** [comment]
This is an SDK problem that impacts all upstream consumers like TF. I'll file a ticket on Go SDK and link to this one.

**Comment by jonasmw94** [comment]
We're facing the same issue when trying to provision `databricks_metastore_data_access`. We have the following tf-code

```hcl
resource "databricks_metastore" "this" {
  provider      = databricks.accounts
  name          = "${local.metastore_name_prefix}-${var.env}"
  storage_root  = "gs://${gs_metastore_location}/metastore"
  owner         = var.deploy_service_account
  region        = var.databricks_ws_region
  force_destroy = true
}

resource "databricks_metastore_data_access" "this" {
  provider     = databricks.accounts
  metastore_id = databricks_metastore.this.id
  name         = "metastore-sa-${var.env}"
  databricks_gcp_service_account {}
  is_default = true
}
```

Are these issues related or should I submit a new issue?

**Comment by jonasmw94** [comment]
@mgyucht Do you have a link to the ticker, so I can follow its progress?

**Comment by mgyucht** [comment]
Looking a bit closer: @nkvuong: I am actually not sure this is an issue in the Go SDK. If we set `databricks_gcp_service_account` to any non-nil value (including an empty struct), it should work. We may need some special case handling in the create/update methods of this resource to support this, but I think it should still work without change to the Go SDK. One thing I noticed is that the corresponding field is marked as `tf:"computed"`, which may not be correct in this case.

**Comment by nkvuong** [comment]
@mgyucht the API behaviour is very specific here:
- You need to send an empty struct called `databricks_gcp_service_account` in the create request
- The struct will then be filled with `email` and `credential_id` by the UC server
- This is not updateable

**Comment by jonasmw94** [comment]
Is possible to get a guesstimate when this issue will be resolved?

**Comment by shane-atg** [comment]
I have been banging my head on this issue for 2 days.  Please get it fixed!  Unity catalogs can no longer be deployed via terraform.

**Comment by mgyucht** [comment]
Sorry about the delays here folks. I understand this is blocking you from using Unity Catalog in Terraform, and I'm going to work with @nkvuong on the appropriate fix over the next week or so.

**Comment by jonasmw94** [comment]
Thank you!

**Comment by clementboscoa** [comment]
Hi, we are touched here as well at L'Oréal. Very blocking point. Thanks

**Comment by jonasmw94** [comment]
@nkvuong @tammyma-db  I still get the same error as before, using the same terraform code posted here earlier. I'm using version 1.26.0 of the provider. What could be the issue?

**Comment by alexott** [comment]
@jonasmw94 it's not released yet. you can build from the `master` branch.

**Comment by jonasmw94** [comment]
I see. Thank you!
