### ISSUE TITLE
Support partitions and clustering on tables for Unity Catalog Terraform

### ISSUE THREAD

**Issue by shubhamnautiyal6894** [databricks/terraform-provider-databricks#2639]
The databricks_sql_table resource in Terraform doesn't support either partitioning or liquid clustering. For liquid clustering, this means any table created with Terraform can never be clustered. 
So there should be some support around one or both of these options.

https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_table

**Comment by alexott** [comment]
Fixed by #2789
