### ISSUE TITLE
[ISSUE] Issue with `databricks_job` resource and `run_job_task` `task` block

### ISSUE THREAD

**Issue by ryan-daly-AgFCS** [databricks/terraform-provider-databricks#2643]
### Configuration
Boiler plate configuration provided below for example due to restrictions of internal code sharing.

```hcl
data "aws_iam_instance_profile" "job_cluster" {
  name = "job_cluster_profile"
}

resource "databricks_job" "child" {
  name = "child"

  job_cluster {
    job_cluster_key = "job_cluster"
    new_cluster {
      ## ....
    }
    task {
      task_key = "task"
      job_cluster_key = "job_cluster"
      notebook_task {
        notebook_path = "/notebook"
         base_parameters = {
             "param1" = "<default>"
             "param2" = "<default>"
         }
      }
    }
  }
}

resource "databricks_job" "parent" {
  name = "parent"

  task {
    task_key = "parent"

    run_job_task {
      job_id = databricks_job.child.id
      job_parameters = {
          "param1" = "A"
          "param2" = "B"
      }
    }
  }
}
```

### Expected Behavior
Terraform Apply should apply job_parameters to the Databricks Run Job Task.

### Actual Behavior
No errors are present in logs. Terraform Plan and Apply functions as expected. Terraform Apply creates job with default parameters, however the `run_job_task` doesn't have parameters applied. Databricks job with Run Job Task shows default parameters instead. Databricks json of job's run job task doesn't show parameters applied. Manually changing of parameters in job will yield different json body of `notebook_params` instead of Terraform provider's documented `job_parameters` block.

### Steps to Reproduce

1. `terraform apply`
2. Review of Databricks job shows default parameters within `Run Job Task`
3. Change of job parameters will yield new block in Databricks json labeled `notebook_params`

### Terraform and provider versions
Terraform: 1.5.6
Databricks: 1.24.0

### Debug Output
Will provide log if absolutely required, however no errors are present and Terraform Plans and Applies as expected.

**Comment by ryan-daly-AgFCS** [comment]
The Databricks Jobs 2.1 API appears to only support providing a `job_id` required parameter. Is this a limitation of the API?

![image](https://github.com/databricks/terraform-provider-databricks/assets/55713746/ac1c33cc-536a-47b7-9eb6-35ee3f8d4c18)

**Comment by ryan-daly-AgFCS** [comment]
Any thoughts on why the `job_parameters` aren't mapping forward, or is it a feature gap between the databricks api?

[run_job_task-configuration-block](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#run_job_task-configuration-block)

**Comment by TakumiHaruta** [comment]
The same issue here. 

I looked at the Go SDK for databricks, and the type of `job_parameters` seems different;

https://github.com/databricks/databricks-sdk-go/blob/main/service/jobs/model.go#L84

```
	JobParameters []JobParameter `json:"job_parameters,omitempty"`
```

```
type JobParameter struct {
	// The optional default value of the parameter
	Default string `json:"default,omitempty"`
	// The name of the parameter
	Name string `json:"name,omitempty"`
	// The value used in the run
	Value string `json:"value,omitempty"`
}
```

But I've not confirmed this struct actually works

**Comment by ryan-daly-AgFCS** [comment]
> The same issue here.
> I looked at the Go SDK for databricks, and the type of `job_parameters` seems different;
> But I've not confirmed this struct actually works

It could also be on the Go/Terraform side of things, but I'm thinking the Databricks Jobs 2.1 API doesn't support this. So the Go/Terraform commands could be sending extra parameters, and the Jobs 2.1 API is ignoring the commands.

**Comment by ryan-daly-AgFCS** [comment]
Closing this issue. The parameters started working sometime in Dec/Jan, around version 1.1.32. I'm unaware of when exactly this was resolved, as we revisited the project and found parameters to be working when we reintroduced the code to the TF files.
