### ISSUE TITLE
Cluster library removal scenario failing 

### ISSUE THREAD

**Issue by WAG10** [databricks/terraform-provider-databricks#2656]
### Configuration
terraform {
required_providers {
databricks = {
source = "databricks/databricks"
version = "1.21.0"
}
}
}

### Expected Behavior
Cluster library should get removed after cluster export and import. 

### Actual Behavior
Cluster library not getting removed after cluster export and import. 

### Steps to Reproduce

1. Create a cluster in primary databricks
2. Goto cluster >> Libraries >> Install now, And then install some libraries(eg azure == 4.0.0, adal) and wait for that to finish
3. Run the terraform exported to export the cluster.
4. Run terraform plan and apply to import the cluster to secondary workspace
5. Now come back to primary cluster and delete one of the library which was added in step 2
6. Run terraform export and import for the clsuter.
7. Cluster library is not getting deleted form the secondary after import
8. It is expected that clsuter library should get deleted after the import as it is not there in cluster any more in primary workspace

### Terraform and provider versions
$ terraform version
Terraform v1.1.7
on windows_amd64

provider registry.terraform.io/databricks/databricks v1.21.0

**Comment by alexott** [comment]
Next release of TF provider will generate libraries differently, so this won't be an issue anymore
