### ISSUE TITLE
Default name databricks notebooks not getting exported 

### ISSUE THREAD

**Issue by WAG10** [databricks/terraform-provider-databricks#2661]
### Configuration
terraform {
required_providers {
databricks = {
source = "databricks/databricks"
version = "1.21.0"
}
}
}

### Expected Behavior
Databricks notebooks with default name(eg **Untitled Notebook 2023-09-07 19:20:51**) should get exported.

### Actual Behavior
Databricks notebooks with default name(eg Untitled Notebook <timestamp>) not getting exported.

### Steps to Reproduce
1. Navigate to workspace >>add >> notebook and create notebook. Add some sample python code in that.
2. Please note that the name will be in format Untitled Notebook <timestamp>
3. Run the terraform exporter to export the notebooks
4. It is seen that notebooks with the default names are not getting exported

### Terraform and provider versions
$ terraform version
Terraform v1.1.7
on windows_amd64

provider registry.terraform.io/databricks/databricks v1.21.0

**Comment by WAG10** [comment]
Hi @alexott , Thanks for looking. Unfortunately issue still persists
terraform importer version used :  **1.25.0** (as per docs)
Notebook name : **Untitled Notebook 2023-09-12 12:47:14** 
Requesting you to kindly have notebook with this sort of name and try

**Comment by alexott** [comment]
provide logs, there should be some errors reported or something like that - it works on Mac just fine. I suspect that it could be file naming issue on Windows

**Comment by WAG10** [comment]
Hi @alexott , Scanned logs , there are no visible errors and mention of that notebook at all. Can u plz try with the name which i suggested?
The ones which you tried still seems custom name.

**Comment by alexott** [comment]
No, I tested with default name. Please try to run this on Linux or Mac OS to check if this issue is specific to Windows
