### ISSUE TITLE
[ISSUE] Issue with `databricks_volume` resource: External volume storage location change not reflected

### ISSUE THREAD

**Issue by bloewes** [databricks/terraform-provider-databricks#2692]
### Configuration
```hcl
resource "databricks_volume" "volume" {
  catalog_name     = "foo"
  schema_name      = "bar"
  name             = "baz"
  volume_type      = "EXTERNAL"
  storage_location = "${databricks_external_location.loc[container].url}${local.volume_suffix}"
  comment          = "Managed by Terraform"
}
```

I initially created the volume with storage location only pointing to external location url, meaning `locals.volume_suffix = ""` .

### Expected Behavior

If I in a later stage change `local.volume_suffix = "databricks_volume"`, I expect a change of the storage location.

### Actual Behavior

Plan shows the change
```hcl
# module.databricks.module.databricks_stable[0].databricks_volume.volume["stable-container-work"] will be updated in-place
  ~ resource "databricks_volume" "volume" {
        id               = "foo.bar"
        name             = "baz"
      ~ storage_location = "abfss://container@account.dfs.core.windows.net/" -> "abfss://container@account.dfs.core.windows.net/databricks_volume"
        # (5 unchanged attributes hidden)
    }
```

Apply gets also run, but the `storage_location` does not change. 
Only deletion and recreation of the volume allows me to change the `storage_location`.

### Terraform and provider versions

Terraform version: 1.5.7
Databricks provider version: 1.25.1

### Important Factoids

However, according to your own API this is not supposed to work:
![image](https://github.com/databricks/terraform-provider-databricks/assets/117997874/a616f5e4-c6f3-4e9c-ab9f-38852534c0dd)

**Comment by mgyucht** [comment]
To clarify, would you expect that `terraform plan` fails because you're trying to change an attribute that can't be modified?

**Comment by bloewes** [comment]
I would expect the plan to show 1 destroy and 1 create, because this attribute cannot be changed, so I'd expect a `tf:"force_new"` here: https://github.com/databricks/terraform-provider-databricks/blob/c0b8bc1ec68bf7ead0a14b5a6f3f7b4e4341a13a/catalog/resource_volume.go#L27C5-L27C5
