### ISSUE TITLE
[DOC] add an example of granting permissions to a service principal

### ISSUE THREAD

**Issue by tb-db** [databricks/terraform-provider-databricks#2702]
### Affected Resource(s)
[databricks_grants](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/grants)

### Expected Details
can we add an example of granting permissions to a service principal to the databricks_grants doc page? The page currently states "principal - User name, group name or service principal application ID". but it’s not clear what the syntax should be unless the viewer also pulls up the doc page for the SP resource.

### List of things to potentially add/remove:
add a new SP grant block to the existing example under schema grants:
```
resource "databricks_grants" "things" {
  schema = databricks_schema.things.id
  grant {
    principal  = "Data Engineers"
    privileges = ["USE_SCHEMA", "MODIFY"]
  }
 grant {
    principal  = data.databricks_service_principal.my_sp.application_id
    privileges = ["USE_SCHEMA", "MODIFY"]
  }
}
```

**Comment by mgyucht** [comment]
Thanks for reporting this @tb-db. Would you like to contribute this change? Those docs are defined in [docs/resources/grants.md](https://github.com/databricks/terraform-provider-databricks/blob/master/docs/resources/grants.md).
