### ISSUE TITLE
[FEATURE?] (Databricks.sql) Select `catalog` and `schema` for `sqlQuery` resource

### ISSUE THREAD

**Issue by WP-LKL** [databricks/terraform-provider-databricks#2708]
### Use-cases
We should be able to select catalog and schema for sqlQuery resource:
![image](https://github.com/databricks/terraform-provider-databricks/assets/15800648/37c4224b-07c6-4958-bac8-92ca49d5f16c)

```typescript
export const q1 = new databricks.SqlQuery("q1", {
  dataSourceId: sqlEndpoint.dataSourceId,
  query: "SELECT 1",
  runAsRole: "viewer",
  description: "Query 1",
  name: "q1",
  tags: [common.project, common.stack],
});
```

This may already be possible, but I haven't been able to see how.

### Attempted Solutions
Manually through the UI :)

### Proposal
Add this as an option, likely as the path.

### References
...

### Notes
I am using a downstream Pulumi provider for Databricks: https://www.pulumi.com/registry/packages/databricks/api-docs/sqlquery/

**Comment by alexott** [comment]
This is a pure UI feature, there is no support for it in the [API](https://docs.databricks.com/api/workspace/queries/create), and implementing it will require parsing of the SQL query that is outside of the scope of the provider.

You can always use locals in your query to achieve this:

```hcl
locals {
  catalog = "c"
  schema = "s"
}

...
query: "SELECT * from ${local.c}.${local.schema}.my_table",
...
```

**Comment by WP-LKL** [comment]
Thanks @alexott for the quick response and clarification. Will move forward with the full table path within the query X)
