### ISSUE TITLE
UC metastore admin should be able to change ownership of Catalog/Schema

### ISSUE THREAD

**Issue by steyler-db** [databricks/terraform-provider-databricks#2717]
### Affected Resource(s)

1. Create Catalog no owner with TF. means the creator is the owner
in my case: [username@domain.iam.gserviceaccount.com](mailto:username@domain.iam.gserviceaccount.com)
2. Changed the catalog owner to my username with TF
3. Changing catalog owner back to: [username@domain.iam.gserviceaccount.com](mailto:username@domain.iam.gserviceaccount.com) with TF
╷
│ Error: cannot update catalog: User is not an owner of Catalog 'tf_ctalogaka'.
│
│ with module.catalog_test_module["tf_ctalogaka"].databricks_catalog.cat,
│ on .terraform/modules/catalog_test_module/[catalogs.tf](https://catalogs.tf/) line 1, in resource "databricks_catalog" "cat":
│ 1: resource "databricks_catalog" "cat"
As the customer is doing the task in TF, however as the API says: *correctly* that Metastore admin should be able to do what we want to do (change owner) but it doesn't work ....
https://docs.databricks.com/api/gcp/workspace/catalogs/update
Customer is metastore admin: Updates the catalog that matches the supplied name. The caller must be either the owner of the catalog, or a metastore admin (when changing the owner field of the catalog).
But the path is not working, error is showing as the 3 bullet sent from customer.
 
![image](https://github.com/databricks/terraform-provider-databricks/assets/140017157/8241882b-f2c2-4106-b8b1-d72d6a8edd25)

![image](https://github.com/databricks/terraform-provider-databricks/assets/140017157/c5686194-71e7-4a00-818e-4fb296cf0ddd)

![image](https://github.com/databricks/terraform-provider-databricks/assets/140017157/58e8b672-1057-44ee-95b5-d3a0dac4a7e9)

#### Brief Summary
When customer applies the TF task, is when they received the error: Error: cannot update schema: User is not an owner of Schema '[prod.ms](http://prod.ms/)_ivt"
with module.schemas_prod_module("ms_ivt"].databricks_schema.dbx_schema,
on .terraform/modules/schenas_prod_nodule/schemas.tf line 1, in resource "databricks_schema" "ab_schema":
1: resource "databricks_schema* "dbx_schema"

### Expected Details

When customer tries to do this via terraform for a user that is a metastore admin he receives the error Error: cannot update schema: User is not an owner of Schema, this should work fine as user is a metastore admin

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] First item to change
       When customer tries to do this via terraform for a user that is a metastore admin he receives the error: Error: cannot update schema: User is not an owner of Schema
- [ ] Second item to change 

### References

SF ticket and slack thread is on the process internally

**Comment by adamcain-db** [comment]
The [UC change](https://github.com/databricks/universe/pull/431928) adding the `new_name` field to all UC Update* APIs and removing the problematic `name` fields from the payloads of UC Update* APIs that have conflicting `{name}` fields in the URI has merged.  That change should be included in the 12/8 UC release, to be deployed to prod 12/14-18.  To complete the fix, the DeCo folks will need to update the SDK(s) and Terraform Provider.

**Comment by alexott** [comment]
Fixed by #3029, released in 1.33.0
