### ISSUE TITLE
[FEATURE] `databricks_job` create similar `definition` argument as `databricks_cluster_policy`

### ISSUE THREAD

**Issue by michaeljmc** [databricks/terraform-provider-databricks#2720]
### Use-cases
migrating jobs between databricks workspaces.
with in the databricks workspace UI it is very easy to export a job definition from the view json option and then click create tab under view json and the create tab. 

### Attempted Solutions
these job definitions can use to create jobs with the databricks cli natively like so 
`databricks jobs create --json-file create-job.json`
it also looks pretty easy to use the databricks api with the json file 
https://docs.databricks.com/api/workspace/jobs/create
exporting from json and then converting to HCL for terraform is a little tedious as the job json files can be 100's of lines of json. 

### Proposal
Update the `databricks_job` resource to be able create jobs with similar `definition` argument as `databricks_cluster_policy`

```hcl
resource "databricks_job" "json_definition" { 
  name       = "${var.team} job"
  definition = jsonencode(merge(local.default_job, var.job_overrides))
}
```
proposed databricks_job resource code example above modified from original example found here for databricks_cluster_policy:
https://github.com/databricks/terraform-provider-databricks/blob/323ae445158d234ade811314c78344eb1fac5b4a/docs/resources/cluster_policy.md?plain=1#L54

This way if the Databricks jobs are in terraform they can be tracked for changes using it's native state capabilities. Terraform would be able to see job changes and life cycle jobs out if needed.
hopefully this is a simple and relatively easy ask.

**Comment by alexott** [comment]
This may not give you the desired result due complexity of mapping different pieces of JSON into internal structure and handling of dependencies. Have you looked into [exporter functionality](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/experimental-exporter)? The combination of `-listing jobs` + `-match <job-name>` will allow to export job together will all dependencies as HCL.

**Comment by michaeljmc** [comment]
hi, @alexott . I had not looked at the exporter before. That is really quite cool. I'm not entirely sure how it would scale with many devs to migrate their jobs between environments. The json method mentioned above seemed like a more scalable solution and easier to teach a self service method. This would not only likely provide a built in job provisioning capability but also provide job life cycle management capability. please continue to let me know your thoughts.

**Comment by alexott** [comment]
For the developer's self-service, I recommend looking at Databricks Asset Bundles.

But in general, it looks like a misunderstanding  - in cluster policies, the `definition` attribute is just a string, it's not magically decoded - all decoding happens on the backend side. You can implement a job module that will pick up data from JSON and use `dynamic`, `for_each`, etc. to build a job. But we won't do that in the Terraform provider.

**Comment by michaeljmc** [comment]
thank you @alexott . will look at the string method for the jobs with terraform, and databricks asset bundles.
