### ISSUE TITLE
[ISSUE] Issue with `databricks_job` task with multiple dependencies not possible

### ISSUE THREAD

**Issue by kai-carlisle** [databricks/terraform-provider-databricks#2722]
### Configuration
```hcl
task { 
   task_key = "ichi"
   job_cluster = "C64"
   notebook_task { 
      notebook_path = "REPO_NOTEBOOK"
      source = "GIT
   }
}

task { 
    task_key = "ni"
    job_cluster = "C64"
    notebook_task { 
        notebook_path = "REPO_NOTEBOOK"
        source = "GIT
   }
}
task { 
    task_key = "san"
    depends_on { 
       task_key = "ichi" ... but how make this dependant also from the "ni" task? 
    }
    job_cluster = "C64"
    notebook_task { 
       notebook_path = "REPO_NOTEBOOK"
       source = "GIT
    }
}
```

### Expected Behavior
The docs (subtly) suggest that it's possible to have a task with mutliple dependant tasks `[depends_on] - (Optional) block specifying dependency(-ies) for a given task.`, and it's certainly possible through the UI. But this isn't supported in the terraform provider. I'm referencing this issue https://community.databricks.com/t5/community-discussions/terraform-provider-problemi-in-creating-dependant-task/m-p/44117 in the databricks community forum, and have also tried similar workarounds as the original poster. But as the marked solution states, this is a hard limit in the terraform provider.

### Actual Behavior
terraform points out that the type for task_key is invalid, when attempting any of the workarounds in the linked post.
```
│ Error: Incorrect attribute value type
│ 
│   on databricks_jobs.tf line 502, in resource "databricks_job" "job_name":
│  502:       task_key = [
│  503:         "ichi",
│  504:         "ni"
│  506:       ]
│ 
│ Inappropriate value for attribute "task_key": string required.
```
```
│ Error: cannot update job: Invalid dependency graph for task 'san', job specification does not contain task with key 'ichi,ni'
```

### Terraform and provider versions
Terraform v1.5.7
on darwin_amd64

**Comment by alexott** [comment]
You simply need to put multiple `depends_on` blocks, like [this](https://github.com/alexott/terraform-playground/blob/main/jobs-demo/jobs.tf#L35):

```hcl
  task {
    task_key = "Task4"
    notebook_task {
      notebook_path = databricks_notebook.test4.id
    }
    job_cluster_key = "Shared_job_cluster"
    depends_on {
      task_key = "Task3"
    }
    depends_on {
      task_key = "Task2"
    }
  }

```
