### ISSUE TITLE
[DOC] Unity Catalog: request - GCP equivalent of AWS/Azure guides

### ISSUE THREAD

**Issue by PaulCornellDB** [databricks/terraform-provider-databricks#2728]
### Affected Resource(s)

- "Unity Catalog set up on AWS": https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/guides/unity-catalog
- "Unity Catalog set up on Azure": https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/guides/unity-catalog-azure

### Expected Details

- We should also have a "Unity Catalog set up on GCP".

**Comment by alexott** [comment]
Paul, you're looking into the wrong docs (it's still labs release) - [UC on GCP](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog-gcp) is covered for a long time already.
