### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource

### ISSUE THREAD

**Issue by yugireddy** [databricks/terraform-provider-databricks#2764]
As per Unity Catalog implementation databricks_catalog resource should create "default" schema along with Catalog but it's not working as expected.

### Configuration
```hcl
resource "databricks_catalog"
```

### Expected Behavior
"default" schema gets created with the catalog creation.

### Actual Behavior
"default" schema is not getting created with the catalog creation.

### Steps to Reproduce
1. `Use databricks terraform provider with version 1.26.0`
2. `Use databricks catalog resource`

### Terraform and provider versions
Terraform provider version - 1.26.0

**Comment by nkvuong** [comment]
@yugireddy the terraform provider removes the default schema by default, since the schema is not managed by Terraform and could cause issues

if you want the default schema in a catalog, please explicitly create them using `databricks_schema` resource
