### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore_data_access` resource. `databricks_gcp_service_account` does not return SA properties

### ISSUE THREAD

**Issue by owlleg6** [databricks/terraform-provider-databricks#2766]
Hello, it looks like `databricks_metastore_data_access` has an issue with GCP, to be exact `databricks_gcp_service_account`. I have created this resource, however, i can't use it's output attribute to assign role for generated Service Account.
### Configuration
```hcl
provider "databricks" {
  alias                  = "account"
  host                   = "https://accounts.gcp.databricks.com"
  google_service_account = var.databricks_google_service_account
  account_id             = var.databricks_account_id
}

resource "databricks_metastore_data_access" "this" {
  provider = databricks.account

  metastore_id = databricks_metastore.this.id
  name         = "dac-gcp"
  databricks_gcp_service_account {}
  is_default = true
}

output "metastore_service_account" {
  value = databricks_metastore_data_access.this.databricks_gcp_service_account
}
```
### Actual Behavior

![MicrosoftTeams-image (4)](https://github.com/databricks/terraform-provider-databricks/assets/3865349/fee7942e-5622-46b4-9f70-42d9ad64ef9b)
![MicrosoftTeams-image (5)](https://github.com/databricks/terraform-provider-databricks/assets/3865349/d378a0e5-4aac-42d1-89af-a3105eac6962)

### Terraform and provider versions

![MicrosoftTeams-image (6)](https://github.com/databricks/terraform-provider-databricks/assets/3865349/fa15d29b-9814-4b20-8506-9da4ef778eb8)

**Comment by nkvuong** [comment]
it is the same root cause as #2697
