### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource when creating foreign catalog. `UpdateCatalog options_kvpairs can not be provided`

### ISSUE THREAD

**Issue by DrKabum** [databricks/terraform-provider-databricks#2770]
### Configuration
```hcl
resource "databricks_catalog" "test_synapse" {
  metastore_id    = databricks_metastore.adh_metastore.id
  name            = "test_synapse"
  connection_name = databricks_connection.synapse_connection.name
  owner = "<service-principal-name>"
  options = {
    database = "<database-name>"
  }
  isolation_mode = "ISOLATED"
  provider       = databricks.test_workspace
}

resource "databricks_catalog_workspace_binding" "test_synapse" {
  catalog_name = databricks_catalog.test_synapse.name
  workspace_id = data.azurerm_databricks_workspace.test_pipeline.workspace_id
  provider     = databricks.test_workspace
}
```

### Expected Behavior
Catalog should be created as per configuration and be visible in this single one workspace linked.

### Actual Behavior
Partially succeeds with an error during `terraform apply`.
```
Error: cannot create catalog: UpdateCatalog options_kvpairs can not be provided.
```
- the Catalog is created, with the right connection and database setup, but is `OPEN`, and doesn't have the specified owner (but the one specified with the `provider.test_pipeline`)
- Feels like the catalog is created with some default values and then updated with at least the owner and isolation mode but the API rejects it (is it because the `options` field is provided but [not expected](https://docs.databricks.com/api/workspace/catalogs/update) when updating?)
(not a go expert 😅 )
https://github.com/databricks/terraform-provider-databricks/blob/364512f1abf157c6da7610fd710a7d31337b28ca/catalog/resource_catalog.go#L76-L86

### Steps to Reproduce
Just `terraform apply` in my case.

### Terraform and provider versions
```
Terraform v1.5.7
+ provider registry.terraform.io/databricks/databricks v1.27.0
+ provider registry.terraform.io/hashicorp/azurerm v3.57.0
```

**Comment by nkvuong** [comment]
@DrKabum v1.2.8 should fix this issue, could you validate?

**Comment by DrKabum** [comment]
Yep, all good now. Thanks :)
