### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore` resource when creating metastore without root storage

### ISSUE THREAD

**Issue by EritaSkendaj** [databricks/terraform-provider-databricks#2818]
### Configuration
```hcl
# Copy-paste your Terraform configuration here
```

### Expected Behavior
The customer tried creating a metastore without root storage, as per our recommandation.
We told them it would be easier for them to later activate UC.

### Actual Behavior
ERROR WHEN CREATING A METASTORE WITHOUT STORAGE ROOT:
resource "databricks_metastore" "db_metastore" {
The argument "storage_root" is required, but no definition was found.

### Terraform and provider versions
Customer is using version 1.28.0 (latest published at the moment of test)

**Comment by alexott** [comment]
it's not possible. Storage root is required by API: https://docs.databricks.com/api/account/accountmetastores/create

**Comment by EritaSkendaj** [comment]
Hello,
API specs were updated and TF provider needs to be updated now.
Is there any ETA on this please?

Best,
Erita Skendaj

**Comment by tanmay-db** [comment]
We are working on the release, reopening this issue for now. It got auto closed when the PR in main branch got merged.

**Comment by mgyucht** [comment]
The fix is merged and there is no more remaining work for this. This will be included in release v1.30.
