### ISSUE TITLE
[ISSUE] Issue with foreign `databricks_catalog` isolation mode

### ISSUE THREAD

**Issue by jacovg91** [databricks/terraform-provider-databricks#2820]
Hello,

the `databricks_catalog` catalog resource when set to a `connection_name` (so a foreign catalog) can not set the isolation mode correctly.

By default it is open, but if i set it to isolated, it will give me: `cannot update catalog: UpdateCatalog options can not be provided`

### Configuration
```hcl
resource "databricks_connection" "sql_server" {
  provider        = databricks.workspace
  name            = "con123"
  connection_type = "SQLSERVER"
  #owner           = var.ad_group_principal_name currently does not work, need to set it manually (https://github.com/databricks/terraform-provider-databricks/issues/2743)
  comment = "comment"
  options = {
    host     = "hostname"
    port     = "1433"
    user     = "user"
    password = "pass"
  }
  properties = {
    purpose = "Azure SQL Lakehouse Federation"
  }
}

resource "databricks_catalog" "foreign_sql_catalog" {
  provider        = databricks.workspace
  metastore_id    = var.databricks_metastore_id
  name            = "sql_catalog"
  comment         = "comment"
  isolation_mode  = "ISOLATED"
  connection_name = databricks_connection.sql_server.name
  properties = {
    purpose = "foo"
  }
  options = {
    database = "db"
  }
}
```

### Expected Behavior
The catalog should have been created with isolation set to the workspace it was created with. According to the docs: `Setting the catalog to ISOLATED will automatically allow access from the current workspace.` Btw, this works fine on regular catalogs, just not on foreign ones. 

### Actual Behavior
Getting: `cannot update catalog: UpdateCatalog options can not be provided`

**Comment by nkvuong** [comment]
@jacovg91 which provider version are you using?

**Comment by jacovg91** [comment]
@nkvuong ah good you mention it, i'm using 1.27. Didn't see anything about this in the release notes though?

**Comment by jacovg91** [comment]
can confirm, 1.28.1 solves it. 
closing ticket
thanks @nkvuong

**Comment by TMRert** [comment]
It seems this issue has regressed and is replicable with provider version `1.65.1` . The issue arises when trying to set either (or both) of these options:
- `isolation_mode`
- `owner`

Full Terraform config:
```tf
resource "databricks_connection" "sqlserver" {
  name            = "<SERVERNAME>"
  connection_type = "SQLSERVER"
  comment         = "Databricks Federation Connection to connect to Azure SQL Server."
  options = {
    applicationIntent      = "ReadOnly"
    host                   = "<HOST>"
    port                   = "1433"
    user                   = "<USER>"
    password               = data.azurerm_key_vault_secret.xxxxxx
  }
  owner = <GROUP_NAME>
}

resource "databricks_catalog" "test_catalog" {
  name            = "test_catalog"
  comment         = "this catalog is managed by terraform"
  connection_name = databricks_connection.sqlserver.name
  owner           = <GROUP_NAME>
  isolation_mode = "ISOLATED" 
  options = {
    database = "<DATABASE>"
  }
}
```

Terraform is successful in creating the connection object, but fails on the databricks catalog. The resource is created, but the owner and isolation_mode values are not applied to it. Pipeline fails with the error:
```logs
╷
│ Error: cannot create catalog: UpdateCatalog options can not be provided.
│ 
│   with databricks_catalog.test_catalog,
│   on sql_server_connection.tf line 22, in resource "databricks_catalog" "test_catalog":
│   22: resource "databricks_catalog" "test_catalog" {
│ 
```
