### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster_policy` resource - destroying resource fails

### ISSUE THREAD

**Issue by usaidkkb** [databricks/terraform-provider-databricks#2833]
### Configuration
```hcl
variable "policy_overrides" {
  description = "Cluster policy overrides"
}

locals {
  default_policy = {
    "dbus_per_hour" : {
      "type" : "range",
      "maxValue" : 10
    },
    "autotermination_minutes" : {
      "type" : "fixed",
      "value" : 20,
      "hidden" : true
    },
    "custom_tags.Team" : {
      "type" : "fixed",
      "value" : "dev-dat-1111-xx-abcdefgh Vanilla - Data Scientists - Data Scientists"
    }
  }
}

resource "databricks_cluster_policy" "fair_use" {
  name       = "dev-dat-1111-xx-abcdefgh Vanilla - Data Scientists - Data Scientists"
  definition = jsonencode(merge(local.default_policy, var.policy_overrides))
}
```

### Expected Behavior
`Terraform apply` creates the `databricks_cluster_policy` resource and `Terraform destroy` destroys it.
### Actual Behavior
`Terrraform apply` works as expected. There is an error on `Terraform destroy`
`Error: cannot delete cluster policy: timed out: Unexpected error. Message: java.sql.SQLDataException: (conn=10681314) Data too long for column 'policy_name' at row 1`. 

The `databricks_cluster_policy` name is under the 100 characters limit and there is no error on creation. This error is non-deterministic i.e. the destruction of the resource is sometimes successful with exactly the same conditions.

Shortening the `databricks_cluster_policy` name solves the issue for example, `dev-dat-1111-xx-abcdefgh Vanilla - Data Scientists - Data Scientists` to `dev-dat-1111 Vanilla - Data Scientists - Data Scientists`

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

### Terraform and provider versions
Terraform v1.5.2
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.13.0

**Comment by mgyucht** [comment]
Thanks for raising & for the clear bug report. I'll escalate this ticket to the backend team responsible for cluster policies.

**Comment by jeffliang-db** [comment]
@usaidkkb - There should've been a fix that went out for this exact issue on 10/19 so if this issue occurred prior to that, could you try retrying now?  If it's still failing now, could you let us know which region this is happening in? Thanks!

**Comment by usaidkkb** [comment]
@jeffliang-db It looks like it's working now. Thanks for checking!
