### ISSUE TITLE
 Issue with `Experimental resource exporter` when importing databricks_groups

### ISSUE THREAD

**Issue by ankitha-v1** [databricks/terraform-provider-databricks#2855]
### Configuration

provider "databricks" {
  host  = "https://<workspace>.cloud.databricks.com"
  token = "token"
}

### Expected Behavior
The import of groups also imports all the users, during which some of the fields are missing in the `databricks_user` resources which causes a drift in the template

### Actual Behavior

1) After running the exporter command (importing only groups here, which creates groups.tf, users.tf and import.sh files) 
2) when we run the terraform plan it shows `Plan: 36 to add, 0 to change, 0 to destroy`. As expected the 36 would be the resources that are to be imported (groups and users)
3) But after executing the import.sh file, if I run terraform plan again I would expect it to show 0 to add 0 to change 0 to destroy as I've made no changes in the resources
But it shows 0 to add, 17 to change, 0 to destroy.
<img width="873" alt="image" src="https://github.com/databricks/terraform-provider-databricks/assets/114205046/75c2ac8d-b93c-4fb2-ad07-4d0a1ac2e1a6">

And if we check the users.tf at this point, we can only see the fields which are true are imported and the fields set to false are the ones that shows up in the drift

### Steps to Reproduce
1) Run ./terraform-provider-databricks exporter   
2) Give 'Y' to import groups
3) ./import.sh
4) terraform plan

### Terraform and provider versions
Terraform v1.4.6
provider version = "1.28.1"

### Is it a regression?
No.

**Comment by mgyucht** [comment]
@alexott do you think you can take a look at this?

**Comment by alexott** [comment]
It's less issue with exporter and more with the `terraform import` functionality.

**Comment by alexott** [comment]
@ankitha-v1 The 1.30.0 release included the #2878 which was the primary issue with groups/users/... I'm not sure if we can completely remove the initial drift after import.

**Comment by alexott** [comment]
The biggest obstacle was fixed in #2878, so closing this - we can't completely remove the initial drift...
