### ISSUE TITLE
[ISSUE] Issue with `databricks/databricks versions matching "~> 1.29.0"` resource

### ISSUE THREAD

**Issue by katerinagreif** [databricks/terraform-provider-databricks#2860]
### Configuration

```hcl
# Copy-paste your Terraform configuration here
```

### Expected Behavior
Should of donloaded version of package for win.

### Actual Behavior
 Error: Incompatible provider version
│
│ Provider registry.terraform.io/databricks/databricks v1.29.0 does not have
│ a package available for your current platform, windows_386.
│
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.

### Terraform and provider versions
Terraform v1.6.2
on windows_386

**Comment by alexott** [comment]
It's covered in the [troubleshooting guide](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting#error-provider-registryterraformiodatabricksdatabricks-v-does-not-have-a-package-available-for-your-current-platform-windows_386). We don't release 32-bit versions anymore
