### ISSUE TITLE
[ISSUE]  `databricks_share` does not support materialised views

### ISSUE THREAD

**Issue by raymonds-backyard** [databricks/terraform-provider-databricks#2861]
### Configuration
We are using the `databricks_tables` data source to fetch all the tables in our schemas to add to a databricks delta share. However we find that materialised views cannot be delta shared. We note that this is possible in the latest LTS 13.3. Is this something we need to configure on our end?
```hcl
data "databricks_tables" "all" {
  for_each = data.databricks_schemas.all.ids

  catalog_name = var.catalog_name
  schema_name  = trimprefix(each.value, "${var.catalog_name}.")
}

# Adds the tables above to a share resource
resource "databricks_share" "some" {
  name  = "some_share"
  dynamic "object" {
    for_each = flatten([for schema in data.databricks_tables.all : schema.ids])
    content {
      name             = object.value
      shared_as        = join(".", slice(split(".", object.value), 1, length(split(".", object.value))))
      data_object_type = "TABLE"
    }
  }
}
```

### Expected Behavior
Expect that the resource "databricks_share" is able to share materialised views to align with 13.3 LTS features.

### Actual Behavior
"databricks_share" does not support sharing of materialised views at the moment. The data source is returning both tables and materialised views without a clear way to differentiate between them.

### Steps to Reproduce
1. Create a materialised view
2. Run terraform apply

### Terraform and provider versions
Terraform v1.5.5
on darwin_arm64

databricks = {
  source  = "databricks/databricks"
  version = "~> 1.27.0"
}

### Is it a regression?
No

### Debug Output
Error: cannot update share: Sharing materialized views is not supported yet.

**Comment by raymonds-backyard** [comment]
Saw that the latest DBR https://docs.databricks.com/en/release-notes/runtime/13.3lts.html#share-materialized-views-with-delta-sharing) solves our issues, but unsure how this correlates with the databricks provider version.

**Comment by andyl-db** [comment]
@raymonds-backyard Hi I'm from the Delta Sharing team - this feature is not publicly available yet. The documentation was released by accident and will be corrected. This feature will be coming soon! However, no ETA can be given yet.
