### ISSUE TITLE
[ISSUE] Issue with databricks_permissions sql_endpoint_id

### ISSUE THREAD

**Issue by shortpoet** [databricks/terraform-provider-databricks#2865]
Same as closed issue https://github.com/databricks/terraform-provider-databricks/issues/2678

SQL Warehouse exists since before the change.  Not experiencing issue with newly created SQL warehouses

We still get this issue with `v1.28.0`

Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/databricks/databricks v1.28.0
+ provider registry.terraform.io/hashicorp/azuread v2.37.0
+ provider registry.terraform.io/hashicorp/azurerm v3.34.0

│ Error: cannot update permissions: PUT requests for warehouse 3bc8a799f01c9aa6 with no existing owner must provide a new owner.
│ 
│   with module.databricks_components_dev.module.databricks_components.databricks_permissions.endpoint_usage["llc_warehouse"],
│   on .terraform\modules\databricks_components_dev.databricks_components\permissions_sql_warehouse.tf line 1, in resource "databricks_permissions" "endpoint_usage":
│    1: resource "databricks_permissions" "endpoint_usage" {
│ 
╵
╷
│ Error: cannot update permissions: PUT requests for warehouse 8b7cd3ca6ff1ccfc with no existing owner must provide a new owner.
│ 
│   with module.databricks_components_dev.module.databricks_components.databricks_permissions.endpoint_usage["pbi_warehouse"],
│   on .terraform\modules\databricks_components_dev.databricks_components\permissions_sql_warehouse.tf line 1, in resource "databricks_permissions" "endpoint_usage":
│    1: resource "databricks_permissions" "endpoint_usage" {
│ 
╵
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: cannot update permissions: PUT requests for warehouse 3bc8a799f01c9aa6 with no existing owner must provide a new owner.
│ 
│   with module.databricks_components_dev.module.databricks_components.databricks_permissions.endpoint_usage["llc_warehouse"],
│   on .terraform\modules\databricks_components_dev.databricks_components\permissions_sql_warehouse.tf line 1, in resource "databricks_permissions" "endpoint_usage":
│    1: resource "databricks_permissions" "endpoint_usage" {
│ 
╵

╷
│ Error: cannot update permissions: PUT requests for warehouse 8b7cd3ca6ff1ccfc with no existing owner must provide a new owner.
│ 
│   with module.databricks_components_dev.module.databricks_components.databricks_permissions.endpoint_usage["pbi_warehouse"],
│   on .terraform\modules\databricks_components_dev.databricks_components\permissions_sql_warehouse.tf line 1, in resource "databricks_permissions" "endpoint_usage":
│    1: resource "databricks_permissions" "endpoint_usage" {
│ 
╵

```
resource "databricks_permissions" "endpoint_usage" {
  for_each = local.db_sql_warehouse_config

  sql_endpoint_id = databricks_sql_endpoint.warehouse[each.key].id
  access_control {
    permission_level       = local.db_permissions_presets_sql_is_owner
    service_principal_name = local.db_sp_tooling_client_id
  }

  dynamic "access_control" {
    for_each = { for entry in local.db_sql_warehouse_groups : "${entry.sql_warehouse}-${entry.group_name}" => entry if entry.sql_warehouse == each.value.name }

    content {
      group_name       = access_control.value.group_name
      permission_level = access_control.value.sql_permissions
    }
  }
  depends_on = [
    databricks_permission_assignment.db_user_group
  ]

  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by mgyucht** [comment]
@tanmay-db can you please look into this?

**Comment by tanmay-db** [comment]
Looking

**Comment by tanmay-db** [comment]
Hi @shortpoet, as you mentioned:

> SQL Warehouse exists since before the change. Not experiencing issue with newly created SQL warehouses

Can you confirm if there is an owner for the old warehouse?

**Comment by shortpoet** [comment]
Yes, I was the owner. I resolved it by manually deleting the resource and then recreating via IaC. Feel free to close. I am more than happy to provide any additional info/context in any case! Thank you 😀
