### ISSUE TITLE
Docs for importing databricks instance profile incorrectly show arn where profilename is required

### ISSUE THREAD

**Issue by JoaoCarlinho** [databricks/terraform-provider-databricks#2874]
### Affected Resource(s)
[(https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/instance_profile)

### Expected Details
terraform import databricks_instance_profile.this "instance-profile-arn" needs to be updated to:
terraform import databricks_instance_profile.this "instance-profile-name"

### References

Running the import command with the instance-profile-arn specified results in the following error:
│ Error: reading IAM Instance Profile ("instance-profile-arn"): ValidationE
rror: 1 validation error detected: Value "instance-profile-arn" at 'insta
nceProfileName' failed to satisfy constraint: Member must satisfy regular expression pattern: [\w+=,.@-]+
│       status code: 400, request id: f225fd34-878c-4dd5-81e0-fdc737e7834a

**Comment by nkvuong** [comment]
this is not an issue, you need to specify the actual instance profile arn to import, e.g.
`terraform import databricks_instance_profile.this arn:aws:iam::111111111111:instance-profile/instance-profile`
