### ISSUE TITLE
[ISSUE] Issue with `databricks_metastore_data_access` Cannot create

### ISSUE THREAD

**Issue by DevopsMercenary** [databricks/terraform-provider-databricks#2875]
This worked yesterday with the same provider config etc.  But today not.  This is basically a simplifcation of the Unitiy Catalog Demo  https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog-azure

### Configuration

```hcl

# Initialize the 3 providers to set up the required resources. See Databricks provider authentication, Azure AD provider authentication and Azure provider authentication for more details.

# Define the required variables, and calculate the local values

variable "databricks_resource_id" {

  default     = "/subscriptions/0f8..."
  description = "The Azure resource ID for the databricks workspace deployment."
}

variable "databricks_account_id" {
  default     = "e5217fd3..."
  description = "Logged into https://accounts.azuredatabricks.net and under my name the id was there."
}

locals {
  resource_regex            = "(?i)subscriptions/(.+)/resourceGroups/(.+)/providers/Microsoft.Databricks/workspaces/(.+)"
  subscription_id           = regex(local.resource_regex, var.databricks_resource_id)[0]
  resource_group            = regex(local.resource_regex, var.databricks_resource_id)[1]
  tenant_id                 = data.azurerm_client_config.current.tenant_id
  prefix                    = replace(replace(lower(data.azurerm_resource_group.this.name), "rg", ""), "-", "")
}

data "azurerm_resource_group" "this" {
  name = local.resource_group
}

data "azurerm_client_config" "current" {
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
    databricks = {
      source = "databricks/databricks"
    }
  }
}

provider "azurerm" {
  subscription_id = local.subscription_id
  features {}
}

provider "databricks" {
  alias      = "accounts"
  host       = "https://accounts.azuredatabricks.net"
  account_id = var.databricks_account_id
}

# The first step is to create the required Azure objects:

# An Azure storage account, which is the default storage location for managed tables in Unity Catalog. Please use a dedicated account for each metastore.

# A Databricks Access Connector that provides Unity Catalog permissions to access and manage data in the storage account.

resource "azurerm_databricks_access_connector" "unity" {
  name                = "${local.prefix}-databricks-mi"
  resource_group_name = data.azurerm_resource_group.this.name
  location            = data.azurerm_resource_group.this.location
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_storage_account" "unity_catalog" {
  name                     = substr("${local.prefix}storage", 0, 24)
  resource_group_name      = data.azurerm_resource_group.this.name
  location                 = data.azurerm_resource_group.this.location
  tags                     = data.azurerm_resource_group.this.tags
  account_tier             = "Standard"
  account_replication_type = "GRS"
  is_hns_enabled           = true
}

resource "azurerm_storage_container" "unity_catalog" {
  name                  = "${local.prefix}-container"
  storage_account_name  = azurerm_storage_account.unity_catalog.name
  container_access_type = "private"
}

resource "azurerm_role_assignment" "example" {
  scope                = azurerm_storage_account.unity_catalog.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_databricks_access_connector.unity.identity[0].principal_id
}


###
### A databricks_metastore is the top level container for data in Unity Catalog. You can only create a single metastore for each region in which your organization operates, and attach workspaces to the metastore. Each workspace will have the same view of the data you manage in Unity Catalog.
###

resource "databricks_metastore" "this" {
  provider = databricks.accounts
  name     = "primary"
  storage_root = format("abfss://%s@%s.dfs.core.windows.net/",
    azurerm_storage_container.unity_catalog.name,
  azurerm_storage_account.unity_catalog.name)
  force_destroy = true
  region        = data.azurerm_resource_group.this.location
}

resource "databricks_metastore_data_access" "first" {
  provider     = databricks.accounts
  metastore_id = databricks_metastore.this.id
  name         = "the-keys"
  azure_managed_identity {
    access_connector_id = azurerm_databricks_access_connector.unity.id
  }

  is_default = true
}


```

### Expected Behavior

I expected it to create it and complete ok.  It did yesterday.

### Actual Behavior

```
│ Error: cannot create metastore data access:
│
│   with databricks_metastore_data_access.first,
│   on create-unity-catalog-metastore-and-link-workspace.tf line 16, in resource "databricks_metastore_data_access" "first":
│   16: resource "databricks_metastore_data_access" "first" {
```

### Steps to Reproduce

1. `terraform apply`

### Terraform and provider versions

Terraform v1.6.3
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.29.0
+ provider registry.terraform.io/hashicorp/azurerm v3.78.0

### Is it a regression?

N/A

### Debug Output

I have a trace gist 

https://gist.github.com/DevopsMercenary/b5a7981e4541086a4da34680e268fb48

and one as recommended

https://gist.github.com/DevopsMercenary/6a6ba78c4ae508c09bee19e817e70658

**Comment by jakeWatsonOakland** [comment]
I'm getting the same error, but using Terraform 1.5.7 on Windows. Even the traces are the same. Looks like error is caused around getting the ADD token of access connector identity.

**Comment by nkvuong** [comment]
This suggests that auth was okay

`2023-11-02T14:16:53.572-0400 [DEBUG] provider.terraform-provider-databricks_v1.29.0: GET /api/2.0/accounts/e5217fd3-92a0-45b8-825c-ab096df62fe9/metastores/981d0321-2c14-4b7d-90ec-baaab47b35a4
< HTTP/2.0 200 OK`

then we got a backend error creating the storage credential

```
2023-11-02T14:17:25.240-0400 [DEBUG] provider.terraform-provider-databricks_v1.29.0: POST /api/2.0/accounts/e5217fd3-92a0-45b8-825c-ab096df62fe9/metastores/981d0321-2c14-4b7d-90ec-baaab47b35a4/storage-credentials
> {
>   "credential_info": {
>     "azure_managed_identity": {
>       "access_connector_id": "/subscriptions/0f849332-18f0-45f6-abf6-3bcd9058d3eb/resourceGroups/databricksdemovqajh4-rg/provi... (77 more bytes)"
>     },
>     "name": "the-keys"
>   }
> }
< HTTP/2.0 500 Internal Server Error
```

**Comment by jakeWatsonOakland** [comment]
Thanks for the reply @nkvuong, I'm guessing there is not much we can try to remediate if it's a Internal Error?

**Comment by ivenw** [comment]
> This suggests that auth was okay
> 
> `2023-11-02T14:16:53.572-0400 [DEBUG] provider.terraform-provider-databricks_v1.29.0: GET /api/2.0/accounts/e5217fd3-92a0-45b8-825c-ab096df62fe9/metastores/981d0321-2c14-4b7d-90ec-baaab47b35a4 < HTTP/2.0 200 OK`
> 
> then we got a backend error creating the storage credential
> 
> ```
> 2023-11-02T14:17:25.240-0400 [DEBUG] provider.terraform-provider-databricks_v1.29.0: POST /api/2.0/accounts/e5217fd3-92a0-45b8-825c-ab096df62fe9/metastores/981d0321-2c14-4b7d-90ec-baaab47b35a4/storage-credentials
> > {
> >   "credential_info": {
> >     "azure_managed_identity": {
> >       "access_connector_id": "/subscriptions/0f849332-18f0-45f6-abf6-3bcd9058d3eb/resourceGroups/databricksdemovqajh4-rg/provi... (77 more bytes)"
> >     },
> >     "name": "the-keys"
> >   }
> > }
> < HTTP/2.0 500 Internal Server Error
> < {
> <   "details": [
> <     {
> <       "@type": "type.googleapis.com/google.rpc.RequestInfo",
> <       "request_id": "3349c8bc-3fea-4d0f-87be-39f4510615c4",
> <       "serving_data": ""
> <     }
> <   ],
> <   "error_code": "INTERNAL_ERROR",
> <   "message": ""
> < }
> ```

Can confirm that I just stumbled upon the same error, and found this issue in search for a solution. I am getting the same internal server error when trying to post the storage credentials.

**Comment by ivenw** [comment]
I got this to work by swapping the account scoped provider for the workspace scoped provider. This hits this api endpoint instead https://docs.databricks.com/api/azure/workspace/storagecredentials/create and creates a storage credential that is visible from the workspace ui. The path is then to the metastore root and the external location is given the name `metastore_default_location`.

Subsequently this patches the metastore with this api endpoint https://docs.databricks.com/api/azure/workspace/metastores/update

Interestingly I also ran into issues provisioning a metastore using the UI, so something seems to maybe be borked right now in some tennants.

**Comment by TMRert** [comment]
It seems like the Account-level Storage Credential API has been patched this morning, as I was able to create Storage Credentials using both the API as well as the Terraform provider `v1.29.0` configured for the account level. Up until yesterday both failed with the error described above by @ivenw.

**Comment by jakeWatsonOakland** [comment]
I forgot to mention: this issue seems to be resolved for me after the fix to the API.
