### ISSUE TITLE
[ISSUE] issue with databricks_permissions sql_endpoint_id

### ISSUE THREAD

**Issue by zexoor** [databricks/terraform-provider-databricks#2894]
Hi, I believe this is a different issue than #2865 & #2678.

I've recently modified our terraform to bring warehouse permissions under control. Initial terraform apply worked, but a subsequent terraform plan showed that it needed to update the permissions in place, due to a missing is_owner permission. 

```hcl
# module.warehouses.databricks_permissions.name will be updated in-place
  ~ resource "databricks_permissions" "name" {
        id              = "/sql/warehouses/###########"
        # (2 unchanged attributes hidden)

      - access_control {
          - permission_level = "IS_OWNER" -> null
          - user_name        = "Admin@COMPANY" -> null
        }
      - access_control {
          - group_name       = "User Access" -> null
          - permission_level = "CAN_USE" -> null
        }
      + access_control {
          + group_name       = "User Access"
          + permission_level = "CAN_USE"
        }
    }
``` 

The databricks_permissions block does not support providing an is_owner permission for a sql_endpoint_id, giving the error 
```
Terraform encountered an error while generating this plan.

╷
│ Error: permission_level IS_OWNER is not supported with sql_endpoint_id objects
```

As such there isn't an apparent way to reconcile the difference between the permissions actually on the object and the tf code  

### Configuration
```hcl
resource "databricks_sql_endpoint" "sql_warehouse" {
  name                 = var.warehouse_name
  cluster_size         = var.warehouse_size
  auto_stop_mins       = var.warehouse_auto_stop_mins
  max_num_clusters     = var.warehouse_max_num_clusters
  warehouse_type       = var.warehouse_type
  min_num_clusters     = var.warehouse_min_num_clusters
  spot_instance_policy = var.spot_instance_policy
  tags {
    dynamic "custom_tags" {
      for_each = var.warehouse_custom_tags
      content {
        key   = custom_tags.key
        value = custom_tags.value
      }
    }
  }
}

resource "databricks_permissions" "name" {
  sql_endpoint_id = databricks_sql_endpoint.sql_warehouse.id

  dynamic "access_control" {
    for_each = var.use_groups
    content {
      group_name = access_control.value
      permission_level = "CAN_USE"
    }
  }
  dynamic "access_control" {
    for_each = var.manage_groups
    content {
      group_name = access_control.value
      permission_level = "CAN_MANAGE"
    }
  }
}
```
### Steps To Reproduce
1. Use terraform to create a cluster and apply some permissions to it in the UI
2. Recreate those permissions in terraform and run an apply
3. The next plan will suggest it wants to update the object in place to remove IS_OWNER

**Comment by pachorussowd** [comment]
+1 I'm facing the same issue! I don't know how to avoid the removal of the IS_OWNER

**Comment by tanmay-db** [comment]
Hi @zexoor @pachorussowd , which version are you using? Also is this a regression? When did it start happening? + @nkvuong for visibility.

**Comment by zexoor** [comment]
I've managed to resolve the issue by upgrading provider to the latest version (v1.29.0), updating from 1.19, Apologies should have tried updating first.
