### ISSUE TITLE
cluster_policy documentation does not indicate that data_security_mode is required for UC

### ISSUE THREAD

**Issue by pohlposition** [databricks/terraform-provider-databricks#2904]
The API for cluster policies needs to be annotated in some way so that data_security_mode is highlighted as being required for UC enabled clusters.  This is causing confusion with customers.

The cluster policy documentation in Teraform does not indicate that data_security_mode is a required field if using Unity Catalog.

https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster_policy 

The API documentation does not mention data_security_mode either:

https://docs.databricks.com/api/workspace/clusterpolicies/create 

However, the cluster documentation in Teraform correctly indicates as such:

https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster 

data_security_mode - (Optional) Select the security features of the cluster. [Unity Catalog requires](https://docs.databricks.com/data-governance/unity-catalog/compute.html#create-clusters--sql-warehouses-with-unity-catalog-access) SINGLE_USER or USER_ISOLATION mode. LEGACY_PASSTHROUGH for passthrough cluster and LEGACY_TABLE_ACL for Table ACL cluster. Default to NONE, i.e. no security feature enabled. In the Databricks UI, this has been recently been renamed Access Mode and USER_ISOLATION has been renamed Shared, but use these terms here.

This maps  to our API documentation:

https://docs.databricks.com/api/workspace/clusters/create

**Comment by alexott** [comment]
For Terraform & API, cluster policy definition is just a string - what is inside is completely opaque to Terraform/API. Terraform documentation points to the official documentation that should provide all necessary information, including requirements for UC clusters.
