### ISSUE TITLE
[ISSUE] Issue updating `databricks_workspace_conf` resource with an invalid property

### ISSUE THREAD

**Issue by jiropardo** [databricks/terraform-provider-databricks#2913]
### Configuration

```hcl
resource "databricks_workspace_conf" "this" {
  provider = databricks.workspace  
  custom_config = {
    "enableIpAccessLists" : false
    "enableWrongProperty": true
    "enableDeprecatedGlobalInitScripts": true
  }
}
```

### Expected Behavior

If an invalid property is passed in the custom_config map, we should get the error **"Error: cannot read workspace conf: Invalid keys: ["enableWrongProperty"]** and then be able to get back to the resource, remove the invalid property and run apply with no issues

### Actual Behavior

When an invalid property is passed in the custom_config map, terraform gets stuck in a state with the error **"Error: cannot read workspace conf: Invalid keys: ["enableWrongProperty"]**. It does not matter if we go back to terraform code and delete the invalid property, Terraform will not move out of this state and will continue to throw above error indefinitely even when the invalid property has been removed from the code making the rest of the code unusable

As the values of the workspace conf API are not guaranteed to be stable yet, we should be able to remove an invalid value in the case a valid value changes and causes the issue see  Ref https://github.com/databricks/terraform-provider-databricks/issues/2609

### Steps to Reproduce

Provider 1.29

### Debug Output

[tf-debug.log](https://github.com/databricks/terraform-provider-databricks/files/13337780/tf-debug.log)

**Comment by alexott** [comment]
Should be fixed by #2914
