### ISSUE TITLE
Example provided on page for "databricks_catalog_workspace_binding" is out-of-date

### ISSUE THREAD

**Issue by dbhaigh** [databricks/terraform-provider-databricks#2922]
The example you provide for "databricks_catalog_workspace_binding" here https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/catalog_workspace_binding is out-of-date

It still refers to the DEPRECATED attribute "catalog_name", and makes no reference to the new, REQUIRED attributes "securable_name", "securable_type", and "binding_type"

This needs to be addressed

**Comment by jacovg91** [comment]
Same here, vscode going bonkers

![image](https://github.com/databricks/terraform-provider-databricks/assets/72300830/82ff3afa-2c98-45b7-8cf8-9ba1f4b76e97)

It works though, but is really annoying. I hope for a quick fix.

**Comment by dbhaigh** [comment]
I know - and I've flagged that up with the VSCode extension people too

I'd rather not get told that required attributes are unexpected and that my correct code is wrong  :P

**Comment by jacovg91** [comment]
I'm not sure if its to do with the extension, it doesn't recognize the new `binding_type` property either, which I believe is an issue in the newly released provider version?

**Comment by dbhaigh** [comment]
Whatever the root cause?  It still needs to be fixed - I hate it when programs lie to me :P

**Comment by jacovg91** [comment]
@alexott @nkvuong without pressuring you guys, greatly appreciate your work, it would be great if we could get a hotfix for this asap

**Comment by dbhaigh** [comment]
Anyway - as far as the topic of the post goes?  THIS is what the example should look like 

¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬

resource "databricks_catalog" "sandbox" {
  name           = "sandbox"
  isolation_mode = "ISOLATED"
}

resource "databricks_catalog_workspace_binding" "sandbox" {
  securable_name = databricks_catalog.sandbox.name
  workspace_id   = databricks_mws_workspaces.other.workspace_id
}

¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬¬

I've omitted "securable_type" and "binding_type" as they default to "catalog" and "BINDING_TYPE_READ_WRITE" respectively and that's good enough for the example

Cheers

-=A=-

.

**Comment by jacovg91** [comment]
Wouldn't say this is just docs. Not sure what exactly in the provider checks the validity, but in [catalog_workspace_binding_test.go](https://github.com/databricks/terraform-provider-databricks/blob/b090a409dcb63368030220a063865b2e5104cf23/internal/acceptance/catalog_workspace_binding_test.go#L21) there's still old values too.

**Comment by dbhaigh** [comment]
The red-highlighting of the spurious error is extension related - just got an update on the thread I started regarding it

"...it looks the provider made some changes in 1.30.0, while the language server still bundles [1.29.0](https://registry.terraform.io/providers/databricks/databricks/1.29.0/docs)...."

From [ https://github.com/hashicorp/vscode-terraform/issues/1627#issuecomment-1812611599 ]

So, they are aware of the problem now, and are working towards a resolution

**Comment by jacovg91** [comment]
Ah, that's really great news. I've just made a PR for the docs changes, which is just a line line change
