### ISSUE TITLE
[FEATURE] Alternative for databricks_dbfs_file resource for init scripts

### ISSUE THREAD

**Issue by vadivelselvaraj** [databricks/terraform-provider-databricks#2926]
### Use-cases
Given that dbfs files cannot be configured in init scripts, can we create a `databricks_workspace_file` resource to create workspace files from within a codebase?

### Proposal

```hcl
resource "databricks_directory" "init_scripts_directory" {
  path = "/Shared/init_scripts"
}

resource "databricks_dbfs_file" "example_init_script" {
  source = "../../src/init_scripts/example.sh"
  path   = "${databricks_directory.init_scripts_directory.id}/example.sh"
}
```
This would effectively replace the current `databricks_dbfs_file`.

```hcl
resource "databricks_dbfs_file" "example_init_script" {
  source = "../../src/init_scripts/example.sh"
  path   = "${databricks_directory.init_scripts_directory.id}/example.sh"
}
```

**Comment by alexott** [comment]
Yes, you can - it's [documented](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#init_scripts). Upgrade TF provider to get access to [databricks_workspace_file](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/workspace_file)
