### ISSUE TITLE
[FEATURE] Add queue attribute to databricks_job

### ISSUE THREAD

**Issue by maikelos** [databricks/terraform-provider-databricks#2928]
### Use-cases

The databricks_job is missing a queue attribute as present in databricks API that allows to enable queues for databricks jobs.
The queue can be enabled normally via an API or UI and is not a private preview feature but GA at this point.

The end goal is to be able to set this queue attribute/flag such that queues can be enabled via terraform.

### Attempted Solutions

None, as there is none.

### Proposal

Add a new attribute called queue at a job level (simillaly to max_concurrent_runs) and have it accept boolean.

This API doc page [Databricks API Job create](https://docs.databricks.com/api/workspace/jobs/create) contains the queue attribute so you can just replicate it.

### References

- #2531 issue from few months ago that asked for the same thing but was cancelled as the feature was at private preview back then.

**Comment by alexott** [comment]
It's already [there](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#queue-configuration-block), upgrade your terraform version.
