### ISSUE TITLE
Issue with DENYing 'users' access to workspace resources (keyvault backed secret scope)

### ISSUE THREAD

**Issue by marc88** [databricks/terraform-provider-databricks#2930]
Hello,

I have an ACL on a azure key-vault backed scope (scope_name: _scope-limited-to-user123_) as follows. 

`{ "items": [ { "principal": "user123", "permission": "MANAGE" } ] }`

The scope was created from the databricks workspace UI with 'MANAGE' access, only granted to the creator ('user123').
This does NOT state that the default '**users**' group has any privilege on the resource. Hence, I assumed it should be a 'DENY' for 'users' by default.

But, surprisingly, users other than 'user123' are also able to READ and use secrets from this scope like so.

`dbutils.secrets.get(scope="scope-limited-to-user123",key=my_key_name)`

The other users have workspace admin privileges (Entitlements: Workspace access, Databricks SQL access, Allow unrestricted cluster creation, allow-instance-pool-create).
Also, users that have only Workspace access and Databricks SQL access, are all able to access this scope.

Question,

1) How is the aforesaid possible when there is no ACL granting privileges to the scope, for 'users'?
2) There is no way in the databricks REST API documentation to 'DENY' them this privilege. Is there a workaround? Or maybe a way to set a DENY ACL?

Regards

**Comment by mgyucht** [comment]
@marc88 This ACL should in general be respected for non-workspace admins. However, workspace admins can always read secrets from any scope, regardless of whether they have been explicitly granted access to this scope. Are you able to reproduce this with non-workspace admin users?

**Comment by marc88** [comment]
Understood.

No. The ACL is respected by non-admins.
you may close this issue

**Comment by marc88** [comment]
The ACL is respected by non-admins.
