### ISSUE TITLE
[FEATURE] add custom_tags property to databricks_mws_workspace

### ISSUE THREAD

**Issue by jiropardo** [databricks/terraform-provider-databricks#2938]
### Use-cases

Adding support for this would be beneficial for differentiating business units. It is possible to set workspace-level tags when creating a workspace using the workspaces API Ref https://docs.databricks.com/en/administration-guide/workspace/create-workspace-api.html

### Proposal

Add custom_tags property to databricks_mws_workspace resource as the API does. 

### References

Currently custom_tags is not supported on the provider https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces

**Comment by alexott** [comment]
done
