### ISSUE TITLE
[ISSUE] run_as_role Issue with `databricks_sql_query` resource

### ISSUE THREAD

**Issue by SlevinBE** [databricks/terraform-provider-databricks#2939]
### Configuration

```hcl
resource "databricks_sql_query" "sample_query" {
  provider = databricks.created_workspace
  run_as_role    = "viewer"
  query          = <<EOT
    select * from test_table;
  EOT
  parent         = "folders/${databricks_directory.operational.object_id}"
  name           = "sample_query"
  data_source_id = databricks_sql_endpoint.this.data_source_id
}
```

### Expected Behavior
The query should've been created with a run as "viewer" role.

### Actual Behavior
The query is created with the default run as role, which is `owner`. This means we have a constant Terraform drift when running TF apply.
```
# databricks_sql_query.sample_query will be updated in-place
  ~ resource "databricks_sql_query" "sample_query" {
        id             = "65bd4581-5f07-4ef6-8f27-262ccc89b46d"
        name           = "sample_query"
      ~ run_as_role    = "owner" -> "viewer"
        # (5 unchanged attributes hidden)
    }
```

### Steps to Reproduce
1. `terraform apply`using the provided `databricks_sql_query` resource definition
2. once applied, run `terraform plan`, which results in the TF config drift.

### Terraform and provider versions
terraform_version: 1.5.5
databricks provider version: latest

### Is it a regression?
no

### Important Factoids
In the Terraform provider code, we found that it tries to create the query resource using an incorrect API call. Specifically in [this piece of code](https://github.com/databricks/terraform-provider-databricks/blob/master/sql/resource_sql_query.go#L296), it's trying to set the `run_as_role` property on the `options` object. However, looking at the [Databricks API definition for creating a query resource](https://docs.databricks.com/api/workspace/queries/create), the options block is "Exclusively used for storing a list parameter definitions", so it doesn't include the same number of properties as the response or GET object.  

For example, when creating a SQL Query via the API with the following body, similar to what the TF provider currently does:
```
{
    "data_source_id": "8ac1d7df-01d9-4218-935f-6ec6a1539f34",
    "query": "SELECT * from sample_query",
    "name": "test query",
    "parent": "folders/123456",
    "description": "Tests the creation of a query",
    "options": {
        "parameters": [
        ],
        "run_as_role": "viewer"
    }
}
```
We get the following response with an incorrect run_as_role configuration:
```
{
    "id": "2853db7e-3edc-48be-840a-36feff665e82",
    "version": 1,
    "description": "Tests the creation of a query",
    "name": "test query",
    "run_as_role": "owner",
    ...
    "parent": "folders/123456",
    "options": {
        "parameters": [],
        ...
        "run_as_role": "owner",
    },
    "query": "SELECT * from sample_query"
}
```

When creating the SQL Query via the API by setting the `run_as_role` as a top-level property:
```
{
    "data_source_id": "8ac1d7df-01d9-4218-935f-6ec6a1539f34",
    "query": "SELECT * from sample_query",
    "name": "test query",
    "parent": "folders/123456",
    "description": "Tests the creation of a query",
    "run_as_role": "viewer"
}
```
Then the created query does have the correct run_as_role configuration:
```
{
    "id": "2853db7e-3edc-48be-840a-36feff665e82",
    "version": 1,
    "description": "Tests the creation of a query",
    "name": "test query",
    "run_as_role": "viewer",
    ...
    "parent": "folders/123456",
    "options": {
        "parameters": [],
        ...
        "run_as_role": "viewer",
    },
    "query": "SELECT * from sample_query"
}
```

**Comment by alexott** [comment]
Fixed in #2940
