### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_table` resource: error to create a view when catalog name has an hyphen

### ISSUE THREAD

**Issue by alexandrebunn** [databricks/terraform-provider-databricks#2944]
### Configuration

```hcl
# Copy-paste your Terraform configuration here

## Module definition
resource "databricks_sql_table" "table" {
  provider                = databricks.workspace
  name                    = var.name
  catalog_name            = var.catalog_name
  schema_name             = var.schema_name
  table_type              = var.table_type
  storage_location        = var.storage_location
  data_source_format      = var.data_source_format
  view_definition         = var.view_definition
  cluster_id              = var.cluster_id
  storage_credential_name = var.storage_credential_name
  comment                 = var.comment
  properties              = var.properties

  dynamic "column" {
    for_each = var.columns
    content {
      name = column.value.name
      type = column.value.type
      nullable = column.value.nullable
    }
  }
}

## module call
module "teste_view2" {
  source = "./modules/table"
  providers = {
    databricks.workspace = databricks.workspace
  }
  name         = "teste_view"
  catalog_name = "`catalog-teste`"
  schema_name  = "teste_schema"
  table_type   = "VIEW"

  view_definition = format("SELECT name FROM %s WHERE id == 1", "catalog-teste.teste_schema.teste_table2")

  comment = "this view is managed by terraform"
}
```

### Expected Behavior

Create the view at catalog-teste.teste_schema.teste_view, the error occour when the catalog has an hyphen in it's name, if we use a catalog name "test" the view creation happen normally.

### Terraform and provider versions

$ terraform version
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.30.0
+ provider registry.terraform.io/hashicorp/aws v4.58.0
+ provider registry.terraform.io/hashicorp/null v3.2.2

Your version of Terraform is out of date! The latest version
is 1.6.4. You can update by downloading from https://www.terraform.io/downloads.html
$

### Is it a regression?

It didn't work on both 1.23.0 and at 1.30.0

### Debug Output

module.teste_view2.databricks_sql_table.table: Creating...
module.teste_view2.databricks_sql_table.table: Still creating... [10s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [20s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [30s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [40s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [50s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [1m0s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [1m10s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [1m20s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [1m30s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [1m40s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [1m50s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [2m0s elapsed]
module.teste_view2.databricks_sql_table.table: Still creating... [2m10s elapsed]
╷
│ Error: cannot create sql table: cannot execute CREATE VIEW ``catalog-teste``.`teste_schema`.`teste_view`
│ COMMENT 'this view is managed by terraform'
│ AS SELECT name FROM catalog-teste.teste_schema.teste_table2 WHERE id == 1;: [PARSE_SYNTAX_ERROR] Syntax error at or near 'catalog'.(line 1, pos 14)
│ 
│   with module.teste_view2.databricks_sql_table.table,
│   on modules/table/main.tf line 1, in resource "databricks_sql_table" "table":
│    1: resource "databricks_sql_table" "table" {
│ 
╵

**Comment by flaviomalavazi** [comment]
Hey, @alexandrebunn!
You may be missing a backtick in the query that contains the view definition. Could you try the following snippet instead?
```view_definition = format("SELECT name FROM %s WHERE id == 1", "`catalog-teste`.teste_schema.teste_table2")```

**Comment by mgyucht** [comment]
@alexandrebunn Given it's been nearly 30 days since the last update on this ticket with the proposed solution, I'll close this for now. Please re-open if the proposed solution still doesn't work for you.
