### ISSUE TITLE
databricks_cluster_policy should accept library{} blocks, currently accepts only libraries{} blocks

### ISSUE THREAD

**Issue by justindwhitney** [databricks/terraform-provider-databricks#2965]
This resource is documented as supporting library{} blocks:
https://github.com/databricks/terraform-provider-databricks/blob/e68f0d29c71293d925e82b5175a55d4196622afc/docs/resources/cluster_policy.md?plain=1#L58

But the SDK library.CreatePolicy struct from:
https://github.com/databricks/terraform-provider-databricks/blob/e68f0d29c71293d925e82b5175a55d4196622afc/policies/resource_cluster_policy.go#L13

Specifies Libraries[]:
https://github.com/databricks/databricks-sdk-go/blob/e0d1b0b6ba5bfea447a9e5f95d3d7e8659689145/service/compute/model.go#L1654

So in 1.30 libraries{} blocks succeed while library{} blocks currently fail.  Seems like the schema needs a helper to implement intended library{} block behavior?

**Comment by alexott** [comment]
Cluster & Jobs resources are using custom code to set new names on the structures defined inside the provider itself. Cluster policies are using Go SDK structures that don't have such aliases. The documentation was already updated to highlight this (#2934), but not released yet.
