### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster` resource

### ISSUE THREAD

**Issue by FORDBX4** [databricks/terraform-provider-databricks#2966]
Hello,

databricks_cluster defines "id" in its schema as an "optional" and a "computed" but if I try and define the id, it throws an error "Invalid or unknown key"

### Configuration

```hcl
terraform {
	required_providers {
		databricks = {
			source = "databricks/databricks"
			version = "1.30.0"
		}
	}
}
```

### Expected Behavior
```json
. . .
"id": {
        "type": "string",
        "description_kind": "plain",
        "computed": true
},
. . .
```

### Actual Behavior
```json
. . .
"id": {
        "type": "string",
        "description_kind": "plain",
        "optional": true,
        "computed": true
},
. . .
```

### Steps to Reproduce

1. terraform init
2. terraform providers schema -json

### Terraform and provider versions

Terraform v1.5.5
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.6.4. You can update by downloading from https://www.terraform.io/downloads.html

**Comment by FORDBX4** [comment]
> `id` is generated on the backend, you can't set it explicitly.

That is the case, but it is declared in the schema that `id` can optionally be set. As you have just pointed out, that is incorrect.

**Comment by alexott** [comment]
closing as outdated
