### ISSUE TITLE
[DOC] Updated documentation not reflected on `registry.terraform.io`

### ISSUE THREAD

**Issue by BasVerlooy** [databricks/terraform-provider-databricks#2967]
Hi all, I noticed that the documentation on registry.terraform.io is not up to date with what is available in this repository I believe. An example is the job resource [terraform docs](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job) has no mention of `condition_task`, while in [this file](https://github.com/databricks/terraform-provider-databricks/) there clearly is a mention of `condition_task`. I believe I'm looking at the correct versions for both Github and Terraform, but please correct me if I'm wrong.

**Comment by alexott** [comment]
Docs are published to the registry only when the release is done. This documentation update hasn't been released yet, so not on the registry. Use files in the repo for reference.
