### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster` resource

### ISSUE THREAD

**Issue by jefflaubtgcs** [databricks/terraform-provider-databricks#2976]
### Configuration

```hcl
resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = var.cluster_name
  spark_version           = data.databricks_spark_version.latest.id
  node_type_id            = var.node_type
  autotermination_minutes = var.autotermination_minutes
  spark_env_vars          = var.spark_env_vars
  init_scripts {
    workspace {
      destination = var.init_path_default.init_path
    }
  }
  spark_conf              = var.spark_conf
  depends_on              = [time_sleep.wait]
  autoscale {
    min_workers = var.min_workers
    max_workers = var.max_workers
  }
  custom_tags = {
    "ResourceClass" = "MultiNode"
  }
}
```

### Expected Behavior
Init_script should have been injected and Databricks Cluster started successfully.

### Actual Behavior
 Error: cannot create cluster: 1201-133137-m9sel7yu is not able to transition from TERMINATED to RUNNING: Init scripts failed. instance_id: 71e7ade16f5949229812426e8b937078, databricks_error_message: Cluster scoped init script /ETL/script.sh failed: Script exit status is non-zero, Termination info: code: INIT_SCRIPT_FAILURE, type: CLIENT_ERROR, parameters: map[databricks_error_message:Cluster scoped init script /ETL/script.sh failed: Script exit status is non-zero instance_id:71e7ade16f5949229812426e8b937078]. Please see https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterclusterstate for more details

### Steps to Reproduce
1.terraform init 
2.terraform select workspace
1. `terraform apply`

### Terraform and provider versions
Terraform v1.5.5
on windows_amd64
+ provider registry.terraform.io/databricks/databricks v1.30.0
+ provider registry.terraform.io/hashicorp/azuread v2.46.0
+ provider registry.terraform.io/hashicorp/azurerm v3.66.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.2

### Is it a regression?
Unknown. Since I have also seen this work. But seems to fail every time on a new deploy. Where on existing deploy only some of the time,

### Debug Output
"start_time": 1701438550603,
<   "state": "TERMINATED",
<   "state_message": "Init scripts failed. instance_id: 8c73ac7dd2484ed08a7f7f80776d4b79, databricks_error_message: Cl... (84 more bytes)",
<   "terminated_time": 1701438714201,
<   "termination_reason": {
<     "code": "INIT_SCRIPT_FAILURE",
<     "parameters": {
<       "databricks_error_message": "Cluster scoped init script /ETL/script.sh failed: Script exit status is non-zero",
<       "instance_id": "8c73ac7dd2484ed08a7f7f80776d4b79"
<     },
<     "type": "CLIENT_ERROR"
<   }
< }: @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/logger/logger.go:33 tf_provider_addr=registry.terraform.io/databricks/databricks tf_rpc=ApplyResourceChange @module=databricks tf_req_id=1dcb57e9-7b6f-a26c-694d-80bbfa7fdb2d tf_res
2023-12-01T08:51:58.249-0500 [DEBUG] provider.terraform-provider-databricks_v1.30.0.exe: Cluster 1201-134910-idib3ob4 is TERMINATED: Init scripts failed. instance_id: 8c73ac7dd2484ed08a7f7f80776d4b79, databricks_error_message: Cluster scoped init script /ETL/script
2023-12-01T08:51:58.249-0500 [ERROR] provider.terraform-provider-databricks_v1.30.0.exe: Cleaning up created cluster, that failed to start: 1201-134910-idib3ob4 is not able to transition from TERMINATED to RUNNING: Init scripts failed. instance_id: 8c73ac7dd2484ed08a7f7f
2023-12-01T08:51:58.466-0500 [DEBUG] provider.terraform-provider-databricks_v1.30.0.exe: POST /api/2.0/clusters/delete
> {
>   "cluster_id": "1201-134910-idib3ob4"
> }
< HTTP/2.0 200 OK
< {}: @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/logger/logger.go:33 tf_resource_type=databricks_cluster tf_req_id=1dcb57e9-7b6f-a26c-694d-80bbfa7fdb2d tf_rpc=ApplyResourceChange @module=databricks tf_provider_addr=registry.terr
2023-12-01T08:51:58.466-0500 [DEBUG] provider.terraform-provider-databricks_v1.30.0.exe: Waiting for state to become: [success]: timestamp=2023-12-01T08:51:58.466-0500
2023-12-01T08:51:58.524-0500 [DEBUG] provider.terraform-provider-databricks_v1.30.0.exe: GET /api/2.0/clusters/get?cluster_id=1201-134910-idib3ob4
< HTTP/2.0 200 OK
< {
<   "autoscale": {
<     "max_workers": 18,
<     "min_workers": 2,
<     "target_workers": 2
<   },
<   "autotermination_minutes": 30,
<   "azure_attributes": {
<     "availability": "ON_DEMAND_AZURE",
<     "first_on_demand": 1,
<     "spot_bid_max_price": -1
<   },
<   "cluster_id": "1201-134910-idib3ob4",
<   "cluster_name": "Job_cluster",
<   "cluster_source": "UI",
<   "creator_user_name": "70cf12e6-219f-46df-8ce7-61077585fb37",
<   "custom_tags": {
<     "ResourceClass": "MultiNode"
<   },

< {}: tf_provider_addr=registry.terraform.io/databricks/databricks tf_req_id=1dcb57e9-7b6f-a26c-694d-80bbfa7fdb2d @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/logger/logger.go:33 @module=databricks tf_resource_type=databricks_clus
2023-12-01T08:51:58.687-0500 [ERROR] provider.terraform-provider-databricks_v1.30.0.exe: Response contains error diagnostic: @caller=/home/runner/work/terraform-provider-databricks/terraform-provider-databricks/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/in
2023-12-01T08:51:58.688-0500 [DEBUG] states/remote: state read serial is: 158; serial is: 158
2023-12-01T08:51:58.688-0500 [DEBUG] states/remote: state read lineage is: 2d3b0229-e9fa-3a5d-4b12-3826567e607a; lineage is: 2d3b0229-e9fa-3a5d-4b12-3826567e607a
2023-12-01T08:51:58.692-0500 [DEBUG] Azure Backend Request:
HEAD /lp-byot/myDataBricksSetup-LP%2Fterraform.tfstateenv%3Astag HTTP/1.1
Host: keepitsecuresaas.blob.core.windows.net
User-Agent: HashiCorp Terraform/1.5.5 (+https://www.terraform.io)
X-Ms-Date: Fri, 01 Dec 2023 13:51:58 GMT
X-Ms-Lease-Id: df15b73e-ff6b-4234-b246-30b7afff34a0
X-Ms-Version: 2018-11-09
2023-12-01T08:51:58.818-0500 [DEBUG] Azure Backend Response for https://keepitsecuresaas.blob.core.windows.net/lp-byot/myDataBricksSetup-LP%2Fterraform.tfstateenv%3Astag:

### Important Factoids
Other debugging performed was issue occurs even when the init script is empty. Also add timers to the script same issue.

**Comment by alexott** [comment]
1. Enable cluster logs where you can look into script execution, maybe add `set -x` at the script beginning
2. Make sure that there is CAN_RUN permissions on the workspace file for cluster owner

**Comment by jefflaubtgcs** [comment]
Currently the script has Admins can Manage. What seems strange it the init script works fine if I deploy the Databricks Cluster without the script. Then I add the init script back into the terraform code and rerun terraform apply. I can even get the Databricks Cluster to start with the init_script, by manually deleting the Databricks cluster. Then rerun the terraform apply. The issue seems to only occur on setting up Databricks resources for the first time and then afterwards when this is the first time creating the Databricks Cluster.

**Comment by alexott** [comment]
It's hard to say without logs - I've created dozens of clusters in the last few days with init scripts as workspace files, and never had a problem

**Comment by jefflaubtgcs** [comment]
Log file

[databricks.log](https://github.com/databricks/terraform-provider-databricks/files/13529624/databricks.log)

**Comment by alexott** [comment]
Anyway, the error is coming from the backend, Terraform can't do anything with it. File the support ticket to investigate.

**Comment by alexott** [comment]
It looks like a problem with the init script, according to the message: `Script exit status is non-zero`. This is not a TF problem
