### ISSUE TITLE
[ISSUE] Issue with azure authentication in provider version 1.31

### ISSUE THREAD

**Issue by pmoosh** [databricks/terraform-provider-databricks#2999]
### Configuration

```hcl
terraform {
  required_providers {
    databricks = {
      source = "databricks/databricks"
    }
  }
}
```

### Expected Behavior
Authentication should work as it did with provider version 1.30

### Terraform and provider versions

Terraform version is 1.5.7

```
02:40:52  Initializing provider plugins...
02:40:52  - terraform.io/builtin/terraform is built in to Terraform
02:40:52  - Finding latest version of hashicorp/azuread...
02:40:52  - Finding latest version of hashicorp/random...
02:40:52  - Finding latest version of hashicorp/aws...
02:40:52  - Finding latest version of hashicorp/local...
02:40:52  - Finding latest version of hashicorp/null...
02:40:52  - Finding latest version of hashicorp/azurerm...
02:40:52  - Finding latest version of hashicorp/time...
02:40:52  - Finding latest version of databricks/databricks...
02:40:52  - Finding latest version of hashicorp/tls...
02:40:52  - Installing hashicorp/random v3.6.0...
02:40:52  - Installed hashicorp/random v3.6.0 (signed by HashiCorp)
02:40:52  - Installing hashicorp/aws v5.29.0...
02:40:55  - Installed hashicorp/aws v5.29.0 (signed by HashiCorp)
02:40:55  - Installing hashicorp/local v2.4.0...
02:40:56  - Installed hashicorp/local v2.4.0 (signed by HashiCorp)
02:40:56  - Installing hashicorp/time v0.9.2...
02:40:56  - Installed hashicorp/time v0.9.2 (signed by HashiCorp)
02:40:56  - Installing hashicorp/tls v4.0.5...
02:40:56  - Installed hashicorp/tls v4.0.5 (signed by HashiCorp)
02:40:56  - Installing hashicorp/azuread v2.46.0...
02:40:56  - Installed hashicorp/azuread v2.46.0 (signed by HashiCorp)
02:40:56  - Installing hashicorp/azurerm v3.83.0...
02:40:59  - Installed hashicorp/azurerm v3.83.0 (signed by HashiCorp)
02:40:59  - Installing databricks/databricks v1.31.0...
02:40:59  - Installed databricks/databricks v1.31.0 (self-signed, key ID 92A95A66446BCE3F)
02:40:59  - Installing hashicorp/null v3.2.2...
02:40:59  - Installed hashicorp/null v3.2.2 (signed by HashiCorp)
```

### Is it a regression?

By setting the provider version back to 1.30 it works again 

### Debug Output
```
Error: default auth: azure-client-secret: resolve host: resolve workspace: token: oauth2: cannot fetch token: 
02:41:12  │ Response: {"token_type":"Bearer","expires_in":"3599","ext_expires_in":"3599","expires_on":"1701862868","not_before":"1701858968","resource":"https://management.azure.com/","access_token":"ZZZZZZZZZZZZZZZZ"}. Config: azure_workspace_resource_id=/subscriptions/****/resourceGroups/adbc-databricks/providers/Microsoft.Databricks/workspaces/datasource, azure_client_secret=***, azure_client_id=****, azure_tenant_id=****. Env: ARM_CLIENT_SECRET, ARM_CLIENT_ID, 
```

**Comment by firevegeta** [comment]
> There could be changes in the Go SDK where some refactoring was done

Is there a possibility that the problem can be solved by us as users, through a different configuration?

Or is this a problem that needs to be investigated and checked by the developers?

**Comment by mgyucht** [comment]
I just tested the Go SDK on `main`, and I believe the issue has already been fixed but not yet released. https://github.com/databricks/databricks-sdk-go/commit/2dbf06aac25d25f7cddc164c175a24001be6a6d5#diff-dee6ad9ad3aba46844b4d0037da3aaeab2aec544f8b496cda788c786e676c730R41-R42 ensures that the RoundTrip() implementation properly sets the Status and StatusCode on the http.Response object. I'm working on a release and hope to have the fix merged into TF and released by EOD.

**Comment by mgyucht** [comment]
Databricks Go SDK Release v0.26.2 is complete. @tanmay-db will handle releasing a patch release of the TF provider with this fix.

**Comment by firevegeta** [comment]
Amazing!
Thank you so much for the fast response!

**Comment by tanmay-db** [comment]
Hi @firevegeta @pmoosh, release has been done: https://github.com/databricks/terraform-provider-databricks/releases/tag/v1.31.1. The issue should be resolved by this, can you please confirm? Thanks!

**Comment by pmoosh** [comment]
@tanmay-db - I can confirm it works with:
`Installing databricks/databricks v1.31.1..`

thank you

**Comment by firevegeta** [comment]
@tanmay-db i can also confirm that v.1.31.1 fixed the Problem

Thank you!
