### ISSUE TITLE
[ISSUE] Issue with provider `databricks` resource

### ISSUE THREAD

**Issue by tylerhains** [databricks/terraform-provider-databricks#3008]
### Configuration
```hcl
// initialize provider in "MWS" mode to provision new workspace
provider "databricks" {
  alias    = "mws"
  host     = "https://accounts.cloud.databricks.com"
  client_id = "318477c1-e16d-402e-8ba5-46653a2c98e1"
  client_secret = "<omitted for security>"
  account_id = "67533872-e1d4-4932-b025-0642043fb05c"
}
```

### Expected Behavior
We should be able to connect to our account and create resources.

### Actual Behavior
Error: cannot create mws credentials: default auth: cannot configure default credentials. Config: host=https://accounts.cloud.databricks.com

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
Terraform v1.6.4
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.29.0
+ provider registry.terraform.io/hashicorp/aws v5.25.0
+ provider registry.terraform.io/hashicorp/time v0.9.1

Your version of Terraform is out of date! The latest version
is 1.6.5. You can update by downloading from https://www.terraform.io/downloads.html

### Is it a regression?
We had some consultants who were able to use the username/password authentication method, but we wanted to use a service account for our production process.

### Debug Output
https://gist.github.com/tylerhains/47630553f4831a10f008a9adb53ad0b6

### Important Factoids
We're using a pay-as-you-go account for Databricks.

**Comment by mgyucht** [comment]
Great, glad you were able to work this out.
