### ISSUE TITLE
[ISSUE] enable_serverless_compute needs to be 'true' by default

### ISSUE THREAD

**Issue by Satyadeepak-Databricks** [databricks/terraform-provider-databricks#3009]
### Expected Behavior
By default `enable_serverless_compute` needs to be true

Currently by default `enable_serverless_compute` is false. Please set this to true by default

// GlobalConfig used to generate Terraform resource schema and bind to resource data
GoogleServiceAccount    string            `json:"google_service_account,omitempty"`
	EnableServerlessCompute bool              `json:"enable_serverless_compute,omitempty" tf:"default:false"`
	SqlConfigParams         map[string]string `json:"sql_config_params,omitempty"`
}

### Actual Behavior
Customer is getting SQL Serverless connection fails to connect and something changed the flag to serverless enabled = false?

**Comment by tanmay-db** [comment]
Hi @alexott, just to confirm but I think https://github.com/databricks/terraform-provider-databricks/issues/1436 needs to be resolved before we can make this as default right?

**Comment by alexott** [comment]
No, it's not required... But we need to be careful as it's a behavior change. Maybe we just need to remove the default value and allow the backend to set a default value. But then we'll need to handle `omitempty` with `ForceSendFields`

**Comment by cpanpalia** [comment]
Hi, this is a big blocker for us as well. We want to create Classic SQL warehouse with terraform and it just fails. Help is much appreciated here, thanks.

**Comment by mgyucht** [comment]
Just to confirm: this has to do with databricks_sql_global_config, not databricks_sql_endpoint, correct @Satyadeepak-Databricks?

I think we can make this change and announce it in release notes. It is a breaking change for those relying on default values, but it does match the documented experience for serverless.

**Comment by AbishekS01** [comment]
Hi @alexott one more customer also facing the same issue, do we have any ETA for this fix 

databricks_sql_endpoint.sql-endpoint-classic-small: Modifying... [id=9659a1067a9318d6]
╷
│ Error: cannot update sql endpoint: Invalid warehouseType: Serverless is only available for PRO warehouses.
│ 
│  with databricks_sql_endpoint.sql-endpoint-classic-small,
│  on main.tf line 16, in resource "databricks_sql_endpoint" "sql-endpoint-classic-small":
│  16: resource "databricks_sql_endpoint" "sql-endpoint-classic-small" {
│ 
╵

![image](https://github.com/databricks/terraform-provider-databricks/assets/105917367/b7428479-6107-4b40-b340-38096dd7b3b5)

**Comment by mgyucht** [comment]
@AbishekS01 What has the user set for `warehouse_type`? I think it needs to be set to `"PRO"` to use serverless.

**Comment by cpanpalia** [comment]
> @AbishekS01 What has the user set for `warehouse_type`? I think it needs to be set to `"PRO"` to use serverless.

Hi @mgyucht, we are trying to create classic sql warehouse, but not able to create them.

**Comment by mgyucht** [comment]
@cpanpalia @AbishekS01 @Satyadeepak-Databricks Sorry if I'm misunderstanding, but is the issue with `databricks_sql_endpoint` or `databricks_sql_global_config`, or an interaction between the two? This issue appears to be about `databricks_sql_global_config`, but it is confusing as both resources have an `enable_serverless_endpoint` parameter.

We can change the default for `enable_serverless_compute` to true, meaning that people who add `databricks_sql_global_config` to their TF modules will have a different default behavior after this change. However, existing users will still need to explicitly set this value. The current version of the TF SDK does not allow us to easily check whether or not a user has set a value in the config, in which case we would fall back to the API default, especially if a value had been explicitly set before.

I have just tested the following:

```
resource databricks_sql_global_config conf {
    enable_serverless_compute = true # This can also be missing, as it is not required when creating classic SQL warehouses.
}

resource databricks_sql_endpoint endpoint {
  name = "sql-endpoint"
  cluster_size     = "Small"
  max_num_clusters = 1
  warehouse_type = "CLASSIC"
  enable_serverless_compute = false
}
```
This works and creates a non-serverless SQL warehouse.

**Comment by cpanpalia** [comment]
> @cpanpalia @AbishekS01 @Satyadeepak-Databricks Sorry if I'm misunderstanding, but is the issue with `databricks_sql_endpoint` or `databricks_sql_global_config`, or an interaction between the two? This issue appears to be about `databricks_sql_global_config`, but it is confusing as both resources have an `enable_serverless_endpoint` parameter.
> 
> We can change the default for `enable_serverless_compute` to true, meaning that people who add `databricks_sql_global_config` to their TF modules will have a different default behavior after this change. However, existing users will still need to explicitly set this value. The current version of the TF SDK does not allow us to easily check whether or not a user has set a value in the config, in which case we would fall back to the API default, especially if a value had been explicitly set before.
> 
> I have just tested the following:
> 
> ```
> resource databricks_sql_global_config conf {
>     enable_serverless_compute = true # This can also be missing, as it is not required when creating classic SQL warehouses.
> }
> 
> resource databricks_sql_endpoint endpoint {
>   name = "sql-endpoint"
>   cluster_size     = "Small"
>   max_num_clusters = 1
>   warehouse_type = "CLASSIC"
>   enable_serverless_compute = false
> }
> ```
> 
> This works and creates a non-serverless SQL warehouse.

Hi @mgyucht after upgrading our TF provider it worked. We had the serverless workflow enabled from global config and when we were trying to create a classic workflow it wasn’t letting us via TF. Thanks for pushing out the changes.
