### ISSUE TITLE
[ISSUE] Issue with `databricks_catalog` resource

### ISSUE THREAD

**Issue by zshao9** [databricks/terraform-provider-databricks#3014]
There is still a bug in the Terraform provider: In most cases, it simply *ignores the `metastore_id` attribute of a resource*
specification and default to the one assigned to the workspace. IMO it should simply error out if the *metastore_id* doesn't match the workspace's default metastore.

See an example <https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/catalog#example-usage>
where `metastore_id` is an attribute:

```
resource "databricks_catalog" "sandbox" {
  metastore_id = databricks_metastore.this.id
  name         = "sandbox"
  comment      = "this catalog is managed by terraform"
  properties = {
    purpose = "testing"
  }
}
```

### Expected Behavior
The catalog should be created on the metastore specified by metastore_id.  or if metastore doesn't match, let's just output an error.

### Actual Behavior
The catalog is actually created on the metastore assigned to the workspace (from the provider).

**Comment by mgyucht** [comment]
@nkvuong can we use https://docs.databricks.com/api/workspace/metastores/current to check?

**Comment by hectorcast-db** [comment]
Hi @zshao9 
The `metastore_id` is only used for account-level settings. For workspace-level it is indeed ignored. As requested, we added a validation to the workspace-level to ensure that it matches the one assigned to the worskpace. 
The validation will be added to the next release:
https://github.com/databricks/terraform-provider-databricks/pull/3035
