### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_table` resource. When we pass SQL using a here-document, differences appear even though there have been no changes.

### ISSUE THREAD

**Issue by case-k-git** [databricks/terraform-provider-databricks#3019]
issue with `databricks_sql_table` resource. When we pass SQL using a here-document, differences appear even though there have been no changes. if we does not pass by here-document it will not detect the changes.

To add a view in Terraform without modifying the tf file. The SQL file used for the view is managed as a separate file(.sql) and passed as follows configuration. At this time, the SQL file is passed as a here-document and is detected as a change even though it has not been modified. I want to resolve this issue as it decreases deployment performance.

### Configuration

```hcl
# Copy-paste your Terraform configuration here
resource "databricks_sql_table" "views" {
  for_each = local.sql-association-map-read-from-json

  catalog_name    = each.value.catalog_name
  name            = each.value.name
  schema_name     = each.value.schema_name
  table_type      = "VIEW"
  view_definition =  each.value.sql
}
```

### Expected Behavior

Not detected as a difference in 'terraform plan'. Because not changing SQL

### Actual Behavior

 differences appear even though there have been no changes. if we does not pass by here-document it will not detect the changes

here-document
```
  # databricks_sql_table.views["table"] will be updated in-place
  ~ resource "databricks_sql_table" "views" {
        id              = "catalog.schema.table"
        name            = "table"
      ~ view_definition = <<-EOT
            SELECT * FROM catalog.schema.table
        EOT
        # (4 unchanged attributes hidden)

        # (10 unchanged blocks hidden)
    }
```

### Terraform and provider versions

- terraform 1.5.2
- databricks 1.29.0
### Debug Output

```
  # databricks_sql_table.views["table"] will be updated in-place
  ~ resource "databricks_sql_table" "views" {
        id              = "catalog.schema.table"
        name            = "table"
      ~ view_definition = <<-EOT
            SELECT * FROM catalog.schema.table
        EOT
        # (4 unchanged attributes hidden)

        # (10 unchanged blocks hidden)
    }
```

**Comment by case-k-git** [comment]
May be related to this issue
https://github.com/hashicorp/terraform-provider-aws/issues/9042

**Comment by anineharto** [comment]
I'm also experiencing the same issue ➕

**Comment by case-k-git** [comment]
I have found workaround using trimspace can avoid this issue. 

```
resource "databricks_sql_table" "views" {
  for_each = local.sql-association-map-read-from-json

  catalog_name    = each.value.catalog_name
  name            = each.value.name
  schema_name     = each.value.schema_name
  table_type      = "VIEW"
  view_definition =  trimspace(each.value.sql)
}
```
https://developer.hashicorp.com/terraform/language/functions/trimspace
https://github.com/fastly/terraform-provider-fastly/issues/123#issuecomment-685204954

**Comment by rondefreitas** [comment]
@case-k-git thank you for that workaround. You just saved me from spending another 2 hours of pulling my hair out.

**Comment by trico** [comment]
Also putting the trimspace this way worked for me

```  
params = {
    query = trimspace(<<-EOT
        select * from all
   EOT
   )
```
