### ISSUE TITLE
[ISSUE] Issue with `databricks_1.31.1` provider invalid Configuration

### ISSUE THREAD

**Issue by logically-sankit** [databricks/terraform-provider-databricks#3023]
Hi team,

Currently running the IAC under these versions

 ```
Terraform v1.6.5
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.31.1
+ provider registry.terraform.io/hashicorp/aws v5.30.0
+ provider registry.terraform.io/hashicorp/random v3.6.0
```
Previously I was using version 1.29.0 and everything was working fine. I updated the version number and ran `terrafrom init -upgrade`. since then getting the below error

```
╷
│ Error: default auth: oauth-m2m: oidc: fetch .well-known: Get "/oidc/.well-known/oauth-authorization-server": unsupported protocol scheme "". Config: client_id=***, client_secret=***. Env: DATABRICKS_CLIENT_ID, DATABRICKS_CLIENT_SECRET
│ 
│   with provider["registry.terraform.io/databricks/databricks"],
│   on <empty> line 0:
│   (source code not available)
│ 
╵
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/databricks/databricks" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│ 
╵
Operation failed: failed running terraform plan (exit 1)
```

below is the file where I'm defining the provider 

```
terraform {
  cloud {
    organization = "***"

    workspaces {
      name = "general"
    }
  }
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.31.1"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.30.0"
    }
  }
}

provider "databricks" {
  alias         = "mws"
  host          = var.databricks_account_host
  account_id    = var.databricks_account_id
}

provider "aws" {
  region = var.aws_region
}
```
The CLIENT_ID and CLIENT_SECRET are set as env variables in Terrafrom cloud and I'm triggering the run from CLI.

Please help resolve this issue

**Comment by mgyucht** [comment]
@logically-sankit thanks for the report. Can you please include debug logs by setting TF_LOG=debug when applying your TF template? This error comes from the Go SDK, but it suggests that the provider is not correctly configured with the host & account ID. See https://github.com/databricks/databricks-sdk-go/blob/main/config/auth_m2m.go#L56:

```go
func oidcEndpoints(ctx context.Context, cfg *Config) (*oauthAuthorizationServer, error) {
	prefix := cfg.Host
	if cfg.IsAccountClient() && cfg.AccountID != "" {
		// TODO: technically, we could use the same config profile for both workspace
		// and account, but we have to add logic for determining accounts host from
		// workspace host.
		prefix := fmt.Sprintf("%s/oidc/accounts/%s", cfg.Host, cfg.AccountID)
		return &oauthAuthorizationServer{
			AuthorizationEndpoint: fmt.Sprintf("%s/v1/authorize", prefix),
			TokenEndpoint:         fmt.Sprintf("%s/v1/token", prefix),
		}, nil
	}
	oidc := fmt.Sprintf("%s/oidc/.well-known/oauth-authorization-server", prefix)
	var oauthEndpoints oauthAuthorizationServer
	err := cfg.refreshClient.Do(ctx, "GET", oidc,
		httpclient.WithResponseUnmarshal(&oauthEndpoints))
	if err != nil {
		return nil, errOAuthNotSupported
	}
	return &oauthEndpoints, nil
}
```
Account-level provider should go down the if branch, but it seems like you're going down the else branch. What are you specifying for those variables?

**Comment by logically-sankit** [comment]
Hi @mgyucht. appreciate the help

Well, I'm passing the variables using Terraform Cloud, below are the definitions 

```
variable "databricks_account_id" {
  description = "Databricks account Id"
  type        = string
}

variable "databricks_account_host" {
  type        = string
  description = "Databricks account URL"
  default = "https://accounts.cloud.databricks.com"  ## Takes the default value as the variable is not defined in Terraform Cloud
}
```

And yes, I'm using the version below, and everything is working as expected.

```
Terraform v1.6.5
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.29.0
+ provider registry.terraform.io/hashicorp/aws v5.30.0
+ provider registry.terraform.io/hashicorp/random v3.6.0

Your version of Terraform is out of date! The latest version
is 1.6.6. You can update by downloading from https://www.terraform.io/downloads.html
```

if if update the version on my main.tf file and run `terraform init -upgrade` and then run `terraform plan`. This happens

### Current Version

```
Terraform v1.6.5
on linux_amd64
+ provider registry.terraform.io/databricks/databricks v1.32.0
+ provider registry.terraform.io/hashicorp/aws v5.30.0
+ provider registry.terraform.io/hashicorp/random v3.6.0

Your version of Terraform is out of date! The latest version
is 1.6.6. You can update by downloading from https://www.terraform.io/downloads.html
```

### RUN in Debug mode

```
2023-12-20T16:03:38.731+0530 [INFO]  Terraform version: 1.6.5
2023-12-20T16:03:38.732+0530 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2023-12-20T16:03:38.732+0530 [DEBUG] using github.com/hashicorp/hcl/v2 v2.19.1
2023-12-20T16:03:38.732+0530 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2023-12-20T16:03:38.732+0530 [DEBUG] using github.com/zclconf/go-cty v1.14.1
2023-12-20T16:03:38.732+0530 [INFO]  Go runtime version: go1.21.3
2023-12-20T16:03:38.732+0530 [INFO]  CLI args: []string{"terraform", "apply"}
2023-12-20T16:03:38.732+0530 [DEBUG] Attempting to open CLI config file: /home/sankit/.terraformrc
2023-12-20T16:03:38.732+0530 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2023-12-20T16:03:38.732+0530 [INFO]  Loading CLI configuration from /home/sankit/.terraform.d/credentials.tfrc.json
2023-12-20T16:03:38.732+0530 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2023-12-20T16:03:38.732+0530 [DEBUG] ignoring non-existing provider search directory /home/sankit/.terraform.d/plugins
2023-12-20T16:03:38.732+0530 [DEBUG] ignoring non-existing provider search directory /home/sankit/.local/share/terraform/plugins
2023-12-20T16:03:38.732+0530 [DEBUG] ignoring non-existing provider search directory /usr/share/ubuntu/terraform/plugins
2023-12-20T16:03:38.732+0530 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2023-12-20T16:03:38.732+0530 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2023-12-20T16:03:38.732+0530 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2023-12-20T16:03:38.732+0530 [INFO]  CLI command args: []string{"apply"}
2023-12-20T16:03:38.735+0530 [DEBUG] Service discovery for app.terraform.io at https://app.terraform.io/.well-known/terraform.json
2023-12-20T16:03:41.507+0530 [DEBUG] Service discovery for app.terraform.io aliased as localterraform.com
2023-12-20T16:03:42.899+0530 [DEBUG] checking for provisioner in "."
2023-12-20T16:03:42.904+0530 [DEBUG] checking for provisioner in "/usr/bin"
2023-12-20T16:03:43.264+0530 [INFO]  cloud: starting Apply operation
...
...
╷
│ Error: default auth: oauth-m2m: oidc: databricks OAuth is not supported for this host. Config: client_id=20e7cb01-f22d-451a-9e4d-80a4cc4e29e1, client_secret=***. Env: DATABRICKS_CLIENT_ID, DATABRICKS_CLIENT_SECRET
│ 
│   with provider["registry.terraform.io/databricks/databricks"],
│   on <empty> line 0:
│   (source code not available)
│ 
╵
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/databricks/databricks" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│ 
╵
Operation failed: failed running terraform plan (exit 1)
```

Well the IF clause only checks if the host starts with a prefix pattern(which it does) and account _id is not null. So it should work but not sure.

**Comment by logically-sankit** [comment]
> I am getting similar issue with the latest provider build 1.33.0. My use case is configuring a workspace provider in the same module where it would be created, so the workspace doesnt exist yet. The error happens in the plan phase.
> 
> `provider "databricks" { alias = "reserve_workspace" host = databricks_mws_workspaces.this.workspace_url client_id =*** client_secret = *** account_id = var.databricks_account_id }`
> 
> default auth: oauth-m2m: oidc: databricks OAuth is not supported for this host. Config: account_id=, client_id=_**, client_secret=**_ │ │ with provider["registry.terraform.io/databricks/databricks"].reserve_workspace, │ on providers.tf line 19, in provider "databricks":

@huzaifak I don't think this is related to the issue I posted. But I understand what you are trying to accomplish, I have tried something similar but apparently, it's impossible on Terraform. Terraform starts its execution with provider blocks so you can't use one provider block's output into another. I also tried adding depend_on in the provider block but that also failed. I got to know this from an issue posted. I created two different projects to take care of it, not ideal but works. hope it helps!

**Comment by huzaifak** [comment]
@logically-sankit that's not correct, i am able to get this to work on 1.29.0 it only breaks from 1.30.0 onwards. I even found some comments in provider code to be able to handle the situation where workspace might not exist yet when creating a provider. Maybe it's different, but since the error is exactly the same i would like the dev team to look and comment as well.

**Comment by mgyucht** [comment]
@huzaifak @logically-sankit: Terraform does allow this but it doesn't treat provider blocks in the same way as normal resources/data sources from a dependency perspective. If you do this, you need to do a targeted apply to create all dependencies of the provider block before applying any resources from the provider block.

What is confusing to me is that the error message

> default auth: oauth-m2m: oidc: databricks OAuth is not supported for this host. Config: client_id=20e7cb01-f22d-451a-9e4d-80a4cc4e29e1, client_secret=***. Env: DATABRICKS_CLIENT_ID, DATABRICKS_CLIENT_SECRET

lists all of the configuration that was specified to the provider. Here, `client_id` and `client_secret` are listed, but not `host` or `account_id`.

I'm going to take a look at changes to the Go SDK & the TF provider between 1.29 and 1.30 to figure out what broke here.

**Comment by mgyucht** [comment]
@huzaifak @logically-sankit can you share the full logs from this? Specifically, do you see `Explicit and implicit attributes` from https://github.com/databricks/terraform-provider-databricks/blob/master/provider/provider.go#L238 in your log anywhere?

**Comment by mgyucht** [comment]
I think I know what the issue is here. Because the oauth2 library caches the context used when constructing the token source, and that context may have a timeout, refreshing OAuth tokens eventually fails once that timeout is reached. This was a first pass to fix that problem, but it seems like we would need to add additional error cases in the if statement after authenticating.

Since then, we have refactored the OAuth token refresh client in the Go SDK to use context.Background(). This prevents users from overriding the HTTP client used for token refresh, but we control that in the Go SDK anyways. This means that we can remove the auth-at-configure-time logic from TF and rely on the Go SDK to correctly refresh credentials without a timeout.
