### ISSUE TITLE
[ISSUE] Issue with `databricks_storage_credential` resource

### ISSUE THREAD

**Issue by zshao9** [databricks/terraform-provider-databricks#3031]
A better error message could be displayed instead of:

```
Error: cannot read storage credential: invalid character '<' looking for beginning of value
│ 
│   with databricks_storage_credential.storage_credential,
│   on main.tf line 66, in resource "databricks_storage_credential" "storage_credential":
│   66: resource "databricks_storage_credential" "storage_credential" {
```

I suspect that the API server sometimes return a XML error message instead of whatever format was anticipated.

### Configuration
I specifically was using the databrick.workspace level provider.

I first run "terraform apply" with one user name, and then run "terraform plan" with a second user name, and "terraform plan" throws out this error.

Both users are users of the Databricks workspace.

### Expected Behavior
Good error message

### Actual Behavior
Error: cannot read storage credential: invalid character '<' looking for beginning of value

### Terraform and provider versions
Databricks provider 1.31.1
Terraform 1.1.3

**Comment by alexott** [comment]
Have you checked the [troubleshooting guide](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting)?

We need to make Go SDK to produce better errors for this case. Cc: @mgyucht 

P.S. @zshao9 - I sent you a message on LI, can you please answer?

**Comment by zshao9** [comment]
Thanks Alex!  I will try.  The problem is that the error is only seen in
our CI system (and not my local environment) and I don't have a way (yet)
to get our CI to run with TF_LOG=TRACE.  Still the error message could be
improved anyway.

**Comment by zshao9** [comment]
Sorry I couldn't modify our CI system.  Can someone help explain what does "invalid character '<' looking for beginning of value" mean?  I am pretty sure it's internal to the provider (and the underlying API server) since my terraform code doesn't have a '<' char at all. 😄

**Comment by alexott** [comment]
It's really coming from the Go SDK that handles all work with REST APIs. It's also one of the quirks of REST API that returns HTML page if the API call is missing something in path...

**Comment by mgyucht** [comment]
@alexott is right. The underlying SDK assumes that all responses follow a standard format (JSON) so that it can consistently parse and present error messages to users. Certain APIs don't behave this way, instead returning an HTML page. However, because this page is not structured in a consistent way (it could be any HTML page), we can't consistently retrieve the error message embedded within it (if there is one there at all). 

To figure out why your template triggered this error, we'll need to see a bit more about the setup (specifically, the configuration for this resource and the provider block). @zshao9 can you include this info in the issue description?

**Comment by mgyucht** [comment]
In the meantime, I'm working on a PR to improve the error message returned from the Go SDK to include more debugging information for this case.

**Comment by zshao9** [comment]
This error `invalid character '<' looking for beginning of value` has completely disappeared in `v1.32.0`.

Thanks @mgyucht for the quick response!
