### ISSUE TITLE
[FEATURE] Support for granting privileges to Unity Catalog functions

### ISSUE THREAD

**Issue by vadivelselvaraj** [databricks/terraform-provider-databricks#3036]
Currently, there isn't a way to grant privileges to Unity Catalog functions defined within a schema.

### Use-cases
- Grant explicit access to a list of UC functions within a schema i.e cases where privileged inheritance cannot be done.

### Proposal
```hcl
resource "databricks_grants" "foo_udf_grant" {
  function = "main.reporting.foo"
  grant {
    principal  = "Data Engineers"
    privileges = ["EXECUTE"]
  }
}
```

### References
- https://docs.databricks.com/en/data-governance/unity-catalog/manage-privileges/privileges.html#privilege-types-by-securable-object-in-unity-catalog

**Comment by nkvuong** [comment]
@vadivelselvaraj your code snippet should already work - we just need to add documentation for it
