### ISSUE TITLE
Update `databricks_model_serving` resource to match latest API spec/SDK

### ISSUE THREAD

**Issue by alexott** [databricks/terraform-provider-databricks#3067]
We need to make a number of changes in `databricks_model_serving` to make it matching to latest API spec:

- Document new configuration options: `rate_limits`, `tags`, `config.auto_capture_config`
- Add `ForceNew` to some fields of `config.auto_capture_config`
- Add deprecation message to `config.served_models` to use `config.served_entities` instead
- Use `config.served_entities` instead of `config.served_models` to support foundational models, etc.

**Comment by mgyucht** [comment]
@michael-berk @840 can one of you help with this?

**Comment by 840** [comment]
Sure, I'll review it!
