### ISSUE TITLE
[DOC] Authentication section does not include OAuth

### ISSUE THREAD

**Issue by ACSmith07** [databricks/terraform-provider-databricks#3094]
The Authentication section for the overall provider guide does not mention OAuth as an authentication option, even though it seems to be best/preferred. The list of 3 supported authentications is thus also incorrect. 

[Header Link](https://registry.terraform.io/providers/databricks/databricks/0.4.9/docs#authentication)

Oauth documentation on the main Databricks docs is also incomplete/misleading that when connecting to a workspace the account_id is no longer required when it is. A TF code sample for a provider databricks.workspace block would be very valuable. Sussing out this error cost me several hours, and a consultant agreed the docs are incorrect and they also had to deduce the error for other clients.

As a minor note, the list of authentication methods also doesn't match the following headers with details - Config file auth is missing from the bullet list, while Azure AD Tokens is bulleted but does not have a header & details. Azure AD Tokens does have external links, maybe those cover it, I'm not an Azure user.

### Affected Resource(s)
https://registry.terraform.io/providers/databricks/databricks/0.4.9/docs#authentication
![image](https://github.com/databricks/terraform-provider-databricks/assets/7284601/f0156484-ac19-4538-8137-f702fc7db65d)

### Expected Details
Header & discussion of Oauth provider blocks, with sample code. Ideally for both Account and Workspace operations.

### List of things to potentially add/remove:
See above.

### Important Factoids
Databricks existing docs on Oauth, including for Terraform specifically, do not make clear that account_id is required even in a workspace-level provider block, It would be great if this could be clarified too.

**Comment by ACSmith07** [comment]
Good catch. This is the page Google landed me on from googling mws_create_workspace then clicking up to the overview to figure out my bug. FWIW. Looking at the auth section on latest version there's still similar issues, I'll update my issue to be accurate to the latest version now.

**Comment by alexott** [comment]
The samples for provider configuration are in the guides or in the terraform examples repo. Workspace or account level providers are distinguished by parameters - the rest is just normal TF aliases that are required only if you use both account & workspace level providers in the same module

**Comment by ACSmith07** [comment]
You can close this issue, I'm not able to replicate the problem Oauth behavior at the root of the issue, though I saw adding account_id resolve failed Oauth, and then had same confirmed by a Databricks Partner consultant that they've had the same issue, and same resolution, with multiple clients.

What's the expected discovery path for the Examples Repo? I'm not saying this to be snarky, but I've been coding at this configuration for several weeks, with support from a Databricks SA, the Partner consultant, extensive googling & blog reading, and reading tons of the docs and this is the first reference to it I've seen. It looks like a killer resource that would have saved me a ton of time if it was more discoverable.

**Comment by alexott** [comment]
It's basically linked from the top-level page of the documentation (the lower rectangle).

![Screenshot 2024-01-10 at 08 46 58](https://github.com/databricks/terraform-provider-databricks/assets/30342/5d50ae4d-1931-4a45-b2f2-fb46a57306d2)

Can you drop me an email to alexey.ott at databricks.com with more details about what caused most of the problems, etc.?

btw, we have a public [specialist session on Terraform](https://pages.databricks.com/databricks-specialist-sessions.html) next week, so you're welcome to attend and ask questions (at least register to watch it in recording).

We have [discussions](https://github.com/databricks/terraform-databricks-examples/discussions) at terraform examples repository, although I would recommend to use [Databricks Community](https://community.databricks.com/) forum to ask questions, etc.

**Comment by ACSmith07** [comment]
Hey Alex, sorry I didn't get to respond here. We're in super-crunch mode
trying to get this data platform live for users. I appreciate the extra
resources you sent over and intend to review them soon as I have a few
spare hours.

In the meantime, here's an example of frustrating docs that came up today.
Not TF related, and no answer/action expected. Just to give you some color
on what I was frustrated with. It's the teams message I sent our account
reps, sorry for an odd format. This is the link.
https://docs.databricks.com/api/workspace/clusters/create

[image: image.png]


Adam

**Comment by alexott** [comment]
I don't see the image, but if you find problem with specific documentation page, open github issue...
