### ISSUE TITLE
[ISSUE] Issue with `databricks_mws_private_access_settings` resource

### ISSUE THREAD

**Issue by rcmarxDBX** [databricks/terraform-provider-databricks#3102]
### Configuration

Standing up a new environment using Terraform in a PSC-enabled GCP environment

# Copy-paste your Terraform configuration here
public_access_enabled = false
...This is set in the databricks_mws_private_access_settings  resource
Databricks support had indicated to use public_network_access_enabled=false,  however, when trying to use this attribute, it was flagged as incorrect syntax.   "Unexpected Attribute"

### Expected Behavior
Public Access Enabled should have been "DISABLED" in the Acccount Console UI

### Actual Behavior
Public Access Enabled was actually left as "ENABLED" in teh Account Console UI

### Steps to Reproduce
PSC environment in GCP
Try to set public_access_enabled=false

**Comment by caveman8fb** [comment]
This appears to a duplicate of this old issue that we are also running into.
https://github.com/databricks/terraform-provider-databricks/issues/2273

**Comment by tanmay-db** [comment]
Hi @rcmarxDBX, thanks for raising this, we are working on other higher priority issues at the moment and will take a look at this one.

**Comment by hectorcast-db** [comment]
Hi @rcmarxDBX 
Thanks again for raising this. We have addressed this and the fix will be added to the next release:
https://github.com/databricks/terraform-provider-databricks/pull/3132
