### ISSUE TITLE
[FEATURE] New account-level resource - Network Connectivity Configuration (NCC)

### ISSUE THREAD

**Issue by w0ut0** [databricks/terraform-provider-databricks#3104]
### Use-cases

There is a [public preview](https://learn.microsoft.com/en-us/azure/databricks/security/network/serverless-network-security/serverless-private-link) for private connectivity to serverless compute using private link. This is a feature request to add 1 (or more) resource(s) for Network Connectivity Configuration (NCC).

### Attempted Solutions
We have manually added the configuration, but would like to do it using 

### Proposal

Resources
```
databricks_network_connectivity_configuration

databricks_network_connectivity_configuration_workspace_binding

databricks_network_connectivity_configuration_private_endpoint_rule
```

### References
https://learn.microsoft.com/en-us/azure/databricks/security/network/serverless-network-security/serverless-private-link

**Comment by tanmay-db** [comment]
Hi @w0ut0, thanks for reaching out, we are checking this with internal teams on when this could be supported and will update here soon.

**Comment by clowa** [comment]
Hi folks, I would love to see terraform support for this feature! NCCs are a good thing to enable us to switch to the serverless SQL warehouse, because we heavily rely on private endpoints. And of cause I would be nice to manage these configurations via terraform as well.

**Comment by samhughes91** [comment]
I would love to see TF support this feature too! Any updates yet @tanmay-db ?

**Comment by pablordoricaw** [comment]
+1 on the Terraform support for NCCs
