### ISSUE TITLE
[FEATURE] Reintroduce databricks_file

### ISSUE THREAD

**Issue by javeedshaikh-db** [databricks/terraform-provider-databricks#3106]
### Use-cases
databricks_file was added in https://github.com/databricks/terraform-provider-databricks/pull/2495 but then reverted.

Our team would like to use databricks_file to upload files to managed volumes. We have a metrics push job written in scala which depends on a JAR file. Today the JAR file was uploaded manually to all of our workspaces.

### References
Previous PR: https://github.com/databricks/terraform-provider-databricks/pull/2495

**Comment by alexott** [comment]
It's done already
