### ISSUE TITLE
Issue with notebook folder deletion scenario

### ISSUE THREAD

**Issue by WAG10** [databricks/terraform-provider-databricks#3127]
### Configuration
terraform {
required_providers {
databricks = {
source = "databricks/databricks"
version = "1.29.0"
}
}
}

### Expected Behavior
Folder containing notebooks should get deleted

### Actual Behavior
notebooks inside the folder gets deleted but folder still remains

### Steps to Reproduce

- Create a folder and place some notebooks inside that in primary workspace
- Export the same using terraform exporter and import it to secondary workspace
- now from primary delete the folder containing the notebooks
- Export the same again and import that to secondary workspace
- Expectation is that, the folder in secondary too should deleted but the folder remains still in secondary, only the notebooks inside that folder gets deleted

### Terraform and provider versions
$ terraform version
Terraform v1.1.7
on windows_amd64

**Comment by alexott** [comment]
This requires implementation of #2585
