### ISSUE TITLE
Issue with databricks_grants which does not allow CREATE_MODEL on the Schema

### ISSUE THREAD

**Issue by Divya1388** [databricks/terraform-provider-databricks#3130]
### Configuration
resource "databricks_grants" "test" {
  schema = databricks_schema.test.id
  grant {
    principal  = "xyz"
    privileges = ["USE_SCHEMA", "SELECT", "CREATE_TABLE", "MODIFY", "APPLY_TAG", "CREATE_MODEL", "EXECUTE"]
  }
}

### Expected Behavior
The grants should have bee created as we see the grant available in the UC on Schemas
![image](https://github.com/databricks/terraform-provider-databricks/assets/47507148/366157bf-cb5d-429a-9800-4e6b00aacbe6)

### Actual Behavior
Error: CREATE_MODEL is not allowed on schema

### Steps to Reproduce
Replace the schema id and principal 
terraform init
terraform apply

### Terraform and provider versions
Terraform Version : 1.3.0
Provider: 1.19.0

Please let us know if this is a bug or a feature not yet implemented in the provider

**Comment by alexott** [comment]
Please check the new provider - it's the first step in the troubleshooting guide... it was released in 1.24: https://github.com/databricks/terraform-provider-databricks/blob/master/catalog/resource_grants.go#L231

**Comment by Divya1388** [comment]
Hi @alexott thanks for looking in to this but we tested with 1.34 as well and have the same error
