### ISSUE TITLE
[DOC] Wrong examples for databricks_permission_assignment

### ISSUE THREAD

**Issue by camilo-s** [databricks/terraform-provider-databricks#3139]
### Affected Resource(s)

[`databricks_permission_assignment`](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/permission_assignment)
According to the examples, the user/group/sp to be assigned from the account-level to the workspace-level should be created as a resource at the workspace level. Doing this leads to Terraform failing when attempting to create the `databricks_permission_assignment`, because it expects an account-level `principal_id`, whereas the resource produces a workspace-level one.
![Screenshot 2024-01-19 at 21 34 50](https://github.com/databricks/terraform-provider-databricks/assets/45207084/0e925772-7701-4a95-8c86-4103b1f970b3)
### Expected Details

Since the resource's description is minimal, a correct example should be included that illustrates how to use the correct providers to assign an account-level user/group/sp to the workspace using `databricks_permission_assignment`:
1. Reading an account-level user/group/sp with a data resource using the account provider.
2. Creating the `databricks_permission_assignment` resource using the account-level `principal_id` read previously.
3. Read the workspace-assigned group. Here it's necessary to add an explicit dependency on `databricks_permission_assignment` lest Terraform try read it before it has been assigned to the workspace, hence failing.
Example:
```hcl
terraform {
  required_providers {
    databricks = {
      configuration_aliases = [databricks.account]
      source                = "databricks/databricks"
    }
  }
}

# Use the account provider
data "databricks_group" "account_level" {
  display_name = "example-group"

  provider = databricks.account
}

#Use the workspace provider
resource "databricks_permission_assignment" "this" {
  principal_id = data.databricks_group.account_level.id
  permissions  = ["USER"]
}

data "databricks_group" "workspace_level" {
  display_name = "example-group"

  depends_on = [databricks_permission_assignment.this]
}

output "databricks_group_id" {
  value = data.databricks_group.workspace_level.id
}
```
### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Change the examples by correct ones

### Important Factoids

I'm using this resource in an Azure deployment.

**Comment by alexott** [comment]
Please open pull request as you have a working example already
