### ISSUE TITLE
[FEATURE] Add a `databricks_sql_table` data source

### ISSUE THREAD

**Issue by jdavidheiser** [databricks/terraform-provider-databricks#3148]
### Use-cases
We want to reference metadata from our Unity catalog tables in other Terraform configs - for example, we'd like to read the S3 paths where managed tables are stored, and the properties set on those tables.

### Attempted Solutions
We tried managing table creation in Terraform, so we could read the path from the resource, but this does not cover use cases where tables are dynamically generated outside of Terraform.

### Proposal
create a `databricks_sql_table` data source whose outputs mirror those in the existing `databricks_sql_table` resource.

**Comment by nkvuong** [comment]
Closed by #3571
