### ISSUE TITLE
[FEATURE] `databricks_service_principal_secret` available for Azure

### ISSUE THREAD

**Issue by andrewmetcalfbede** [databricks/terraform-provider-databricks#3160]
### Use-cases

Currently the `databricks_service_principal_secret` resource is only available for AWS.  I need to be able to create Azure Databricks OAuth secrets for service principals in Azure Databricks for M2M authentication: https://learn.microsoft.com/en-us/azure/databricks/integrations/odbc/authentication#--oauth-machine-to-machine-m2m-authentication 

### Attempted Solutions

None

### Proposal

N/A

### References

Was not able to find any

**Comment by alexott** [comment]
Service Principals on Azure are Azure Active Directory objects so you need to use `azuread` provider for that: https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal_password

**Comment by andrewmetcalfbede** [comment]
Documentation that I linked states the following about the client secret for M2M in Azure:

_The service principal’s Azure Databricks OAuth secret.

(Microsoft Entra ID (formerly Azure Active Directory) secrets are not supported for OAuth M2M or OAuth 2.0 client credentials authentication.)_

**Comment by andrewmetcalfbede** [comment]
Evidenced elsewhere as well: https://learn.microsoft.com/en-us/azure/databricks/dev-tools/service-principals#step-6-create-an-azure-databricks-oauth-secret-for-the-microsoft-entra-id-formerly-azure-active-directory-service-principal

@alexott FYI

**Comment by alexott** [comment]
Ah, sorry - it was rolled out already... But there is no API for that on Azure, so no support until it's implemented
