### ISSUE TITLE
[ISSUE] Issue with `data . databricks_metastore` not able to read metastore and ad group using ADO pipleine

### ISSUE THREAD

**Issue by dmchakram** [databricks/terraform-provider-databricks#3172]
### Configuration

```hcl
data "databricks_metastore" "int_meta" {
  provider = databricks.account
  metastore_id = "xxxxxxxxxxxxxxxxxxxxxxxxx"
  }


data "databricks_group" "admins" {
  provider = databricks.account
  display_name = "METASTORE_ADMINS"
}

terraform provider config

provider "databricks" {
  host = "https://accounts.azuredatabricks.net"
  account_id = var.databricks_account_id
  auth_type = "basic"
}

provider "databricks" {
  alias = "account"
  host = "https://accounts.azuredatabricks.net"
  account_id = var.databricks_account_id
}

provider "databricks" {
  alias = "wrkshp"
  host = var.databricksurl
  token = var.databricks_token
  auth_type = "pat"
}
```

### Expected Behavior
I am using Azure devops pipline to assign my databricks workspace to existing unity catalog. i provided all the required data to read the metastore but it is not able to read metastore and also group admins. It should read and assign worksapce to exisiting unity catalog.

### Actual Behavior
Error: cannot read data metastore: 

  with data.databricks_metastore.int_meta,
  on metastore_data.tf line 19, in data "databricks_metastore" "int_meta":
  19: data "databricks_metastore" "int_meta" {

Error: Empty Summary: This is always a bug in the provider and should be reported to the provider developers.

  with data.databricks_group.admins,
  on metastore_data.tf line 26, in data "databricks_group" "admins":
  26: data "databricks_group" "admins" {

### Steps to Reproduce
Terraform init
terraform validate
terraform plan
terraform apply

### Terraform and provider versions
Initializing provider plugins...
- Finding hashicorp/time versions matching "0.10.0"...
- Finding hashicorp/azurerm versions matching "> 3.24.0, >= 3.87.0"...
- Finding databricks/databricks versions matching ">= 1.33.0, 1.34.0"...
- Finding latest version of azure/azapi...
- Installing hashicorp/time v0.10.0...
##[debug]Agent running environment resource - Disk: available:22922.00MB out of 29588.00MB, Memory: used 16MB out of 15990MB, CPU: usage 29.06
- Installed hashicorp/time v0.10.0 (signed by HashiCorp)
- Installing hashicorp/azurerm v3.89.0...
- Installed hashicorp/azurerm v3.89.0 (signed by HashiCorp)
- Installing databricks/databricks v1.34.0...
- Installed databricks/databricks v1.34.0 (self-signed, key ID 92A95A66446BCE3F)

### Is it a regression?
Nope

**Comment by dmchakram** [comment]
can anyone please help me on this ?

**Comment by alexott** [comment]
Follow the instructions and add logs

**Comment by alexott** [comment]
https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting

**Comment by dmchakram** [comment]
Hi @alexott  Thanks for the response  i tried and enabled the debug . But there is no information in debug log .  My pipeline is failing in plan stage . May i know if is should enable this prior to the plan stage or after . ?

For now i enabled the debug prior to the plan stage - terraform plan ?

**Comment by alexott** [comment]
Same way:

```
TF_LOG=DEBUG DATABRICKS_DEBUG_TRUNCATE_BYTES=250000 terraform plan -no-color 2>&1 |tee tf-debug.log
```
