### ISSUE TITLE
[ISSUE] Issue with `databricks_connection` resource

### ISSUE THREAD

**Issue by portoedu** [databricks/terraform-provider-databricks#3175]
### Configuration
```
resource "databricks_connection" "this" {
  name            = "test"
  owner           = "admins"
  connection_type = "BIGQUERY"
  comment         = "test"
  options = {
    GoogleServiceAccountKeyJson = MY-KEY
  }
}
```

### Expected Behavior
No changes after apply

### Actual Behavior
This error occurred during `terraform apply` and continues to occur on all `terraform plan` afterwards.
│ Error: cannot read connection: panic: assignment to entry in nil map

### Terraform and provider versions
Databricks Provider 1.35

### Is it a regression?
I opened this [issue](https://github.com/databricks/terraform-provider-databricks/issues/3079) which is already closed, the owner has changed and it seems that the credential is in the state, but now I can't do no terraform plan/apply.

**Comment by nkvuong** [comment]
This happens because the API does not return any options back (`GoogleServiceAccountKeyJson` is considered secure)
