### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource

### ISSUE THREAD

**Issue by bmp-six** [databricks/terraform-provider-databricks#3199]
### Configuration

```hcl

provider "databricks" {
  alias      = "accounts"
  host       = "https://accounts.azuredatabricks.net"
  account_id = "XXXXX"  # Account ID of the Databricks Admin Account for SIX
  azure_client_id = var.app_id
  azure_client_secret = var.pwd
  azure_tenant_id = var.tenant_id
}

locals {
  location_alias        = "chn"
  location              = "switzerlandnorth"
  name_metastore        = "XXXXX"
  name_owners           = "XXXXX"
  # Create Storage Account name for default location
  storage_account_name  = "XXXXX"
  container_name        = "unity-metastore"
}

resource "databricks_metastore" "this" {
  name                                              = local.name_metastore
  #storage_root = "XXXXX"
  region                                            = local.location
  owner                                             = local.name_owners
  delta_sharing_scope                               = "INTERNAL" # Used to enable delta sharing on the metastore
  delta_sharing_recipient_token_lifetime_in_seconds = "3600"     # Used to set expiration duration in seconds on recipient data access tokens
  force_destroy                                     = true
}
```

### Expected Behavior

I am using Azure DevOps pipeline with a service principal that is contributor. In the terraform project we put all the requried information to create a new metastore in a region.

### Actual Behavior

Error code:403
message: Invalid access token

│ POST /api/2.1/unity-catalog/metastores
│ > * Host: 
│ > * Accept: application/json
│ > * Authorization: REDACTED
│ > * Content-Type: application/json
│ > * User-Agent: databricks-tf-provider/1.34.0 databricks-sdk-go/0.29.0 go/1.20.13 os/linux terraform/1.6.6 resource/metastore auth/pat
│ > {
│ >   "name": "XXX",
│ >   "region": "XXX",
│ >   "storage_root": "XXX"
│ > }
│ < HTTP/2.0 403 Forbidden
│ < * Content-Length: 52
│ < * Content-Type: application/json; charset=utf-8
│ < * Server: databricks
│ < * Vary: Accept-Encoding
│ < * X-Databricks-Reason-Phrase: Invalid access token.
│ < {
│ <   "error_code": 403,
│ <   "message": "Invalid access token."
│ < }

### Steps to Reproduce

```
az login --service-principal -u "${contributor_sp_app_id}" -p "${sp_pwd}" --tenant $tenant_id  -o none
az account set --subscription $subscription -o none


terraform apply \
  -var "access_key=${access_key}" \
  -var "app_id=${contributor_sp_app_id}" \
  -var "subscription_id=${subscription_id}" \
  -var "pwd=${sp_pwd}" \
  -var "commit_message=plan-only" \
  -var "commit_hash=plan-only" \
  -var "troux_id=${trouxid}" \
  -var "stage_alias=${stage}" \
  -var "prefix=${prefix}" \
  -var "suffix=${suffix}"
```

### Terraform and provider versions

Initializing provider plugins...
- Finding latest version of hashicorp/azurerm...
- Finding databricks/databricks versions matching "~> 1.12"...
- Installing hashicorp/azurerm v3.89.0...
- Installed hashicorp/azurerm v3.89.0 (signed by HashiCorp)
- Installing databricks/databricks v1.35.0...
- Installed databricks/databricks v1.35.0

### Is it a regression?

Nope

**Comment by alexott** [comment]
most probably configuration error.
