### ISSUE TITLE
[ISSUE] Volume upload error due to impossibility to read status from Volume path

### ISSUE THREAD

**Issue by erickgmatos** [databricks/terraform-provider-databricks#3209]
I've been trying to upload files via Terraform, 
```terraform
resource "databricks_dbfs_file" "file" {
  source   = "${path.root}/../dist/package.whl"
  path     = "/Volumes/<catalog>/<schema>/<volume>/package.whl"
}
```
but it always give me an error:
```
╷
│ Error: cannot create dbfs file: cannot create handle: No operations allowed on this path
│ 
│   with module.jobs.databricks_dbfs_file.file,
│   on jobs/main.tf line 14, in resource "databricks_dbfs_file" "file":
│   14: resource "databricks_dbfs_file" "file" {
│ 
╵
```
I tried to use the api directly to make an upload with FilesAPI in python (v. 0.18.0) and in Databricks CLI (latest version - v0.212.3) (the same used by the Terraform Provider) and it works. I think the problem resides on reading status from this path, because it doesn't work in the FilesAPI as well. 
In python retrieves the follow error for `get_status` method form FilesAPI
```python
from databricks.sdk import WorkspaceClient
WorkspaceClient().files.get_status("/Volumes/<catalog>/<schema>/<volume>/package.whl")
```
```
PermissionDenied: Get-status API is not enabled. Config: host=https://dbc-xxxxx.cloud.databricks.com/, auth_type=metadata-service, metadata_service_url=***. Env: DATABRICKS_HOST, DATABRICKS_AUTH_TYPE, DATABRICKS_METADATA_SERVICE_URL
```

Versions:
Terraform 1.5.7
databricks/databricks 1.34.0
hashicorp/aws 4.47.0

**Comment by mgyucht** [comment]
UC Volumes are not yet supported in Terraform. We're working hard to get this available to you as soon as possible. Watch https://github.com/databricks/terraform-provider-databricks/issues/3106 for updates on this, and feel free to comment/post on that isuse.

**Comment by DataBach-maker** [comment]
I noticed that the topic was closed as "not planned." Could you please provide recommendations on how we can upload files to volumes using Terraform? Additionally, is this practice generally recommended or should it be avoided?
Thank you!

**Comment by alexott** [comment]
Use `databricks_file` resource
