### ISSUE TITLE
[FEATURE] Databricks runtime 'block beta LTS' option.

### ISSUE THREAD

**Issue by DoyleDev** [databricks/terraform-provider-databricks#3210]
### Use-cases
When terraforming clusters, I am wanting to use 'data.databricks_spark_version.latest_lts_spark_version.id' to retrieve the latest LTS version. When choosing an LTS version I am needing a reliable, dependable, and stable cluster runtime to work with. The current data block does not allow for you to ignore beta versions with LTS. In terraform, I do not have a way to automatically get the latest LTS version while ignoring beta versions. This allows for unstable, often changing versions to make their way into clusters. 
For example: 13.3LTS is currently the latest, non-beta LTS runtime. Version 14.3LTS is the latest, but is in beta version and is frequently changing. I do not want to use a frequently changing, beta runtime as my LTS.

### Attempted Solutions
I have manually specified the current 13.3 LTS version that is not in beta, I have tested the Beta flag in the data block configuration, this did not achieve the desired behavior. 

### Proposal
exclude_beta flag. This boolean value would exclude beta runtimes when set to True in the data block configuration. This would allow users to get the latest LTS that is not in a beta state. 

### References
None found

**Comment by alexott** [comment]
What TF version have you used?

**Comment by alexott** [comment]
And provide logs - I can't reproduce the issue with the current version if I mock the output of the API...
The Beta versions will match only when `beta` flag is explicitly provided: https://github.com/databricks/terraform-provider-databricks/blob/main/clusters/data_spark_version.go#L83, but this flag conflicts with `long_term_support`...

**Comment by alexott** [comment]
Not reproducible, no logs... Please reopen with logs
