### ISSUE TITLE
[DOC] Remove deprecated `account_id` field from `mws_credentials` resource

### ISSUE THREAD

**Issue by frosforever** [databricks/terraform-provider-databricks#3217]
### Affected Resource(s)
`mws_credentials` https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_credentials

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] `account_id` is deprecated and should be labeled as such. 
- [ ] Example usage reference `account_id` should be updated

### Important Factoids
Using `account_id` can lead to issues like #3016 & #3059

### References
https://github.com/databricks/terraform-provider-databricks/commit/3c89aee8d7d457407473d89cd0ce0ef46f703ea2#diff-d31a73b687cffca05e7023c32777485f2ebde6261bec07296c05a75de39898afR114
#3028

**Comment by dgomez04** [comment]
Other documentation such as [mws_workspaces](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces) and [databricks_aws_assume_role_policy](https://registry.terraform.io/providers/databricks/databricks/latest/docs/data-sources/aws_assume_role_policy) also reference deprecated usage of `mws_credentials`.
