### ISSUE TITLE
[DOC] Anchor in `databricks_service_principal_secret` documentation does not take you to the correct place

### ISSUE THREAD

**Issue by frosforever** [databricks/terraform-provider-databricks#3218]
### Affected Resource(s)
`databricks_service_principal_secret` https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/service_principal_secret

### Expected Details
![image](https://github.com/databricks/terraform-provider-databricks/assets/1630422/1f47e8d3-aad3-4913-87ae-ce0767e7ac70)

When clicking the "Authenticating with service principal" I would expect to be linked to https://registry.terraform.io/providers/databricks/databricks/latest/docs#authenticating-with-service-principal. However, it instead links to https://registry.terraform.io/providers/databricks/databricks/latest/docs/index#authenticating-with-service-principal which doesn't exist and just loads the default docs at https://registry.terraform.io/providers/databricks/databricks/latest/docs without directing you to the appropriate section.

### List of things to potentially add/remove:
Likely something with this reference would need to be updated https://github.com/databricks/terraform-provider-databricks/blob/662a0bd08043be9f36fca43978ab8a81f60c91d5/docs/resources/service_principal_secret.md?plain=1#L10

**Comment by alexott** [comment]
This will be reworked as part of #3197

**Comment by alexott** [comment]
should be fixed by #3197

**Comment by alexott** [comment]
it's deployed, let me double check

**Comment by alexott** [comment]
Hmmm. It looks like it's a problem with Registry itself, generating incorrect links

**Comment by frosforever** [comment]
Yeah I don't know where it should link, I'm just certain it's not doing the thing it's intended to do!

**Comment by alexott** [comment]
It should link to the index page, but it's handled specially in registry :-(
