### ISSUE TITLE
[ISSUE] Issue with `databricks_storage_credential` resource on group ownership

### ISSUE THREAD

**Issue by afreyermuth98** [databricks/terraform-provider-databricks#3220]
### Configuration

```hcl
data "databricks_group" "mygroup" {
  display_name = "mygroup"
}
resource "databricks_storage_credential" "my_storage_credential" {
  name = "my-storage-credential"
  aws_iam_role {
    role_arn = "<MY_ROLE_ARN"
  }
  owner = data.databricks_group.mygroup.id
}
```

### Expected Behavior

The storage credential is created and the owner is the group "mygroup"

### Actual Behavior

│ Error: cannot update storage credential: Could not find principal with name <GROUP_ID>

### Steps to Reproduce
1. terraform apply

### Terraform and provider versions

TF Version : 1.5.7
Databricks provider version : 1.35.0

**Comment by w0ut0** [comment]
We seem to have the same issue with `databricks_metastore`

**Comment by nkvuong** [comment]
it is quite clear in the doc
> - `owner` - (Optional) Username/groupname/sp application_id of the storage credential owner.
