### ISSUE TITLE
[FEATURE] pipeline_id output for databricks_pipeline resource

### ISSUE THREAD

**Issue by n8nc** [databricks/terraform-provider-databricks#3235]
I want to be able to pass the pipeline_id of my dlt pipeline into other resources, like databricks_pipeline.this.pipeline_id

### Use-cases

My particular use-case is to pass a pipeline into a databricks_job resource as one of the tasks for my workflow.

### Attempted Solutions

I've tried using the databricks_pipelines data source and selecting the first id from the list data.databricks_pipelines.this.ids but wasn't able to get it to work if my pipeline was being created during the same terraform apply.

**Comment by alexott** [comment]
Just use `id` attribute, like this:

```
pipeline_task {
      pipeline_id = databricks_pipeline.this.id
    }
```
