### ISSUE TITLE
[ISSUE] Authorization error with workspace resources when using DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET env vars

### ISSUE THREAD

**Issue by lsanchez-v** [databricks/terraform-provider-databricks#3257]
### Configuration

```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.36.0"
    }
  }
}

provider "databricks" {
  alias = "created_workspace"
  host  = var.workspace_host
  token = var.workspace_token
}
```

### Expected Behavior
The provider should be taking only the "host" and "token" parameters, and ignoring the DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET env vars

### Actual Behavior
The following error is raised:

**Error: validate: more than one authorization method configured: oauth and pat.**

### Steps to Reproduce

1. Define DATABRICKS_CLIENT_ID and DATABRICKS_CLIENT_SECRET env vars
2. Try to create some workspace resource, configuring in the workspace resources module's provider the host and token returned by the workspace module

### Terraform and provider versions

TF version: 1.7.2
Databricks provider: 1.36.2

### Debug Output

Error: validate: more than one authorization method configured: oauth and pat. Config: host=https://dbc-710c08ff-32ac.cloud.databricks.com, token=***, client_id=XXXXXXXXXXXXXXXXX, client_secret=***. Env: DATABRICKS_CLIENT_ID, DATABRICKS_CLIENT_SECRET
│
│   with module.databricks.module.workspace_resources.provider["registry.terraform.io/databricks/databricks"].created_workspace,
│   on modules/databricks/modules/workspace_resources/provider.tf line 10, in provider "databricks":
│   10: provider "databricks" {

**Comment by 840** [comment]
You have to explicitly set the `auth_type` inside the provider block if you have multiple authorization methods set. Since you want to use PAT, you can define the following:

```
provider "databricks" {
  alias = "created_workspace"
  host  = var.workspace_host
  token = var.workspace_token
  auth_type = "pat"
}
```

The [documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs#auth_type) provides a list of `auth_type` which you can set.

**Comment by lsanchez-v** [comment]
@840 Indeed that did the trick. Do you think it's worth it adding that to this guide? https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/aws-workspace#provider-configuration

Thank you!

**Comment by 840** [comment]
@lsanchez-v Filed in a PR to add this in the guide. Thank you for your suggestion.

**Comment by lsanchez-v** [comment]
PR created: https://github.com/databricks/terraform-provider-databricks/pull/3262

Thank you!
