### ISSUE TITLE
[ISSUE] Issue with `databricks_secret_scope` resource

### ISSUE THREAD

**Issue by katerinagreif** [databricks/terraform-provider-databricks#3269]
### Configuration

```hcl

terraform {


  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.91.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "~>1.36.3"
    }
  }

  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

provider "azurerm" {
  alias           = "dns"
  tenant_id       = var.environment.dns_tenant_id
  subscription_id = var.environment.dns_subscription_id

  features {}
}

provider "databricks" {
  host            = var.dbws_host
  account_id      = var.dbws_account_id
  azure_tenant_id = data.azurerm_client_config.current.tenant_id
  azure_use_msi   = true
}
```

### Expected Behavior
Redeploy of external locations and global scripts

### Actual Behavior
We get a lot of error about not being able to parse the DBX API resposes here is the log:

[dbxlog.txt](https://github.com/databricks/terraform-provider-databricks/files/14308428/dbxlog.txt)

### Terraform and provider versions
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.91.0"
    }
    databricks = {
      source  = "databricks/databricks"
      version = "~>1.36.3"
    }
  }

```
### Is it a regression?
We deployed first before xmass on version 1.31.1 now we get similar problem even if we regress, but less info.

**Comment by alexott** [comment]
You have the network connectivity problem - you're connecting to the workspace with the private link from the outside of Azure:

```
GET /login.html?error=private-link-validation-error:5161134394011045
```

See [this item in the troubleshooting guide](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting#error-cannot--unexpected-error-handling-request-invalid-character--for-beginning-of-value)
