### ISSUE TITLE
[ISSUE] Issue with Databricks Service Principal resource. 

### ISSUE THREAD

**Issue by DoyleDev** [databricks/terraform-provider-databricks#3297]
### Configuration

```hcl
Calling the module: 
/*-----------------SP FOR EACH GROUP--------------------------*/
module "databricks_service_principal" {
  for_each = var.dbr_account_groups
  providers = {
    databricks = databricks.mws
  }
  source          = "./modules/service_principal"
  sp_display_name = "${each.key}_service_principal"
  principal_name  = each.value
  workspace_id    = databricks_mws_workspaces.this.workspace_id
}

inside the module: 
resource "databricks_service_principal" "this" {
  display_name               = var.sp_display_name
  allow_cluster_create       = var.allow_cluster_create
  allow_instance_pool_create = var.allow_instance_pool_create
  databricks_sql_access      = var.databricks_sql_access
  active                     = var.active
}

resource "databricks_service_principal_role" "this" {
  depends_on           = [databricks_service_principal.this]
  service_principal_id = databricks_service_principal.this.id
  role                 = "account_admin"
}

resource "databricks_mws_permission_assignment" "this" {
  depends_on   = [databricks_service_principal.this]
  workspace_id = var.workspace_id
  principal_id = databricks_service_principal.this.id
  permissions  = ["ADMIN"]
}
```

### Expected Behavior
One service principal per group should be created at the account level. 

### Actual Behavior
Two service principals with the same display name are being created. 

### Steps to Reproduce
We have a dev and prod workspace in databricks and in Terraform enterprise. Because this resource is an account level resource it shouldn't matter that I am essentially doing two applies. 
1. Create the resource
2. Apply in dev
3. Apply in prod

### Terraform and provider versions
Terraform: 1.2.9
Databricks: 1.36.3
AWS: 5.30

### Is it a regression?
New resource

### Debug Output
There is no error to debug, just unexpected behavior

### Important Factoids
We dev and prod workspaces in terraform enterprise.

**Comment by alexott** [comment]
It's expected behaviour because you have two different pipelines against the same target, and Account level SCIM API allows the creation of service principals with the same name. For account-level operation, you need to have one state...

**Comment by DoyleDev** [comment]
sounds like I need a "count         = var.prod_only_number[var.envr]" on the resource, thank you!

**Comment by tanmay-db** [comment]
Hi @DoyleDev, thanks for creating the issue, from your comment it seems it is resolved? Please feel free to reopen if the issue persists.
