### ISSUE TITLE
Inference tables for databricks_model_serving resource

### ISSUE THREAD

**Issue by keenanwells-tatari** [databricks/terraform-provider-databricks#3315]
### Use-cases
We would like enable [inference tables](https://docs.databricks.com/en/machine-learning/model-serving/enable-model-serving-inference-tables.html) on our model serving endpoints with terraform. It doesn't look like this option is available currently? 

### Attempted Solutions
No other solutions exist using this terraform provider .

### Proposal
The inference table configuration should reference a `databricks_schema` resource.

**Comment by alexott** [comment]
Added in 1.39.0
