### ISSUE TITLE
[ISSUE] Issue with `databricks_external_location` resource

### ISSUE THREAD

**Issue by ssaenzf** [databricks/terraform-provider-databricks#3344]
There is a problem regarding of how to configure that when a resource it’s recreated during the apply phase, another resource is destroyed first in the Databricks plugin. It needs to be taken in consideration that create_before_destroy cannot be used for the resource recreated because this resource must be unique within the Databricks plugin.

The particular use case it’s a Databricks Workspace, that got an storage credential, which its used for creating some external locations, necessary for creating some catalogs. When I change the external locations and run terraform apply, they need to be recreated but they cannot be destroyed because the catalogs are depending on them. Also cannot be used create_before_destroy because it is raised an error that cannot be created the external location because its url overlaps with the previous one

As a work around I handle it through different terraform commands using the -target flag. Nevertheless it would be nicer that this is handled automatically through the terraform configuration and the provider during the apply phase.

Terraform and provider versions:
Terraform 1.4.0
Databricks provider 1.36.2

**Comment by nkvuong** [comment]
@ssaenzf if you specify `force_destroy=true`, the external location should be removed cleanly, and then recreated correctly

**Comment by santos-saenz** [comment]
@nkvuong with force_destroy the catalogs won't be updated to use the updated external location, although the external location will be recreated correctly

**Comment by ssaenzf** [comment]
@nkvuong with force_destroy the catalogs won't be updated to use the updated external location, although the external location will be recreated correctly

**Comment by nkvuong** [comment]
the dependency between catalog & external location is done by path matching, so you won't need to recreate the catalogs

**Comment by ssaenzf** [comment]
Great, thanks for the explanation!
