### ISSUE TITLE
[ISSUE] Issue with `databricks_provider` resource oauth-m2m doesn't work with azure when deploying clusters

### ISSUE THREAD

**Issue by drew-altana** [databricks/terraform-provider-databricks#3394]
### Configuration
provider "databricks" {
  host      = "https://adb-<identifier>.19.azuredatabricks.net"
  auth_type = "oauth-m2m"
  client_id = <a client id>
  client_secret = <a secret>
  azure_workspace_resource_id = /subscriptions/<uuid>/resourceGroups/<workspace name>/providers/Microsoft.Databricks/workspaces/<workspace name>
}

### Expected Behavior
Jobs deploy as normal. 

### Actual Behavior

Error: cannot create job: aws_attributes can only be specified for clusters running in AWS

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
Terraform v1.6.6
`required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = ">= 1.38.0"
}`

### Is it a regression?
Not as far as I know
### Would you like to implement a fix?
No.

**Comment by alexott** [comment]
Collect logs. The error says that you're trying to create a cluster with `aws_attributes` - it's not related to the OAuth

**Comment by drew-altana** [comment]
Yeah, was a weird caching issue on my side, deleted the state and recreated and it worked.
