### ISSUE TITLE
[FEATURE] ability to toggle unity catalog support on a SQL warehouse

### ISSUE THREAD

**Issue by michaelvonderbecke** [databricks/terraform-provider-databricks#3404]
### Use-cases
We're trying to adopt unity catalog but to support it we need to have clusters and SQL warehouses that are non-UC supported so we can access our internal data lake through our old spark conf/assumed role method.  There doesn't appear to be a way to set a SQL endpoint to non-UC compatible via terraform despite there being a unity catalog toggle button for SQL warehouses in the UI.

### Attempted Solutions
None because it doesn't appear possible

### Proposal
A true/false flag in databricks_sql_endpoint that allows disabling UC support on a warehouse

**Comment by alexott** [comment]
Closing as duplicate of #3203
