### ISSUE TITLE
[FEATURE] Resource for default_catalog_assignment

### ISSUE THREAD

**Issue by adrianabreu** [databricks/terraform-provider-databricks#3406]
### Use-cases

Currently, there is no straightforward method to establish a new default catalog using the terraform provider. Let's say that we want to add Unity catalog to 3 workspaces using terraform.

1. We create a metastore using the account / workspace provider.
2. We do a llop and assign the metastore to each workspace, here we are able to specify the default_catalog, but we can't still create one!
3. After the metastore is assigned to a workspace we can create the catalog but we end up with a cyclic dependency. 

### Attempted Solutions

There are no solutions available at the moment using the terraform provider.

### Proposal

Create a new resource like `workspace_default_catalog` that uses the patch call on https://docs.databricks.com/api/workspace/metastores/updateassignment#default_catalog_name

**Comment by adrianabreu** [comment]
Just closing it as our databricks representative referred to this new section that does exactly this:
https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/default_namespace_settings

**Comment by alexott** [comment]
You can also set default catalog when attaching metastore to the workspace: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/metastore_assignment#default_catalog_name
