### ISSUE TITLE
Terraform Exporter : Reference to undeclared resource (databricks Jobs and Databricks Pipelines)

### ISSUE THREAD

**Issue by lmallepaddi** [databricks/terraform-provider-databricks#3413]
**We ran the Terraform exporter on a workspace and encountered the following problems while attempting to restore it to a new workspace. It appears that permissions for non-existent resources are being generated in the access.tf file, leading to failures in the Terraform plan. Multiple instances of these permissions exist, but I'm highlighting one of the common occurrences below.**

│ Error: Reference to undeclared resource
│
│   on access.tf line 7562, in resource "databricks_permissions" "job_de_mgr_workflowjobtemplate_922880175114333":
│ 7562:   job_id = databricks_job.de_mgr_workflowjobtemplate_922880175114333.id
│
│ A managed resource "databricks_job" "de_mgr_workflowjobtemplate_922880175114333" has not been declared in the root module.

│ Error: Reference to undeclared resource
│
│   on access.tf line 21171, in resource "databricks_permissions" "pipeline_7d89d3ae_daa9_418e_81c8_7842613531e1":
│ 21171:   pipeline_id = databricks_pipeline.r2e314719721.id
│
│ A managed resource "databricks_pipeline" "r2e314719721" has not been declared in the root module.

**Comment by alexott** [comment]
Are resources like `databricks_job.de_mgr_workflowjobtemplate_922880175114333` listed in the `ignored_resources.txt` file?
