### ISSUE TITLE
[ISSUE] Issue with using databricks terraform provider 1.39.0

### ISSUE THREAD

**Issue by rahulgul** [databricks/terraform-provider-databricks#3422]
### Configuration

```hcl
Terraform Code attached
```

### Expected Behavior
Expecting terraform init to work and download the provider

### Actual Behavior
I am getting the following error while trying to run `terraform init from azure devops terraform init task. The task looks like this.

`
 - task: TerraformTaskV3@3
          displayName: 'terraform init'
          inputs:
            command: init
            backendType: azurerm
            backendServiceArm: $(az_service_connection)
            workingDirectory: '$(System.DefaultWorkingDirectory)/modules/cluster_policies'
            # Subscription id of the target backend. This can be used to specify the subscription when using Management Group scoped
            # Service connection or to override the subscription id defined in a Subscription scoped service connection
            backendAzureRmSubscriptionId: $(az_subscription_id)
            # create backend storage account if doesn't exist
            backendAzureRmResourceGroupName: $(az_resource_group)
            # azure location shortname of the backend resource group and storage account
            backendAzureRmStorageAccountName: $(az_storage_account_name)
            # azure storage account sku, used when creating the storage account
            # azure blob container to store the state file
            backendAzureRmContainerName: $(az_container_name)
            # azure blob file name
            backendAzureRmKey: ${{ parameters.environment }}.tfstate
`

Error while installing databricks/databricks v1.39.0: could not query
│ provider registry for registry.terraform.io/databricks/databricks: failed
│ to retrieve authentication checksums for provider: the request failed after
│ 2 attempts, please try again later: Get

### Terraform and provider versions
I am using databricks provider version 1.39.0

(https://github.com/databricks/terraform-provider-databricks/releases), please make sure to use the latest one. -->

### Is it a regression?

Nope, trying for the first time.

### Important Factoids

Nope
[databricks_terraform_microsoft_ticket.zip](https://github.com/databricks/terraform-provider-databricks/files/14835432/databricks_terraform_microsoft_ticket.zip)

**Comment by nkvuong** [comment]
@rahulgul could you make sure that the ADO runners have access to registry.terraform.io to download the necessary provider
`could not query
│ provider registry for registry.terraform.io/databricks/databricks: failed
│ to retrieve authentication checksums for provider: the request failed after
│ 2 attempts, please try again later: Get`

**Comment by alexott** [comment]
Looks like ADO configuration issue, not provider issue
