### ISSUE TITLE
[FEATURE] Specify Subscription Plan for databricks_mws_workspaces Resources

### ISSUE THREAD

**Issue by slizzi** [databricks/terraform-provider-databricks#3429]
### Use-cases
As an Enterprise customer using Databricks on AWS, we are able to create workspaces in the Databricks Account Management portal using either the "Enterprise" or "Premium" Subscription Plan level. Our use cases do not all require the Enterprise level features, and the DBU charges for Enterprise workspaces is higher. 

We deploy our workspaces via Terraform, and need to set the Subscription Plan for each workspace according to the requirements of its intended purpose. 

#### Provider Configuration
```
provider "databricks" {
  alias = "mws"
  host  = "https://accounts.cloud.databricks.com"
  account_id    = var.databricks_account_id
  client_id     = var.databricks_client_id
  client_secret = var.databricks_client_secret
}

provider "aws" {
  
  region = "eu-central-1"

  assume_role {
    role_arn = var.deploy_role
  }
}
```

#### Workspace Module Top Level
``` 
module "aws_workspace" {

  providers = {
    # databricks          = databricks
    databricks.mws = databricks.mws
  }

  source = "./convenience/workspace"

  databricks_account_id = var.databricks_account_id
  workspace_name        = "ph-rd-portfolio-datalayer-${var.environment}"

}
```

#### Workspace Module (from ./convenience/workspace)
```
module "workspace" {

  source = "../../foundational/workspace"

  providers = {
    databricks.mws = databricks.mws
  }

  aws_region                    = data.aws_region.current.name
  databricks_account_id         = var.databricks_account_id
  workspace_name                = var.workspace_name
  workspace_storage_bucket_name = module.workspace_bucket.bucket_details.bucket

  storage_configuration_name = "${var.workspace_name}-storage"
  network_name               = "${var.workspace_name}-network"
  deployment_name            = "${var.workspace_name}-deployment"
  vpc_id                     = local.vpc_id
  subnet_ids                 = local.subnet_ids
  security_group_ids         = [local.security_group_ids]

  databricks_mws_credentials_id = module.role.databricks_credentials.credentials_id

}
```

#### Workspace Resource Definition (from ../../foundational/workspace)
```
resource "databricks_mws_workspaces" "this" {

  provider = databricks.mws
  account_id      = var.databricks_account_id
  aws_region      = var.aws_region
  workspace_name  = var.workspace_name
  deployment_name = var.deployment_name
  credentials_id           = var.databricks_mws_credentials_id
  storage_configuration_id = databricks_mws_storage_configurations.this.storage_configuration_id
  network_id               = databricks_mws_networks.this.network_id

}
```

### Proposal
Add an optional supported Argument (e.g. "subscription_plan") to the databricks_mws_workspaces resource. It would be used to specify the desired Subscription Plan for the workspace resource. 

Possible values would be "Enterprise" or "Premium". If not specified, then the default would be whichever plan the Databricks Account uses.

### References
[databricks_mws_workspaces resource](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/mws_workspaces#argument-reference)

**Comment by alexott** [comment]
can you specify `pricing_tier` [code](https://github.com/databricks/terraform-provider-databricks/blob/main/mws/resource_mws_workspaces.go#L88) - if it will work, we'll need to add a doc.

**Comment by slizzi** [comment]
@alexott thanks for the quick reply! That does the trick :) 

pricing_tier was added to the workspace resource with a default value "premium". Upon Terraform Plan it is recognized and reports that the current value is "PREMIUM":
```
  # module.by-sats-eu.module.databricks_workspace.databricks_mws_workspaces.this will be updated in-place
  ~ resource "databricks_mws_workspaces" "this" {
        id                       = "***/8223549837865536"
      ~ pricing_tier             = "PREMIUM" -> "premium"
        # (13 unchanged attributes hidden)
    }
```

**Comment by alexott** [comment]
Ok, we'll need to add a corresponding suppress_diff function for it...
