### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource

### ISSUE THREAD

**Issue by Aksh11499** [databricks/terraform-provider-databricks#3440]
why am i getting this error "Error: Failed to install provider
│
│ Error while installing databrickslabs/databricks v1.5.0: could not query provider registry for
│ registry.terraform.io/databrickslabs/databricks: failed to retrieve authentication checksums for provider: 403 Forbidden     
│ returned from objects.githubusercontent.com" i tried to fix this issue lot of times but i didn't get solution
### Configuration

```hcl
terraform {
  required_version = ">= 1.3.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.44.1"
    }
    databricks = {
      source  = "databrickslabs/databricks"
      version = "1.5.0" ## works for 0.6.2
    }
  }
}
```

**Comment by alexott** [comment]
https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/troubleshooting#error-failed-to-install-provider - you should switch from `databrickslabs` two years ago - it's not supported
