### ISSUE TITLE
[FEATURE] Request API job setting Job duration threshold warning

### ISSUE THREAD

**Issue by leonlaf66** [databricks/terraform-provider-databricks#3442]
Hi team
   Looks like your API doesn't support job setting - job duration threshold warning right now, I only see timeout setting, can you please add it? Please also support it in the terraform provider.

Thanks
Leon Li

**Comment by alexott** [comment]
it's the [health block](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/job#health-configuration-block)
