### ISSUE TITLE
[ISSUE] Issue with `databricks_instance_pool` resource export; empty instance_pool_name

### ISSUE THREAD

**Issue by makie17** [databricks/terraform-provider-databricks#3521]
Hi,

I'm working on synchronization between two workspaces using exporter and have problem with databricks_instance_pool.
Strange is this instance pool is not visible when used `databricks instance-pools list`
### Configuration
./terraform_exporter/terraform-provider-databricks_1.41.0 exporter \
                  -skip-interactive \
                  -last-active-days=60 \
                  -directory exported_code_prd \
                  -listing="workspace,compute,jobs,sql-endpoints,uc-catalogs,uc-external-locations,uc-storage-credentials"

### Expected Behavior
pools.tf shouldn't contain the resource "databricks_instance_pool" "zincs139" definition or instance_pool_name should contain value.

### Actual Behavior
pools.tf contains
```
resource "databricks_instance_pool" "zincs139" {
  instance_pool_name                    = ""
  idle_instance_autotermination_minutes = 0
  enable_elastic_disk                   = false
}
```

### Terraform and provider versions
terraform-provider-databricks_1.41.0 exporter

### Would you like to implement a fix?
I'm open to work on the implementation. But first need to setup dev environment :)

**Comment by alexott** [comment]
Most probably this pool is still referenced in some job, although it was deleted...
