### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster_policy` with v1.42

### ISSUE THREAD

**Issue by kolyarice** [databricks/terraform-provider-databricks#3545]
hi team, I was making a change to an instance pool using the new provider version (1.42). It failed to re-create the associated policy with the following error:

`│ Error: cannot update cluster policy: max_clusters_per_user must be greater than 0
│ 
│   with databricks_cluster_policy.datsci_jobs_xl,
│   on cluster_policies.tf line 98, in resource "databricks_cluster_policy" "datsci_jobs_xl":
│   98: resource "databricks_cluster_policy" "datsci_jobs_xl" {
│ `

I don't have this attribute in my policy
In fact, it does not appear in the policy attribute reference (https://docs.databricks.com/en/administration-guide/clusters/policy-definition.html)

per the API docs (https://docs.databricks.com/api/workspace/clusterpolicies/create) this attribute should not be required

I reverted back to 1.41 and re-created the policy & pool with no issue

**Comment by ag-manik** [comment]
Yes, similar issue we faced on 3rd May. Version v1.41.0 is working absolutely fine.
