### ISSUE TITLE
[FEATURE] Pipeline edition missing "PREVIEW" option

### ISSUE THREAD

**Issue by alankritjoshi** [databricks/terraform-provider-databricks#3546]
### Use-cases

To enable pipeline in `serverless` mode, edition=`PREVIEW` option is needed.

Currently the only options in Pipeline available are CORE, PRO and ADVANCED.

### Attempted Solutions

N/A

### Proposal

Add the `PREVIEW` option to play with experimental features.

### References

- https://github.com/pulumi/pulumi-databricks/issues/446#issuecomment-2093650279

**Comment by alankritjoshi** [comment]
Tested a bit more, looks like the actual usage is:

```
channel="PREVIEW"
edition="ADVANCED"
```

**Comment by alexott** [comment]
it's correctly documented: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/pipeline#channel
