### ISSUE TITLE
Terraform Plan failure when I use the exporter

### ISSUE THREAD

**Issue by Swathi41bora** [databricks/terraform-provider-databricks#3595]
I receive the following error when I run terraform plan on the files that were generated using exporter.

│ Error: cannot read group: default auth: cannot configure default credentials, please check https://docs.databricks.com/en/dev-tools/auth.html#databricks-client-unified-authentication to configure credentials for your preferred authentication method

**Comment by alexott** [comment]
You need to have authentication configured - follow the provider docs for it.

**Comment by Swathi41bora** [comment]
I already did that 
![auth](https://github.com/databricks/terraform-provider-databricks/assets/92799974/3e183883-f07a-4fb8-8d51-a4c08aa54bd6)
