### ISSUE TITLE
TF Plan failure

### ISSUE THREAD

**Issue by Swathi41bora** [databricks/terraform-provider-databricks#3609]
I receive the following error during terraform plan, could you please help

│ Error: Cycle: databricks_grants.catalog_deltashare, databricks_schema.deltashare_dbo
│
│
╵
╷
│ Error: Cycle: databricks_grants.catalog_uat, databricks_schema.uat_exchpwa

**Comment by alexott** [comment]
Please share the code

**Comment by alexott** [comment]
Closing as not providing sufficient details
