### ISSUE TITLE
[FEATURE] Data resource for `databricks_mws_network_connectivity_config`

### ISSUE THREAD

**Issue by owlleg6** [databricks/terraform-provider-databricks#3614]
### Use-cases

I would like to propose a feature request for the creation of a data resource for "databricks_mws_network_connectivity_config". My intention is to manually create Network Connectivity Configurations (NCCs) and subsequently reference their IDs using a data resource when binding to a workspace.

**Comment by alexott** [comment]
Would support for this resource in the TF exporter help?

**Comment by owlleg6** [comment]
I don't know, haven't used TF exporter yet. For sure regular data resource would help, right now i take NCC id from databricks cli and directly paste it in terraform configuration. Would be nice to get this id using data resource.
