### ISSUE TITLE
[ISSUE] Pinned Clusters keep showing as unpinned on subsequent runs.

### ISSUE THREAD

**Issue by PaulW** [databricks/terraform-provider-databricks#3616]
### Configuration
```hcl
resource "databricks_cluster" "dbc-cluster" {
  provider            = databricks.workspace
  cluster_name        = "Domain Cluster"
  spark_version       = local.dbc_merged_cluster_policy.spark_version.defaultValue
  policy_id           = databricks_cluster_policy.dbc-notebook-cluster[0].id
  node_type_id        = local.dbc_merged_cluster_policy.node_type_id.value
  driver_node_type_id = local.dbc_merged_cluster_policy.driver_node_type_id.value
  is_pinned           = true
  autoscale {
    min_workers = local.dbc_merged_cluster_policy["autoscale.min_workers"].value
    max_workers = local.dbc_merged_cluster_policy["autoscale.max_workers"].value
  }
  gcp_attributes {
    google_service_account = google_service_account.dbc-service-account[0].email
  }
  custom_tags = {
    "DomainOwner" = local.databricks_cluster_group_name
    "CreatedBy"   = "Terraform"
  }
}
```

### Expected Behavior
Cluster should be created which is pinned.

### Actual Behavior
Cluster is created, and is pinned, however subsequent runs of Terraform when refreshing the remote state of the resource, pick up an incorrect pinned state and as such will plan to re-pin the cluster:

```
  # module.domain["some-domain"].databricks_cluster.dbc-domain-cluster[0] will be updated in-place
  ~ resource "databricks_cluster" "dbc-domain-cluster" {
        id                           = "xxx"
      ~ is_pinned                    = false -> true
        # (16 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

### Steps to Reproduce
1. Create initial resource in Terraform.  Plan and Apply, pinned cluster will be created in relevant workspace.
2. With no changes, run another Plan.  Terraform will detect the Pinned state incorrectly.

### Terraform and provider versions
Terraform 1.7.1
Databricks Provider 1.41.0 (Also tested outside of main CI pipelines using 1.45.0)

### Is it a regression?
No, however this issue started around the 30th April 2024.  No underlying infrastructure or provider versions were changed at this point.

### Important Factoids
We've noticed the Clusters API returns a Pinned state with the field `pinned_by_user_name`, however I can't find any mention of this within the Provider code itself.  All references to anything relating to Pinned clusters in the code seem to use the `is_pinned` flag which appears to no longer be part of the API response.

The API documentation also seems to have no reference to either `is_pinned` or `pinned_by_user_name` in the Clusters REST API documentation either, yet the response when calling from `api/2.0/clusters/list`, the response of listed clusters does contain `pinned_by_user_name`

**Comment by pdbarrington** [comment]
Please prioritise this issue. This issue is generating a lot of spam in our plans causing simple PRs to be error prone requiring more effort than should be needed.

**Comment by bgrams** [comment]
This is because the pinning status is determined from [cluster events](https://github.com/databricks/terraform-provider-databricks/blob/1e067f7e7914d4493fe4736aca8ee2f596ab0169/clusters/resource_cluster.go#L515-L530), which presumably expire after some time. It would be great to be able to determine this status from a different API.

Upvote for priority as this behavior has started to break our drift detection pipelines.
