### ISSUE TITLE
[FEATURE] Add isolation mode support in external locations and storage credentials

### ISSUE THREAD

**Issue by alexott** [databricks/terraform-provider-databricks#3624]
https://learn.microsoft.com/en-us/azure/databricks/release-notes/product/2024/may#bind-storage-credentials-and-external-locations-to-specific-workspaces-public-preview

**Comment by matthewchoy-envisso** [comment]
Looks to be closed in https://github.com/databricks/terraform-provider-databricks/pull/3704

**Comment by alexott** [comment]
Fixed by #3704
