### ISSUE TITLE
[ISSUE] Issue with `databricks_grants` resource

### ISSUE THREAD

**Issue by videnden** [databricks/terraform-provider-databricks#3630]
### Configuration
Hello,

I am trying to add permissions to **access system schema**  with the below configuration:

# Copy-paste your Terraform configuration here
resource "databricks_system_schema" "enable_system_tables_schema" {
  provider = databricks.workspace
  schema   = "access"
}

resource "databricks_grants" "system_access_schema_grants" {
  provider = databricks.workspace
  schema   = databricks_system_schema.enable_system_tables_schema.schema
  grant {
    principal  = data.databricks_group.data_engineers.display_name
    privileges = ["USE_SCHEMA"]
  }
}

### Expected Behavior
Permissions to be added to the system table **access**. (I have tested this manually and I am able to add it)

### Actual Behavior
Terraform apply fails with the following error:

Error: cannot create grants: GetPermissions invalid schema name: 'id_of_our_metastore|access'

  with databricks_grants.system_access_schema_grants,
  on metastore.tf line 21, in resource "databricks_grants" "system_access_schema_grants":
  21: resource "databricks_grants" "system_access_schema_grants" {

### Steps to Reproduce
1. `terraform apply`-->

### Terraform and provider versions

terraform {
  required_version = ">=1.5.7"
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "1.35.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

**Comment by alexott** [comment]
From the error message it looks like it you were using `databricks_system_schema.enable_system_tables_schema.id` instead of the schema name. Also, the `.schema` returns only the name, not the full name - you need to use `"system.${databricks_system_schema.enable_system_tables_schema.schema}"` instead - it works just fine with 1.36.2

**Comment by fidelcuevas** [comment]
The provided "solution" here doesn't seem to work:

`resource "databricks_grants" "schemas" {
  for_each    = databricks_schema.this
  provider = databricks
  catalog = databricks_catalog.this.name
  schema  = each.value.name
  grant {
    principal  = var.grant_principal
    privileges = ["ALL_PRIVILEGES"]
  }
  depends_on = [ databricks_schema.this  ]
}`

I've tried every permutation for these attributes that makes sense: system.catalog_name.schema_name, schema_name, catalog_name.schema_name, using string reference or object reference, yet I still get the same error:

`Error: cannot read grants: GetPermissions invalid schema name: 'mySchemaName'`
