### ISSUE TITLE
[ISSUE] Issue with `databricks_sql_table`: configuration drift without changes ignoring terraform `lifecycle_rules` 

### ISSUE THREAD

**Issue by mansenfranzen** [databricks/terraform-provider-databricks#3652]
This issue is related to #3378. Every terraform apply causes a change in `databricks_sql_table` given no change in configuration. This is fairly annoying given the fact that the change requires databricks compute to spin up to execute the change which roughly takes 5 minutes to complete while blocking subsequent steps in CI/CD. 

This behavior persists even after adding terraform's lifecycle rule [`ignore_changes`]() which should ignore such external configuration drifts.

### Configuration

```hcl
resource "databricks_sql_table" "bronze_layer" {
  name     = "session_files"

  catalog_name = "default"
  schema_name  = "bronze"

  table_type              = "EXTERNAL"
  data_source_format      = "PARQUET"
  storage_location        = "XXX"
  storage_credential_name = "XXX"

  # prevent configuration drift on properties
  lifecycle {
    ignore_changes = all
  }
}
```

### Expected Behavior
No change upon `apply` given no configuration changes

### Actual Behavior
```
  ~ update in-place
Terraform will perform the following actions:
  # databricks_sql_table.bronze_layer will be updated in-place
  ~ resource "databricks_sql_table" "bronze_layer" {
        id                      = "XXX"
        name                    = "session_files"
      + properties              = (known after apply)
        # (6 unchanged attributes hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

### Terraform and provider versions
terraform= 1.8.3
databricks = 1.41.0

**Comment by nkvuong** [comment]
@mansenfranzen there might be some properties that we need to ignore in TF, are there any changes shown in the plan or is it just shown as `(known after apply)`?

Could you also share the debug log as well, since that would show the properties being sent back from the server

**Comment by svrijssel** [comment]
We're having the same issue, indeed on external tables.

**Comment by svrijssel** [comment]
Has anyone found a fix for this?
