### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster` provider

### ISSUE THREAD

**Issue by Gaurang033** [databricks/terraform-provider-databricks#3653]
### Configuration

```
resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = var.cluster_name
  spark_version           = var.spark_version
  autotermination_minutes = 15
  policy_id               = var.policy_id
  is_pinned               = true
  autoscale {
    min_workers = 1
    max_workers = 10
  }
  gcp_attributes {
    availability           = var.availability
    zone_id                = var.zone_id
    google_service_account = var.google_service_account
  } /*
  init_scripts {
    gcs {
      destination = var.destination
    }
  }*/
  instance_pool_id = var.instance_pool_id
 
```

### Expected Behavior
If running running apply twice on a row without any changes to code for second time it should now no changes to infrastructure. 

### Actual Behavior
it shows that the custom tag added by policy will be removed every time you run `terraform apply`.  however, it's not able to do remove that custom_tag as it's coming from policy. 

### Steps to Reproduce
 Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply` 

### Terraform and provider versions
Terraform v1.8.2
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.47.0
+ provider registry.terraform.io/hashicorp/google v3.90.1

### Is it a regression?
not sure

**Comment by alexott** [comment]
it's actually documented: https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/cluster#policy_id

> For example, when you specify policy_id of [external metastore](https://docs.databricks.com/administration-guide/clusters/policies.html#external-metastore-policy) policy, you **still have to fill in relevant keys** for spark_conf. **If relevant fields aren't filled in, then it will cause the configuration drift detected on each plan/apply, and Terraform will try to apply the detected changes.**

So you need to add this tag to your cluster definition
