### ISSUE TITLE
[ISSUE] Issue with `databricks_cluster` resource

### ISSUE THREAD

**Issue by manojhegde97** [databricks/terraform-provider-databricks#3689]
workload_type  configuration in  databricks_cluster  resource is not taking effect, we can see a blank in the cluster JSON . however when we use the true statement instead of false it is accepting,

### Configuration

```hcl
resource "databricks_cluster" "this" {
  provider                = databricks.ws
  cluster_name            = "manoj-job-new"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = "c5d.xlarge"
  driver_node_type_id     = "c5d.xlarge"


  autoscale {
    min_workers = 1
    max_workers = 1
  }

  aws_attributes {
    zone_id = "auto"
  }

  # Prevent submitting job to run in interactive cluster
  workload_type {
    clients {
      jobs      = false
      notebooks = true
    }
  }

}
```

### Expected Behavior
It should take the false statement for  workload_type 

### Actual Behavior
only true statement is accepting 

### Terraform and provider versions
Terraform v1.6.2 , databricks : 1.47.0

**Comment by seanjw13** [comment]
I encountered this issue today. 

With Databricks Terraform Provider v1.45.0 this correctly creates a cluster with workload tags set that prevent Jobs from running on it.

But when I update the Databricks provider to v1.46.0 or later, `jobs=false` is not propagated to the created cluster.

From looking at the release notes for v1.46.0, it seems like it may have to do with [this change](https://github.com/databricks/terraform-provider-databricks/pull/3627).

**Comment by Woffendm** [comment]
This is causing issues at my company as well.
