### ISSUE TITLE
[ISSUE] Issue with `databricks_storage_credential` and `databricks_external_location ` resource isolation mode

### ISSUE THREAD

**Issue by harry19023** [databricks/terraform-provider-databricks#3728]
### Configuration

```hcl
resource "databricks_storage_credential" "external" {
  provider = databricks.workspace
  name     = "${var.environment}-external-access"
  //cannot reference aws_iam_role directly, as it will create circular dependency
  aws_iam_role {
    role_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.uc_iam_role}"
  }
  isolation_mode = "ISOLATED"
  force_update   = true
}

resource "databricks_external_location" "catalog" {
  provider        = databricks.workspace
  name            = "${var.environment}-catalog-external-location"
  url             = "s3://${aws_s3_bucket.catalog-bucket.id}"
  credential_name = databricks_storage_credential.external.id
  isolation_mode  = "ISOLATED"
  force_update    = true
}
```

### Expected Behavior

Both the storage credential and the external location should have been bound to 1 workspace.

### Actual Behavior

Both the storage credential and the external location are available from all workspaces.

### Steps to Reproduce
1. `terraform plan` says it will make the change
```
  # databricks_storage_credential.external will be updated in-place
!   resource "databricks_storage_credential" "external" {
        id                    = "stg-external-access"
!       isolation_mode        = "ISOLATION_MODE_OPEN" -> "ISOLATED"
        name                  = "stg-external-access"
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # databricks_external_location.catalog will be updated in-place
!   resource "databricks_external_location" "catalog" {
        id              = "stg-catalog-external-location"
!       isolation_mode  = "ISOLATION_MODE_OPEN" -> "ISOLATED"
        name            = "stg-catalog-external-location"
        # (7 unchanged attributes hidden)
    }
```
2. `terraform apply` says it made the change
```
  # databricks_storage_credential.external will be updated in-place
  ~ resource "databricks_storage_credential" "external" {
        id                    = "stg-external-access"
      ~ isolation_mode        = "ISOLATION_MODE_OPEN" -> "ISOLATED"
        name                  = "stg-external-access"
        # (6 unchanged attributes hidden)
            # (1 unchanged attributes hidden)
        }
    }

  # databricks_external_location.catalog will be updated in-place
  ~ resource "databricks_external_location" "catalog" {
        id              = "stg-catalog-external-location"
      ~ isolation_mode  = "ISOLATION_MODE_OPEN" -> "ISOLATED"
        name            = "stg-catalog-external-location"
        # (7 unchanged attributes hidden)
    }

databricks_storage_credential.external: Modifying... [id=stg-external-access]
databricks_storage_credential.external: Modifications complete after 0s [id=stg-external-access]
databricks_external_location.catalog: Modifying... [id=stg-catalog-external-location]
databricks_external_location.catalog: Modifications complete after 1s [id=stg-catalog-external-location]
```
3. No change applied
![image](https://github.com/databricks/terraform-provider-databricks/assets/8812828/8af0d368-7761-4171-8c42-bb658484a58e)

### Terraform and provider versions
terraform version: 1.7.5
provider "registry.terraform.io/databricks/databricks" {
  version     = "1.48.2"
}

### Is it a regression?

Not sure, have not tested.

**Comment by nkvuong** [comment]
there is a missing PR that needs to be merged - https://github.com/databricks/terraform-provider-databricks/pull/3678

**Comment by jamesdehart** [comment]
@nkvuong this mr #3678 has been merged. The API seems to have changed and this "feature" has been removed. See [here](https://docs.databricks.com/api/workspace/externallocations/create). I see the API backend has changed from 2.0 to 2.1 for some of the calls.

**Comment by iswariyam** [comment]
@nkvuong Any updates on this issue? Looks like all the previous PRs are merged and a new version 1.49.0 of the provider is also released, but the isolation mode does not work.

**Comment by matthewchoy-envisso** [comment]
Seems like its a bug, when I change storage credential / external location isolation_mode to include the full string expected by the API it works.
`isolation_mode = "ISOLATION_MODE_ISOLATED"`

**Comment by iswariyam** [comment]
> Seems like its a bug, when I change storage credential / external location isolation_mode to include the full string expected by the API it works. `isolation_mode = "ISOLATION_MODE_ISOLATED"`

@matthewchoy-envisso Thanks for the hint. I also checked the source code changes that were made in the PR #3678 and indeed it is a typo in the documentation. Using `isolation_mode = "ISOLATION_MODE_ISOLATED"` works.
