### ISSUE TITLE
[ISSUE] Databricks terraform exporter provider not working fine. - Unwanted objects extracted

### ISSUE THREAD

**Issue by harshitha-2406-git** [databricks/terraform-provider-databricks#3749]
Hello,

### Configuration

While I ran the below command for running the terraform exporter which will prompt you to confirm exporting resources with a 'y' or 'n':
**terraform-provider-databricks exporter -directory clouddrive/<workspace-name>**

Even if we explicitly said No, for the extraction of the Unity Catalog objects for some reason they have been exported, all the files will the prefix uc- are related to the unity catalog, so we had to remove it manually as it got exported even after giving No, is an issue here.
![terraform exporter issue](https://github.com/databricks/terraform-provider-databricks/assets/175126904/2d7cbc29-d4d9-47f3-9bc6-d44dadf67693)

```hcl
**terraform-provider-databricks exporter -directory clouddrive/<workspace-name>**
```

### Expected Behavior
When i explicitly give No for not exporting the uc prefixed resources, while I exported the resources and check with ls there should not be any files with uc- prefixed

### Actual Behavior
Even if we explicitly said No, for the extraction of the Unity Catalog objects for some reason they have been exported, all the files will the prefix uc- are related to the unity catalog, so we had to remove it manually.

### Steps to Reproduce
1. **terraform-provider-databricks exporter -directory clouddrive/<workspace-name>**

### Terraform and provider versions
Terraform v1.8.3
Databricks CLI v0.221.1

### Is it a regression?
No

### Important Factoids
No

### Would you like to implement a fix?
No

**Comment by alexott** [comment]
This happens because, in the interactive mode, we're specifying only values for the `-listing` option, but all dependencies of that service will be exported, including UC objects.  To have a more granular export it's better to use the non-interactive mode specifying both `-listing` and `-services` options for services that you need to export. I'll file docs PR clarifying this behavior.
