### ISSUE TITLE
Limitations - Specific Case for Serverless- DBSQL Serverless has been imported as a PRO instance

### ISSUE THREAD

**Issue by harshitha-2406-git** [databricks/terraform-provider-databricks#3758]
Hello, 

### Use-cases
 **Migration of DBSQL Serverless to New Workspace Results in PRO Configuration**
 
When migrating DBSQL serverless configurations to a new workspace, there are specific limitations to be aware of:

**Scenario:**

Source Workspace Configuration: The DBSQL configuration is set to serverless.
After Import to New Workspace: The configuration is automatically updated to PRO.

**Details:**

If the warehouse_type in the original (source) workspace is set to serverless, it will be converted to PRO upon importing to the new workspace.
Conversely, if the warehouse_type was already set to PRO in the source workspace, it remains unchanged during the migration process.

When we import the resources its is expected to import as it is in the source workspace, as its changing the warehouse type to PRO from serverless.
-->

### Proposal

In order to have imported the DBSQL instance properly just tried to  flag enable_serverless_compute=true to the resource block and than the warehouse type changed to serverless, but it is expected to happen automatically, once its imported, as the source workspace had serverless as the warehouse_type.

Thanks!

**Comment by alexott** [comment]
Please provide more details on what you mean by migration/importing... What tool is used, etc. Serverless implies PRO.

**Comment by harshitha-2406-git** [comment]
We are trying to use terraform exporter to export/import the objects or the resources from older databricks workspace to new workspace during this process of export/import the sql warehouse with the configuration of serverless on the older workspace changed to PRO when imported in the new workspace.

This is the limitations just for the serverless, Suppose the configuration of sql warehouse is PRO in older workspace it remains same as PRO after importing to the new workspace.

The limitation is just towards the serverless sql warehouse configuration.
