### ISSUE TITLE
[ISSUE] Issue with databricks provider

### ISSUE THREAD

**Issue by swedishstyle** [databricks/terraform-provider-databricks#3776]
### Configuration

```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.0"
    }
  }

  required_version = ">= 1.0"
}
```

### Expected Behavior

Terraform plan should have executed correctly

### Actual Behavior

The installed provider plugins are not consistent with the packages selected in the dependency lock file:
│   - registry.terraform.io/databricks/databricks: failed to verify checksum of registry.terraform.io/databricks/databricks 1.48.3 package cached in in .terraform\providers: open .terraform\providers\registry.terraform.io\databricks\databricks\1.48.3\windows_amd64\terraform-provider-databricks_v1.48.3.exe: Access is denied

### Steps to Reproduce

terraform init, using either version = "~> 1.0" or version = "1.48.3"
terraform plan

### Terraform and provider versions

Terraform v1.9.0
on windows_amd64
+ provider registry.terraform.io/databricks/databricks v1.48.3
+ provider registry.terraform.io/hashicorp/azuread v2.53.1
+ provider registry.terraform.io/hashicorp/azurerm v3.112.0

### Is it a regression?

Yes, this worked earlier this morning with version 1.4.2

### Debug Output

Seems unnecessary, but can provide if required

### Important Factoids

N/A

**Comment by alexott** [comment]
It's not a terraform provider issue - it's something wrong on that machine - see `Access is denied` error message.
