### ISSUE TITLE
[ISSUE] Issue with `databricks_permissions` resource in 1.49.0

### ISSUE THREAD

**Issue by orolega** [databricks/terraform-provider-databricks#3799]
After upgrading to 1.49.0 getting errors on the `databricks_permissions` resource with no changes made to the resource

### Configuration

```hcl
terraform {
  required_version = "~> 1.9.0"
  required_providers {
    databricks = {
      source  = "databricks/databricks"
      version = "~> 1.49.0"
    }
  }
}

resource "databricks_permissions" "dashboard" {
  sql_dashboard_id = databricks_sql_dashboard.dashboard.id

  access_control {
    group_name       = var.group_name
    permission_level = "CAN_RUN"
  }
}
```

### Expected Behavior
After updating, no changes to configuration when doing plan.

### Actual Behavior
Threw an error `Error: cannot read permissions: unknown object type dashboard`. Also experienced a similar error on a resource block using `sql_query_id` instead of the dashboard id `Error: cannot read permissions: unknown object type query`

### Steps to Reproduce
1. Update provider to 1.49.0
2. terraform plan

### Terraform and provider versions
Terraform v1.9.2
on linux_arm64

### Is it a regression?
Yes. Downgrading to 1.48.3 works with no issue

**Comment by alexott** [comment]
Can you please provide debug logs?

**Comment by orolega** [comment]
https://gist.github.com/orolega/e1194d3eec4aa0068749868dba3980fe

**Comment by orolega** [comment]
Legend @alexott !
