### ISSUE TITLE
[ISSUE] Azure databricks Issue with `databricks_workspace_binding` ,  databricks workspace is not binded to the catalog

### ISSUE THREAD

**Issue by krupakar1329** [databricks/terraform-provider-databricks#3802]
### Configuration

```hcl
resource "databricks_workspace_binding" "main" {
  # securable_name = databricks_catalog.unity_catalog.name
  securable_name = data.databricks_catalog.test.name
  workspace_id   = data.azurerm_databricks_workspace.test.workspace_id
}
```

### Expected Behavior
The specified databricks workspace should be allowed access to catalog.

### Actual Behavior
The databricks workspace is not granted access though the information is present in state file.

### Terraform and provider versions

3.49

### Is it a regression?

All versions has this issue.

**Comment by Hekter** [comment]
@krupakar1329 Can you further explain what you mean by 'databricks workspace is not granted access'? Does it not show up in the Workspaces tab in the UI for that catalog like below?

![image](https://github.com/user-attachments/assets/b6e38678-812b-4f22-8091-358b89d3ceb0)

**Comment by krupakar1329** [comment]
Please ignore the issue created. Never an issue at all.
