### ISSUE TITLE
[ISSUE] Issue with databricks_metastores Data Source

### ISSUE THREAD

**Issue by shiva171819** [databricks/terraform-provider-databricks#3814]
databricks_metastores Data Source issue:

terraform code used:

data "databricks_metastores" "all" {}

output "all_metastores" {
  value = data.databricks_metastores.all.ids
}

I have used the azure account level provider as below.

provider "databricks" {
  alias      = "azure_account"
  host       = "https://accounts.azuredatabricks.net"
  account_id = "valid account id" # provided valid account id
  auth_type  = "azure-cli"
}
Error:

Planning failed. Terraform encountered an error while generating this plan.

╷ │ Error: cannot read metastores: cannot get client metastores: invalid Databricks Account configuration │

│   `with data.databricks_metastores.all,
│   on main.tf line 59, in data "databricks_metastores" "all":
│   59: data "databricks_metastores" "all" {}

Could you please help me to resolve this? Trying to get the meatastore id

**Comment by alexott** [comment]
you're missing `provider` in your data source declaration - you use an alias on the provider config, but you don't specify that alias in the data source
