### ISSUE TITLE
[FEATURE] Support R2 Buckets for databricks_storage_credential

### ISSUE THREAD

**Issue by nick-amplify** [databricks/terraform-provider-databricks#3834]
Hello! I have a feature request to be able to provision `databricks_storage_credential` resources with terraform in the same way you can for s3, azure, and gcs. 

### Use-cases

* Ability to create [databricks_storage_credential](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/storage_credential) with terraform
* I would like to be able to create and manage cloudflare buckets with terraform and automatically provision permission to those buckets directly in terraform. 

### Proposal

The resource could look something like: 
```terraform

resource "databricks_storage_credential" "r2_credential" {
  name = "your-cred-name"
  cloudflare {
    r2_account_id  = var.cloudflare_account_id
    r2_bucket_name = var.bucket_name
    r2_api_token   = cloudflare_api_token.django_service_token.value
  }
}
```

**Comment by nick-amplify** [comment]
@alexott Do you have any idea when this will be available in a new release?

**Comment by alexott** [comment]
Releases happen every 2-3 weeks. Last release was last week, so it's either next week, or week after
