### ISSUE TITLE
[DOC] Incorrect documented allowed values against workspace_binding securable_type attribute

### ISSUE THREAD

**Issue by robbruce** [databricks/terraform-provider-databricks#3941]
### Affected Resource(s)

https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/workspace_binding

### List of things to potentially add/remove

This is a list of things to manipulate in the docs:

- [ ] `securable_type` attribute - listed allowed types are incorrect, provider returns error if trying to use value from docs - see screenshot

#### Documentation

![image](https://github.com/user-attachments/assets/6e7bdd26-4687-4f63-8cd2-d9154493cd21)

#### Error Message

![image](https://github.com/user-attachments/assets/a9965075-18fd-40fa-bcdf-164b8a037244)

**Comment by robbruce** [comment]
@alexott - issue is actually a difference between 1.49 and 1.50 - in version 1.50 the allowed values are as per the documentation (with `_` separators) - changed in PR https://github.com/databricks/terraform-provider-databricks/pull/3808/files#diff-e0900dfdceab23ec601e80a92175cdbed0acb4b7eaa5bd874ac9d6afb2ec9e30

**Comment by alexott** [comment]
Technically, both are allowed...
