### ISSUE TITLE
[FEATURE] databricks_notification_destination in old Databricks provider versions

### ISSUE THREAD

**Issue by oleksandrshynkarov** [databricks/terraform-provider-databricks#3991]
Hello!
Will databricks_notification_destination be available in older versions of provider. Now it is available in versions 1.50.0 and newer, however it is very important feature and it will be awesome to have it in an older versions.
Thank you for your response!

**Comment by alexott** [comment]
What is the reason for staying on old version?

**Comment by oleksandrshynkarov** [comment]
Thank you for pointing on it. Discussed it with a team and decided to migrate with time. Closing the issue. Sorry for inconvenience
