### ISSUE TITLE
[ISSUE] missing artifact_matcher block in exported databricks_artifact_allowlist resources (maven, jar) 

### ISSUE THREAD

**Issue by mkieszek** [databricks/terraform-provider-databricks#4024]
Hello,

I encountered a deprecation warning and multiple errors while running terraform validate using the Databricks provider v1.51.0. The errors are related to missing artifact_matcher blocks and a deprecated argument (enable_serverless_compute). Below is the detailed configuration, the expected and actual behavior, steps to reproduce, and additional relevant information.

### Configuration

```hcl
# Example Terraform configuration that caused the issue
resource "databricks_sql_global_config" "sql_global_config" {
  enable_serverless_compute = true
}

resource "databricks_artifact_allowlist" "library_jar_west_europe_metastore_xxxxxxxx" {
  # Missing artifact_matcher block
}

resource "databricks_artifact_allowlist" "library_maven_west_europe_metastore_xxxxxxxx" {
  # Missing artifact_matcher block
}

```

### Expected Behavior
Terraform should validate the configuration without any warnings or errors.

### Actual Behavior
Received the following warning and errors during terraform validate:

- Warning: Argument is deprecated for enable_serverless_compute in databricks_sql_global_config.
- Error: Insufficient artifact_matcher blocks on multiple resources.

### Steps to Reproduce
1. Run `terraform-provider-databricks_v1.51.0.exe exporter -skip-interactive -services=uc-grants`
2. Run `terraform validate`.

### Terraform and provider versions
- Terraform version: v1.9.5
- Databricks provider version: v1.51.0

### Is it a regression?
It is not clear if this is a regression. This behavior was encountered using the v1.51.0 provider.

### Debug Output
N/A

### Important Factoids
```shell
databricks artifact-allowlists get LIBRARY_JAR
{
  "metastore_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
databricks artifact-allowlists get LIBRARY_MAVEN
{
  "metastore_id":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}

```

### Would you like to implement a fix?
I would like to but need to learn more about GO and this project.

**Comment by alexott** [comment]
we already have https://github.com/databricks/terraform-provider-databricks/pull/4019 to fix it
