### ISSUE TITLE
[ISSUE] Issue with `databricks_dashboard` resource

### ISSUE THREAD

**Issue by creachel** [databricks/terraform-provider-databricks#4065]
#### Terraform configuraton:
resource "databricks_dashboard" "dashboard" {
  display_name = "xxx"
  warehouse_id = databricks_sql_endpoint.xyz.id
  serialized_dashboard = {}
  embed_credentials = false
  parent_path       = "/Shared/Dashboards"
}

Executing the above (with legitimate values), returns the following error:
<img width="549" alt="image" src="https://github.com/user-attachments/assets/c821f8aa-11e4-48f0-8299-cbb213b6ecbc">

The [docs](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/dashboard) specifically say the folder will be created if it does not exist but seems like it isn't the case here.
![image](https://github.com/user-attachments/assets/a47e5a0f-a6ee-4e17-97c0-f2d802ae3d18)

### Expected Behavior

I should not be getting a `Error: cannot create dashboard: Path (/Shared/Dashboards) doesn't exist.` error and the folder should be created.

**Comment by alexott** [comment]
It was fixed by #3778 - upgrade to at least 1.51.0

**Comment by creachel** [comment]
Ah, we are a few versions behind. Thanks.
