### ISSUE TITLE
[ISSUE] Issue with exporter databricks_workspace_file, exceeded the the limit 10485760

### ISSUE THREAD

**Issue by mkieszek** [databricks/terraform-provider-databricks#4077]
While exporting workspace files I get error
Failed custom import of databricks_workspace_file[...] (id: /...): content size (29861532) exceeded the the limit 10485760
and later using the code generated with.

Later using the generated code I get a message
Error: cannot create workspace file: File size imported is (11396743 bytes), exceeded max size (10485760 bytes)

Of course it is for different file. 
But:
1. If limited exceeded on export, there shouldn't be any file larger then 10M
2. How to extend the content size limit ?

### Configuration
terraform-provider-databricks v1.51.0

**Comment by alexott** [comment]
it's a problem with underlying APIs - raise the issue with your account team

**Comment by mkieszek** [comment]
thanks, raised a Support ticket to MS
