### ISSUE TITLE
[ISSUE] Issue with `databricks_XXX` resource

### ISSUE THREAD

**Issue by ofirmac** [databricks/terraform-provider-databricks#4174]
Since today, I'm experiencing the following error when trying to install the `databrickslabs/databricks` provider:

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing databrickslabs/databricks v1.5.0: checksum list has no SHA-256 hash for
│ "https://github.com/databricks/terraform-provider-databricks/releases/download/v1.5.0/terraform-provider-databricks_1.5.0_darwin_arm64.zip"
╵
```

This issue prevents me from working with any Databricks module in Terraform.

**Steps Tried:**
1. Specifying a newer version in my provider block.
2. Running `terraform init -upgrade` to refresh provider configurations.

**Environment:**
- Terraform Version: 1.3.6
- Operating System: macOS ARM64

I would appreciate any guidance or a workaround to resolve this issue.

Thank you!

**Comment by nkvuong** [comment]
You are specifying the provider as `databrickslabs/databricks` - we are now using the `databricks` namespace. More details in the [doc](https://registry.terraform.io/providers/databricks/databricks/latest/docs#switching-from-databrickslabs-to-databricks-namespace)
