### ISSUE TITLE
[ISSUE] Issue with `databricks_query` resource - perpetual diff on `run_as_mode`

### ISSUE THREAD

**Issue by apamildner** [databricks/terraform-provider-databricks#4228]
### Configuration
```hcl
resource "databricks_query" "this" {
  warehouse_id = "some-id-123"
  query_text   = "SELECT FOO FROM BAR"
  display_name = "My query"
  parent_path  = "some/path"
  run_as_mode  = "viewer"
}
```

### Expected Behavior
I expect the query to be created with the run_as_mode "viewer".

### Actual Behavior
We get this
<img width="425" alt="image" src="https://github.com/user-attachments/assets/5b171c2e-5044-45d8-8ba0-00fbebfedcef">

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
```text
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/databricks/databricks v1.55.0

```
### Is it a regression?
Not sure, just started using this one

### Important Factoids
When I check the query in databricks under "Share", I see this:
<img width="861" alt="image" src="https://github.com/user-attachments/assets/2903cd42-a2de-4f29-a7a5-71c6ca772498">
Also it seems it is greyed out. Not sure who becomes the owner of the query when I create it via terraform either, as it seems a "principal" cannot be an owner of a query. From [this](https://docs.databricks.com/en/sql/user/queries/index.html#transfer-ownership-of-a-query)

> You must be a workspace admin to transfer ownership of a query. Service principals and groups cannot be assigned ownership of a query

### Would you like to implement a fix?
I don't have capacity or knowledge for that sadly

**Comment by alexott** [comment]
Please attach the logs as described in the troubleshooting guide.
Can you also try to specify `VIEWER` not `viewer`

**Comment by apamildner** [comment]
@alexott It was actually solved by explicitly writing `VIEWER` as suggested, good catch 👍  I was not able to attach logs due to company policy, sorry about that.
