### ISSUE TITLE
[ISSUE] Issue with generating `databricks_job` HCL with  import block

### ISSUE THREAD

**Issue by botchniaque** [databricks/terraform-provider-databricks#4255]
I am trying to use the experimental feature of generating HCL for imported resources as described here https://opentofu.org/docs/language/import/generating-configuration/

I am getting errors. 

### Configuration

```hcl
terraform {
  required_providers {

    databricks = {
      source  = "databricks/databricks"
      version = ">= 1.58.0, < 2.0.0"
    }
  }

}

import {
  to = databricks_job.test_import
  id = "123456..."
  
}
```

### Expected Behavior
- call `tofu plan -generate-config-out=generated.tf` works without errors
- i get `generated.tf` file with my job's HCL

### Actual Behavior

- call `tofu plan -generate-config-out=generated.tf` shows errors
    ```
    │ Error: Invalid combination of arguments
    │
    │   with databricks_job.test_import,
    │   on generated.tf line 29, in resource "databricks_job" "test_import":
    │   29:     service_principal_name = ""
    │
    │ "run_as.0.service_principal_name": only one of `run_as.0.service_principal_name,run_as.0.user_name` can be specified, but `run_as.0.service_principal_name,run_as.0.user_name` were specified.
    ╵
    ╷
    │ Error: Invalid combination of arguments
    │
    │   with databricks_job.test_import,
    │   on generated.tf line 30, in resource "databricks_job" "test_import":
    │   30:     user_name              = "email@address.com"
    │
    │ "run_as.0.user_name": only one of `run_as.0.service_principal_name,run_as.0.user_name` can be specified, but `run_as.0.service_principal_name,run_as.0.user_name` were specified.
    ```
- `generated.tf` file with my job's HCL does not specify `tasks` 

### Steps to Reproduce

1. add `import` block for an existing databricks job (see "Configuration" section)
2. call `tofu plan -generate-config-out=generated.tf`

### Terraform and provider versions

```
tofu --version
OpenTofu v1.8.5
on darwin_arm64
+ provider registry.opentofu.org/databricks/databricks v1.59.0
```

**Comment by alexott** [comment]
It's not a provider issue but is more on the TF/Tofu side.

Don't use it; instead, use the [Terraform exporter](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/experimental-exporter) functionality. It will correctly handle dependencies on other objects, and you can do selective exports, etc.
