### ISSUE TITLE
[FEATURE] Add ability to import databricks_notification_destination

### ISSUE THREAD

**Issue by kishaningithub** [databricks/terraform-provider-databricks#4275]
From the [provider documentation](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/notification_destination#attribute-reference), i see that there is no way to import [databricks_notification_destination resource](https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/notification_destination#attribute-reference). I would be great if this feature can be added.

## Use case
- We have lot of notification destination resources created manually via databricks UI. We would like to import the same into terraform.

**Comment by alexott** [comment]
btw, you can use [terraform exporter](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/experimental-exporter) to generate code for existing objects - it will also create import definitions.
