### ISSUE TITLE
[FEATURE] Databricks jobs to trigger pipeline_task

### ISSUE THREAD

**Issue by estraviz** [databricks/terraform-provider-databricks#864]
Hi there,

my first question here... It has to do with the invocation of pipelines in a scheduled job. Is this an option that could be added, the same way as for example the support for multi-task orchestration jobs option was recently included (thank you!) with v0.39.0? 

Thank you in advance.

**Comment by nfx** [comment]
It's a few line addition to JobTaskSettings struct, PRs welcome
